### PR TITLE
[PLT-4951] Don't send a desktop notification and don't mark channel unread if a comment thread for that channel is open in right hand sidebar, and Mattermost is in focus

### PR DESCRIPTION
**Pull request by kulak-at**
#### Summary
Pull request for the PLT-4951. I hope I covered all the cases. I stoped showing mention count and notification when window is in focus and new message appeared in the thread on the right.

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-4951

#### Checklist

### CODE REVIEW

**Comment by jasonblais** [comment]
You're awesome @kulak-at, wonderful work 👍 

@esethna please help with testing when you get the chance?

**Comment by esethna** [comment]
Hi @kulak-at, just checking if I can help clarify anything from the above message?

**Comment by esethna** [comment]
Hi @kulak-at, hope you're doing well. Is there anything I can help with so we can push this PR across the finish line? Looking forward to getting it in!

**Comment by jasonblais** [comment]
Hey @kulak-at, closing for now due to inactivity -- if you'd still be interested to help, let us know!

**Pull request closed without merging**
