### PR TITLE
[PLT-6159] Fix Error Message When Password is too Long

### PR DESCRIPTION
**Pull request by R-Wang97**
#### Summary
Update all the password error messages to say that the password length must be `between {min} and {max}` characters long.

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-6159
https://github.com/mattermost/platform/issues/5979

#### Checklist
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/platform/blob/master/i18n/en.json) and [.../webapp/i18n/en.json](https://github.com/mattermost/platform/tree/master/webapp/i18n/en.json)) updates

### CODE REVIEW

**Comment by jasonblais** [comment]
@lindalumitchell please help with testing?

**Comment by jasonblais** [comment]
Thanks @R-Wang97! 

Tested various combinations of the error messages, all looks good on that front.

Just one minor issue: In System Console > Security > Password, in the `Password Requirements` section, the help text reads `{min}` and `{max}` instead of `5` and `64`.

Can you help take a look?

image

**Comment by R-Wang97** [comment]
@jasonblais Will take a look at that, thanks for pointing it out.

**Comment by R-Wang97** [comment]
@jasonblais Should be fixed!

**Comment by jasonblais** [comment]
@R-Wang97 Sorry, I still seem to have the same issue

image

**Comment by R-Wang97** [comment]
@jasonblais Hm okay, will take another look at it soon.

**Pull request merged**
