### PR TITLE
[PLT-1099] Add Default Purpose to Town Square

### PR DESCRIPTION
**Pull request by R-Wang97**
#### Summary
Added a default purpose to the Town Square channel, and it will only show when there isn't a custom purpose set. The default purpose text at the beginning of `Town Square`'s history has also been updated to the one specified in the ticket.

#### Ticket Link
https://github.com/mattermost/platform/issues/5259
https://mattermost.atlassian.net/browse/PLT-1099

#### Checklist
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/platform/blob/master/i18n/en.json) and [.../webapp/i18n/en.json](https://github.com/mattermost/platform/tree/master/webapp/i18n/en.json)) updates

### CODE REVIEW

**Comment by lindalumitchell** [comment]
@jasonblais @R-Wang97 this looks good! I see the new default purpose, as described in the ticket, 1) at the beginning of the channel, and 2) in Town Square > down-arrow menu > View Info (desktop view).

Two questions: 

1) In mobile view, when I click / tap the question mark Info icon, I do not see the purpose listed. Just info about adding a new header (screenshots attached). Should it appear in mobile view as well?

2) On user-created channels, when I update the purpose, it appends that info to the intro text at the beginning of the channel:
  - "This is the start of the LMTest channel, created by test on March 20, 2017. Any member can join and read this channel. This channel's purpose is: The purpose of this channel is to test a PR."
  - On Town Square and Off-Topic, that doesn't happen. It just displays the original intro text at the beginning of the channel. Is that okay?

Testing notes:
- Tested adding and removing new Town Square purpose, and default text was replaced and came back as expected.
- Other channels still behaving as expected.
- System messages displaying when the purpose is changed, as expected.

town-square-info-mobile
town-square-info-desktop

**Comment by jasonblais** [comment]
Thanks @lindalumitchell -

1. The view info design is different for the mobile app, and I think it's going to be updated in the new mobile app. So what we have now is fine.
2. The channel intros are different for Town Square and Off-Topic since they're automatically created --- the other channels are user-created. So that's okay.

Both are good catches, nice attention to detail. 👍

**Comment by jwilander** [comment]
@jasonblais just a heads-up this will cause `Purpose:` to appear in the modal even when it is blank for channels. Previously, it would not show up at all if the purpose was blank. Is that OK?

**Comment by jasonblais** [comment]
Thanks @jwilander for the note

We shouldn't show the purpose in the "View Info" modal if the purpose is blank.

@R-Wang97 would you be able to help make an update for the PR? Below is an example of a channel header in Town Square and Off-Topic. Since there's no header in Off-Topic, the title doesn't appear in the "View Info" modal

image
image

**Comment by JeffSchering** [comment]
I think this might be a better default message:

*Post messages here that you want everyone to see. Everyone automatically becomes a permanent member of this channel when they join the team.*

The reasons are as follows:
  1. It's directed at the end user and leaves out stuff that only a system admin needs to know.
  2. It's more active, and is more encouraging. "Post messages here ..." gives permission and freedom to participate, and is written in the context of achievement. "This channel is for communicating to all members..." sounds more like "This channel is not for you. It's for the boss to tell you what to do."
  3. The most important information is "above the fold" so to speak. That is, because the amount of space available for the text is limited, only the first 50 characters or so can be seen without clicking the text to get the whole thing. So we should put the most important information at the beginning where it'll always be visible.

**Comment by jasonblais** [comment]
Thanks @JeffSchering! Agree this sounds better

@R-Wang97 it's up to you if you'd like to update the string to `Post messages here that you want everyone to see. Everyone automatically becomes a permanent member of this channel when they join the team.`. I'm happy to push the update as well

**Comment by R-Wang97** [comment]
@jasonblais I'll update the description in this PR.

**Comment by R-Wang97** [comment]
@jasonblais Changes made!

**Comment by grundleborg** [comment]
Looks great. Thanks for the PR @R-Wang97

**Pull request merged**
