### PR TITLE
plt-375 - Making modals compatible with themes

### PR DESCRIPTION
**Pull request by asaadmahmoodspin**

### CODE REVIEW

**Comment by crspeller** [comment]
@asaadmahmoodspin Why the switch from png to jpg?

**Comment by jwilander** [comment]
+1

**Comment by asaadmahmoodspin** [comment]
@crspeller I think I saved them for web and the format was jpeg, however for these images png would be better for these images so changed them back.

**Comment by asaadmahmoodspin** [comment]
Hey guys, please review this PR. There have been new changes regarding the themes so I went ahead and did them all in the same PR.

**Comment by hmhealey** [comment]
Looks good

**Comment by jwilander** [comment]
+1

**Pull request merged**
