### PR TITLE
HOTFIX MM-2046 - Updating momentum scroll on IOS

### PR DESCRIPTION
**Pull request by asaadmahmoodspin**
Hey guys have a look. Just updating the momentum scroll with css rather than having perfectscrollbar.

### CODE REVIEW

**Comment by it33** [comment]
@jwilander I think MM-2046 was marked 0.7.0 in triage meeting this morning?

**Comment by coreyhulen** [comment]
+1

**Comment by crspeller** [comment]
Looks good to me.

**Comment by jwilander** [comment]
+1

**Comment by crspeller** [comment]
Closed because I had to cherry pick these commits onto the release branch.

**Pull request closed without merging**
