### PR TITLE
Set timeout to http client

### PR DESCRIPTION
**Pull request by jostyee**
Please make sure you've read the [pull request](http://docs.mattermost.com/developer/contribution-guide.html#preparing-a-pull-request) section of our [code contribution guidelines](http://docs.mattermost.com/developer/contribution-guide.html).

When filling in a section please remove the help text and the above text.

#### Summary
Add a http client with 5 seconds timeout.
The default http.client would hang forever if the request url doesn't return.

### CODE REVIEW

**Comment by jasonblais** [comment]
Awesome, thanks @jostyee. Can you help review the build failures and we'll start with the review process after?

If you need any help or tips, let us know

**Comment by jostyee** [comment]
```
=== RUN   TestUpdateOAuthUserAttrs
[2017/02/27 10:44:49 UTC] [WARN] Permanently deleted account 4iteuw8tjjr7jr6cmksb716kcc@simulator.amazonses.com id=wp71mdj5s3dcfdmt1k5wjpsm7w
--- FAIL: TestUpdateOAuthUserAttrs (0.02s)
	user_test.go:235: unable to create the user
FAIL
coverage: 24.8% of statements
exit status 1
FAIL	github.com/mattermost/platform/app	5.378s
make: *** [test-server] Error 1
```

[This test](https://github.com/mattermost/platform/blob/c0bb6f99f89259f6728856ace23d5dd505494b26/app/user_test.go#L95) is not related to the PR.

**Comment by jasonblais** [comment]
Let me try closing and re-opening the PR to re-trigger the build

**Comment by jasonblais** [comment]
Looks like that resolved it, queuing for dev review

**Comment by jostyee** [comment]
btw @jasonblais , any thoughts of my request https://github.com/mattermost/platform/issues/5522 ? I can send another PR to init different http client according to os environment settings.

**Comment by jostyee** [comment]
https://github.com/mattermost/platform/pull/5540#issuecomment-282721937
@jasonblais I guess you can click the `Rebuild` button to trigger it.
screen shot 2017-02-28 at 1 20 12 pm

**Comment by jasonblais** [comment]
That might be easier :)

**Pull request merged**
