### PR TITLE
PLT-1890 Added (at)username and full name to user popover

### PR DESCRIPTION
**Pull request by DavidLu1997**
#### Summary
Always have `@username` be the title of the user profile popover.
Add the full name underneath the profile picture if the user has one.

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-1890

#### Checklist
- [x] Has UI changes

### CODE REVIEW

**Comment by enahum** [comment]
One thing i found here @DavidLu1997 and actually not required for this ticket is that the popover for `user_profile` is always present even if its not shown, can you try and have it render only when clicking on the user in the post_header? I think that would help a little bit with performance. :)

**Comment by lfbrock** [comment]
Alright I can't get the test server to work for this, but just going to remove the PM approval label and we can test on CI.

**Comment by DavidLu1997** [comment]
@enahum changed by adding a state variable and an onClick

**Comment by enahum** [comment]
seems to work ok, but I think that `handleClick` is a little bit confused on the wrapping div.

**Comment by DavidLu1997** [comment]
Yeah, it behaves a little weirdly, but it works :P

**Comment by crspeller** [comment]
@DavidLu1997 Maybe instead of the strange hacky stuff with two click handlers you could create a custom popover component that handles that internally?

**Comment by DavidLu1997** [comment]
closing to rewrite

**Pull request closed without merging**
