### PR TITLE
PLT-3026 Basic App Center UI

### PR DESCRIPTION
**Pull request by enahum**
PLT-3023 Create Endpoints for App Center (client side)
PLT-2960 Add the battlehouse to the LHS header menu list

### CODE REVIEW

**Comment by jwilander** [comment]
Looks good, but can you set up the directory structure and filenames like this?

`app_center/app_center_controller.jsx` (the view controller for app center)
`app_center/app_view_controller.jsx` (the view controller for app view)
`app_center/components/` (all child components used by either view controller)

**Comment by enahum** [comment]
@jwilander done

**Comment by jwilander** [comment]
+1

**Comment by hmhealey** [comment]
+1

**Pull request merged**
