### PR TITLE
Fix issue 4161

### PR DESCRIPTION
**Pull request by wget**
#### Summary
Rewrite consistent logs for the Slack Importer

#### Ticket Link
#4161

#### Checklist
- [ ] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [ ] All new/modified APIs include changes to the drivers
- [ ] Has enterprise changes (please link)
- [ ] Has UI changes
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/platform/blob/master/i18n/en.json) and [.../webapp/i18n/en.json](https://github.com/mattermost/platform/tree/master/webapp/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by wget** [comment]
@grundleborg Ok. Gonna make the aforementioned changes :)

**Comment by esethna** [comment]
Hi @wget, please let us know if you have any questions about the changes.

**Comment by wget** [comment]
@grundleborg @esethna Ok I made the changes you mentioned. However, like requested, I only took messages from `log.WriteString()`. I didn't take into account messages with `l4g.Warn()`.

**Comment by jasonblais** [comment]
@wget I made minor tweaks (e.g. used "message" instead of "post").

For some reason I couldn't create a PR against your branch so had to commit the changes directly..let me know if you have any feedback/thoughts?

https://github.com/mattermost/platform/pull/6919/commits/1c6c00f7fc9deea4b32f6bf98232b091f5c5ca7c

Otherwise looks great, big thanks for working on this.

**Comment by wget** [comment]
@jasonblais Nope, I have nothing to add. :) Looks good to me :)

**Comment by wget** [comment]
@grundleborg I think you can merge this. This would be cool if this could be merged before the code freeze due this week, that way, we can get this included for the translations for 4.1.
cc @jasonblais

**Pull request merged**
