### PR TITLE
PLT-1849 Added extra system-wide statistics for EE

### PR DESCRIPTION
**Pull request by jwilander**
@enahum / @coreyhulen should I be leaving the ES translations blank when I don't have them or should I put in the EN strings like I have done?

### CODE REVIEW

**Comment by enahum** [comment]
Don't include them, if you do is harder to track them down, if they're not in the file then it's easier to find, translate and then add them.

**Comment by jwilander** [comment]
Ok, removing..

**Comment by enahum** [comment]
I'll add the translations in my next PR.

btw commit `320fe1c` from @crspeller  added a few translations that I don't see them used anywere

**Comment by crspeller** [comment]
@enahum They are for Enterprise Edition.

**Comment by coreyhulen** [comment]
+1

**Comment by crspeller** [comment]
+1

**Pull request merged**
