### PR TITLE
Add IDs to the LHS "+" channel creation button and create channel menu

### PR DESCRIPTION
**Pull request by doh5**
For UI Automation

### CODE REVIEW

**Comment by jwilander** [comment]
Hmm this is going to require updating of the snapshots for the tests to pass, which will require some training for non-devs. I've queued an item to talk about it in the next dev meeting https://pre-release.mattermost.com/core/pl/4o8n44tukty3bnpy9646ufzpdw

**Comment by doh5** [comment]
Cool. Thanks.

**Comment by jasonblais** [comment]
Any next steps here?

**Comment by doh5** [comment]
This one is not urgent. I will close this one and create new one later. Thanks.

**Pull request closed without merging**
