### PR TITLE
Update web socket help

### PR DESCRIPTION
**Pull request by it33**
This error message is showing on iOS when websockets are properly configured, but it's slow to load the site. Propose a message that explains this, and also shortening the text.

### CODE REVIEW

**Comment by coreyhulen** [comment]
there is something else going on that we should look at.  This message shouldn't show for the first 5 (?) failed attempts or approx 15 sec.  You should see the yellow box instead.  Basically you should only see it when mattermost is down or misconfigured.

**Comment by crspeller** [comment]
Message is correct. Displayed in incorrect situation. Closing per Corey's comment.

**Comment by it33** [comment]
@coreyhulen What happens if

**Comment by it33** [comment]
@coreyhulen agree if it's not working we should fix it. Until we fix it, propose we update the help text so it doesn't have end users spam administrators? Working on some new text...

**Pull request merged**
