### PR TITLE
PLT-2351 Switch to Apple emoji set

### PR DESCRIPTION
**Pull request by hmhealey**
Here's the diff without all the image files
https://github.com/hmhealey/mattermost-platform/compare/7af2e6f...016c179

### CODE REVIEW

**Comment by enahum** [comment]
+1 awesome!!

**Comment by loafoe** [comment]
+1 excellent!!

**Comment by crspeller** [comment]
+1

**Comment by enahum** [comment]
this one is not working for me, not in Chrome and in FF on Mac, emojis are just simply missing

**Comment by hmhealey** [comment]
@enahum Yeah I screwed up and added an extra character to a hex number when fixing ESLint. I'm restarting the spinmint with the updated version

**Comment by enahum** [comment]
+1 now they are working

**Comment by jwilander** [comment]
+1

**Pull request merged**
