### PR TITLE
Preview markdown post

### PR DESCRIPTION
**Pull request by florianorben**
Followup from #1349, only contains the actual changing commit

### CODE REVIEW

**Comment by it33** [comment]
Hi @florianorben, 

Really excited about adding this, 

Just a couple of thoughts: 

1. There's one older ticket for [help text on markdown](https://mattermost.atlassian.net/browse/PLT-327) that was inadvertently left private, and I wondered if we could have your help adding it, since it's related to this PR? 

  The help text could go on the left and the Preview/Edit on the right? 

2. Instead of "Edit Message" propose just "Edit" since the user will have just clicked "Preview" so it'll be clear the "Edit" applies to the message? 

If we could have your help getting this in, I think the overall usability and quality of the markdown feature could improve significantly,

**Comment by derWalter** [comment]
would it be hard to live preview it?
having two windows,... i dont know, would you like to work
in a word processor like ms word, where you have an input field for
your source code and an outputfield where you can view how it would look like?

i mean, thats cool for math formulas written in latex but not actual text.

imho

**Comment by jwilander** [comment]
Hi @derWalter ,

I think it's much better to not have it live previewing for a couple reasons:

1. It's very difficult (both technically and from a user perspective) to edit Markdown when it's formatting as you type. Think about tables, how would you edit a Markdown table easily that has been formatted? The only easy way to do this would be to have toolbars attached to the textbox, and I think that's much too heavy weight
2. Leaving the Markdown unprocessed as the user types actually leaves more screen space for typing, since if I entered a big header a live preview would take up a ton of space.

If screen space is the biggest worry then I think that can be addressed by having the preview overlap the textbox just like it does here on GitHub. @florianorben does the preview do this or is it currently appearing below the textbox?

**Comment by kernicPanel** [comment]
Maybe adding a button "Preview" which opens a modal where we can edit and preview before sending ?
This way current layout is preserved, but preview will be available for particular messages.

**Comment by it33** [comment]
Hi @derWalter, hi @kernicPanel, 

Appreciate your feedback on how usability could be approved. The features you're bringing up are very large and would require their own tickets. 

Would we have your help adding them [to the feature idea forum](www.mattermost.org/feature-requests/) so they can be upvoted by the community? 

The Markdown feature itself began as a feature idea there, and it's through discussion and collaboration that the best ideas make it into the product. 

As features are designed, they'll be made into the tickets accepting pull requests, like this one: 
https://mattermost.atlassian.net/browse/PLT-327

From there, contributors from the community know what ideas from the community have been vetted and thought through, so everything flows smoothly, 

We'd love your help bringing the very best new feature ideas in the forum to the attention of peers, so they can flow into the design process, as so many features have before: http://mattermost.uservoice.com/forums/306457-general/status/1588363

**Comment by jwilander** [comment]
+1

**Comment by crspeller** [comment]
+1

**Pull request merged**
