### PR TITLE
PLT-2341 Adding webpack code splitting

### PR DESCRIPTION
**Pull request by crspeller**

### CODE REVIEW

**Comment by enahum** [comment]
+1 @crspeller this looks awesome!!

need explaining on why there are some route files that export <Route> and others that exports an object, didn't quite understood.

Overall this seems to be pretty amazing.

**Comment by crspeller** [comment]
Thanks! Going to put a do not merge on this so we can do a team review.

**Comment by jwilander** [comment]
+!

**Comment by hmhealey** [comment]
+1

**Pull request merged**
