### PR TITLE
PLT-1800 Replace webhooks documentation URL

### PR DESCRIPTION
**Pull request by kernicPanel**
Es localization needs review.

### CODE REVIEW

**Comment by kernicPanel** [comment]
I don't get why check failed… :/

**Comment by jwilander** [comment]
It was just a build gremlin, should pass now that I restarted it

**Comment by kernicPanel** [comment]
I hope travis won't pour water on it

**Comment by crspeller** [comment]
+1

**Comment by jwilander** [comment]
+1

**Pull request merged**
