### PR TITLE
[PLT-6452] Remove edit button on mobile, and have the edit icon beside the value, and the value as a link

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
Remove edit button on mobile, and have the edit icon beside the value, and the value as a link

#### Ticket Link
Jira: https://mattermost.atlassian.net/browse/PLT-6452
Github: https://github.com/mattermost/platform/issues/6520

#### Checklist
- [x] Has UI changes

### CODE REVIEW

**Comment by cpanato** [comment]
done @esethna

**Comment by esethna** [comment]
Thanks @cpanato looks great!

**Comment by coreyhulen** [comment]
@crspeller can you review?

**Comment by jasonblais** [comment]
@JeffSchering Adding a `Docs: Needed` label if we have screenshots showing the mobile settings page as they would need to be updated.

**Pull request merged**
