### PR TITLE
Remove redundant mobile web search hint popover

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
Remove redundant mobile web search hint popover

#### Ticket Link
GitHub: https://github.com/mattermost/platform/issues/5074

### CODE REVIEW

**Comment by jasonblais** [comment]
@doosp is helping with initial testing

**Comment by doosp** [comment]
Hi, @cpanato 

Cool. Another awesome work. Thanks!

I couldn't find anything broken or acting differently from expected. :)

@jasonblais Please check when you have a chance?

Tested the followings:
-Mobile web search (Android + Chrome): Confirmed
-Desktop web search (Window 10 + Chrome): Confirmed
-App search: Confirmed
-Jump and remove or edit a message: Confirmed
-Test language other than English: Confirmed

**Comment by esethna** [comment]
Hi @cpanato, great work, there is just one issue I could find:

1. The pop-over should not be removed if the comment thread is open, since it is not redundant information:

image

When you tap the search icon, the pop-over info is redundant because the blank search page provides the same info:

image

Let me know if you have any questions?

**Comment by cpanato** [comment]
@esethna all clear,  i will take a look on that

**Comment by cpanato** [comment]
@esethna do you know How I can know id the search is not more in the initial page? in order to enable the popover again.

**Comment by esethna** [comment]
I wouldn't propose removing the help text since the page will be blank when the user hits the search icon.

@grundleborg any ideas? The question is how to not show the search tip pop-over from the page when you tap the search icon, but keep the pop-over if you tap in the search box from an RHS thread.

**Comment by andreistanciu24** [comment]
Hey 
Check out my PR here: https://github.com/mattermost/platform/pull/5233

I think the popover should show on search page no matter what the search returns. Because the text changes and it will no longer be redundent. E.g: 

image

@cpanato did a good job, but he removes the popover entirely for mobile version.

Let me know what you think

**Comment by cpanato** [comment]
ok sounds good, will close this one.

**Pull request closed without merging**
