### PR TITLE
Hotfix: PLT-4959 Allow any user in a channel to remove other users

### PR DESCRIPTION
**Pull request by jwilander**
#### Summary
Allow any user in a channel to remove other users. I tested as system admin, team admin and regular user in both private and public channels.

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-4959

### CODE REVIEW

**Comment by it33** [comment]
CH and I are testing and in this build we're able to remove a user from Town Square

**Comment by jwilander** [comment]
Can I get repro steps? I don't see how to do that from the UI

**Comment by coreyhulen** [comment]
@jwilander https://mattermost.atlassian.net/browse/PLT-4965

**Comment by coreyhulen** [comment]
looks un-related.

**Comment by esethna** [comment]
@coreyhulen @jwilander are we blocked on anything to get this merged? We should also get this fix into master.

**Comment by jwilander** [comment]
I will be merging this into `master` tomorrow. I'm not sure of the status of whether we're doing a 3.5.2 or not.

**Comment by coreyhulen** [comment]
@jwilander you have a build failure.

**Comment by jwilander** [comment]
Closing because I don't think we're doing a dot release for this.

**Pull request closed without merging**
