### PR TITLE
MM-1284 Fixed auto-linking (for good hopefully)

### PR DESCRIPTION
**Pull request by nickago**

### CODE REVIEW

**Comment by rgarmsen2295** [comment]
Other than a few missing semi-colons this looks good (no more link issues :D )

**Comment by jwilander** [comment]
@nickago please add missing semi-colons and then I'll merge

**Comment by nickago** [comment]
Alright, ready to go

**Comment by nickago** [comment]
Ready for re-review

**Comment by jwilander** [comment]
@rgarmsen2295 please sign off on a re-review when you get a chance

**Comment by rgarmsen2295** [comment]
Looks good, ready for merge

**Pull request merged**
