### PR TITLE
PLT 1658: Add file attachment preview to search result

### PR DESCRIPTION
**Pull request by VeraLyu**
Please make sure you've read the [pull request](http://docs.mattermost.com/developer/contribution-guide.html#preparing-a-pull-request) section of our [code contribution guidelines](http://docs.mattermost.com/developer/contribution-guide.html).

When filling in a section please remove the help text and the above text.

#### Summary
Add file attachment preview to search result.

#### Ticket Link
issue: https://github.com/mattermost/platform/issues/5776
jira: https://mattermost.atlassian.net/browse/PLT-1658

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Has UI changes

### CODE REVIEW

**Comment by jasonblais** [comment]
@lindalumitchell please help with review?

Big thanks @VeraLyu for getting this done so quick 👍

**Comment by lindalumitchell** [comment]
@jasonblais @VeraLyu tested this one and it looks great! Verified all attachment types in loadtest, with various searches, both desktop view and mobile view. Behaves as described in Jira ticket: Show thumbnails in the search result. Clicking on the thumbnail should open the file previewer, and clicking the download icon should download the file (same behaviour as in posts). No issues found.

**Comment by grundleborg** [comment]
Thanks very much for the PR @VeraLyu - looks great.

**Comment by JeffSchering** [comment]
@esethna I don't see where this would be documented; it doesn't seem to be needed here: https://docs.mattermost.com/help/getting-started/searching.html... Is there someplace else you have in mind?

**Comment by esethna** [comment]
@JeffSchering I was thinking we should mention that the file names are not searchable. Users might  expect to be able to search file names since attachments appear in the now.

**Pull request merged**
