### PR TITLE
Disabling plt-3366 due to a bug

### PR DESCRIPTION
**Pull request by crspeller**
#### Summary
Disables the ALT+click on message functionality due to a bug: https://mattermost.atlassian.net/browse/PLT-3785

#### Checklist
- [x] Includes text changes and localization files updated

### CODE REVIEW

**Comment by enahum** [comment]
failing due to

```
/var/lib/jenkins/jobs/mattermost-platform-pr/workspace/src/github.com/mattermost/platform/webapp/components/post_view/components/post.jsx
  13:13  error  'PostActions' is defined but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)
```

**Comment by crspeller** [comment]
Already fixed it!

**Comment by enahum** [comment]
+1

on a side note: the keyboard shortcuts strings has been a total pain, I think this is like the 5th time we'll need to translate them

**Comment by crspeller** [comment]
Ya they should be separate strings formatted programmatically. 
Ticket here: https://mattermost.atlassian.net/browse/PLT-3797

**Comment by coreyhulen** [comment]
+1

**Pull request merged**
