### PR TITLE
PLT-3154 Updated help text on Select Team page

### PR DESCRIPTION
**Pull request by DavidLu1997**
Please make sure you've read the [pull request](http://docs.mattermost.com/developer/contribution-guide.html#preparing-a-pull-request) section of our [code contribution guidelines](http://docs.mattermost.com/developer/contribution-guide.html).

#### Summary
Changed Select Team UX to be more informative.

#### Issue/Ticket Link
https://mattermost.atlassian.net/browse/PLT-3154

#### Screenshots

- Only one closed team, `david` 
- Team creation enabled

temp1

- Only one open team `david`

temp2

- No open teams
- Team creation enabled

temp3

- No open teams
- Team creation disabled

temp4

- No teams
- Team creation disabled
temp5

- No teams
- Team creation enabled
temp6

- Some teams (normal situation)
- Team creation enabled

image

### CODE REVIEW

**Comment by jasonblais** [comment]
@DavidLu1997 

For the case where team creation is disabled and no teams have been created, propose changing the help text to `No teams have been created. Please contact your administrator.`


image

**Comment by jwilander** [comment]
Needs a rebase @DavidLu1997

**Comment by DavidLu1997** [comment]
@jasonblais changed text as described
@jwilander rebased

**Comment by jwilander** [comment]
+1

**Comment by crspeller** [comment]
+1

**Pull request merged**
