### PR TITLE
PLT-6346 - Show tooltips for channel name

### PR DESCRIPTION
**Pull request by prateeksriv**
Please make sure you've read the [pull request](http://docs.mattermost.com/developer/contribution-guide.html#preparing-a-pull-request) section of our [code contribution guidelines](http://docs.mattermost.com/developer/contribution-guide.html).

When filling in a section please remove the help text and the above text.

#### Summary
Shows tooltips when mouse is hovered against channel name in sidebar.
The tooltip contains the channel header.

#### Ticket Link
https://github.com/prateeksriv/platform/tree/PLT-6346

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [ ] All new/modified APIs include changes to the drivers
- [ ] Has enterprise changes (please link)
- [x] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/platform/blob/master/i18n/en.json) and [.../webapp/i18n/en.json](https://github.com/mattermost/platform/tree/master/webapp/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by jasonblais** [comment]
Thanks @prateeksriv for the pull request! Appreciate it,

Curious if there was a Help Wanted GitHub issue for it as per [the contribution guidelines](https://docs.mattermost.com/developer/contribution-guide.html#choose-a-ticket)?

**Comment by prateeksriv** [comment]
Hi @jasonblais ,

No, there was no "Help Wanted" for this issue/patch. I know this does not comply with the guidelines.
However, this is something I use in my organization and found it useful. I assumed other organizations will also find it useful. Please help me make it process compliant so that I can contribute to this project.
The use-case is described [in the discussion](https://github.com/mattermost/platform/issues/6346). 

Use-case: If you are a member of many channels, the sidebar can be quite long and you may want to know the channel details before you click into one of them. If there are many channels with similar names, you may want to know the details.

I am facing trouble making the build pass. This code is working in my local view. "make test" is passing in my local environment. But fails in jenkins.

2017-05-07-15 37 30_1920x1080_scrot

**Comment by prateeksriv** [comment]
Is there a way forward or this is the end?

**Comment by prateeksriv** [comment]
Adding a mention for alert: @jasonblais

**Comment by jasonblais** [comment]
Thanks @prateeksriv, I just responded to you on the issue :)

**Comment by jasonblais** [comment]
Hey @prateeksriv, I'll close this PR for now and we can continue the discussion at https://github.com/mattermost/platform/issues/6346

**Pull request closed without merging**
