### PR TITLE
Improving some post stuff

### PR DESCRIPTION
**Pull request by asaadmahmoodspin**
#### Summary
Improvements for the post dropdown and improved post highlight stuff.

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-3554

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields.]
- [ ] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [ ] Has driver changes that have been merged and package.json updated
- [ ] Has enterprise changes (please link)
- [x] Has UI changes
- [ ] Includes text changes and localization files updated
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by jwilander** [comment]
+1

**Comment by crspeller** [comment]
@asaadmahmoodspin Is this supposed to be for 3.2?

**Comment by asaadmahmoodspin** [comment]
@crspeller @coreyhulen and @it33 will decide. Can we setup a test server for this?

**Comment by coreyhulen** [comment]
+1

**Comment by asaadmahmoodspin** [comment]
This PR is no longer needed, I would be submitting a PR with the improved behaviour which would work better and have the highlight improvement aswell.

**Pull request closed without merging**
