### PR TITLE
PLT-5080 (WebApp): Channel Admin permission level.

### PR DESCRIPTION
**Pull request by grundleborg**
#### Summary
Adds a Channel Admin level permission for channel management and deletion in the system console.

Updates when channel menu options are shown to include channel admin role.

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-5080

#### Checklist
- [x] Has UI changes
- [x] Includes text changes and localization file updates

### CODE REVIEW

**Comment by esethna** [comment]
Hi @grundleborg, thanks for the PR! A few notes:

1. Can we please remove the "Team and System Admins" option from the dropdown for renaming and deletion? So the options should be "All channel members", "Channel, Team and System Admins", and "System Admins".

2. I seem to be getting a JS error on channel creation for public and private channels. The system console setting is set to "All team members" for private and public creation

image

**Comment by grundleborg** [comment]
@esethna fixed point 2. On point 1, are you sure that's desirable? It seems a bit arbitrary to me to allow setting the permission at System and Channel admin level but not at Team admin level.

**Comment by esethna** [comment]
Spinmint not firing, @hmhealey can you please take a look?

**Comment by esethna** [comment]
Hey George, sorry for the delay, I tested this out. Still a few blocking issues:

1. When the "Channel, Team and System Admin" option is selected in the system console for renaming public and private channels, once a new channel is created, you have to open the Manage Members modal before the options for "Edit Channel Header", "Rename Channel", "Edit Channel Purpose" appear in the channel menu. Even a hard refresh doesn't help.

2. Similarly, When the "Channel, Team and System Admin" option is selected in the system console for deleting public and private channels, once a new channel is created and members are added, you have to open the Manage Members modal before the option for "Delete Channel" appears in the channel menu. Even a hard refresh doesn't help.

3. When the "Channel, Team and System Admin" option is selected in the system console for renaming and deleting public/private channels, the channel menu for Team and System Admins will never show the options for "Edit Channel Header", "Rename Channel", "Edit Channel Purpose", "Delete Channel". Even after a hard refresh. Note: This only occurs in the case where the Team or System Admin is NOT also a channel admin in the channel.

**Comment by grundleborg** [comment]
@esethna Nice catches there. I've fixed all 3 issues.

**Comment by esethna** [comment]
Hey @grundleborg, thanks for the tweaks! I still seem to be hitting a few blocking issues:

1. When the "Channel, Team and System Admin" option is selected in the system console for renaming public and private channels, Team Admins can open the Rename Channel modal but get the "You do not have the appropriate permissions" error when trying to save a new name or handle. Note: System Admins and Channel Admins work as expected.

2. Similarly, When the "Channel, Team and System Admin" option is selected in the system console for deleting public and private channels, if a Team Admin attempts to delete a channel, a console error is thrown and the delete is unsucessful. Note: System Admins and Channel Admins work as expected.

image

**Comment by grundleborg** [comment]
Once https://github.com/mattermost/platform/pull/5478 is merged, I'll rebase on top of it, and this will resolve the issues mentioned above.

**Comment by grundleborg** [comment]
@esethna these should both be fixed now.

**Comment by esethna** [comment]
Hey @grundleborg, I seem to be getting a console error when creating a new channel, not sure if that's related to the PR?
 
image

Other than that this PR is looking great!

**Comment by grundleborg** [comment]
@esethna Fixed.

**Comment by esethna** [comment]
Thanks @grundleborg, thanks for the fix, I found one more issue:

1. If a regular team member creates an account, adds users, then toggles the dropdown on a user from "Channel Member" to "Make Channel Admin" to "Make Channel Member", notice that the buttons for "Remove Member" appear (see GIF)

manage_members

**Comment by grundleborg** [comment]
@esethna fixed. Hopefully that's the last issue you find :)

**Pull request merged**
