### PR TITLE
PLT-3427 Added channel header to view channel info modal

### PR DESCRIPTION
**Pull request by DavidLu1997**
#### Summary
Added channel header to view channel info modal

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-3427

#### Checklist
- [ ] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [ ] Has driver changes that have been merged and package.json updated
- [ ] Has enterprise changes (please link)
- [x] Has UI changes
- [x] Includes text changes and localization files updated
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

image

### CODE REVIEW

**Comment by enahum** [comment]
+1

**Comment by jwilander** [comment]
+1

**Comment by esethna** [comment]
@DavidLu1997 thanks, I tested this:

1. Sorry, this should have been written out explicitly in the ticket, can we get markdown to render in the modal for the channel header?
2. There is one piece of functionality missing where the "Header" label should be hidden from the modal if the channel header is not set.

**Comment by DavidLu1997** [comment]
Closing to resubmit

**Pull request closed without merging**
