### PR TITLE
MM-1733 Team URLs no longer accept a number as the first character

### PR DESCRIPTION
**Pull request by rgarmsen2295**
Also updates the error message displayed to users when they do not follow the URL specification.

However the bigger change here is the refactoring of the `signup_team_complete.jsx` file into several different component files.  It previously contained all of it's child components within its own file which breaks the style guide's rule of having only one react component per jsx file.

### CODE REVIEW

**Comment by nickago** [comment]
Initial look through is good, need to check a couple things before approval.

**Comment by coreyhulen** [comment]
Since these are all tightly coupled wizard pages I wonder if it make sense to name them so they group together (team_signup_*.jsx)

**Comment by rgarmsen2295** [comment]
Agreed that makes sense, I'll go ahead and rename them with that in mind.

**Comment by rgarmsen2295** [comment]
Okay @coreyhulen renamed the newly created component files as suggested (and mirrored the changes in the parent file require lines) so please take another look when you have a chance, thanks!

**Comment by nickago** [comment]
I'm gonna say +1

**Comment by coreyhulen** [comment]
+1 looks good

**Pull request merged**
