### PR TITLE
PLT-2805 Added message for users joining Town Square

### PR DESCRIPTION
**Pull request by DavidLu1997**
#### Summary
Primary purpose: Add system message to users joining Town Square

To do that, I had to:
- Remove `c *Context` from `CreatePost`, `CreateWebhookPost`, `handlePostEvents`, `handleWebhookEvents`, `sendNotifications`, `sendNotificationEmail`, and `checkForOutOfChannelMentions`.
- Add `teamId` in place of `c *Context`
- Add `channelId` to a few functions

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-2805

#### Checklist
- [x] Added or updated unit tests (required for all new features)
- [x] Touches critical sections of the codebase (auth, upgrade, etc.)

image

### CODE REVIEW

**Comment by jwilander** [comment]
Bunch of unit test failures @DavidLu1997

**Comment by DavidLu1997** [comment]
@jwilander rebased and should pass unit tests now

(one of the few non-automatic rebases I've done...)

**Comment by jwilander** [comment]
+1

**Comment by coreyhulen** [comment]
+1, needs a rebase

**Comment by DavidLu1997** [comment]
@coreyhulen rebased

**Pull request merged**
