### PR TITLE
PLT-638: added display tab under account settings. added 24h time option

### PR DESCRIPTION
**Pull request by stasvovk**
* Display tab under Account Settings
* Clock Display option under Display

### CODE REVIEW

**Comment by hmhealey** [comment]
Looks like your changes have a style guide issue that isn't passing ESLint. Should be easy enough to fix since it's just the one.
```
/home/travis/gopath/src/github.com/mattermost/platform/web/react/utils/utils.jsx
  178:5  error  Keyword "if" must be followed by whitespace  space-after-keywords
```

**Comment by stasvovk** [comment]
the issue should be fixed. sorry, forgot to check it with eslint

**Comment by hmhealey** [comment]
Looks good, but you'll also need to add an onChange method to the RhsRootPost and RhsComment components as well so that the posts shown in the right sidebar are updated when the preference changes as well. There's going to be some duplicated code for now, but we're planning on recombining these classes in the future.

**Comment by stasvovk** [comment]
oops, I didn't notice that we have posts in the sidebar. that should be fixed now

**Comment by hmhealey** [comment]
Cool, looks good.

The only other thing that I noticed was that you assume the use_military_time preference is actually never pulled down from the server so if you clear your browser cache, it'll lose that setting. That's okay though since #1079 is going to load those preferences already whenever the page loads so this can be merged as soon as that is in.

**Comment by stasvovk** [comment]
@hmhealey oh I missed that we don't pull all user preference on page load. Thank you for the notice

**Comment by crspeller** [comment]
+1

**Pull request merged**
