### PR TITLE
Multiple UI improvements

### PR DESCRIPTION
**Pull request by asaadmahmoodspin**
Hey guys have a look. Changes include:
- Improving login UI.
- Removing safari specific code for account settings sidebar ( Did that to support safari 7/8 I think).
- Adding compatible flexbox code using compass.

### CODE REVIEW

**Comment by jwilander** [comment]
@asaadmahmoodspin you have an eslint error `error  "utils" is defined but never used  no-unused-vars`

**Comment by asaadmahmoodspin** [comment]
Fixed.

**Comment by crspeller** [comment]
@asaadmahmoodspin Needs rebase due to @it33 breaking the build.

**Comment by asaadmahmoodspin** [comment]
Updated it guys, have a look.

**Comment by jwilander** [comment]
+1

**Pull request merged**
