### PR TITLE
fix font not being changed on first page visit (if preferences havent been loaded before)

### PR DESCRIPTION
**Pull request by florianorben**
> Lindsay:
fix font not being changed on first page visit (if preferences havent been loaded before)
#bug New font does not load on first page load
Repro: 
Change display font, and save
Open Core on a new tab
Observed: In the new tab, the old font shows up until you refresh the page

### CODE REVIEW

**Comment by coreyhulen** [comment]
@hmhealey please take a look

I wonder if it would make more sense to pull some inital pref settings like
```
    <script>
        window.mm_config = {{ .ClientCfg }};
        window.mm_team = {{ .Team }};
        window.mm_user = {{ .User }};
        window.mm_channel = {{ .Channel }};
```

from head.html

**Comment by hmhealey** [comment]
This looks pretty good, but I agree with @coreyhulen that having the prefs pulled on page load would make a lot of sense instead of doing it asynchronously. Perhaps we should discuss this in the dev meeting this week?

**Comment by florianorben** [comment]
Perhaps an actual discussion would be useful, I imagine this isn't the only part where async loading of preferences could become a problem (e.g. language settings later on etc.).

The changes in here are pretty small anyway, so it should be safe to let them wait a while longer :)

**Comment by coreyhulen** [comment]
+1

**Comment by coreyhulen** [comment]
added https://mattermost.atlassian.net/browse/PLT-1416

**Comment by jwilander** [comment]
+1

**Pull request merged**
