### PR TITLE
PLT-1088 Fixes issue where an admin could not delete a root post in the RHS

### PR DESCRIPTION
**Pull request by rgarmsen2295**
Before the [...] menu would not appear on hover if the user did not own the post.

### CODE REVIEW

**Comment by jwilander** [comment]
+1

**Comment by crspeller** [comment]
@rgarmsen2295 Needs a rebase.

**Comment by crspeller** [comment]
@rgarmsen2295 Make sure when you rebase you do so with the new module system in mind.

**Comment by rgarmsen2295** [comment]
Ok rebased to work with the new module system, please re-review when possible @jwilander @crspeller thanks!

**Pull request merged**
