### PR TITLE
ticket #4665 - emoji picker

### PR DESCRIPTION
**Pull request by bonespiked**
#### Summary
This adds a Emoji picker to the post message box and keeps a recent history of recently used emojis for quick access

#### Ticket Link
https://github.com/mattermost/platform/issues/4665

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] Has UI changes

### CODE REVIEW

**Comment by jasonblais** [comment]
Awesome, thanks @bonespiked! 🎉 🎆 

Looks like we've got a CLA signed by `bonespike` not `bonespiked`. Might have been a typo when you filled it out, can you help sign it again?

Also, there seems to be a build failure if you help can take a look.

**Comment by bonespiked** [comment]
Ah - I used my 'organization' github handle instead of my individual one, I'll fill it out again.

There was a build failure, but in looking into the eslint issues, I managed to find not only a critical bug (since fixed), but a sizeable (pun intended) UI/UX issue with showing the emoji picker from the post comment sidebar... so this PR can be cancelled for now

**Comment by jasonblais** [comment]
Just saw your note in the Contributors channel - I can either label this PR as "Work in Progress" or close and you can reopen a new one.

Either way works, whichever you'd prefer

**Comment by jwilander** [comment]
Nice work guys! Looks likes there's a few ESLint errors though
```
/home/ubuntu/workspace/mattermost-platform-pr/src/github.com/mattermost/platform/webapp/components/create_comment.jsx
   32:1   error  './create_post.jsx' import is duplicated  no-duplicate-imports
   32:48  error  Missing semicolon                         semi
  201:62  error  Block must not be padded by blank lines   padded-blocks
  204:11  error  Missing semicolon                         semi

✖ 4 problems (4 errors, 0 warnings)
```

**Comment by bonespiked** [comment]
I'm closing this PR for now - in closing the create_comment.jsx jslint errors (skipped looking at it, as I forgot I touched it), I found more serious issues.  I'm going to resolve them (likely not until Monday due to family commitments this weekend), then submit a new PR...

**Pull request closed without merging**
