### PR TITLE
Mm 1894 Add state listening to the sidebar relative to the team store

### PR DESCRIPTION
**Pull request by nickago**

### CODE REVIEW

**Comment by crspeller** [comment]
You would think there would be a way to let the stores update before any of this happens. This causes rendering twice in the case of it not being available. Is there no way to just wait for it to be available the first time?

**Comment by nickago** [comment]
This is the ticket we talked about last Wednesday and it references the problem of us loading everything asynchronously. This should be fine since React won't re-render the whole DOM, just the parts that weren't loaded because they couldn't be loaded because the information hadn't reached this stores yet.

**Comment by crspeller** [comment]
Alright I guess this is ok untill we fix the bigger issue. Need a seconder.

**Comment by rgarmsen2295** [comment]
+1

**Pull request merged**
