### PR TITLE
PLT-40 adding experimental support for emojis

### PR DESCRIPTION
**Pull request by coreyhulen**

### CODE REVIEW

**Comment by crspeller** [comment]
+1

**Comment by hmhealey** [comment]
Don't we already have emoji support? We have the twemoji library running as well

**Comment by coreyhulen** [comment]
twemoji converts unicode emojis to img emojis and is really a heavy hammer for fixing a bug where unicode emojis wouldn't appear on windows (??).

**Comment by jwilander** [comment]
+1

**Pull request merged**
