### PR TITLE
PLT-5267: Remove fake img preview before loaded

### PR DESCRIPTION
**Pull request by VeraLyu**
Please make sure you've read the [pull request](http://docs.mattermost.com/developer/contribution-guide.html#preparing-a-pull-request) section of our [code contribution guidelines](http://docs.mattermost.com/developer/contribution-guide.html).

When filling in a section please remove the help text and the above text.

#### Summary
Remove fake img preview and collapse toggle before it is loaded,
only show img and toggle after it is fully loaded.
Fix markdown img size and add scroll down behaviour.

#### Ticket Link
Issue: https://github.com/mattermost/platform/issues/5368
Jira: https://mattermost.atlassian.net/browse/PLT-5267

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Has UI changes

### CODE REVIEW

**Comment by jasonblais** [comment]
Awesome, thanks @VeraLyu ! 

@lindalumitchell please help with testing?

**Comment by lindalumitchell** [comment]
@jasonblais @VeraLyu this looks great! Tested image links with preview and without, and both loaded as expected, with no more fake image preview. Tested in center panel and RHS reply thread, desktop and mobile views (verified that mobile view and RHS still don't show any preview, fake or real, anyway, and that should continue to be the case, right Jason?).

- https://www.dropbox.com/s/qe1edr8nu6l5f1r/icon.png?dl=0 (does not have preview, and doesn't load fake preview)
- https://about.mattermost.com/wp-content/uploads/2016/01/logo.png?foo (has preview)
- https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png (has preview)

**Comment by esethna** [comment]
Thanks for another great PR @VeraLyu!  Once again, just letting you know that there may be a delay in reviewing and merging your PR since we are approaching code complete for v3.8, releasing April 16th. Please see our [release process](https://docs.mattermost.com/process/release-process.html) for more details.

**Comment by VeraLyu** [comment]
Hi,
@esethna , I will fix the second one. And I tested the 1. in current master branch and it behaves the same as you mentioned, since I didn't change scroll behaviour for collapse action, I think this one is an issue out of scope of this patch, but I can address this in another patch. Let me know what you think, thanks for review.

**Comment by VeraLyu** [comment]
Updates: Fixed #2 "height flickering" @esethna mentioned, as I didn't change scroll behaviour for collapse action, and master behaviours the same as #1, I think it is out of this patch's scope and decide to address it in a single patch. Thanks.

**Comment by esethna** [comment]
@VeraLyu, sorry for the delay in reviewing this PR. When you have a chance can you please fix the conflicts so we can start up a new test server.

**Comment by jasonblais** [comment]
Hey @VeraLyu, looks like this PR just needed to resolve the merge conflicts so a new test server could be started.

Can you help with that when you get the chance? @esethna will help re-test it afterwards.

Big thanks for the contribution!

**Comment by jasonblais** [comment]
Thanks @VeraLyu! Looks like there's a build failure, can you help take a look?

**Comment by esethna** [comment]
Hi @VeraLyu, hope you're doing well. Just checking in again to see if we can resolve the conflicts on this PR so we can get a test server running?

**Comment by VeraLyu** [comment]
This one is updated and tested.

**Comment by jasonblais** [comment]
@esethna please help with testing next week when you have the chance, so we can move this PR to dev review if it looks okay?

**Comment by coreyhulen** [comment]
@hmhealey can we merge this?

**Comment by hmhealey** [comment]
Yeah, I don't see why not

**Pull request merged**
