### PR TITLE
PLT-3193 Added channel push notification preferences

### PR DESCRIPTION
**Pull request by DavidLu1997**
#### Summary

Added channel push notification preferences. They should behave the same way as desktop notification preferences (Channel specific settings override all other settings).

If push notifications are disabled in the system console, the section does not show up in channel notification preferences.
#### Ticket Link

https://mattermost.atlassian.net/browse/PLT-3193
#### Checklist
- [x] Added or updated unit tests (required for all new features)
- [x] All new/modified APIs include changes to the drivers
- [x] Has UI changes
- [x] Includes text changes and localization files updated

### CODE REVIEW

**Comment by coreyhulen** [comment]
Lets hold off on this until the perf branch is merged

**Comment by jasonblais** [comment]
Perf branch merged, @DavidLu1997 please help with rebase and we can fire a test server?

**Comment by jasonblais** [comment]
Sorry, this needs a rebase..

**Comment by jasonblais** [comment]
Adding WIP label until build errors fixed

**Comment by jasonblais** [comment]
@esethna Please help review when you get the chance?

**Comment by esethna** [comment]
Hey @DavidLu1997 sorry for the delay on reviewing this, after a brief test Yang and I ran into a few issues,

There seems to be a console error being thrown when you change the channel push notification setting, then click save. The setting does not save.

Also it seems to be defaulted to "Never" the first time I opened the setting. Can we please default it to "Global Default".

**Comment by DavidLu1997** [comment]
@esethna should be fixed now

**Comment by esethna** [comment]
@DavidLu1997 thanks, after another test there seems to be an issue with posts appearing in Mattermost after the notification setting is changed.

Repro:
1. Change the channel push notification preference to "For all activity", Save
2. Post with a second account into the channel with modified push notification preferences,

Observed:
Push notifications are received as expected but posts from the second account only appear on desktop after switching channels or refreshing the page.

Expected:
Push notifications are received and the posts appear in the channel as normal on desktop

**Pull request closed without merging**
