### PR TITLE
PLT-488 Update incoming webhooks to hide DMs and accept direct JSON payloads.

### PR DESCRIPTION
**Pull request by jwilander**
Also turned on incoming webhooks by default.

### CODE REVIEW

**Comment by hmhealey** [comment]
Looks good

**Comment by crspeller** [comment]
+1

**Comment by coreyhulen** [comment]
+1.  looks good but you should also modify the config.json files in docker/dev and docker/local.  Feel free to merge after updated configs.

**Comment by jwilander** [comment]
Waiting on Travis to pass

**Pull request merged**
