### PR TITLE
PLT-4042 Moved {createSetHeaderButton(channel)} order

### PR DESCRIPTION
**Pull request by cybershambles**
https://mattermost.atlassian.net/browse/PLT-4042

### CODE REVIEW

**Comment by cybershambles** [comment]
Confirmed change.
Invite is always first in town-hall, new channel and private channels.

**Comment by jasonblais** [comment]
Thanks again @cybershambles, much appreciated!

Verified on the test server (on Windows 10, Chrome) as well.

**Comment by enahum** [comment]
+1

**Comment by DavidLu1997** [comment]
+1

**Comment by jwilander** [comment]
+1

**Pull request merged**
