### PR TITLE
PLT-6023: Add Users to Team in WebApp.

### PR DESCRIPTION
**Pull request by grundleborg**
#### Summary
WebApp parts of Add Users to Team.

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-6023

#### Checklist
- [x] Has UI changes
- [x] Includes text changes and localization file updates

### CODE REVIEW

**Comment by jasonblais** [comment]
Verified (on desktop browser and mobile browser)
 - correct order and placement of menu options in desktop and mobile view
 - team invite link works
 - sending email invite works
 - add team member selector works as expected
    - up/down arrows for navigation
    - enter/mouse to select
    - enter/Go to confirm
    - users can be removed and added up to 20 at a time
 - permissions to add people to a team correctly applied against the team invite policy setting

Couple of notes:

1) `Add Member to Team` --> `Add Members to Team`

image

Sorry, this is on me. The UI text should be `Members` to match the same option for channels

2) Member count doesn't update after you add users to a team.

Note: Member count updates properly when you add users to a channel

image

3) Most items in section 2 [of the spec](https://docs.google.com/document/d/16loc5SoOe0xWxpAS9XIKckOsoCWFyjFoXPjjpmPjVF4/edit) don't work, not sure if that was missed during implementation?

image

-----

Other notes: Will queue the following items for UX discuss, which are related to the DM selector, not this PR
 - changing the "Add Members to Channel" modal to use the same DM selector, for consistency
 - better experience after you've reached the limit of how many users you can add to a team
     - now the selection stops working, but it's confusing why I can't add more people to a team (same when creating a GM, hence not related to this PR)

**Comment by grundleborg** [comment]
1. Fixed
2. This is an existing issue. If you try adding a member through any of the existing methods (email invite, invite link) the member count doesn't update for the existing members in the UI until there's a refresh. Would it be OK to suggest this is made a separate bug ticket?
3. You are right, I misunderstood this, thinking that it was already taken care of automatically, which of course it isn't, because at the moment the action to join a new team is always actively taken by the joining user, not by someone else. I'll look into how to do this now.

**Comment by grundleborg** [comment]
Updated again. This solves all of 3. except for the wording of the system messages, and correspondingly the notifications. I'm investigating them now, but they look to be a bit more involved. Given that code cut-off is imminent, we could consider deferring that bit? What do you think @jasonblais ?

**Comment by jasonblais** [comment]
1. 👍 
2. Ticket: https://mattermost.atlassian.net/browse/PLT-6197
3. Verified new team icon appears in the sidebar. Verified team sidebar appears if the user only belonged to one team before being added to a second one. Verified user automatically added to Town Square and Off-Topic.

I'm less worried about the exact wording (it can be changed later), but it would be important to trigger a mention/notification to the user -- if they belong to a few teams already, they might not realize they were added to a new team (and be confused after they do realize)

**Comment by grundleborg** [comment]
Have managed to fix 3 in full, so you can restart the spinmint and do PM review again on this @jasonblais - however, it also incorporates the code changes from #5968 and #5969 so these need to be reviewed and merged before this one.

**Comment by jasonblais** [comment]
Thanks @grundleborg! Looks like the build failed,

**Comment by jasonblais** [comment]
https://github.com/mattermost/platform/pull/5969 merged so removing `Awaiting PR` label

**Comment by grundleborg** [comment]
Devs, ignore the server side changes in this PR when reviewing - they've already been merged as part of another PR.

**Pull request merged**
