### PR TITLE
Slash command: goto_location not working as expected

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
Slash command: goto_location not working as expected, it was not opening the links. Now it open the external link and also relative to the Mattermost

#### Ticket Link
https://github.com/mattermost/platform/issues/4359

### CODE REVIEW

**Comment by jasonblais** [comment]
@cpanato Glad to see you around! Can you help take a look at the build failure?

**Comment by jasonblais** [comment]
@cpanato Thanks! Can you also help share the testing steps you did to reproduce the original issue?

**Comment by cpanato** [comment]
@jasonblais sure, I used a small script created by @jwilander and he shared that on the dev channel.
I changed that to add the goto_location and did two test cases:

1 - A goto_location with a relative path like /TeamName/channels/off-topic. when you can the slash command the return should redirect you to the off topic channel.

2 - using an external URL like www.mattermost.org. when you call the slash command it should open a new window and go to the site.


this is the script I used:

```
from flask import Flask
from flask import request
app = Flask(__name__)

@app.route('/')
def root():
    return "Server is running"

@app.route('/test_command', methods=['POST'])
def newpost():
    print request.headers
    print request.get_data()
    return '{"response_type": "in_channel", "text": "This is some response text", "username": "TestCommandServer", "goto_location": "/<CHANGE TO TEAM NAME>/channels/off-topic"}'

if __name__ == "__main__":
    app.run()
```

`"goto_location": "/<CHANGE TO TEAM NAME>/channels/off-topic"` for test case 1
`"goto_location": "http://www.mattermost.org"` for test case 2

**Comment by jwilander** [comment]
I can test it

**Comment by jwilander** [comment]
Apologies, got tied up with some other things. Will test + review today

**Comment by grundleborg** [comment]
Thanks @cpanato - looks good.

**Pull request merged**
