### PR TITLE
translations PR for 3.5

### PR DESCRIPTION
**Pull request by enahum**
Ideally this PR should be review by community members for each language.

Note: In the event that you see an english translation instead of the desired language is because this PR was submitted before the translation was made on the Mattermost Translation Server and probably will be submitted for the next PR.

### CODE REVIEW

**Comment by cpanato** [comment]
pt-br lgtm

**Comment by meilon** [comment]
de looks good

**Comment by aeomin** [comment]
zh-CN looks ok.

**Comment by kaakaa** [comment]
`ja` looks good.

**Comment by chikei** [comment]
`zh_TW` LGTM

**Comment by ArchRoller** [comment]
`ru` ok.

**Pull request merged**
