### PR TITLE
PLT-3870 Use correct column type for Postgres TriggerWhen column

### PR DESCRIPTION
**Pull request by jwilander**
#### Summary
I thought this was supposed to be a boolean before when fixing it originally, I was wrong it should be an integer.

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-3870

#### Checklist
- [x] Touches critical sections of the codebase (upgrade)

### CODE REVIEW

**Comment by enahum** [comment]
+1

**Comment by enahum** [comment]
do we want to test this?

**Comment by jwilander** [comment]
I tested it locally

**Comment by crspeller** [comment]
+1

**Comment by hmhealey** [comment]
+1

**Pull request merged**
