### PR TITLE
PLT-4606: Date separator in RHS

### LINKED ISSUE #5291: [Help Wanted] [PLT-4606] Add date separators to the right hand side to prevent dates overlapping the '...' menu on mobile right hand sidebar
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-4606)

Add date separators to the right hand side (like in the center channel).

image

The first date separator should appear below the channel name given at the top of right hand sidebar. Other date separators would appear if the date changes in the thread.

This prevents issues where the date can overlap with the '...' menu on mobile right hand sidebar (see below).

image

### PR DESCRIPTION
**Pull request by mikaoelitiana**
#### Summary
Use date separator in right hand sidebar like in main posts

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-4606

#### Checklist
- [x] Has UI changes

fixes #5291

### CODE REVIEW

**Comment by jasonblais** [comment]
Sorry @mikaoelitiana, looks like your branch has conflicts with two of the files. Can you help rebasing the branch and I'll spin up a test server after?

**Comment by mikaoelitiana** [comment]
Ok I will do that

**Comment by mikaoelitiana** [comment]
I update my commit after rebase.

**Comment by jasonblais** [comment]
Thanks @mikaoelitiana! Looks like the rebase took additional changes not related to #5291

**Comment by mikaoelitiana** [comment]
Oh sorry for that. I will close this and make another pull request with another branch

**Pull request closed without merging**
