### PR TITLE
PLT-3846 Fixed loading screen not disappearing upon joining team

### PR DESCRIPTION
**Pull request by DavidLu1997**
#### Summary
Fixed an endless loading screen on Windows/Chrome when an user joins a team through an invite link/the select team screen while logged in.

We set `loading = false` and `loading = true` in seemingly random places, it should be fine now. This is cleaned up in PLT-2951

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-3846

### CODE REVIEW

**Comment by coreyhulen** [comment]
+1

**Comment by crspeller** [comment]
+1

**Comment by jasonblais** [comment]
@DavidLu1997 Still reproducing for me on team creation

image

**Comment by jasonblais** [comment]
Have tested on CI, and the issue reported above reproduces on RC3. It is tied with a user leaving a team, after which the error intermittently occurs. [Ticket added for v3.4](https://mattermost.atlassian.net/browse/PLT-3881) and a [known issue filed for v3.3](https://github.com/mattermost/docs/pull/352/files#diff-6d8bc7fdf1108df5a6734816051a32e3)

**For this PR:** 

+1 

Everything works as expected both for Windows and Mac. Loading screen disappears when joining a team, no longer requiring a refresh.

**Pull request merged**
