### PR TITLE
Unescape HTML entities in e-mail titles (fixes #3906)

### LINKED ISSUE #3906: HTML entities in e-mail title
#### Summary
I get HTML entities when there is `&` in an e-mail title:
capture d ecran_2016-08-30_15-00-16

#### Steps to reproduce
1. Create a team with `&` in the title.
1. Send a notification.

#### Expected behavior
`&` is displayed correctly.

#### Observed behavior
`&` is displayed as `&amp;`

### PR DESCRIPTION
**Pull request by Rudloff**
#### Summary
This PR unescapes HTML entities in e-mail notification titles.

#### Ticket Link
https://github.com/mattermost/platform/issues/3906

### CODE REVIEW

**Comment by enahum** [comment]
Hi @Rudloff the build is failing cause of a GOFMT issue

**Comment by Rudloff** [comment]
I fixed the issue and updated the build.

**Comment by jasonblais** [comment]
+1

Tested on Windows 10, Chrome using various combinations of team names with and without HTML entities.

Thanks @Rudloff!

**Comment by coreyhulen** [comment]
+1

**Comment by jwilander** [comment]
+1

**Pull request merged**
