### PR TITLE
PLT-827 Changing email notifications to use permalinks

### PR DESCRIPTION
**Pull request by crspeller**

### CODE REVIEW

**Comment by hmhealey** [comment]
+1 for dev review

**Comment by enahum** [comment]
+1 for dev

**Comment by jasonblais** [comment]
Tested on Windows 10, Chrome
 - links to the correct post in a public channel, private group, DM
 - links to the correct post containing `@mention`, `@channel`, name mention, a system message containing the user's username, or a regular direct message
 - links to the correct post located behing the "Load More Messages" indicator

Queued for UX meeting: If I reply to the post, I don't see it in the center channel as I'm still in permalink view. I don't think it satisfies the 'obvious' design principle

image

**Comment by jasonblais** [comment]
We'll keep the functionality submitted here - if we hear other requests from customers/community, we can adjust the permalink view at that time

**Pull request merged**
