### PR TITLE
PLT-1297 Replaced SearchAutocomplete with new suggestion components

### PR DESCRIPTION
**Pull request by hmhealey**
Redo of the last pull request now that I've reorganized a lot of the code. The new stuff is:
1) SuggestionBox is passed providers as props now instead of children and thus doesn't need to do funky prop manipulation stuff for them.
2) Providers are now separate from the rendering and from each other. The code from the previous SearchSuggestionProvider is now split across SuggestionList (still a component) and SearchChannelProvider/SearchUserProvider (singletons that aren't components).
3) Suggestions are stored with a ReactComponent that will be used to render them. These are essentially stateless components, but not completely because that would prevent them from being used as refs. Those refs are needed to scroll the SuggestionList when navigating it by keyboard.

### CODE REVIEW

**Comment by coreyhulen** [comment]
@hmhealey maybe we can find some time today for a team review?

**Comment by hmhealey** [comment]
@crspeller @jwilander Changed the SuggestionProviders to no longer be singletons so it's ready for final review

**Comment by ninja-** [comment]
Is this purely a backend refactor or does change some visible behaviour?

**Comment by hmhealey** [comment]
There shouldn't be any visible differences. It's the first part of a rewrite of the various autocomplete systems in the search box and post textbox so that they all work the same and are more easily extended.

**Comment by jwilander** [comment]
+1

**Comment by coreyhulen** [comment]
+1

**Comment by crspeller** [comment]
+1

**Pull request merged**
