### PR TITLE
PLT-2939 Fix Default slash command icon is invalid

### PR DESCRIPTION
**Pull request by enahum**

### CODE REVIEW

**Comment by jwilander** [comment]
Instead of having a blank constant, can we just use `""` in it's place and remove the constant? I did a quick grep and it's only used in one place I think

**Comment by enahum** [comment]
Let me check and if thats correct i'll remove the constant

**Comment by enahum** [comment]
@jwilander check it out

**Comment by jwilander** [comment]
+1

**Comment by hmhealey** [comment]
+1

**Pull request merged**
