### PR TITLE
PLT-3537 Added a space before all entries in @mention autocomplete

### PR DESCRIPTION
**Pull request by hmhealey**
#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-3537

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields.]
- [ ] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [ ] Has driver changes that have been merged and package.json updated
- [ ] Has enterprise changes (please link)
- [x] Has UI changes
- [ ] Includes text changes and localization files updated
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by crspeller** [comment]
Why does this work?

**Comment by hmhealey** [comment]
I just moved the space from being included as part of the description, but since I was having to do that for 4 different cases, I just moved it to be just before the description. The `@all` and `@channel` cases have their own localized descriptions (not shown in the diff) that didn't begin with spaces and I didn't want to have to go through adding spaces to all the localized versions.

**Comment by crspeller** [comment]
+1

**Comment by jwilander** [comment]
+1

**Pull request merged**
