### PR TITLE
Fixed PLT-1798

### PR DESCRIPTION
**Pull request by sunchips**
Notes:
- Seems to work.
- NO tests.
- ~~Google translated Spanish localization.~~
- Added setting_button.jsx as component that can be used in the future.

### CODE REVIEW

**Comment by enahum** [comment]
@sunchips Please remove the spanish translations from the es.json file.

Thanks.

**Comment by sunchips** [comment]
@enahum done.

**Comment by it33** [comment]
Thanks @sunchips, thanks @enahum!

A server has been created to test this PR: http://i-d8720202.spinmint.com:8065

Any volunteers from the community open to helping test this and confirming it works? https://mattermost.atlassian.net/browse/PLT-1798

**Comment by jwilander** [comment]
Hi @sunchips, sorry for the late response.

Your new component is very similar to `setting_item_max.jsx`. I think it would be better to just modify that component to allow customizing the text of the submit button rather than create a whole new component for it. Unless there's some reason that wouldn't work that I'm missing

I also noticed some weird behaviour when testing your changes that caused some error text to appear both in the confirm dialog and below the setting itself. Ideally, the confirm dialog should always close on a button press and any error text should be shown only with the setting. See my screenshot:
screen shot 2016-02-22 at 8 18 21 am

**Comment by sunchips** [comment]
@jwilander Yeah, I didn't like the name. max and min didn't make any sense to me.

I'll make the behavior as you have suggested. I'll update when the changes are done.

**Comment by sunchips** [comment]
I'll work on this tonight. Sorry for the delay guys.

**Comment by crspeller** [comment]
@sunchips Please re-submit when ready.

**Pull request closed without merging**
