### PR TITLE
fix PLT-3916

### PR DESCRIPTION
**Pull request by seyoung-hyun**
Please make sure you've read the [pull request](http://docs.mattermost.com/developer/contribution-guide.html#preparing-a-pull-request) section of our [code contribution guidelines](http://docs.mattermost.com/developer/contribution-guide.html).

When filling in a section please remove the help text and the above text.

#### Summary
[A brief description of what this pull request does.]

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-3916?jql=issuetype%20%3D%20Bug%20AND%20status%20%3D%20Open%20AND%20resolution%20%3D%20Unresolved

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [ ] All new/modified APIs include changes to the drivers
- [ ] Has enterprise changes (please link)
- [x] Has UI changes
- [ ] Includes text changes and localization files updated
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by coreyhulen** [comment]
I'll defer to @asaadmahmood

**Comment by enahum** [comment]
Yeap @asaadmahmood check this one, if thats the only change needed then +1

**Comment by asaadmahmood** [comment]
I think this may not fix the issue as the date can be longer for eg:  in some cases and it may leave less space for the flag icon.
I think a better fix would be to convert the full months in the RHS to 3 letter months.

screen shot 2016-08-23 at 6 17 18 pm

**Comment by asaadmahmood** [comment]
I have submitted a fix for this [here](https://github.com/mattermost/platform/pull/3898), so we can close this PR.

**Pull request closed without merging**
