### PR TITLE
PLT-1383: Infinite scroll

### PR DESCRIPTION
**Pull request by VeraLyu**
Automatically load the previous messages instead of click link

Please make sure you've read the [pull request](http://docs.mattermost.com/developer/contribution-guide.html#preparing-a-pull-request) section of our [code contribution guidelines](http://docs.mattermost.com/developer/contribution-guide.html).

When filling in a section please remove the help text and the above text.

#### Summary
Automatically load the previous messages instead of click link

#### Ticket Link
issue: https://github.com/mattermost/platform/issues/5292
ticket: https://mattermost.atlassian.net/browse/PLT-1383

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Has UI changes
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/platform/blob/master/i18n/en.json) and [.../webapp/i18n/en.json](https://github.com/mattermost/platform/tree/master/webapp/i18n/en.json)) updates

### CODE REVIEW

**Comment by jasonblais** [comment]
@lindalumitchell please help with testing? When you do, please check it works on both regular and permalink views

@VeraLyu Big thanks! It'll be a great improvement :)

**Comment by lindalumitchell** [comment]
@jasonblais @VeraLyu this is great! Scrolling up through message history, no link clicking is necessary; "Loading more messages" displays at the top, and more messages just load. Also tested and worked as expected in permalink view. (Checked in RHS reply view, and a 66-reply-long thread displayed all messages on scrolling, up to the beginning of the thread, without needing "Loading more messages.") No issues found. Such a nice improvement!

**Comment by jasonblais** [comment]
Thanks! 

@VeraLyu Tested and works quite nicely -- sometimes I noticed that after loading messages, the channel might jump to the bottom or to the top. Not sure if that's related to our existing issues with scrolling.

Mostly it was really smooth, just curious to hear your thoughts on the jumping behaviour.

**Comment by VeraLyu** [comment]
@jasonblais I think I encountered the problem you mentioned too. After some investigation I found because we called "checkAndUpdateScroll" in ComponentDidUpdate every time PostList is re-rendered(which happens when fetched more posts through loading more). Will check if I can figure out a way to distinguish such scenario and not update scroll.

**Comment by lindalumitchell** [comment]
Yes, @jasonblais @VeraLyu I saw that too; I thought it was related to https://mattermost.atlassian.net/browse/PLT-5833 (described in more detail in https://mattermost.atlassian.net/browse/PLT-5568, which was closed to be included in 5833).

**Comment by esethna** [comment]
Thanks @VeraLyu, appreciate the pull request!  Just letting you know that there may be a delay in reviewing and merging your PR since we are approaching code complete for v3.8, releasing April 16th. Please see our [release process](https://docs.mattermost.com/process/release-process.html) for more details.

**Comment by VeraLyu** [comment]
This one has been updated, thanks.

**Comment by jasonblais** [comment]
Re-tested on Win10/Chrome and iOS/Safari.

Very good work here overall. The scrolling issues are mitigated and I didn't find anything major. There might very well be a few remaining issues but as @lindalumitchell mentioned, these will be fixed separately by https://mattermost.atlassian.net/browse/PLT-5833

I did find one thing where sometimes you could end up in a loop where you keep loading more messages. Particularly on iOS Safari browser, the 'load more messages' request was sometimes made multiple times so you ended up losing your position and loaded lots of messages at once.

Is there a way to update the code so that the request is made at most once each time?

**Comment by jasonblais** [comment]
Hey @VeraLyu, you may have missed my note above. Re-sending here just in case

> I did find one thing where sometimes you could end up in a loop where you keep loading more messages. Particularly on iOS Safari browser, the 'load more messages' request was sometimes made multiple times so you ended up losing your position and loaded lots of messages at once.

> Is there a way to update the code so that the request is made at most once each time?

**Comment by VeraLyu** [comment]
@jasonblais Do you mean we should not emit another "loading" request before a previous one comes back and view get refreshed? I think that's reasonable and will figure that out.

**Comment by jasonblais** [comment]
@VeraLyu Yeah - at the moment the request might happen several times, so several "load more messages" actions are performed.

As a result, my location on the page has moved significantly.

PS: It doesn't happen always, but it was more noticeable on mobile browser, such as iOS Safari.

Thanks for looking into it :)

**Comment by jasonblais** [comment]
Thanks again @VeraLyu for working on this, really appreciate it. Curious if there are any updates from last time?

We'd be happy to help if you have any questions

**Comment by jasonblais** [comment]
Thanks @VeraLyu for working on this pull request - @jwilander is actually working on an improvement which will add the infinite scrolling feature as well.

So I'll close this PR for now in favor of the upcoming one.

**Pull request closed without merging**
