### PR TITLE
Allow to switch between default and emoji-one emoji style

### PR DESCRIPTION
**Pull request by florianorben**
Hey,

adds an option to settings -> display to allow switching between default and [Emoji One](http://emojione.com) emoji style.

Also fixes, that twemoji renders emojis in a completely different style

### CODE REVIEW

**Comment by florianorben** [comment]
Ah, btw. License:
http://emojione.com/developers -> http://creativecommons.org/licenses/by-sa/4.0/legalcode

Affiliation link to emojione is included, so should be fine

**Comment by ninja-** [comment]
:blue_heart: 
Was it my recent request that motivated this awesome PR?

**Comment by florianorben** [comment]
yes :)

**Comment by ninja-** [comment]
Perfect, thank you!

**Comment by florianorben** [comment]
You're welcome :)

**Comment by ninja-** [comment]
Oh now that we are on this topic, it would be nice to make the emojis bigger, maybe configurable also?

**Comment by ninja-** [comment]
Also good time to figure out why is : ( broken on master?

**Comment by florianorben** [comment]
> Oh now that we are on this topic, it would be nice to make the emojis bigger, maybe configurable also?

code-wise this shouldn't be a problem at all, the icons should also have a resolution of at least 72x72, so that wouldn't be a problem there too ;)
This should probably be decided by the core team, perhaps @asaadmahmoodspin has a good idea :)?

> We are moving further away from hosting on subpath....
I wish mattermost just used ember-style /APP/#!/channel/test urls :(

I guess this isn't too much of a problem, we just need a `basePath` variable somewhere that we write in front of every path and et voila that was easy :P.
Nah, seriously, I really don't see too many problems here, just some paths that need to be changed ;)

**Comment by florianorben** [comment]
> Also good time to figure out why is : ( broken on master?

PLT-1063 :)
No idea though, I had a quick look at the code, it actually looks fine :-/

**Comment by ninja-** [comment]
Where's the : ) -> : happy: etc mapping anyway?

**Comment by ninja-** [comment]
My very random guess... The ( part could be messing up a regexp and ) would still work in such case based on my experience with regexps...

**Comment by florianorben** [comment]
https://github.com/mattermost/platform/blob/master/web/react/utils/emoticons.jsx#L14
The regex is fine I'd say :-/

**Comment by ninja-** [comment]
Weird. You sure it's deployed on demo?

**Comment by florianorben** [comment]
The emoji parsing stuff, yes, that's the strange thing - looks fine but doesnt work.

**Comment by ninja-** [comment]
To repeat my findings Here looks like markdown is to blame. It will eat the Asterisk for Kissingen emoji.

**Comment by ninja-** [comment]
We are leaving this PR as a WIP, hoping to fix broken emoji mapping tomorrow.

**Comment by jwilander** [comment]
Cool, added DO NOT MERGE label until it's ready for review

**Comment by florianorben** [comment]
As discussed, switch to emoji one as default emoji style and remove setting to switch.
Btw, all extra smileys like :shipit: etc are still included ;)

@jwilander Ready for merge/review!

**Comment by ninja-** [comment]
Why remove setting?

**Comment by ninja-** [comment]
I think this should wait and allow #1582 to go first

**Comment by coreyhulen** [comment]
+1

**Comment by crspeller** [comment]
+1

**Pull request merged**
