### PR TITLE
Switch to right-hand sidebar statement

### PR DESCRIPTION
**Pull request by wget**
#### Summary
Switch to right-hand sidebar statement instead of the acronym RHS nobody knows about. Avoid to create confusion at translators.

#### Ticket Link
N/A

#### Checklist
- [x] Has UI changes
- [x] Includes text changes and localization files updated

### CODE REVIEW

**Comment by jasonblais** [comment]
Thanks @wget!

**Comment by jwilander** [comment]
+1

**Comment by crspeller** [comment]
@wget Do you mind rebasing this? Thanks!

**Comment by wget** [comment]
@crspeller Done! Thanks to @JanJoris for letting let me know about the `git pull myRemote master --rebase` command :-)

**Pull request merged**
