### PR TITLE
PLT-3020 Re-added errors to login page when no username/password is added

### PR DESCRIPTION
**Pull request by hmhealey**
Need to confirm that this actually fixes the problem of the state getting out of sync with the UI due to a password manager

### CODE REVIEW

**Comment by hmhealey** [comment]
@crspeller You were able to repro this issue back when it originally happened, can you see if it still happens on the test instance?

**Comment by crspeller** [comment]
@hmhealey Still occurs for me. When I press the sign-in button both fields go blank and I get `Please enter your Email or Username`

I use http://keepass.info/ with the KeePass HTTP plugin for Chrome.

**Comment by crspeller** [comment]
@hmhealey +1 Works great after update.

**Comment by jwilander** [comment]
+1

**Pull request merged**
