### PR TITLE
User list: surround email with <>

### PR DESCRIPTION
**Pull request by chengweiv5**
Signed-off-by: Chengwei Yang <yangchengwei@qiyi.com>

### CODE REVIEW

**Comment by lfbrock** [comment]
Hi @chengweiv5, can you help add more details on why you want to make this change?

**Comment by chengweiv5** [comment]
Without this patch(sorry, it failed to upload a screenshot, I'm in china), the user list from "system console" will look like

```Chengwei Yangyangchengwei@qiyi.com```

It's, em, unreadable, right?

With this patch, it looks like

```Chengwei Yang <yangchengwei@qiyi.com>```

A little better I think.

**Comment by chengweiv5** [comment]
Seems I can not create an issue in JIRA project, my username there is "chengwei"

**Comment by it33** [comment]
Thanks for the feedback! Sorry, the "Needs Jira ticket" should probably be called "Needs Jira ticket from core team" since opening a Jira ticket is part of the process to approve a change. 

Full [process is documented in Contribution Guidelines](http://docs.mattermost.com/developer/contribution-guide.html)

**Comment by lfbrock** [comment]
Okay I understand, I think @asaadmahmoodspin may have already moved the username + email onto two separate lines on master

**Comment by asaadmahmoodspin** [comment]
Yes they're on 2 separate lines on master, so I don't we need this now.

**Comment by chengweiv5** [comment]
OK， if so, I'm closing this one.

**Pull request closed without merging**
