### PR TITLE
Support Slack attachments in response to outgoing webhooks

### PR DESCRIPTION
**Pull request by simon0191**
#### Summary
Support standard Slack messages with or without attachments and with in_channel or ephemeral type in response to outgoing webhooks.

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-3658
#4237

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Added or updated unit tests (required for all new features)
- [ ] Includes text changes and localization file ([.../i18n/en.json]

### CODE REVIEW

**Comment by simon0191** [comment]
@jasonblais @grundleborg I have some questions:

- Why is the issue tagged with ReactJS?
- How can I test the outgoing webhook response? Should I create a server inside the test?
- I saw that there's some logic repeated in the functions that handle incoming webhooks and command responses, and now outgoing webhook responses. What do you think about grouping some common logic and create something like IncomingMessageRequest ... or something like that?

**Comment by jasonblais** [comment]
Will defer to @grundleborg on this one, given his better-skilled technical knowledge :)

**Comment by grundleborg** [comment]
@simon0191 sorry for the slow reply. Here's some answers to your questions:

1. I'm not sure why it's tagged with ReactJS - quite possibly it doesn't need to involve any client side changes.
2. Yeah, I think that's the only way really of doing it. Start up a trivial single-purpose server in the tests and have the outgoing webhooks go to that.
3. If you'd like to take on splitting out the duplicate code into it's own functions, I think it would be an excellent idea, either as part of this ticket, or as a separate ticket.

**Comment by jasonblais** [comment]
Thanks @simon0191 for your help so far! If you have any questions about George's response above, don't hesitate to let us know,

I added a "Work in progress" label for now as it sounded there's a couple of outstanding changes to do. 

Really appreciate your contributions!!

**Comment by jwilander** [comment]
Hi @simon0191, I'm closing this due to inactivity. Feel free to re-open if you get a chance to work on it some more

**Pull request closed without merging**
