### PR TITLE
Multiple UI Improvements

### PR DESCRIPTION
**Pull request by asaadmahmoodspin**
- Improving contrast of channels in LHS.
- Improving form elements for dark themes.
- Improving more modal for dark themes and also invite member modal.

### CODE REVIEW

**Comment by jwilander** [comment]
+1

**Comment by asaadmahmoodspin** [comment]
Just improving form-control:focus code for signup pages.

**Comment by jwilander** [comment]
Still +1

**Comment by crspeller** [comment]
+1

**Pull request merged**
