### PR TITLE
translations PR 20170220

### PR DESCRIPTION
**Pull request by enahum**
Ideally this PR should be review by community members for each language.

Note: In the event that you see an english translation instead of the desired language is because this PR was submitted before the translation was made on the Mattermost Translation Server and probably will be submitted for the next PR.

### CODE REVIEW

**Comment by enahum** [comment]
@jasonblais FYI the webhook notification for this didn't fire

**Comment by enahum** [comment]
lol got it after a few minutes

**Comment by kaakaa** [comment]
`ja` LGTM

**Comment by jasonblais** [comment]
@enahum I'll fire the webhook notification a bit earlier, it seems to fire about an hour late

**Comment by jasonblais** [comment]
+1 from me as well

**Comment by meilon** [comment]
`de` LGTM

**Comment by jasonblais** [comment]
Thanks @kaakaa and @meilon, appreciate it

**Pull request merged**
