### PR TITLE
PLT-2170 Send payload in application/json for outgoing webhooks

### PR DESCRIPTION
**Pull request by tbalthazar**
The Add outgoing webhook UI now has a 'Content-Type' field that allows
to choose between application/x-www-form-urlencoded and
application/json. All outgoing webhooks created before this change will
be considered as x-www-form-urlencoded. There's also a minor change in
the way the outgoing webhook summary is displayed: the 'Callback URLs'
label was missing.

### CODE REVIEW

**Comment by tbalthazar** [comment]
If you want to play with the outgoing webhooks with Mattermost running on your local machine, here is a super simple quick and dirty echo server:
https://play.golang.org/p/xTpc143wKo

Just create a few webhooks with `http://0.0.0.0:8080` as the callback URL. The echo server will reply back and log a few info about the request.

**Comment by jwilander** [comment]
Hi @tbalthazar, good stuff! I just have a couples comment. 

In `sql_webhook_store.go` can you set the max size for the new column inside the `NewSqlWebhookStore()` function at the top? This will ensure the table gets created correctly from scratch on new DB instances.

Also can we bump the column size up to 128? It's unlikely that we'll start supporting other Content-Types that go that long but I think it would be better to safe. Let me know your thoughts

**Comment by tbalthazar** [comment]
> can you set the max size for the new column inside the NewSqlWebhookStore() 

Good catch, thanks!

> Also can we bump the column size up to 128?

Sure, better safe than sorry ;)

**Comment by jwilander** [comment]
Thanks! +1

**Comment by crspeller** [comment]
+1

**Pull request merged**
