### PR TITLE
PLT-1063 Switched marked to forked version

### PR DESCRIPTION
**Pull request by hmhealey**
This switch allows us to modify marked internals while 1) avoiding copying all their code into our codebase as we've previously done and 2) keeping a better reference for what we've changed for the next time marked is updated.

The reason I needed to make changes to marked is because it would break up certain character strings into multiple tokens which would get rendered separately so for example `:ice_cream:` would be rendered as `:ice` and `_cream:` and not get recognized as an emoji and `:(` would similarly be split into `:` and `(`. I've changed marked's lexer to store a list of tokens and recombine any adjacent plain text tokens so that the renderer just sees `:ice_cream:` and `:(` without having to make potentially breaking changes to the regex.

The relevant changes to marked are available [here](https://github.com/hmhealey/marked/compare/71d8c6583004f2f600e1f847e1fe8bc964865b23...cb85e5cc81bc7937dbb73c3c53d9532b1b97e3ca)

### CODE REVIEW

**Comment by ninja-** [comment]
:+1:

**Comment by coreyhulen** [comment]
We should fork from mattermost not hmhealey

**Comment by hmhealey** [comment]
Thanks @coreyhulen for getting my marked fork into the organization. The PR is updated to point to it instead of my local one.

**Comment by jwilander** [comment]
+1

**Comment by crspeller** [comment]
+1

**Pull request merged**
