### PR TITLE
PLT-3225 Firefox: Channel header disappears after renaming a channel

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
Fixes an issue where the channel name in Channel header disappeared

#### Issue/Ticket Link
https://mattermost.atlassian.net/browse/PLT-3225

### CODE REVIEW

**Comment by crspeller** [comment]
This doesn't seem like the right fix. Why is the channel ID blank in the first place?

**Comment by enahum** [comment]
There are some events that trigger change and and for some reason the prop is undefined at some point

**Comment by hmhealey** [comment]
[It's blank if you switch to a channel that the browser doesn't have](https://github.com/mattermost/platform/blob/master/webapp/components/channel_view.jsx#L28). I assume when it's renamed that the URL changes and then the browser refreshes it from the server or something.

**Comment by jwilander** [comment]
Needs a rebase

**Comment by enahum** [comment]
@jwilander rebased

**Comment by jwilander** [comment]
Bit of a hack but fine with it to get it in for 3.2, +1

**Comment by coreyhulen** [comment]
+1

**Pull request merged**
