### PR TITLE
PLT-3079 System messages trigger notifications when user is mentioned

### PR DESCRIPTION
**Pull request by jwilander**
Also fixes PLT-1366.

### CODE REVIEW

**Comment by enahum** [comment]
+1

**Comment by enahum** [comment]
Needs rebase

**Comment by enahum** [comment]
@jwilander needs another rebase

**Comment by jwilander** [comment]
Jeez, rebase after rebase :P

**Comment by coreyhulen** [comment]
+1, assuming successful build :)

**Pull request merged**
