### PR TITLE
Change ordering of at-mention suggestions

### PR DESCRIPTION
**Pull request by npcode**
#### Summary

Change ordering of at-mention suggestions. List members in the current channel first.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields.]
- [ ] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [ ] Has driver changes that have been merged and package.json updated
- [ ] Has enterprise changes (please link)
- [x] Has UI changes
- [ ] Includes text changes and localization files updated
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by lfbrock** [comment]
Hi @npcode, thanks for the contribution! Would you be able to:

1) Make `@channel` and `@all` their own section, so the ordering appears as: 
- People in the Channel
- @all and @channel
- People not in the channel

2) Add separators between the sections?

**Comment by npcode** [comment]
@lfbrock Good idea! I'll try it.

**Comment by npcode** [comment]
> /var/lib/jenkins/jobs/mattermost-platform-pr/workspace/src/github.com/mattermost/platform/webapp/components/suggestion/at_mention_provider.jsx
>   152:21  error  'filtered' was used before it was defined  no-use-before-define
>
> -- https://build.mattermost.com/job/mattermost-platform-pr/1813/console#skip2content

I can't understaind this failure. I didn't use `filtered` on 152 in `at_mention_provider.jsx` and the `make check-style` passed in my laptop.

**Comment by hmhealey** [comment]
@npcode That's really strange. It looks fine to me and passes ESLint locally as well, but it keeps failing when I rerun the build. Maybe you could try adding `// eslint-disable-line no-use-before-define` to line 152 just to see if that causes ESLint to sort itself out?

**Comment by hmhealey** [comment]
Hey @npcode, do you mind closing and resubmitting this PR? There's something strange going on and that might make it start suddenly working

**Comment by npcode** [comment]
@hmhealey Okay, I'll do it.

**Pull request closed without merging**
