### PR TITLE
Add email images to webpack

### PR DESCRIPTION
**Pull request by enahum**
This should fix the email images not showing

### CODE REVIEW

**Comment by hmhealey** [comment]
Looks good. Mind taking a look at this @crspeller?

**Comment by crspeller** [comment]
@enahum I was hoping to move to attaching the images to the emails that are sent out. That would involve adding that funcitonality to mail.go.

This would reduce the number of client-server dependencies. (something we want to avoid)

**Comment by enahum** [comment]
Ok great!!

I do think that while that is ready this can fix the issue temporarily.

But is your call

2016-04-01 17:07 GMT-03:00 Christopher Speller <notifications@github.com>:

**Comment by crspeller** [comment]
Yup. I haven't started any work on that. So if you want to do it that would be great. Otherwise we can merge this until I get to it.

**Comment by enahum** [comment]
lets merge this for now :)

**Comment by crspeller** [comment]
+1

**Pull request merged**
