### PR TITLE
Re-enable console logging by default

### PR DESCRIPTION
**Pull request by hmhealey**
I know we had this turned off by default for performance reasons, but I think we should just turn it off when we're testing performance. Having it off by default makes debugging difficult.

### CODE REVIEW

**Comment by jwilander** [comment]
We should have it off by default in release builds as well

**Comment by coreyhulen** [comment]
Lets bump it down to INFO at least.

**Comment by hmhealey** [comment]
@coreyhulen Do you mean to drop it to INFO for dev builds or for release builds? I'm going to add a step to `make package` to disable logging to file in the version shipped.

**Comment by coreyhulen** [comment]
@hmhealey leave it enbled just bump it down to INFO like

```
"EnableConsole": true,
"ConsoleLevel": "INFO",
```

**Pull request merged**
