### PR TITLE
PLT-3010 - Updating system console

### PR DESCRIPTION
**Pull request by asaadmahmoodspin**
Hey guys, can we get a PR up for this.

### CODE REVIEW

**Comment by asaadmahmoodspin** [comment]
@coreyhulen @esethna Please do have a look at it.

**Comment by esethna** [comment]
Thanks @asaadmahmoodspin,

A few pieces of feedback:

1) Sounded like the feedback from platform meeting was to move Database to "Advanced" section. Will refer to @coreyhulen to verify if that makes more sense than the current placement in "General"?
2) I don't see the compliance tab. It might be hidden because it's an enterprise feature, I just want to make sure it didn't get lost in the process?
3) I'm noticing that all the help text seems to be justified a few spaces right of the text boxes or radio buttons (see screenshot). Seems a little odd, propose starting the help text left a few spaces?

image

**Comment by asaadmahmoodspin** [comment]
@erikthered I've updated those changes. And yes the compliance is there.

**Comment by esethna** [comment]
Thanks @asaadmahmoodspin, looks good, will refer to @coreyhulen for final review when he is back. Thanks!

**Comment by coreyhulen** [comment]
+1

**Pull request merged**
