### PR TITLE
PLT-2063: Add CLI option to invite user by email

### PR DESCRIPTION
**Pull request by khoa-le**

### CODE REVIEW

**Comment by khoa-le** [comment]
I run the Gofmt on local ok, but on CI it's failure. Can anyone help me? Thanks!

**Comment by enahum** [comment]
Hi @khoa-le thanks for submitting this PR but it seems that you have `gofmt` problems

**Comment by khoa-le** [comment]
Hi @enahum , Can you see the log and have some suggestion for me?

**Comment by crspeller** [comment]
@khoa-le The gofmt output is not too helpfull:
```
diff mattermost.go gofmt/mattermost.go --- /tmp/gofmt719776455	2016-05-28 08:10:18.135098999 +0000 +++ /tmp/gofmt704011130	2016-05-28 08:10:18.135098999 +0000 @@ -799,7 +799,7 @@  			flag.Usage()  			os.Exit(1)  		} -		 +  		if len(flagEmail) == 0 {  			fmt.Fprintln(os.Stderr, flag needs an argument: -email)  			flag.Usage() @@ -815,7 +815,7 @@  				team = result.Data.(*model.Team)  			}  		} -		 +  		var user *model.User  		if result := <-api.Srv.Store.User().GetByEmail(team.Email); result.Err != nil {  			l4g.Error(%v, result.Err) @@ -823,10 +823,10 @@  		} else {  			user = result.Data.(*model.User)  		} -		 +  		invites := []string{flagEmail}  		c := getMockContext() -		api.InviteMembers(c,team, user, invites) +		api.InviteMembers(c, team, user, invites)    		os.Exit(0)  	}
/bin/sh: 1: [: diff mattermost.go gofmt/mattermost.go --- /tmp/gofmt719776455	2016-05-28 08:10:18.135098999 +0000 +++ /tmp/gofmt704011130	2016-05-28 08:10:18.135098999 +0000 @@ -799,7 +799,7 @@  			flag.Usage()  			os.Exit(1)  		} -		 +  		if len(flagEmail) == 0 {  			fmt.Fprintln(os.Stderr, flag: unexpected operator
gofmt failure
```
You should just run gofmt on it locally with the flag that auto fixes problems.

**Comment by khoa-le** [comment]
Thank you very much @crspeller, It's working now.

**Comment by crspeller** [comment]
+1

**Comment by jwilander** [comment]
+1

**Pull request merged**
