### PR TITLE
PLT-6531 Fix JS errors when receiving message when on no teams

### PR DESCRIPTION
**Pull request by jwilander**
#### Summary
Fix JS errors when receiving message when on no teams. I wasn't able to reproduce the exact problem in the ticket but this might have been related.

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-6531

### CODE REVIEW

**Comment by saturninoabril** [comment]
@jwilander I tried to run this locally and it seemed that the issue described on the ticket still persists here - that is the DM does not show unread after rejoining the team.

My observation:
 - On master, the unread shows up when User B joined via `Add Members to Team` but not when joined via `(Get) Team Invite Link`
 - On this PR, the unread momentarily showed up then immediately cleared when User B joined via `Add Members to Team` but not when joined via `(Get) Team Invite Link`

**Comment by jwilander** [comment]
Hmmm I was testing by leaving the team and rejoining through the team selection page and it was working fine. I'll try it through the invite link

**Comment by jwilander** [comment]
@saturninoabril I tried all three joining team methods (link, added, join through team selection page) and the unreads show up for the DMs without issue. Can you give me specific repro steps?

Also please make sure your redux is up-to-date by doing `make clean` in the webapp directory before doing a `make run` to build the client

**Comment by saturninoabril** [comment]
I've tested it again after `make clean` and everything worked fine.

**Pull request merged**
