### PR TITLE
PLT-4977 Sorting teams by display name on team list at system console…

### PR DESCRIPTION
**Pull request by debanshuk**
#### Summary
Sorting teams by name in following team lists:
* Team list when clicking on the three-dotted menu in System Console
* Team list when clicking the "+" button next to "TEAMS" in System Console

#### Ticket Link
Github issue link: https://github.com/mattermost/platform/issues/4775
JIRA ticket link: https://mattermost.atlassian.net/browse/PLT-4977

### CODE REVIEW

**Comment by jasonblais** [comment]
Thanks @debanshuk! 

Tested on Windows 10, Chrome. Looks great! Queuing for second PM review

Found an issue related, but not caused by this PR. Filed ticket here: https://mattermost.atlassian.net/browse/PLT-5021

**Comment by lfbrock** [comment]
Tested this out and found that it's also not sorted in the main menu when you're on a team, but it's not worth fixing since it will be replaced by a sidebar of your teams.

(Not system console) 
screenshot 2016-12-15 11 15 00
(System console) 
screenshot 2016-12-15 11 15 11

**Comment by debanshuk** [comment]
@lfbrock, Yes, as stated here https://github.com/mattermost/platform/pull/4757#issuecomment-266600104, "The ordering in the Main Menu will be resolved by team sidebar PR #4569".

**Comment by jasonblais** [comment]
Thanks @lfbrock and @debanshuk -- that's correct and should be resolved by #4569 

Just waiting for final approval before queuing for dev review.

Great work @debanshuk!

**Comment by it33** [comment]
Tested on Chrome/Win10 and sorting looks okay. 

There are two issues that repro on master that I'll mention here for PM to consider filing: 

1. In LHS a team is called "another" and in the heading in the main panel it's called "lpslfakfoas ()"

Expected: LHS name and center panel name match (or the center panel displays at least what's in the LHS, plus additional information). 

image

2. When a team team is open under System Console > Teams and a second team is opened and we then select System Console > Teams > Users, the user count is blank and formatting for "No users found" is broken

image

However when I click on "Team Statistics" the Total Users count shows "1": 

image

Then, after doing this, when I click back to "Users" we get the correct display: 

image

```
1. In LHS a team is called "another" and in the heading in the main panel it's called "lpslfakfoas ()"

Expected: LHS name and center panel name match (or the center panel displays at least what's in the LHS, plus additional information). 

![image](https://cloud.githubusercontent.com/assets/177788/21253676/44c21636-c315-11e6-87fd-cc4b3f36a52a.png)

2. When a team team is open under System Console > Teams and a second team is opened and we then select System Console > Teams > Users, the user count is blank and formatting for "No users found" is broken

![image](https://cloud.githubusercontent.com/assets/177788/21253714/75dd6f90-c315-11e6-9764-811c3f211445.png)

However when I click on "Team Statistics" the Total Users count shows "1": 

![image](https://cloud.githubusercontent.com/assets/177788/21253733/94fba036-c315-11e6-9fad-daf545e7bbfd.png)

Then, after doing this, when I click back to "Users" we get the correct display: 

![image](https://cloud.githubusercontent.com/assets/177788/21253740/a5eb065c-c315-11e6-90ae-8b455b24fee7.png)
```

**Comment by jasonblais** [comment]
Thanks! Created an issue for both
 - https://mattermost.atlassian.net/browse/PLT-5032
 - https://mattermost.atlassian.net/browse/PLT-5033

Neither is blocking this PR (as they're not caused by it), so I'm sending for dev review next

**Comment by coreyhulen** [comment]
@debanshuk can you rebase your branch.

**Comment by debanshuk** [comment]
@coreyhulen, Done. Rebased the branch from latest state of master branch.

**Pull request merged**
