### PR TITLE
PLT-1042 Add a cancel option for pending posts that have failed to send

### PR DESCRIPTION
**Pull request by samogot**
https://mattermost.atlassian.net/browse/PLT-1042

### CODE REVIEW

**Comment by crspeller** [comment]
+1 Looks good. 
The only thing is the forceUpdate calls everywhere. But they where already there. Created this ticket to take a look at removing them: https://mattermost.atlassian.net/browse/PLT-3000

**Comment by coreyhulen** [comment]
+1 @samogot needs a rebase.

**Comment by samogot** [comment]
@coreyhulen rebase is done

**Comment by crspeller** [comment]
@samogot Thanks!

**Pull request merged**
