### PR TITLE
Let's be consistent with keyboard shortcuts.

### PR DESCRIPTION
**Pull request by wget**
#### Summary
Fix spaces in keyboard shortcuts. Ctrl+Enter should be Ctrl + ENTER to be consistent across the whole codebase.

#### Ticket Link
N/A

#### Checklist
- [x] Has UI changes
- [x] Includes text changes and localization files updated

### CODE REVIEW

**Comment by wget** [comment]
Actually, you should use a sed -i across all your files. The situation is really chaotic. A bunch of files uses `Shift` instead of `SHIFT`, the same applies for Ctrl and Alt.

**Comment by jasonblais** [comment]
Thanks @wget for the pull request! 

We'll take care of the other inconsistencies, looks like there are a few other ones to fix in three files (the others are not user-visible strings)

**Comment by jasonblais** [comment]
+1

**Comment by jwilander** [comment]
+1

**Comment by hmhealey** [comment]
+1 Thanks for fixing that. It was bugging me.

**Comment by wget** [comment]
@hmhealey (cc @jasonblais). Do you know why this commit has not been taken into consideration on Pootle?
screenshot_20161018_230348

**Comment by jasonblais** [comment]
Hm, let me see, maybe it wasn't merged properly

**Comment by jasonblais** [comment]
Yeah, looks like the entry in the [en.json](https://github.com/mattermost/platform/blob/master/webapp/i18n/en.json#L1269) file wasn't merged properly or got overwritten by another PR later... Sorry about that.

We try to avoid them, but it happens at times. If you'd like, you can submit another PR to fix it

**Pull request merged**
