### PR TITLE
Multiple UI improvements

### PR DESCRIPTION
**Pull request by asaadmahmoodspin**
Hey guys, changes include stuff from the following tickets:
https://mattermost.atlassian.net/browse/PLT-2301
https://mattermost.atlassian.net/browse/PLT-2338
https://mattermost.atlassian.net/browse/PLT-2294
https://mattermost.atlassian.net/browse/PLT-2435
https://mattermost.atlassian.net/browse/PLT-2449
https://mattermost.atlassian.net/browse/PLT-2294
https://mattermost.atlassian.net/browse/PLT-2325

### CODE REVIEW

**Comment by jwilander** [comment]
+1

**Comment by hmhealey** [comment]
Where did you get those translations for the "See other themes" link? We're supposed to just leave them blank for new strings so community members can translate them properly

**Comment by asaadmahmoodspin** [comment]
Got those from google translate. Let me know if I should change them to blank.

**Comment by hmhealey** [comment]
Yeah, I think they should be removed. It's better to know that we have missing translations than to have potentially mistranslated ones that we aren't aware of

**Comment by asaadmahmoodspin** [comment]
Done.

**Comment by hmhealey** [comment]
Oh actually you should just delete the translated lines completely instead of blanking them out. That way the UI will just show the default English and enahum's stuff will pick up that there's translations are missing so community members can translate them

**Comment by asaadmahmoodspin** [comment]
Done.

**Comment by hmhealey** [comment]
+1

**Pull request merged**
