### PR TITLE
PLT-3005 Added confirmation screen to integrations

### PR DESCRIPTION
**Pull request by DavidLu1997**
#### Summary
When creating an integration, a confirmation screen now appears with the integration's URL/token, along with a link to appropriate documentation.

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-3005

#### Checklist
- [x] Has UI changes
- [x] Includes text changes and localization files updated

### CODE REVIEW

**Comment by jasonblais** [comment]
+1 from PM:

Tested on Windows 10, Chrome:
 - created an incoming webhook, outgoing webhook, slash command
 - proofread text and UI
 - tested a sample outgoing webhooks worked correctly

No change to docs needed as the information was already previously displayed.

**Comment by coreyhulen** [comment]
+1

**Comment by hmhealey** [comment]
I think these confirmation pages should be moved to their own page. It seems weird to have pages that can render completely different content depending on a flag in their state.

**Comment by DavidLu1997** [comment]
closing to rewrite

**Pull request closed without merging**
