### PR TITLE
PLT-4929: Confirmation Dialog when Deleting Entry on the Integrations…

### PR DESCRIPTION
**Pull request by aautio**
#### Summary
A modal confirmation dialog is shown whenever a users tries to delete an entry on the integrations page.

The confirmation dialog uses the texts described in the ticket.

#### Ticket Link
https://github.com/mattermost/platform/issues/5510
https://mattermost.atlassian.net/browse/PLT-4929

#### Checklist
- [x] Has UI changes
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/platform/blob/master/i18n/en.json) and [.../webapp/i18n/en.json](https://github.com/mattermost/platform/tree/master/webapp/i18n/en.json)) updates

### CODE REVIEW

**Comment by jasonblais** [comment]
@lindalumitchell please help test when you get the chance?

**Comment by lindalumitchell** [comment]
@jasonblais Looks great! Added three different custom integration types (incoming and outgoing webhook, and slash command), and on clicking Delete I saw modal confirmation dialog with the described text, as expected (attaching screenshot for reference). No new issues found.

screen shot 2017-02-27 at 10 00 52 am

**Comment by hmhealey** [comment]
@aautio Looks like you need a merge or rebase, but otherwise your PR is good to go!

**Comment by aautio** [comment]
@hmhealey I just performed the merge. There were overlapping changes in two files which you can see in the commit: New actions had been added to installed_incoming_webhook.jsx and installed_outgoing_webhook.jsx.

Just ping me if this still needs anything.

**Comment by grundleborg** [comment]
That's great. Thanks very much for the PR @aautio

**Pull request merged**
