### PR TITLE
PLT-2283 Improved trimming of punctuation from hashtags and search terms

### PR DESCRIPTION
**Pull request by hmhealey**

### CODE REVIEW

**Comment by jwilander** [comment]
Are there unit tests for the new regexs you added? Might be a good idea to add some

**Comment by hmhealey** [comment]
I already added some in the hashtag parsing unit tests. The newish search term regexes are covered pretty thoroughly by the existing unit tests.

**Comment by crspeller** [comment]
+1

**Comment by coreyhulen** [comment]
+1

**Pull request merged**
