### PR TITLE
PLT-345 adding client side logging

### PR DESCRIPTION
**Pull request by coreyhulen**

### CODE REVIEW

**Comment by crspeller** [comment]
We should probably have a way to turn this off. It will likely be a lot of errors, most of which customers wouldn't care about.

**Comment by hmhealey** [comment]
Code looks good, but I agree with crspeller. Not sure if we just want to leave that for a separate PR though.

**Comment by coreyhulen** [comment]
I've created PLT-505 to add a prop to the config in the future.  If there is a lot of errors then we have real problems. Remember the 'no connection' websocket errors will not get logged since the server is down.

**Comment by crspeller** [comment]
+1

**Pull request merged**
