### PR TITLE
PLT-2138 - Fixing theme sharing box

### PR DESCRIPTION
**Pull request by asaadmahmoodspin**
Hey guys have a look.

### CODE REVIEW

**Comment by asaadmahmoodspin** [comment]
Removed it.

**Comment by coreyhulen** [comment]
+1

**Comment by asaadmahmoodspin** [comment]
Just added another 1 line fix for the search loading icon on mobile.

**Comment by crspeller** [comment]
@asaadmahmoodspin Please don't add anything to pull requests after the review has taken place. Especially on the release branch.

**Pull request merged**
