### PR TITLE
Implement generic OAuth login

### PR DESCRIPTION
**Pull request by gramakri**
Putting this up for review, so you we can get some feedback. Note that the first 2 patches in this series are already part of https://github.com/mattermost/platform/pull/1922

This adds the following config:
        "OAuthSettings": {
            "Enable": false,
            "ProviderName": "",  // like 'cloudron', 'qt', 'google', 'gitlab'
            "Secret": "",        // client secret
            "Id": "",            // client id
            "Scope": "",         // oauth scope
            "AuthEndpoint": "",  // auth endpoint
            "TokenEndpoint": "", // token endpoint
            "UserApiEndpoint": "", // user profile end point
            "UsernameField": "",  // the field in user profile to be used as username
            "EmailField": "",    // the field in user profile to be used as email
            "AuthDataField": ""  // the field in user profile to be used as auth data
        },
    
The above values can be configured via the admin panel.
    
We should be able to merge the gitlab oauth code with this code as well. But we can do this in a separate PR.

### CODE REVIEW

**Comment by gramakri** [comment]
cc @tronical

**Comment by jwilander** [comment]
Hi @gramakri, thanks for the PR! Can you give this a rebase? A bunch of merges just happened

**Comment by gramakri** [comment]
Yes, I was just rebasing :-)

**Comment by gramakri** [comment]
The failure seems to be travis related
```
mv: cannot move ‘dist/mattermost/config/config.json.bak’ to ‘dist/mattermost/config/config.json’: Permission denied

make: *** [dist-travis] Error 1
```

**Comment by gramakri** [comment]
The code has been tested with [Cloudron OAuth](https://cloudron.io/references/addons.html#oauth) and [Qt Account OAuth](https://login.qt.io/login).

We should be able to merge the Gitlab oauth into this one as well with some changes. One issue is that currently we store 'oauth' as the user's AuthService. In the case of gitlab, this is already 'gitlab' for existing installations and will thus affect migration. It's not clear to me yet whether there is value in storing the actual a generic 'oauth' or the providerName in the user object.

Suggestions/Comments? Depending on the reply, we can either add a migration to fixup the user objects OR store the providerName instead of the current 'oauth'. It probably makes sense to set providerName in case we want to support multiple oauth providers at a future point.

**Comment by it33** [comment]
Just FYI, we're focused on working through a 12K line localization PR, which has pushed back a lot of our priorities, will need some time to loop back on this,

**Comment by it33** [comment]
Hi @gramakri 

While we highly appreciate your efforts--and think architecturally you're designing things "the right way"--we've discussed this at length and aren't able to accept this pull request into master right now. 

The effort to properly support, test, document, and troubleshoot generic OAuth--on web, desktop and multiple mobile platforms--is significant, and would require us to cut other features. 

[The request has been upvoted by the community](http://mattermost.uservoice.com/forums/306457-general/suggestions/10096884-oauth2-for-generic-identity-provider) and we plan to reconsider it after more infrastructure is in place. Your work is smart and high quality and it pains us that we're unable to accept it right.

It's our fault for not noticing this issue earlier. You'd communicated your intentions in an earlier PR and we should have given feedback at that point on whether we could take the change. 

We had a [similar issue earlier this week](https://github.com/mattermost/platform/pull/1869) and we'll be changing our process so we avoid mistakes on our side in future. 

Thanks again for contributing, I hope this doesn't sour you on the project. We take great pains to build things thoughtfully, and sometimes that means sequencing priorities. 

PS: Just found out about [Cloudron offering Mattermost hosting](https://cloudron.io/appstore.html#org.mattermost.cloudronapp)--that's awesome! Is it production ready? Would love to promote it.

**Comment by tronical** [comment]
Hi,

Do you have any advice for us how the contribution could be changed so that you would not have to cut features but would feel comfortable accepting the change?

We can add test coverage (we have that actually in a separate change) for example. The idea would be in the longer run to unify the duplicated code paths for oauth. If you think that is a worthwhile goal, then perhaps we can work towards that in one bigger pull request.

The ability to authenticate against a non-gitlab/non-google/etc. oauth provider is a key feature we require for deployment in at least one instance.

Tell us what we could do to make it easier for you in terms of maintenance and acceptance :)

**Comment by it33** [comment]
It's a good question, I don't know the answer. 

I think the key decision is whether making a commitment to OAuth and its variations is higher priority than other features requested by the community (your implementation is very well done and certainly not at issue). 

There are threads discussing OAuth in this repo, in matterircd, in the general forum and I'd propose we move to the [feature idea forum post on OAuth to discuss further--and to encourage upvotes.](http://mattermost.uservoice.com/forums/306457-general/suggestions/10096884-oauth2-for-generic-identity-provider). 

Closing this PR to move the discussion into one place (can re-open as appropriate). 

PS: For the same reasons we hesitate to add OAuth, we're not planning to surface Google Auth right now. This discussion has been happening internally prior to the PR thread.

**Comment by gramakri** [comment]
> PS: Just found out about Cloudron offering Mattermost hosting--that's awesome! Is it production ready? Would love to promote it. 

@it33 Thanks! What's the best way reach out to you to talk about the Cloudron app? I have sent a mail to info but I am just guessing the id here :-) My email is in my profile.

**Comment by vikaskedia** [comment]
This is a high quality pull request.

@it33 are you sure that there are no conflict of interests between enterprise edition and team edition ?

to an outsider it looks the custom oauth is not being merged to get users to pay for the enterprise edition.

I like open source projects that have a revenue stream. Allowing unsupported add ons would seem to be a move in the right direction.

**Comment by it33** [comment]
Hi @vikaskedia, thanks for your interest in Mattermost and for your question. Custom OAuth isn't in either Team or Enterprise Editions right now. 

You can learn more about the [criteria and processes for selecting improvements to Mattermost in our documentation](https://docs.mattermost.com/process/community-systems.html#how-improvements-are-made-to-mattermost).

Quality is a corner stone of the Mattermost open source project and a change like this would require testing on 4 desktop browsers across three operating systems, 2 browsers on mobile devices, 2 mobile apps and 3 desktop apps then maintaining it with each new release testing all over again to ensure quality--and it turns out volunteers aren't eager to sign-up for the work. 

That said, Mattermost is open source software and the community is welcome to add what they'd like to their own forks.

**Comment by tareko** [comment]
@it33 
> There are threads discussing OAuth in this repo, in matterircd, in the general forum and I'd propose we move to the feature idea forum post on OAuth to discuss further--and to encourage upvotes..
This feature is 6th currently in the feature idea forum, with 192 votes. I think it's pretty clear that there is a large desire for it.

In terms of the barriers, it sounds like the ones you mention above are very real and problematic. Could we articulate some mechanism to address them? For example, as an interested person, could I contribute to a bounty on this feature's implementation?

With gitlab authentication already in MM, it makes no sense to me that a generic provider is not available. All the hard work is done..

**Comment by tareko** [comment]
@gramakri @tronical: Since I haven't heard anything from @it33 regarding my suggestion above, I assume that the MM team is not interested in adding this feature.

Are you guys willing to support the feature / rebase the PR with each version? Perhaps we could run a Patreon or some kind of bounty for it? That would both answer the large community need for this feature and the reluctance of the MM team to merge the PR.

What are your thoughts on this?

tarek : )

**Comment by it33** [comment]
@tareko Sorry for the delay in responding. First, thank you for being a long time user, and for your ideas around how to improve the product. So many open source projects fail because they can't draw in an active community and we're fortunate to have your participation--and if the official releases aren't able to do 100% of what you want, I hope you'll still consider being engaged. 

We had a long discussion with core contributors and the thinking the best to address the concerns is to [make it clear than one day when generic OAuth2 is added, it would be in the commercial Enterprise Edition](https://mattermost.uservoice.com/forums/306457-general/suggestions/10096884-oauth2-for-generic-identity-provider), similar to other SSO options like Okta, ADFS, Onelogin, SAML, etc. That addresses the support and mind share costs (what we call "[mana](https://docs.mattermost.com/process/training.html#mana)") and is consistent with other feature decisions. 

If you're in need of SSO in the Enterprise Edition [for a non-profit or academic organization](https://about.mattermost.com/pricing/#faq), there's highly discounted licenses available--plus you get many other enterprise features. 

Alternatively, as with any open source project, anyone is welcome to take the code provided in this PR and maintain their own fork. 

For the official single-sign-on experience with Mattermost Team Edition, [the thinking is we should be encouraging people to use Mattermost Team Edition as an open source OAuth2 provider](https://docs.mattermost.com/developer/oauth-2-0-applications.html). 

This means setting up your users in Mattermost, and you can authenticate into other applications using OAuth2 (rather than the other way around), here's what the screen looks like: 

sa 

PS: GitLab SSO is an exception to the pattern of having SSO in Enterprise Edition. It's a legacy feature from the earliest days of the project and takes significant [mana](https://docs.mattermost.com/process/training.html#mana) to maintain, as we have to test GitLab SSO manually with every release (there have been regressions in the past we had to jump on to fix).

**Comment by tronical** [comment]
@tareko Hi, I have no plans on pursuing this feature further (and I understand that this is a differentiating feature for the MM folks from a business point of view).

**Comment by tareko** [comment]
Thank you @it33 for your detailed response. In our context having a well-established OAuth2 provider via Drupal and several dependent clients in the ecosystem, it is not an option to change to a mattermost provider.

I understand that you are not talking about getting rich, but about sustainably maintaining this feature. We are an academic department, so I'm sure you guys would give us an excellent price on EE. However, while I understand the business case, we have a strict Open Source policy, and so I would rather explore other models of funding that would keep the feature FLOSS and answer your needs.

I know it's a tall order, and I'm ready to put my time and energy into it. Of course that can happen by maintaining a fork, but the consequences of doing that are predictable and undesirable.

I hope we can continue the conversation more to find a FLOSS solution to this. Thank you for your time!

tarek : )

**Comment by torgeirl** [comment]
Sorry for continue on this, but when you in early April started with [monthly releases](https://about.mattermost.com/blog/mattermost-moves-to-monthly-releases/) (otherwise great) it became even less manageable to maintain a fork.

I understand full support for generic OAuth is an issue, but can we not find a midway solution? Some authentication API or plugin architecture included with EE so we could maintain this ourselves while still running the main branch.

**Comment by quasoft** [comment]
Anyone aware of forks that provide general OAuth or other custom authentication methods?

**Pull request closed without merging**
