### PR TITLE
PLT-3766 Change LDAP references to AD/LDAP in the UI

### PR DESCRIPTION
**Pull request by jasonblais**
#### Summary
Change LDAP references to AD/LDAP in the UI.

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-3766

#### Checklist
- [X] Includes text changes and localization files updated

#### Notes
 - Please help review carefully to check no files were overlooked.
 - When merging, please condense the commit messages or let me know how to do so

### CODE REVIEW

**Comment by jasonblais** [comment]
Re-submitting PR from https://github.com/mattermost/platform/pull/3915

WIP label until I've tested this on a spinmint, since I cannot test my changes locally. Will queue for review afterwards.

**Comment by jasonblais** [comment]
Have tested on Windows 10, Chrome:
 - System Console settings
 - Account Settings
 - smoke test on error messages
 - login/account creation screens.

All reference to AD/LDAP now. Ready for dev review.

When merging, please condense the commit messages.

**Comment by crspeller** [comment]
@jasonblais Needs a rebase.

**Comment by jasonblais** [comment]
Rebased

**Comment by enahum** [comment]
I'm not sure we should change the strings in the `vendor` package.

Other than that +1

**Comment by DavidLu1997** [comment]
+1

**Comment by jasonblais** [comment]
Can someone confirm whether strings in the `vendor` package should be changed?

I thought not to, but I'm not totally sure.

**Comment by jwilander** [comment]
No, please don't change the strings in the `vendor` package. If we're using the errors they return somewhere then we should convert them appropriately on our side before displaying them to the user.

**Comment by jasonblais** [comment]
Removed any reference to `vendor` packages.

@enahum please review and condense commit messages when merging

**Comment by DavidLu1997** [comment]
@jasonblais needs rebase

**Comment by jasonblais** [comment]
Rebased,

**Comment by enahum** [comment]
was it just now? cause it still have conflicts

**Comment by jwilander** [comment]
I think it's because I merged, the daily translations PR. Sorry @jasonblais

**Comment by jasonblais** [comment]
No worries, should be good now

**Comment by jasonblais** [comment]
Can someone give a quick review just to confirm everything is fine? Since this was rebased a couple times

**Comment by hmhealey** [comment]
+1

**Pull request merged**
