### PR TITLE
Update emoji and remove duplicates

### PR DESCRIPTION
**Pull request by ubuntor**
This updates the emojione emoticons to v2.1.1.
This also removes duplicate emoticons with the unicode names.

### CODE REVIEW

**Comment by it33** [comment]
@ubuntor, thanks for the PR! Can you share a link to where you found these emojis?

**Comment by ubuntor** [comment]
Sure!
The images are taken from [Ranks/emojione/assets/png @`67cad29`](https://github.com/Ranks/emojione/tree/67cad29299bdbc56721c1cdc0be43cd0f5aa03bf/assets/png).
The shortnames are taken from [Ranks/emojione/emoji.json @`52a1567`](https://github.com/Ranks/emojione/blob/52a15676baa002610384b9207bcf9d11c2851eab/emoji.json).

**Comment by lfbrock** [comment]
I noticed there were a couple emojis where we used different names than emoji one that still seem to post the old version.

screenshot 2016-03-08 12 39 16


Would it be possible to switch `:-1:` to be an updated emoji, and either remove the other out of date shortnames or update them to the new images as well?

**Comment by ubuntor** [comment]
Is it better to keep some duplicates in until there's a system for emoji aliases (e.g. `:us:` and `:flag_us:`, `:satisfied:` and `:laughing:`), or take them out for now?

**Comment by lfbrock** [comment]
Actually, I think it's fine to leave the duplicates for now. Was just talking to the UX team, and they would like to update the emoji set later on to switch to something like https://github.com/github/gemoji/tree/master/images/emoji, and we can update the duplicates then. 

This is coming from feedback from the community that they prefer other emojis to emojione, but we're open to suggestions on which emoji set would be best to use.

**Comment by ubuntor** [comment]
Inconsistencies should be fixed now.

**Comment by it33** [comment]
Thanks @ubuntor, setting up a new test server to review the change

**Comment by lfbrock** [comment]
Hi @ubuntor, we ended up switching back to an emoji set similar to the github emoticons - thanks for the work, the feedback from the community was just that they preferred this from the EmojiOne set.

**Pull request closed without merging**
