### PR TITLE
Shortening help text

### PR DESCRIPTION
**Pull request by it33**

### CODE REVIEW

**Comment by jwilander** [comment]
+1

**Comment by crspeller** [comment]
@it33 I don't think we should use acronyms here as it won't translate well.

**Comment by it33** [comment]
Thanks @crspeller, I think because our documentation is in English only right now, if we use localized phrases instead of acronyms when linking to English documentation it will be more difficult for IT admins to find the right section.

**Comment by it33** [comment]
I should have put this in the comments in original PR, it was just easier to say shortening, appreciate the feedback, it's a valid consideration,

**Comment by hmhealey** [comment]
+1

**Pull request merged**
