### PR TITLE
enhancement permanent_delete_posts, currently incomplete

### PR DESCRIPTION
**Pull request by qcu**
remaining: add unit tests to cover new code, handle removal of uploaded files

### CODE REVIEW

**Comment by qcu** [comment]
This enhancement is not on the Accepting Pull Requests list. This is just a quick hack for compliance with message retention policies (e.g., https://mattermost.uservoice.com/forums/306457-general/suggestions/10007076-add-a-way-to-prune-reset-clear-channels)

**Comment by qcu** [comment]
Cross-posting from: https://mattermost.uservoice.com/forums/306457-general/suggestions/10007076-add-a-way-to-prune-reset-clear-channels

Anonymous commented  ·  May 03, 2016 08:18:
> thank you @anon for creating code to handle this feature request.
> Has the change been approved and committed to the Mattermost platform? Thanks.

Thank you. Happy to share, @anonymous.

This feature patch definitely scratched an itch for one of my engineering/devops teams, and has allowed us to use the mattermost platform while remaining in compliance with a corporate policy relating to chat log retention.

Unfortunately, the mattermost core team has never opened an Accepting Pull Request ticket for this feature, and I don't expect it to be merged until we get their attention. Chat log retention restrictions are a common policy requirement in enterprise environments, and who knows, it is possible that mattermost already has such a feature in one of the enterprise versions of the platform.

The previous !APR #2697 commit (#9a8968f) was branched off release-2.1, and I'll probably be taking a look at doing a maintenance merge with a release-3.x branch in the near future.

Meanwhile, I'm happy to report that the release-2.1-delposts branch has been running just fine in production for several months. The following cron job purges all messages older than 3 days across all channels and teams on the defined cron schedule (midnight UTC).

0 0 * * * cd /opt/mattermost/bin && ./platform -permanent_delete_posts -duration_retained="72h" -confirmation_override

I would post a linux build of the delposts fork to github releases, however it would obviously be far more preferable if this feature was accepted by the core team and merged.

The only minor caveat is that uploaded files are currently not purged. Although, it would be simple enough to write a standalone janitor script for that task.

Aside: on the automation/bot front, we need to write an internally hosted bot to implement a simple /toconfluence or /toquestions slash command to aid in efficiently persisting relevant content from mattermost posts to our internal self-hosted wiki & knowledge base (e.g., in case a team member identifies a post as wiki-worthy prior to the post being purged). If anyone has any pointers to an existing open source Atlassian Confluence slack bot, I'm all ears. Cloudpipes.com has a Confluence integration. However, we need to host the bot in our environment.

**Comment by ajhaydock** [comment]
Does this issue need reopening before the team will consider an APR?

I'd like to lend my support to having the feature (even if it exists only in the command-line-flag form suggested).

This sort of thing is pretty much essential to my deployment, and probably many others so it would be nice to see the changes get incorporated.

**Comment by qcu** [comment]
@ajhaydock:  The project team's [process](http://docs.mattermost.com/process/accepting-pull-request.html) dictates that an [APR ticket (in Mattermost JIRA)](https://mattermost.atlassian.net/issues/?filter=10101) must exist before a PR is created with a reference to the pre-existing APR.

So, this PR was accidentally created by yours truly, and immediately closed, as it didn't conform to the APR process.

Therefore, reopening the PR won't really help. Nor will referencing a core team member by an "@" mention in a rouge PR comments. So, we won't do that either. : )

However, perhaps raising additional voices in the provided "User Voice" / Suggestions forum, will get their attention. Many of us would like to see a response to the [user voices raised on this topic](https://mattermost.uservoice.com/forums/306457-general/suggestions/10007076-add-a-way-to-prune-reset-clear-channels), however we can appreciate how busy they have been with the overall 3.0 release and other features, and appreciate the team's efforts.

**Comment by qcu** [comment]
Looking more closely at the latest APR process, in addition to the User Voice / Suggestions forum perhaps we can [create a Proposed APR ticket](http://docs.mattermost.com/process/accepting-pull-request.html#nominating-changes-for-accepting-pull-request-status) in JIRA to nominate a feature for approval.

I'll look into creating a Proposed APR and report back here and in the Suggestion topic as appropriate.

**Comment by it33** [comment]
Hi @qcu, hi @ajhaydock, 

Thanks for proposing this and offering to help. 

This falls into a class of features that are difficult to turn into APRs because of [items 3 and 4 on the checklist](http://docs.mattermost.com/process/accepting-pull-request.html?highlight=apr), and also because of significant manipulation of the database which could unintentionally break consistency in existing deployments or in future releases if new contributors don't anticipate this feature being turned on. Also corner cases: Are old profile pictures deleted? What happens to comments on deleted messages? What happens if files are stored in S3 and delete permissions aren't available? How do users recover if there's a bug? 

That said, per anon's suggestion in the uservoice thread, perhaps someone is interested in setting up a community project with a cron job to support this use case?

Many of the features requested in uservoice--Hubot integration, XMPP, Desktop apps, etc.--are served via community projects rather than APRs.

**Comment by lpar** [comment]
If you provided suitable API calls, this could be coded up as a community project. Then you wouldn't need to worry about database breakage.

You could have an API call to fetch a list of channels, a call to fetch messages on a specified channel older than a certain date, and a call to delete a specified message or messages. Then you could leave everything else to the community.

**Comment by col-panic** [comment]
What is the state of this? I don't really get it - I only see that this is not part of 3.6.2! I want to use mattermost as a method to communicate logs, and I do not need those for more than 48hours!

**Pull request closed without merging**
