### PR TITLE
PLT-2692 Enabled Team Creation for Sysadmins when Disabled

### PR DESCRIPTION
**Pull request by DavidLu1997**
Previously, if the setting "Restrict Team Creation" was set to true, the "Create Team" link still shows up for system administrators. A server error stops the administrator from actually creating the team. The server error was removed, and help text was added to let the system administrator know that the option is only available for system administrators.

Also corrected a super minor typo in `model/user.go`

image

### CODE REVIEW

**Comment by crspeller** [comment]
+1

**Comment by coreyhulen** [comment]
+1

**Comment by enahum** [comment]
+1

**Comment by jasonblais** [comment]
+1

**Comment by jasonblais** [comment]
On Windows 10, Chrome, tested
 - when team creation is enabled ('create new team' appears on login page and three dot dropdown menu)
 - when team creation is disabled
   - system admins see 'create new team' option on the login page, with the correct help text
   - team admins nor members can see the 'create new team' option on the login page

**Pull request merged**
