### PR TITLE
PLT-1354 Show channel member count up to 100 now

### PR DESCRIPTION
**Pull request by jwilander**

### CODE REVIEW

**Comment by coreyhulen** [comment]
what about `ecm := Srv.Store.Channel().GetExtraMembers(id, 20)` in `getChannelExtraInfo` ?

**Comment by jwilander** [comment]
That will increase the number of members in the popover but the ticket didn't ask for that. We send back a total member count that we use to display the count

**Comment by coreyhulen** [comment]
We discussed in triage and it probably wasn't clear but it was to bump the total to 100 everywhere. So it would show 100 people in the dropdown if 100+ exist in the channel.

**Comment by coreyhulen** [comment]
+1

**Comment by crspeller** [comment]
+1

**Pull request merged**
