### PR TITLE
If login is using mobile respond with JSON object

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
When logging in using SAML or OAuth from mobile we need to return a JSON object instead of redirecting to any page

#### Checklist
- [x] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by MusikPolice** [comment]
I'd feel a lot better about this PR if it included some automated tests. As it stands, I'm not a subject matter expert, so while I'm tempted to approve the PR, my approval is pretty meaningless. Considering that this has been identified as a critical section of the codebase, I'm kind of surprised that this change doesn't require changes to the test suite.

**Comment by enahum** [comment]
@MusikPolice while I totally agree with you I don't really know exactly how to test this because it needs user interaction on the idp for saml or the OAuth provider so if you know a way please feel free to include those tests ;)

**Comment by MusikPolice** [comment]
@enahum I'm no expert, but this seems like a good use case for mocks. Couldn't you mock the SAML and OAuth interface objects and cause them to behave the way you want them to?

**Comment by enahum** [comment]
@MusikPolice probably but I would love to do that on another PR later on, it seems like a lot of work just to fix this regression right now

**Comment by hmhealey** [comment]
I proposed this should go into 4.0.2, so waiting to hear back on that

**Comment by jasonblais** [comment]
I approved this for 4.0.2

**Comment by hmhealey** [comment]
Awesome. We're just waiting on the build to be able to merge this then

**Comment by jasonblais** [comment]
Sounds good. I also pinged Saturn to merge it for 4.0.2-RC1, so he's aware of it too

**Pull request merged**
