### PR TITLE
PLT-199: Add scroll bar to center channel

### PR DESCRIPTION
**Pull request by florianorben**

### CODE REVIEW

**Comment by it33** [comment]
Yay!!

**Comment by jwilander** [comment]
We've had some major issues with perfectscrollbar in the centre channel in the past. It doesn't deal with React's dynamic manipulation of the DOM very well. It might be OK as long as we never call `.perfectScrollbar('update')` other than when it's unmounting but it makes me nervous.

How thoroughly has this been tested?

**Comment by florianorben** [comment]
Hmm, did quite some manual testing on my machine, but that's not really 100% representative to a real prod setup I'd say ;)
I found most of the problems come from this line https://github.com/mattermost/platform/pull/1538/files#diff-35727ca7bb3b466dfb828cca33bc5696R331 where react continuously overrides the `ps-container` class that perfectScrollbar needs to work as it should. 

Currently (in this PR) `.perfectScrollbar('update')` is only called in the `componentDidUpdate`, which "feels" ok ;) ...

Not quite sure how I could test this some more - any specifics I should look out for?

**Comment by jwilander** [comment]
Ok, I think it might be fine. The best way to test it is to get it on CI or pre-release so I'm ok with merging it in, testing on there and reverting if it makes things go bonkers.

+1

**Comment by florianorben** [comment]
Sounds like a plan :)

**Pull request merged**
