### PR TITLE
MM-1427 Copied required Javascript libraries and resources into repository

### PR DESCRIPTION
**Pull request by hmhealey**
Copied the Bootstrap, jQuery, and React libraries into static/js along with their required resources. Loggly, Snowplow, and the Google Visualization apis are still external, but those don't appear to be required to run Mattermost.

### CODE REVIEW

**Comment by coreyhulen** [comment]
You also need to modify the Makefile.  Specifically, "make dist" which replaces some of the .js files with min.js

**Comment by hmhealey** [comment]
Changed the Makefile to correctly use the minified and unminified versions of the local Javascript libraries.

**Comment by coreyhulen** [comment]
please rebase for merge

**Comment by hmhealey** [comment]
Rebased and perfect scrollbar has been updated to 0.6.3 to match the previously conflicting changes. Also, I added the full version number to perfect-scrollbar.js since it took me a while to find the matching unminified version.

**Pull request merged**
