### PR TITLE
code block should be Code block as used in a menu IIRC

### PR DESCRIPTION
**Pull request by wget**
#### Summary
Change the `code block` string to `Code block`

#### Ticket Link
N/A

#### Checklist
- [x] Has UI changes
- [x] Includes text changes and localization files updated

All translators have translated this string item using an uppercase letter.

### CODE REVIEW

**Comment by jasonblais** [comment]
Thanks @wget! 

Verified in our UI and this is fine to change. Will change `code block` to `Code block` in the help docs.

image

**Comment by jasonblais** [comment]
+1

**Comment by jwilander** [comment]
+1

**Comment by crspeller** [comment]
+1

**Pull request merged**
