### PR TITLE
Added build script which helps to build platform package

### PR DESCRIPTION
**Pull request by kayrus**
This script helps to build mattermost in docker environment.

### CODE REVIEW

**Comment by crspeller** [comment]
Hi @kayrus 

We already have a preview docker image. You can find it here: https://github.com/mattermost/mattermost-docker-preview

Thanks for you interest!

Closing as duplicate.

**Comment by kayrus** [comment]
@crspeller this image is not for running mattermost, it is for building mattermost.

**Comment by crspeller** [comment]
Why do you want a docker image for building mattermost?

**Comment by kayrus** [comment]
@crspeller because I don't want to install nodejs and tons of dev stuff on my host.

**Comment by crspeller** [comment]
For development or for use? 
We have releases to download here: http://www.mattermost.org/download/

**Comment by kayrus** [comment]
@crspeller of course for development. guys, just take a look at the code and what it does. some users just want to compile whole package without installing additional soft, just use docker. this is normal practice.

**Comment by kayrus** [comment]
@crspeller did you abandon this PR?

**Comment by it33** [comment]
HI @kayrus, 

Definitely appreciate your work. I can see why you would want this and it's clear you've spent a considerable amount of effort trying to improve the product--not only in the code, but engaging in the discussion. 

Per the [contribution guide](http://docs.mattermost.com/developer/contribution-guide.html), we try to be transparent about the process in place to make sure system improvements have the right level of design critique, discussion, testing, documentation and long term support before we can accept them. 

The first step of this process is making a contribution to the [feature idea forum](http://www.mattermost.org/feature-ideas/) where your idea can be discussed and upvoted by the community. 

Would you be open to this as a starting point?

**Comment by kayrus** [comment]
@it33 It is quite weird workflow for an opensource product. It adds a barrier which prevents contribution to the project and complicates PR from the community. I'd suggest you to simplify this process.

Anyway, [here](https://mattermost.uservoice.com/forums/306457-general/suggestions/15148830-make-build-process-easier) is my "idea".

**Pull request closed without merging**
