### PR TITLE
Fix Key && Slat in config_docker.json for 1.0 and dev

### PR DESCRIPTION
**Pull request by chengweiv5**
There was an update about Key & Slat to 32 characters length recently(after 0.7)
but forgot to fix config for 1.0 and dev.

Signed-off-by: Chengwei Yang <yangchengwei@qiyi.com>

### CODE REVIEW

**Comment by crspeller** [comment]
@chengweiv5 Thanks for the PR. 

The 1.0 docker image won't pick up changes unless they are in the release branch. I would rather not have the change done on master. Can you remove the changes to the 1.0 docker file? The dev docker file should definitely be updated.

**Comment by chengweiv5** [comment]
@crspeller sure, I'll update it soon.

**Comment by chengweiv5** [comment]
updated.

**Comment by crspeller** [comment]
@chengweiv5 Thanks!

**Comment by crspeller** [comment]
+1

**Comment by coreyhulen** [comment]
what about docker/local/config_docker.json

**Comment by chengweiv5** [comment]
I see PLT-499 already fixed this issue, so close this PR

**Pull request closed without merging**
