### PR TITLE
PLT-1527 Add a slash command to set yourself away

### PR DESCRIPTION
**Pull request by daizenberg**
#### Summary
Add a slash command to set yourself away

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-1527

#### Checklist
- [x] Added or updated unit tests (required for all new features)
- [x] Includes text changes and localization files updated
- [?] Touches critical sections of the codebase (auth, upgrade, etc.) - adds a column to a DB (Status/Manual)

### CODE REVIEW

**Comment by jwilander** [comment]
Hi @daizenberg, thanks for the pull request! We're in the middle of a release cycle at the moment but after that's complete someone will take a look at this

**Comment by jwilander** [comment]
Also would you mind giving this a quick rebase? That should resolve the build failures

**Comment by jasonblais** [comment]
Thanks again @daizenberg for your work here! Much appreciated, this will be a great improvement.

Would we be able to have your help rebasing your pull request? We'll then be able to test it out and start the review process now that the release cycle for v3.3 is complete.

We'd also like to welcome you to join our [Developers community channel](https://pre-release.mattermost.com/core/channels/developers) if you'd like (and if you're not already there).

**Comment by daizenberg** [comment]
@jasonblais @jwilander sorry to bother you guys, but looks like I need your help here. I rebased the PR, but the build is still failing...

**Comment by jwilander** [comment]
Hmmm, that's weird. I'll take a look in a little bit and see if I can help you out

**Comment by jwilander** [comment]
OK, I fixed the issue and queue this for rebuild. Should pass in ~20 minutes (there's a back-up of builds)

**Comment by daizenberg** [comment]
@jwilander thank you. What did I miss? Want to avoid having same problem in future

**Comment by jwilander** [comment]
Nothing you missed, we have an enterprise repo that builds with this one that was using the Status model that you modified. I fixed it so it would use defaults for any new fields added to the Status model in the future

**Comment by jwilander** [comment]
@daizenberg sorry about this but it looks like there are some merge conflicts. Can you do one final rebase and then we can get this reviewed?

**Comment by daizenberg** [comment]
@jwilander no worries. I resolved the conflicts, looking forward to the review

**Comment by jwilander** [comment]
+1

**Comment by lfbrock** [comment]
Hi @daizenberg - would you be able to switch the "You are now away"/"You are now online" messages to be ephemeral system messages? Right now they're just posting as normal messages

screenshot 2016-08-29 18 04 00

**Comment by daizenberg** [comment]
@jwilander  thanks
@lfbrock  appreciate your comment, will modify shortly

**Comment by daizenberg** [comment]
@lfbrock done

**Comment by enahum** [comment]
+1 for code

dev review completed

**Comment by lfbrock** [comment]
+1, PM review complete

**Comment by jwilander** [comment]
Great work @daizenberg ! Much appreciated

**Pull request merged**
