### PR TITLE
Implementation endpoint for APIv4: GET /files/{file_id}/preview

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
Implementation endpoint for APIv4: GET /files/{file_id}/preview

#### Ticket Link
Jira ticket: [PLT-5247](https://mattermost.atlassian.net/browse/PLT-5247)

#### Checklist
- [x] Added or updated unit tests (required for all new features)
- [x] Added API documentation (required for all new APIs) [mattermost-api-reference#119](https://github.com/mattermost/mattermost-api-reference/pull/119)
- [x] All new/modified APIs include changes to the drivers
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/platform/blob/master/i18n/en.json))

### CODE REVIEW

**Comment by jasonblais** [comment]
@saturninoabril   Just so you know, there may be a delay in merging this PR as we are locking down feature and improvement contributions for the v3.7 release, per our [release process](https://docs.mattermost.com/process/release-process.html). 

Once this PR is ready to merge, we'll add the `Ready to Merge` label and merge into `master` after we branch `release-3.7` on March 6th. 

Many thanks for your help contributing to the Mattermost code base!

**Comment by jwilander** [comment]
Looks good @saturninoabril, but needs a rebase

**Comment by saturninoabril** [comment]
@jwilander done rebase. thanks!

**Comment by grundleborg** [comment]
Hi @saturninoabril , sorry, would you be able to rebase this again? We've just merged a whole load of PRs into master, which has meant that lots of APIv4 ones have conflicted with each other. If you could rebase your APIv4 PRs one at a time onto master and then we'll merge each one as it's done before you rebase the next one, to avoid this happening any more.

**Comment by saturninoabril** [comment]
@grundleborg i understand, no worry. done rebase. thanks

**Pull request merged**
