### PR TITLE
[webui] fix command-list css

### PR DESCRIPTION
**Pull request by ralder**
* fixed typo in css for command-box class (bottom:38 hasn't `px` and currently it's overlayed textbox)
* fixed typo in command-list.jsx (for calc height command-box: missed .length)
* splited base.sass css-classes for command-list and error-bar components in separate files
* added shadow for mentions-list and command-list
* and also few small changes :)

### CODE REVIEW

**Comment by jwilander** [comment]
@asaadmahmoodspin please review the CSS changes

**Comment by asaadmahmoodspin** [comment]
The css changes look about right to me.

**Comment by crspeller** [comment]
@ralder Looks like this has been reviewed but it needs a rebase before it can be merged.

**Comment by ralder** [comment]
rebased

**Pull request merged**
