### PR TITLE
[PLT-7021] Add missing borders of emoji picker

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
Add missing borders of emoji picker

#### Ticket Link
Jira ticket: [PLT-7021](https://mattermost.atlassian.net/browse/PLT-7021)

#### Checklist
- [x] Has UI changes

### CODE REVIEW

**Comment by asaadmahmood** [comment]
screen shot 2017-07-11 at 12 11 05 am

**Comment by asaadmahmood** [comment]
The way it should work is, that if it is working fine in the center channel, then it should be working fine in the RHS as well, if it's not, then there's something wrong.

**Comment by saturninoabril** [comment]
@asaadmahmood Noted. Also removed unnecessary CSS change in `webapp/utils/utils.jsx` related to border of Emoji picker. See changes made.

**Comment by asaadmahmood** [comment]
Looking good to me.

**Pull request merged**
