### PR TITLE
Multiple UI Improvements

### PR DESCRIPTION
**Pull request by asaadmahmoodspin**
Hey guys have a look. Changes include stuff from tickets:
https://mattermost.atlassian.net/browse/PLT-2439
https://mattermost.atlassian.net/browse/PLT-2454
And the css stuff so it doesn't cause issues locally.

### CODE REVIEW

**Comment by crspeller** [comment]
The bootstrap and jasny-bootstrap should be included from npm so they can be updated automaticly. Don't include them statically in the sass folder.

**Comment by crspeller** [comment]
We discussed this and we are going to merge this and I will fix it later.

**Comment by crspeller** [comment]
+1

**Comment by hmhealey** [comment]
+1

**Pull request merged**
