### PR TITLE
Multiple UI Improvements

### PR DESCRIPTION
**Pull request by asaadmahmoodspin**
Changes include:
- Improvements to backstage
- Fixes for PLT-2495 and PLT-2506

### CODE REVIEW

**Comment by jwilander** [comment]
+1

**Comment by hmhealey** [comment]
Can you change it to just add the class when the Navbar mounts and remove the class when it unmounts? Using toggle seems like we're likely to get into a weird state where it accidentally gets removed on mount or added on unmount. It'll also be a bit clearer when that class will actually be applied to the body.

**Comment by asaadmahmoodspin** [comment]
Done.

**Comment by hmhealey** [comment]
+1 Thanks!

**Pull request merged**
