### PR TITLE
PLT-1555 Message Editing and Deleting permissions

### PR DESCRIPTION
**Pull request by ayadav**
#### Summary
Add support of Message Editing and Deleting permissions

"System Console > Settings > GENERAL > Policy"

Setting one (with radio buttons):

    Allow users to edit their messages: 
    [ x ] Any time 
    [ ] Never 
    [ ] ___ seconds after posting //Where ___ is a text input box where they can enter a number of seconds
    Help Text: After posting a message, set the length of time the author has to edit it.

Setting two (with radio buttons):

    Allow which users to delete messages: 
    [ x ] Message authors can delete their own messages, and Administrators can delete any message
    [ ] Only Team Administrators and System Administrators
    [ ] Only System Administrators
    Help text: Set who has permission to delete messages.

Summary of changes
    - Added System console UI. Re-used existing policy page to have both licensed (existing) & non-licensed options (added in this story).
    - Updated APIs to restrict user actions based on new permissions.
    - Updated UI to show/hide permitted actions in post edit dropdown & handled permissions in edit shortcut.

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-1555

#### Checklist
- [X] Added or updated unit tests (required for all new features)
- [ ] All new/modified APIs include changes to the drivers
- [X] Has UI changes
- [X] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/platform/blob/master/i18n/en.json) and [.../webapp/i18n/en.json](https://github.com/mattermost/platform/tree/master/webapp/i18n/en.json)) updates

### CODE REVIEW

**Comment by ayadav** [comment]
The build seems to have failed for non-code reasons. Please re-run.

**Comment by ayadav** [comment]
@it33 @jwilander - As per my last comment the build seems to have failed for non-code reasons. Let me know how can I help to complete this.

**Comment by jwilander** [comment]
My apologies, re-rerunning the build now. If it fails I'll figure out and fix the issue

**Comment by jwilander** [comment]
@ayadav it looks you need to rebase. Once you do that and push the change the build should run successfully.

**Comment by ayadav** [comment]
@jwilander Tx, it has now been fixed after rebasing.

**Comment by esethna** [comment]
Hi @ayadav, thanks again for this PR. After doing some testing I have a few minor points:

1. It seems that message deleting and editing can still occur from the [...] menu if the message is opened in the right-hand-side. Clicking "Delete" or "Edit" (and then saving the changed text) causes a blue bar error message "You do not have the appropriate permissions"
image

image


2. There seems to be some misalignment with the buttons. Can you please take a look at getting the buttons to line up centered with the text?
image
3. After taking a review of the text that was proposed in the ticket I think we might need to make some updates to be consistent with our other settings (totally our fault that the ticket wasn't up to date, if you'd prefer, I can submit a PR to this branch for the text updates):
  - `Administrator` > `Admin`
  - `Set who has permission to delete messages.` > `Set policy on who has permission to delete messages.`
  - `After posting a message, set the length of time the author has to edit it.` > `Set policy on the length of time authors have to edit their messages after posting.`
  - `Only Team Administrators and System Administrators` > `Team Admins and System Admins`
  - `Only System Administrators` > `System Admins`

**Comment by ayadav** [comment]
Hi @esethna 

I have pushed the fix for 1 & 3.

For 2), it seems to be a site-wide issue with radio button style with Firefox browser (see attached screen for another system console page) and its working well in Chrome/Safari. I think we should cover that in a separate fix so it can also be verified accordingly.

image

**Comment by esethna** [comment]
Hey @ayadav, thanks for the tweaks, I will re-test. Agree the fix for (2) should be covered in a different PR. I've created a [ticket here](https://mattermost.atlassian.net/browse/PLT-5099).

FYI, we have [passed the day for features to be merged in for the v3.6 release](https://docs.mattermost.com/process/release-process.html#c-t-minus-12-working-days-cut-off-for-merging-major-features), so after we cut the `release-3.6` branch, around January 4th, we can start merging features for v3.7 into `master` again. Just making sure you're aware that the release process may cause a delay in getting this PR merged.

**Comment by jasonblais** [comment]
Hey @ayadav, let us know if you need any clarification / if you have any questions about the feedback,

Big thanks for working on this feature!

**Comment by jasonblais** [comment]
Hey @ayadav, you can request a 30-day trial license from [our Trial License page](https://about.mattermost.com/trial/).

You should receive it within a day and you can use it for testing in your local dev environment.

**Comment by ayadav** [comment]
@esethna These are fixed now.

**Comment by esethna** [comment]
@ayadav mostly looking great, I found just one minor issue:

If you select the input box option for "Allow users to edit their messages", then hit backspace three times to remove the default "300", the text box gets replaced with "NaN" which cannot be removed unless you save the setting, which then converts the input to "1".

I'd propose we allow the user to fully clear the textbox with the backspace key and then if they attempt to save it as blank, we treat it similar to the other input boxes where it will put in the default value (300 in this case).

**Comment by ayadav** [comment]
@esethna Sure, this is fixed now.

**Comment by ayadav** [comment]
@jwilander @esethna - Sounds good. Rebased now.

**Pull request merged**
