### PR TITLE
PLT-137: Disable upload button when max uploads reached

### LINKED ISSUE #4495: [Help Wanted] Disable file attachment icon after the maximum number of files is uploaded
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team.

---

**Details** ([Jira ticket](https://mattermost.atlassian.net/browse/PLT-137))

If maximum number of files is reached (i.e. 5 files), then the file attachment icon should be disabled until more files can be uploaded (that is, after at least 1 file removed so we're no longer at maximum).

When clicked on, it should show the existing maximum file error message ("Uploads limited to 5 files maximum. Please use additional posts for more files."), so users know why they can't upload more files.

### PR DESCRIPTION
**Pull request by mikaoelitiana**
#### Summary
The number of upload is currently limited to 5. When a user reaches this number, the upload button shall be disabled and an error message displayed when clicking it.

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-137
fixes #4495 

#### Checklist
- [x] Has UI changes

### CODE REVIEW

**Comment by jasonblais** [comment]
Thanks @mikaoelitiana for the contribution!

Tested on Windows 10, Chrome and iPhone 5S, iOS 10.1:

1) Using the paperclip and uploading 4, 5 and 6 files
2) Using CTRL+U
3) Public/private and direct message channels
4) Center channel and right-hand sidebar

Only noticed two minor issues on the right-hand sidebar

1 - Error message doesn't clear after you remove at least one file on the right-hand sidebar. It does clear as expected on the center channel

Repro steps:
1) Post a message
2) Click on the [...] menu of the message, then "Reply" to open the right-hand sidebar
3) Click the paperclip icon and choose five files to upload
4) Click the paperclip icon again [observe error message]
5) Remove one of the files so that you only have four left

Observed: Error message doesn't disappear

image

Expected: Error message clears and shouldn't appear if the user has 4 or fewer files uploaded.

2) The comment thread on the right-hand sidebar doesn't scroll to the bottom to display the "uploads limited to 5 files...' message. I wasn't able to reproduce this on the `master` branch:

Repro:
1) Post a message
2) Click on the [...] menu of the message, then "Reply" to open the right-hand sidebar
3) Make enough posts on the right-hand sidebar so that the "Add Comment" button reaches the bottom of the screen
4) Click the paperclip icon and upload a file

Observed: Right-hand sidebar doesn't scroll to the bottom and you cannot see the file you uploaded

image

Expected: Right-hand sidebar scrolls to the bottom once file is uploaded

**Comment by mikaoelitiana** [comment]
@jasonblais I will check and fix that

**Comment by jasonblais** [comment]
Awesome! This improvement will be great to have, big thanks @mikaoelitiana for helping with it :)

**Comment by mikaoelitiana** [comment]
@jasonblais I have fixed issue 1 and I am workin gon second one. I have the same behavior in `master` though

**Comment by mikaoelitiana** [comment]
@jasonblais I made an update to scroll sidebar in file preview after upload

**Comment by jasonblais** [comment]
Thanks @mikaoelitiana for this! Will test it out soon

**Comment by mikaoelitiana** [comment]
Thank you @esethna

**Pull request merged**
