### PR TITLE
PLT-3811 Fix OAuth 2.0 provider help text

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
Fix text replaced during a rebase.

Also the en.json file has been sorted by id

This also fixes incorrect Ids on RHS header

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-3811

https://pre-release.mattermost.com/core/pl/gpbnhi1trpnxpnk3td7nhehuur

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [ ] All new/modified APIs include changes to the drivers
- [ ] Has enterprise changes (please link)
- [ ] Has UI changes
- [x] Includes text changes and localization files updated
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by coreyhulen** [comment]
+1

**Comment by crspeller** [comment]
+1

**Comment by jasonblais** [comment]
Additional localization changes not yet discussed in triage, we'll update PM status in a couple hours

**Comment by jasonblais** [comment]
Approved for RC2

**Pull request merged**
