### PR TITLE
MM 1703 Closing access history or activity log returns user to security menu

### PR DESCRIPTION
**Pull request by nickago**

### CODE REVIEW

**Comment by rgarmsen2295** [comment]
Looks good, +1

**Comment by crspeller** [comment]
+1

**Comment by hmhealey** [comment]
Is there a reason that the user settings modal called user_settings1 everywhere instead of just user_settings? We might want to change that if there's no issues with that just so the code is nicer. Other than that, it looks good though.

**Comment by nickago** [comment]
yah, I can't find a compelling reason to keep it. Thoughts @jwilander?

**Comment by jwilander** [comment]
I think there was a jquery issue that wouldn't open the modal with the name "user_settings" due to a conflict somewhere. It might have abated, so feel free to try changing it to "user_settings" and testing that out. It's honestly not a big priority though so don't spend too much mana on it, but it would style a bit nicer without the suffix 1.

**Comment by hmhealey** [comment]
Agree with jwilander. Would be nice to have, but not worth too much time on it.

**Comment by crspeller** [comment]
@nickago This is waiting for the refactoring mentioned above correct?

**Comment by nickago** [comment]
Alright, I changed over the user_settings id

**Comment by jwilander** [comment]
+1

**Comment by hmhealey** [comment]
Cool, looks good

**Pull request merged**
