### PR TITLE
Add cli command to search for users

### PR DESCRIPTION
**Pull request by simon0191**
#### Summary
Add cli command to search for users based on username, email, or user ID

#### Ticket Link
#5627 and https://mattermost.atlassian.net/browse/PLT-5715

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [ ] All new/modified APIs include changes to the drivers
- [ ] Has enterprise changes (please link)
- [ ] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/platform/blob/master/i18n/en.json) and [.../webapp/i18n/en.json](https://github.com/mattermost/platform/tree/master/webapp/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by jasonblais** [comment]
Thanks @simon0191 for the contribution! Really glad to have you join the Mattermost community!

It looks like you implemented the feature as a slash command instead of a CLI command. Did you intend to do that?

**Comment by simon0191** [comment]
@jasonblais I misunderstood the issue description :p
Let me change the implementation, it looks like I can reuse most of the code I've already wrote.

**Comment by jasonblais** [comment]
Really sorry about the misunderstanding @simon0191, completely our fault. 

It's easy to mix between slash and CLI commands, so we should have been more specific about it. I've fixed this in our other help wanted issues by including a link to either our [slash command docs](https://docs.mattermost.com/developer/slash-commands.html) or [command line tool docs](https://docs.mattermost.com/administration/command-line-tools.html) depending on which it's referring to.

Thank you for helping implement this for a CLI command and I'm glad you're able to use most of the code.

Hugely appreciate your contribution! This will be a really nice addition to the tool!

**Comment by simon0191** [comment]
@jasonblais no problem. I just updated the PR, it now implements the CLI command.

**Comment by esethna** [comment]
Thanks @simon0191!  Just letting you know that there may be a delay in reviewing and merging your PR since we are approaching code complete for v3.8, releasing April 16th. Please see our [release process](https://docs.mattermost.com/process/release-process.html) for more details.

**Comment by jasonblais** [comment]
This CLI command supports searching for multiple queries at a time. Huge thanks for this @simon0191 

DEVS: If you'd like a PM to review something, let me know. But diff file looks good to me

**Pull request merged**
