### PR TITLE
[webui] fix loading animation for ie

### PR DESCRIPTION
**Pull request by ralder**
* fixed not working loading animation in IE (just using compass mixin for animation and keyframes)
* moved loading-screen to separate component
* and also fixed (post_list height not was 100% in Firefox, set cursor pointer for link "Invite others to this channel",  post_body.jsx typo for key)
* well and, as usual a bit refactoring :blush:

### CODE REVIEW

**Comment by crspeller** [comment]
Looks good from a technical perspective. 
@asaadmahmoodspin  take a look, test, and assign back to me to merge.

**Comment by asaadmahmoodspin** [comment]
Please have a look at the _loading.scss file. I did some changes a while back and it looks like your changes are overriding mine. Other than that I think it looks fine.

**Comment by ralder** [comment]
if you mean changes in this pr https://github.com/mattermost/platform/pull/151 I have considered and overrode a bit it

**Comment by asaadmahmoodspin** [comment]
Thanks, looks fine. We can merge this.

**Pull request merged**
