### PR TITLE
WIP: Add a new router for direct message

### PR DESCRIPTION
**Pull request by CometKim**
#### Ticket Link
#4598 Change URLs of Direct Messages to usernames
#5912 Add ability to link to channels based on unchanging channel_id instead of channel_url

#### Checklist
- [ ] Added or updated unit tests (required for all new features)
- [x] Has UI changes
- [x] Add redirections for old URLs

### CODE REVIEW

**Comment by jasonblais** [comment]
Posting here a summary of the plan based on the discussion here: https://pre-release.mattermost.com/core/pl/wb8zo1ndjjd4jrdoxeiokk8r7a

- New route for DM: `/messages/@username`
- New route for DM: `/messages/user_id` (redirect to `/messages/@username`)
- New route for DM: `/channels/user_id` (redirect to `/messages/@username`)
- Keep route for DM: `/channels/id1_id2` (redirect to `/messages/@username`)
- New route for GM: `/messages/generated_id`
- Keep route for GM: `/channels/generated_id` (redirect to `/messages/generated_id`)
- New route for Channel: `/channels/channel_id` (redirect to `/channels/channelurl`)

**Comment by jasonblais** [comment]
@CometKim let me know if there's anything we can help clarify? This would be an excellent improvement, really looking forward to it

**Comment by CometKim** [comment]
@dmeza looks working well on PR #6310 
* New route for DM: /messages/@username
* New route for DM: /messages/user_id (redirect to /messages/@username)
* New route for DM: /messages/email

I pushed simple UI changes and redirection rules under `/channels` route. This should be merge after #6310 merged.
* URL of openDirectchannel action
* URL of user profile popover
* Keep route for DM: `/channels/id1_id2` (redirect to `/messages/@username`)
* Keep route for GM: `/channels/generated_id (redirect to /messages/generated_id)`
* New route for Channel: `/channels/channel_id (redirect to /channels/channelurl)`

The `/channels/{user_id}` rule makes conflict in this implemetation because `user_id` has same length of url with `channel_id`

**Comment by jasonblais** [comment]
@CometKim Thanks for working on this!

And that's a good point on `/channels/user_id`. Yes, let's keep `/messages/user_id` and not add `/channels/user_id` to avoid the conflict.

Looks like there's a build failure on the PR -- I can set up a test server once those are resolved.

**Comment by jasonblais** [comment]
@CometKim #6310 is now merged.

Can you help rebase your branch and resolve the build failure? Please let me know if you need any help on those.

Really excited for this PR, looking forward to testing it out.

**Comment by esethna** [comment]
Hi @CometKim, just checking in on this PR. When you have a chance can you please help to resolve the build failure so we can set up a test server?

**Comment by esethna** [comment]
@CometKim let us know if there is anything we can help with to get this PR merged?

**Comment by esethna** [comment]
@CometKim I'm going to close this PR due to inactivity. Please feel free to resubmit if you get a chance to work on this again.

**Pull request closed without merging**
