### PR TITLE
PLT-2784 Channel Navigation Shortcuts

### PR DESCRIPTION
**Pull request by DavidLu1997**
ALT [up arrow]: Previous channel/DM in the left sidebar list
ALT [down arrow]: Next channel/DM in the left sidebar list
ALT SHIFT [up arrow]: Previous channel/DM with unread messages
ALT SHIFT [down arrow]: Next channel/DM with unread messages

@jwilander please review :)

### CODE REVIEW

**Comment by coreyhulen** [comment]
+1

**Comment by enahum** [comment]
+1

**Comment by DavidLu1997** [comment]
@enahum which tests?

**Comment by enahum** [comment]
The build from travis

**Comment by enahum** [comment]
Sorry build from jenkins.

Im all over the place today

**Comment by DavidLu1997** [comment]
It shows that the build passes for me? :)

**Comment by crspeller** [comment]
@DavidLu1997 This needs a rebase.

**Comment by DavidLu1997** [comment]
Rebased

**Pull request merged**
