### PR TITLE
Move SMTP HELO before authentication

### PR DESCRIPTION
**Pull request by hmhealey**
Turns out, it has to be the absolute first thing to happen

#### Checklist
- Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by hmhealey** [comment]
@lindalumitchell Can you test setting up email on this test server to confirm this fixes the issue from #5698? I can't find which credentials to use

**Comment by lindalumitchell** [comment]
@hmhealey On this test server, when I enter the email notification settings and click `Test Connection`, I see error:
```Connection unsuccessful: Failed to close connection to SMTP server - 554 Access denied: User `arn:aws:iam::521493210219:user/ses-smtp-user.ci-servers' is not authorized to perform `ses:SendRawEmail' on resource `arn:aws:ses:us-east-1:521493210219:identity/mattermost.com'```

- Using the same settings on ci-linux-mysql-prev, Test Connection is successful and email sends
- Using the same settings on the other PR 5698's test server, Test Connection produces error ```Connection unsuccessful: Failed to set HELO - smtp: Hello called after other methods```

**Comment by jwilander** [comment]
You won't be able to use our SES credentials with spinmint servers. We restrict by IP address

@hmhealey we should probably just merge this and try it on a CI server

**Comment by hmhealey** [comment]
Thanks @lindalumitchell! That's still a different message than on the other spinmint, so I think it's safe to assume it worked

**Pull request merged**
