### PR TITLE
[APIV4] POST /email/test apiV4 - Send Test Email

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
This PR implements the POST v4/email/test endpoint to send an test email

#### Ticket Link
n/a

#### Checklist
- [x] Added or updated unit tests
- [x] Added API documentation - PR: https://github.com/mattermost/mattermost-api-reference/pull/138
- [x] All new/modified APIs include changes to the drivers

### CODE REVIEW

**Comment by jwilander** [comment]
@cpanato can you give this a rebase when you get a chance?

**Comment by cpanato** [comment]
@jwilander done

**Comment by grundleborg** [comment]
@cpanato sorry, would you be able to give it another rebase at some point? We've just merged a flood of PRs into master, which has meant all the APIv4 PRs have started with conflicting with each other!

**Comment by cpanato** [comment]
@grundleborg I will rebase this one, wait to be merged and rebase the other one. ok? :)

**Comment by grundleborg** [comment]
@cpanato yes, that would be great thanks.

**Comment by cpanato** [comment]
@grundleborg done

**Comment by grundleborg** [comment]
Thanks @cpanato - merged.

**Pull request merged**
