### PR TITLE
PLT-4855 (#4708) Fix overlapping emoji reactions + UI improvements

### PR DESCRIPTION
**Pull request by bjoernr-de**
#### Summary
This PR fixes the overlapping emoji reactions issue plus adds little UI improvements for emoji reactions.
Please see the GitHub issue for screenshots.

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-4855
https://github.com/mattermost/platform/issues/4708

#### Checklist
- [x] Has UI changes

### CODE REVIEW

**Comment by bjoernr-de** [comment]
Added message with some emoji reactions to Spintmint instance for review 😃

**Comment by jasonblais** [comment]
Great work @bjoernr-de! Love the proper alignment of emoji reactions :tada:

Tested on Windows 10, Chrome:
 - center channel and RHS
 - text-only messages, and messages containing files
 - did a quick smoke test on emoji reactions (reactions from multiple users, adding/removing reactions).

-----

Found an unrelated issue with a file upload misalignment, created ticket here: https://mattermost.atlassian.net/browse/PLT-5000

Also found a couple of known issues, again not caused by this PR
 - https://github.com/mattermost/platform/issues/4760
 - https://mattermost.atlassian.net/browse/PLT-4898

**Comment by jasonblais** [comment]
Queuing for second PM review, great work @bjoernr-de!!

**Comment by jasonblais** [comment]
Whoops, sorry, didn't mean to close this,

**Comment by esethna** [comment]
Thanks @bjoernr-de! +1 on this PR, tested on Win 10/Chrome.

____

I found an unrelated minor issue with emoji reactions where if you try to add two of the same reactions then the order of the emojis shifts. We'll have to figure out the best way to approach this fix but it is not blocking this PR.

**Comment by coreyhulen** [comment]
+1 but I'll defer to @asaadmahmood

**Comment by asaadmahmood** [comment]
+1, looks good.

**Pull request merged**
