### PR TITLE
PLT-3357 Fixed scrolling in channel switcher

### PR DESCRIPTION
**Pull request by DavidLu1997**
#### Summary
Fixed broken scrolling when scrolling up in the channel switcher using the UP/DOWN arrows.

This was caused by `location='bottom'` being different from `location='top'`, we have not used `location='bottom'` anywhere before.

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-3357

#### Checklist
- [ ] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [ ] Has driver changes that have been merged and package.json updated
- [ ] Has enterprise changes (please link)
- [x] Has UI changes
- [ ] Includes text changes and localization files updated
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by jwilander** [comment]
+1

**Comment by DavidLu1997** [comment]
@hmhealey Fixed it in CSS now, this took way too long.

**Comment by hmhealey** [comment]
+1

**Comment by enahum** [comment]
+1

**Pull request merged**
