### PR TITLE
PLT-5446: Fix spacing between file uploads

### PR DESCRIPTION
**Pull request by senk**
#### Summary
Fixes spacing between file uploads
#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-5446
#### Checklist
- [x] Has UI changes

### CODE REVIEW

**Comment by jasonblais** [comment]
Sweet, thanks! @asaadmahmood can you help with initial review?

**Comment by asaadmahmood** [comment]
This would mess up spacing for the markdown inside posts.
So I'd suggest just adding the correct margin to `.post-image__column` themselves.

**Comment by jasonblais** [comment]
Hey @senk, did you need any help with this one?

**Comment by senk** [comment]
TBH i don't know what gets broken by my solution. @asaadmahmood could you provide an example? I have currently no idea why the margin on post-image__column gets overwritten

**Comment by asaadmahmood** [comment]
@senk There are div tags sometimes inside the post, that hold other elements inside them, and that have text within them.
If you don't mind, I'll take this issue. The reason it gets overriden is because the post tag is prioritised due to the extra specifications given to.

screen shot 2017-02-14 at 11 22 19 am

**Comment by asaadmahmood** [comment]
Or if you want, you can just change that line you deleted to:
`margin-bottom: .4em;` instead of `margin: 0`.

**Comment by senk** [comment]
Will change it later that Day. Thanks for the explanation and help!

**Comment by senk** [comment]
@asaadmahmood changed to your suggestion

**Comment by jasonblais** [comment]
@asaadmahmood Can you help review the latest changes?

**Comment by asaadmahmood** [comment]
Looks good to me +1.

**Pull request merged**
