### PR TITLE
PLT-4783 Fix autofocus for "Add/Manage Members" and "More public channels" modals

### PR DESCRIPTION
**Pull request by fraziern**
This is a draft PR, as I think more conversation is necessary here. There are a couple of changes here I'm pretty sure about: 

 - `web_client.jsx`: this is just changed in anticipation of #4603 being merged, because otherwise my local repo crashes;
 - `channel_invite_modal.jsx, member_list_team.jsx`: I think these need to pass the prop `focusOnMount` to their `SearchableUserList` components so that autofocus works properly;

***The change I'm not sure about is in `sidebar_header_dropdown.jsx`:***

This is intended to fix the focus issue when you select "Manage Members" from the sidebar dropdown. Selecting this seems to do 2 things synchronously, (1) hide the dropdown, and (2) show the modal. The problem seems to be that both actions want to grab focus, at the same time.

The react-bootstrap Dropdown component will check focus whenever it updates. When it toggles off, if the menu has focus still, the toggle button tries to retain focus. If it doesn't it doesn't. Here, with both the modal and the dropdown getting toggled at the same time, the most likely chain of events is:

 1. modal appears;
 1. menu still has focus when the modal appears, so `Dropdown` calls `focus()` on the toggle button;
 1. the modal calls `focus()` on its search bar;
 1. the toggle button finally takes focus.

My proposed solution (after trying a couple of things) is to pass an "onLoad" function prop to the `TeamMembersModal` that gets run when the modal is mounted. This function is just the dropdown's `toggleDropdown` method. So in effect, the modal is mounted, *then* the dropdown is hidden, and the dropdown doesn't try to take focus because it detects that something else besides itself has focus.

#### Ticket Link
See issue #4599

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] Has UI changes

### CODE REVIEW

**Comment by jasonblais** [comment]
Thanks @fraziern 

I'll defer to devs whether the proposed implementation for `sidebar_header_dropdown.jsx` is acceptable. The user experience appears to be fine, didn't notice any issues.

One note: It appears clicking "More..." at the bottom of your public channel list (to join a new channel) doesn't set focus to the search bar. Can you help take a look?

image


After that, I'll re-test it and queue for dev review to hear their thoughts on the proposed change to `sidebar_header_dropdown.jsx`

**Comment by fraziern** [comment]
Hi @jasonblais - ok the "More..." modal was working OK for me at first, but I can see now that it doesn't always function properly. I'm taking another look.

**Comment by fraziern** [comment]
OK I think I've worked out a fix for this. Let me know what y'all think.

**Comment by jasonblais** [comment]
From UX standpoint, no issues. Focus is set to search bar when any of these modals are opened:

1) Main Menu > Manage Members
2) Channel drop down menu > Manage Members (to remove members)
3) Channel drop down menu > Add Members
4) "More..." at the bottom of your public channel list
5) "More..." at the bottom of your direct message list

Also tested that the dropdown menu in manage members modal works fine

**Comment by jasonblais** [comment]
DEVS: **[Please read details of the proposed change by @fraziern first](https://github.com/mattermost/platform/pull/4610#issue-190579470), before code review**

**Comment by crspeller** [comment]
@fraziern Looks good! Just needs a rebase and it should be good to go.

**Comment by fraziern** [comment]
@crspeller Done. Thanks!

**Comment by crspeller** [comment]
@fraziern I think something went wrong with your rebase. There are a lot of unrelated changes there.

**Comment by fraziern** [comment]
@crspeller yeah that did seem odd, but tbh I don't have much experience with rebasing in an open PR so didn't know what to expect. I'll see if I can get this cleaned up.

**Comment by fraziern** [comment]
@crspeller ok I think we're good now.

**Comment by crspeller** [comment]
@fraziern Looks good!

**Pull request merged**
