### PR TITLE
Fix isMobileApp() to also apply to Android app

### PR DESCRIPTION
**Pull request by CometKim**
#### Summary
Fix the UserAgent.isMobileApp() to also apply to Android app

#### Ticket Link
#4891

### CODE REVIEW

**Comment by esethna** [comment]
Thanks @CometKim, requesting review from @asaadmahmood who has an Android device

**Comment by asaadmahmood** [comment]
+1

**Comment by CometKim** [comment]
I think we should check desktop app also to don't display download app link.

Please don't close this pr yet.

**Comment by esethna** [comment]
@CometKim I think the desktop apps should display the "Download Apps" option so people can download mobile apps.

**Comment by CometKim** [comment]
Let's take a look at this more deeper.

First, the default "Download Apps" link to [https://about.mattermost.com/download/], not a directly link to market and this page contains links for mobile and desktop apps both.

Here is two question,

Why we hide the "Download Apps" link? There are useful information even a user already has the app like recent version.. 

Why we hide it for *mobile only* ? I think desktop app is also an app. It means there is no more things to download on desktop.

**Comment by esethna** [comment]
@CometKim my thinking is that:

1) If you are on mobile, you cannot download the desktop apps to your phone so it doesn't make much sense to link to the download page.

2) If you are on desktop app you can still download mobile apps (for example, via itunes for iphone). So in this case it would make sense to keep the download link.

Open to discussion,

**Comment by CometKim** [comment]
You right. I never have used app store on my desktop before.

**Pull request merged**
