### PR TITLE
PLT-2886 Added name properties to all radio buttons

### PR DESCRIPTION
**Pull request by hmhealey**
Also removed a page from the system console that I should've removed months ago

### CODE REVIEW

**Comment by crspeller** [comment]
+1

**Comment by enahum** [comment]
+1 if all the localization strings removed from team_settings are present in other files with the same id's

**Comment by hmhealey** [comment]
Oh right. I'll check that out tomorrow

**Comment by hmhealey** [comment]
Okay, I think that's all of them. Ready to merge once the build finishes

**Pull request merged**
