### PR TITLE
Add support for SMTP servers with StartTLS

### PR DESCRIPTION
**Pull request by jirkah**
Hello,
  a pull request for my feature idea.

Thanks,
Jirka

### CODE REVIEW

**Comment by jwilander** [comment]
Hi @jirkah  , thanks for the pull request! 

Before we can review and accept your PR we'll need you to sign the CLA here http://www.mattermost.org/mattermost-contributor-agreement/ .

**Comment by jirkah** [comment]
Hi @jwilander,
   Sorry, I've missed the info. Done.

Cheers,
Jirka

**Comment by crspeller** [comment]
Hi @jirkah 

We have a style guide that is found here: https://github.com/mattermost/platform/blob/master/STYLE-GUIDE.md

We are in the process of refactoring all our code to match the style guide. Could you run ESLint on your code and fix any errors you find? You can ignore any pre-existing errors. 

You can install ESLint with npm by running: `npm i -g eslint` and `npm i -g eslint-plugin-react`

Thanks!

**Comment by crspeller** [comment]
This looks good to me.

**Comment by jwilander** [comment]
+1

**Comment by jirkah** [comment]
Many thanks!

**Pull request merged**
