### PR TITLE
PLT-831 Added single image thumbnail

### PR DESCRIPTION
**Pull request by DavidLu1997**
#### Summary
Added single image thumbnails, changed multi-image/file thumbnails.

Single images will be resized based on a max of 500 x 400 px, thumbnails are based on 100 x 65 px. Images will be resized based upon the largest dimension. Dimensions of the thumbnail can be modified in `config.json`. Dimensions of the preview cannot.

Almost all CSS by AM

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-831

#### Checklist
- [x] Has UI changes

image

### CODE REVIEW

**Comment by it33** [comment]
Clicking on a filename downloads the file, but the formatting of the file name looks like regular text (BLACK TEXT), not link (BLUE) 

image

**Comment by DavidLu1997** [comment]
@it33 Added download icons in front of names

**Comment by jasonblais** [comment]
Tested on Windows 10, Chrome -- 

there is one issue with the PR where posting an image doesn't scroll all the way to to bottom of the image, so you only see its top.

Can you help take a look @DavidLu1997? Since it's not reproducible on `master`, it might be caused by something on your PR.

image
image

**Comment by DavidLu1997** [comment]
@jasonblais should be fixed after rebase

**Comment by jasonblais** [comment]
@DavidLu1997  Can you take a second look tomorrow?

Seems to be reproducing still - it needs to have some content in the center channel first.

Best way to reproduce is by posting a few single-file images in the center channel. After a few of them, most of the image stays hidden behind the message box.

**Comment by DavidLu1997** [comment]
Closing to resubmit with PLT-3197

**Pull request closed without merging**
