### PR TITLE
resolves PLT-1527

### PR DESCRIPTION
**Pull request by daizenberg**
- updated DB schema to store user's manually selected status (online/away/offline)
- changed model to handle a combination of manually selected status and inactivity-based status
- added API calls to change status
- added slash commands
- updated tests to cover both API and slash commands parts
- added some test infrastructure to make test better readable (be a documentation in a sense)

### CODE REVIEW

**Comment by jwilander** [comment]
Hi @daizenberg, looks like you've an old version of the Makefile. If you rebase with master your build should pass

**Comment by it33** [comment]
Hi @daizenberg, actually, please hold off on rebasing, we're doing a bunch of changes right now and can't take a feature PR for another couple of weeks. We can let you know when we're ready to accept feature PRs again, bug PRs on master as still welcome.

**Comment by daizenberg** [comment]
@jwilander, @it33 thank you for the prompt replies. I'm waiting until you are ready to accept PRs again. Please let me know.

**Comment by coreyhulen** [comment]
Hi @daizenberg sorry for the long delay.  PLT-2057 has been merged into master.  A lot has changed in the user model and I suspect this PR will need some work.  We would love for you to update and re-submit.  I'm closing this PR awaiting the new PR :)

**Comment by daizenberg** [comment]
Hi @coreyhulen and thanks for keeping in touch. Looks like you completed a big chunk of work - congrats! I will hopefully look into it and bring the PR back to life in a couple of days

**Comment by it33** [comment]
Hi @daizenberg, thanks again for starting this project, things are a lot more stable now, are you interested in finishing things off?

**Pull request closed without merging**
