### PR TITLE
PLT-3502 Fix Team admins can't give "team admin" privilege to members

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
There was a case where a Team admin couldn't make another user team admin

#### Issue/Ticket Link
https://mattermost.atlassian.net/browse/PLT-3502

### CODE REVIEW

**Comment by jwilander** [comment]
Unit test failure
```
--- FAIL: TestUserUpdateRolesMoreCases (0.89s)
	user_test.go:914: Should have succeeded since they are team admin
```

**Comment by enahum** [comment]
@jwilander should be fixed now

**Comment by coreyhulen** [comment]
+1

**Comment by jwilander** [comment]
+1

**Pull request merged**
