### PR TITLE
Fixes the notification display in Firefox (refs #1806)

### PR DESCRIPTION
**Pull request by GuillaumeAmat**
Another PR to fix the #1806 issue.

### CODE REVIEW

**Comment by titleistfour** [comment]
Hi,

So now I can see  "Desktop notification sounds - Please configure notification sounds in your browser settings", so that part is fixed.  However, I can't find exactly what setting this is referring to in Firefox.  I would be glad to test that part as well if someone could point me to what I need to adjust. 

Thanks,
Jay

**Comment by titleistfour** [comment]
Ok, created a new team, added another user.  Testing worked!  Looks like this fixed the FF notification issue.  Thanks!

**Comment by it33** [comment]
Thanks @titleistfour! 

Very much appreciated, can you let us know which OS you used in your testing?

**Comment by lindy65** [comment]
@it33 Tested with two accounts between Firefox on Windows and iOS and confirm desktop notifications are working in Firefox.

**Comment by titleistfour** [comment]
I tested in Windows, but I can test on Mac OS X later today and let you know if it is fixed there too.

**Comment by it33** [comment]
Thanks @lindy65, thanks @titleistfour, and thanks @GuillaumeAmat for the PR! Labels added for final review and merge,

**Comment by jwilander** [comment]
+1

**Comment by GuillaumeAmat** [comment]
@it33 @jwilander You're welcome! I'm looking forward to the merge ;)

**Comment by it33** [comment]
+1

**Comment by GuillaumeAmat** [comment]
@it33 @jwilander Do you know when it will be merged?

**Pull request merged**
