### PR TITLE
Slack format for Slash command messages

### PR DESCRIPTION
**Pull request by ZJvandeWeg**
Right now these are mutually exclusive. I proposed a Format column, however, a one liner, [proposed by @jwilander](https://pre-release.mattermost.com/core/pl/fbhro674biyo3gjqxagy9ennae) fixed this. So no need for a potentially expensive migration.

Note, we do the same check twice now, while executing `generateStaticEmbed()`. However, `attachments` in `getSlackAttachments` could still be `[]` so I don't think we can remove the one in `getSlackAttachments`.

Visual difference between `in_channel` and `ephemeral`:

screen shot 2017-01-06 at 15 12 24

#### Checklist
- [ ] Added or updated unit tests (required for all new features)
- [X] Has UI changes

### CODE REVIEW

**Comment by ZJvandeWeg** [comment]
Note 2: this is based of my other PR: #4996 

So shouldn't be merged before that one. If needed I can rebase this one against master.

**Comment by ZJvandeWeg** [comment]
Supercedes #4996

**Comment by hmhealey** [comment]
@jwilander Which PR is this waiting on? I think both the original PRs were combined into ine

**Comment by jwilander** [comment]
Yep, this is the sole PR now

**Pull request merged**
