### PR TITLE
Fix archive messages

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
 - Fix the error messages int he cmd archive to use the archive wording.
 - Also, refactor the store the use the Delete name but in fact, just archive, change the name to avoid misunderstandings.

@jasonblais @coreyhulen maybe we also can change the db field name deletedAt to be archievedAt. what do you guys think?

#### Ticket Link
N/A

### CODE REVIEW

**Comment by jasonblais** [comment]
@cpanato Can you help describe the benefit for these changes? Do we refer to other similar actions as "archive" or as "delete"?

**Comment by cpanato** [comment]
@jasonblais 
The first commit is to fix this PR: https://github.com/mattermost/platform/pull/6430 which I made a change from delete to archive because the delete didn't delete and actually archive. Do you remember our discussion?

The second commit is more to adjust the name and to try to avoid confusion between delete and archive because those changes don't make a delete it actually apply an archive. 

That's was the reason for this PR.
Also, I made a comment to we discuss if also make sense to change the deleteAt to be archiveAt for the same reasons.

makes sense?

thanks
carlos

**Comment by jasonblais** [comment]
Thanks @cpanato, it makes sense.

The reason we changed it for channels in #6430 is that `delete` command for teams and users permanently deletes them -- so it made sense to do the same for channels (and have `archive` for archiving channels).

As long as we stay consistent here, i.e. `Delete` name is used in the store for permanently deleting any object, whether it's channels, teams or users, and `Archive` is for archiving, then we're good. Does this PR achieve that?

Similarly for the `DeleteAt` DB column -- does it mean permanent deletion in all of our tables, or "archving"? The column name is used in a lot of our tables (teams, users, posts, channels, ...) so it should mean the same thing for each of them.

**Comment by cpanato** [comment]
@jasonblais Ok agree!

this PR just change channels, I did a quick look and for `post` it use the `delete` but actually don't delete is more a soft delete (or archive). For `team`, looks like ok. For others need to check carefully.

if you think this is useful, then I think we can create a ticket and then go thru each one and check. Then for this PR I can remove the commit that changes the name `Delete`to `archieve`  and keeps only the fix for the strings.

what do you think?

**Comment by coreyhulen** [comment]
I think we're very consistent with the DeleteAt db column being the soft delete since if you hard deleted the row would return nothing and have no need for the column.  We shouldn't be renaming the db column or the object model.  We should only rename the UI to be consistent with soft_delete=archive and hard_delete=delete.

**Comment by coreyhulen** [comment]
Changing the app layer from `Delete` to `Archive` is OK.

**Comment by jasonblais** [comment]
Sounds good to me - Carlos can you help ensure the PR reflects the above recommendations? 

I'll queue for dev review since there isn't much otherwise for PMs here.

**Comment by cpanato** [comment]
ok @coreyhulen makes a lot of sense as well.

Then I will keep the PR as is, ok?

**Comment by cpanato** [comment]
@crspeller I will drop this commit and will check deep in the code and make a proposal to you guys.

thanks!

**Comment by cpanato** [comment]
@crspeller dropped the commit and now just the correct messages for archive command.

**Pull request merged**
