### PR TITLE
Add Date header in mail so it will be sorted correctly

### PR DESCRIPTION
**Pull request by BastienDurel**

### CODE REVIEW

**Comment by jwilander** [comment]
Hi @BastienDurel  , thanks for the pull request!

Before we can review and accept your PR we'll need you to sign the CLA here http://www.mattermost.org/mattermost-contributor-agreement/ .

**Comment by BastienDurel** [comment]
done

**Comment by CtrlZvi** [comment]
@BastienDurel Thanks for submitting this PR. I've noticed the issue, too, and it's really annoying. In the interest of helping get this in, I just wanted to mention that it looks like your import of the time package is not aligned correctly. a quick run of `go fmt` should fix that right up.

**Comment by BastienDurel** [comment]
Thanks, it's corrected

**Comment by crspeller** [comment]
@BastienDurel Thanks for the pr. Looks good to me.

**Comment by BastienDurel** [comment]
Most mailers will perform better with numeric timezones, and adding century won't hurt

**Comment by jwilander** [comment]
+1

**Pull request merged**
