### PR TITLE
Update Mac OS X install instructions, switching Boot2Docker to Docker Toolbox

### PR DESCRIPTION
**Pull request by pstonier**
Migrated from boot2docker to docker-machine

### CODE REVIEW

**Comment by it33** [comment]
Thanks @pstonier for the pull request! 

Before we can review, we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**

This is a standard procedure for many open source projects. Your form should be processed within 24 hours and reviewers for your pull request will be able to proceed. 

Please let us know if you have any questions. 

We are very happy to have you join our growing community!

**Comment by pstonier** [comment]
I've completed the agreement.

**Comment by it33** [comment]
Thanks @pstonier! PR is looking good, we're in the [stablization phase](http://forum.mattermost.org/t/preview-mattermost-release-process/179) of our release process right now, so there will be a review on Monday whether this change goes into RC1 or the next release. 

Very glad to have you on the approved contributor list and part of the growing community!

**Comment by hmhealey** [comment]
Looks good. I might borrow some of this for the updates to the dev setup instructions that I need to make.

**Comment by jwilander** [comment]
+1

**Pull request merged**
