### PR TITLE
translations PR 20170509

### PR DESCRIPTION
**Pull request by enahum**
Ideally this PR should be review by community members for each language.

Note: In the event that you see an english translation instead of the desired language is because this PR was submitted before the translation was made on the Mattermost Translation Server and probably will be submitted for the next PR.

### CODE REVIEW

**Comment by wget** [comment]
Ok for `fr`.

**Comment by jasonblais** [comment]
@meilon What changes are they? 

If they're minor, it might be okay to include in the next release

**Comment by meilon** [comment]
Yes, they are minor

**Comment by cpanato** [comment]
`PT-BR` lgtm

**Comment by jasonblais** [comment]
@meilon It looks like more suggestions were added today, so propose we include these changes for 3.10? https://translate.mattermost.com/de/mattermost/translate/#filter=suggestions

Let me know if that's okay,

**Comment by kaakaa** [comment]
`ja` is ok

**Pull request merged**
