### PR TITLE
[WIP] Test PR to explore signature v2 support.

### PR DESCRIPTION
**Pull request by harshavardhana**
#### Summary
Test PR to explore signature v2 support. This optionally also updates minio-go.

#### Ticket Link
None yet.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [ ] All new/modified APIs include changes to the drivers
- [ ] Has enterprise changes (please link)
- [ ] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/platform/blob/master/i18n/en.json) and [.../webapp/i18n/en.json](https://github.com/mattermost/platform/tree/master/webapp/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by harshavardhana** [comment]
// @coreyhulen - this PR adds the change to force V2 for the testing. Please let me know how the testng goes.

**Comment by coreyhulen** [comment]
Awesome...thanks.

**Comment by coreyhulen** [comment]
@harshavardhana this appears to have worked.  Can we do a proper fix by adding a config option to switching between `s3.New()` and `s3.NewV2()` and submit it to master?

**Comment by coreyhulen** [comment]
@crspeller If you're updating the 3rd party libs soon can you update the Minio driver too?

**Comment by harshavardhana** [comment]
> @harshavardhana this appears to have worked. Can we do a proper fix by adding a config option to switching between s3.New() and s3.NewV2() and submit it to master?

Sure will send a fix to the UI as well.

**Pull request closed without merging**
