### PR TITLE
translations PR 20170626

### PR DESCRIPTION
**Pull request by enahum**
Ideally this PR should be review by community members for each language.

Note: In the event that you see an english translation instead of the desired language is because this PR was submitted before the translation was made on the Mattermost Translation Server and probably will be submitted for the next PR.

### CODE REVIEW

**Comment by enahum** [comment]
@jasonblais this PR includes italian

**Comment by jasonblais** [comment]
@enahum Looks like there's a build failure

**Comment by kaakaa** [comment]
`ja` LGTM

**Comment by jasonblais** [comment]
@JeffSchering This PR added Italian language support

**Pull request merged**
