### PR TITLE
Render channel links

### PR DESCRIPTION
**Pull request by pan-feng**
#### Summary
Render channel

#### Ticket Link
Issue #5289 

#### Checklist
- [x] Has UI changes

### CODE REVIEW

**Comment by pan-feng** [comment]
@esethna done

**Comment by jasonblais** [comment]
@pan-feng Thanks for all your contributions, really appreciate your help!

In future PRs that you submit, can you also help follow the three steps [for submitting a pull request included in our contribution guidelines](https://docs.mattermost.com/developer/contribution-guide.html#submitting-a-pull-request)?

You're already doing step 1, which is great. Steps 2 and 3 will help others not familiar with the original issue quickly understand what your PR accomplishes.

**Comment by pan-feng** [comment]
@esethna  thx, I had fix 1, and add auto complete for create NewChannel.

**Comment by esethna** [comment]
Thanks @pan-feng! I've re-tested,

1. To be consistent with our other modals, can we please have the autocomplete open below the text box instead of above it? See edit post modal as example:

image

2. Can you please update the first comment in this PR and fill in the template? This is helpful for our team and other community members during the review phase.

image

Other than that this is looking great! Really appreciate your contributions.

**Comment by pan-feng** [comment]
@esethna done

**Comment by esethna** [comment]
Hi @pan-feng, thanks for the tweaks! I found a few more issues if you don't mind taking a look:

1. If you create a new public channel with a purpose and channel header, then try to create another public channel. The channel header remains in the "Header" input box from the previous channel you created.

3. If you create a new channel, type "~off" in the Header box, then use the autocomplete to select the "Off-Topic" channel. After the channel is created, the channel header appears as "~off", rather than "off-topic". See GIF

channel header

**Comment by esethna** [comment]
Hey @pan-feng, just wondering if you had a chance to take another look at this?

**Comment by jasonblais** [comment]
@pan-feng Just so you know, there may be a delay in merging this PR as we are locking down feature and improvement contributions for the v3.7 release, per our [release process](https://docs.mattermost.com/process/release-process.html). This PR can be merged into `master` after we branch `release-3.7` on March 6th.

**Comment by jasonblais** [comment]
Hey @pan-feng, how are you? Hope all is well,

I noticed there hasn't been activity for a couple of weeks - just wanted to touch base and see if there's anything I can help clarify on the feedback provided above.

Would really love to see this improvement in the product, and work with you to add it in.

**Comment by jasonblais** [comment]
We haven't received an update so we'll assume that the PR is no longer been worked on. Closing the PR so someone else in the community can help take a look.

If you're still interested helping with this improvement, let us know! Would love to work with you on this. Also, feel free to re-submit the PR anytime.

Many thanks for all your help thus far: https://github.com/mattermost/platform/pulls?q=is%3Apr+author%3Apan-feng+is%3Aclosed

**Pull request closed without merging**
