### PR TITLE
MM-319 adding pending post functionality to the client

### PR DESCRIPTION
**Pull request by jwilander**
This PR updates the client to give immediate feedback when a message is posted and also gives the ability to retry failed posts.

There is some reformatting for the style guide in here, and some of it is mixed in with commits that change functionality (since I made those commits before I was told about the separate commits idea).

### CODE REVIEW

**Comment by crspeller** [comment]
A quick look from me everything looks good. @jwilander needs rebase.

**Comment by nickago** [comment]
+1, ready to merge when rebased

**Comment by jwilander** [comment]
Rebase complete with some additional reformatting required due to the rebase. Please give it a quick once-over before merging

**Comment by nickago** [comment]
My +1 still stands, looks like we need to re-run though

**Comment by jwilander** [comment]
Needs another rebase due to the revert :/ Give me a minute..

**Comment by jwilander** [comment]
Ok third and final rebase complete

**Comment by nickago** [comment]
Still + 1

**Comment by jwilander** [comment]
@crspeller does this still look good to you?

**Comment by crspeller** [comment]
@jwilander Looks good... but needs rebase :O

**Pull request merged**
