### PR TITLE
translations PR 20170213

### PR DESCRIPTION
**Pull request by enahum**
Ideally this PR should be review by community members for each language.

Note: In the event that you see an english translation instead of the desired language is because this PR was submitted before the translation was made on the Mattermost Translation Server and probably will be submitted for the next PR.

### CODE REVIEW

**Comment by meilon** [comment]
de LGTM

**Comment by kaakaa** [comment]
`ja` LGTM

**Comment by ArchRoller** [comment]
`ru` LGTM

**Comment by jasonblais** [comment]
Thanks @meilon @kaakaa and @ArchRoller! 

@enahum looks like there's a merge conflict, otherwise should be good to merge

**Comment by enahum** [comment]
@jasonblais can you approve the PR so we can merge it please

**Pull request merged**
