### PR TITLE
(Waiting for PLT-2241): Online status in all modals

### PR DESCRIPTION
**Pull request by samogot**
add wrapper to modal avatar image which show small round indicator of online/away status of member in all modals

image
image

### CODE REVIEW

**Comment by it33** [comment]
Hi @samogot, thanks for completing the CLA, setting up a test server to look into this. 

There's [an existing ticket accepting pull requests related to this](https://mattermost.atlassian.net/browse/PLT-715), but I imagine the design is flexible, 

There's [a related ticket about including status in the center channel](https://mattermost.atlassian.net/browse/PLT-1831) as well. 

I've queued a discussion about this in the [UX Design channel](https://pre-release.mattermost.com/core/pl/cyqxqn1rrbrddknw5wtuk79xac), which meets to discuss design issues on weekdays at 08:30 PST (UTC-7). Anyone is welcome to drop by,

**Comment by samogot** [comment]
don't work(
is https://github.com/mattermost/platform/pull/2729/commits/5caeaac5604135fae9f9351a770589731c35c7ee commit got to test server?

**Comment by jwilander** [comment]
Hi @samogot,

We appreciate the PR, the UI looks really nice and would be very useful to users. However, the status API wasn't originally built to work on the scale required for this and it would be a major performance hit for any team with a lot of users to ask the server for the statuses like you've done here.

As a result we can't accept this PR until the status and profile APIs are updated to handle teams of many users. There is a ticket to do that [here](https://mattermost.atlassian.net/browse/PLT-2241) and when this is completed then we'll gladly accept your UI changes.

**Comment by samogot** [comment]
Hi @jwilander,
I can't see the ticket
> __This issue can't be viewed__
The issue you're trying to view can't be displayed.
It may have been deleted or you don't have permission to view it right now.

Do you mean that there is APR, or that I should implement it inside my PR, or it is just yours internal ticket that mattermost team will complete by themselves

**Comment by jwilander** [comment]
Oops, sorry about that. The ticket was marked internal, I've updated it to be public so you should be able to see it now.

It's a ticket we're going to work on and complete internally.

**Comment by jwilander** [comment]
Closing for now, if you'd like to resubmit once [PLT-2241](https://mattermost.atlassian.net/browse/PLT-2241) that would be much appreciated

**Pull request closed without merging**
