### PR TITLE
PLT-2345 Switch "help" link below text input box to localizable version

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
The "help" link under the input textbox now opens a new `tab` with a localized version of the `Messaging` docs found in https://docs.mattermost.com/help/getting-started/messaging-basics.html

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-2345

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Has UI changes
- [x] Includes text changes and localization files updated

### CODE REVIEW

**Comment by jwilander** [comment]
+1

**Comment by jasonblais** [comment]
+1

**Comment by jwilander** [comment]
Needs a rebase

**Comment by enahum** [comment]
@jwilander rebased

**Comment by crspeller** [comment]
@enahum This doesn't scale. Is it not meant to scale? I doubt PMs will be able to restrain themselves from expanding this. Maybe we should design it to scale? Or push for translating the docs instead?

**Comment by enahum** [comment]
@crspeller as far as I know there are plans to translate the docs but first it has to be converted to `rst` format, and what's required is actually help on how the messaging works.

Happy to discuss a way to make it scalable if you have a proposal.

**Pull request merged**
