### PR TITLE
PLT-3001 Stopped trimming passwords on login

### PR DESCRIPTION
**Pull request by hmhealey**

### CODE REVIEW

**Comment by jwilander** [comment]
+1

**Comment by enahum** [comment]
+1

**Comment by it33** [comment]
@hmhealey this might be one place where having a comment in the code would be helpful, just noting that we are intentionally not trimming because LDAP needs to support spaces in passwords?

**Comment by hmhealey** [comment]
@it33 Good call. I'll add one in in a moment

**Pull request merged**
