### PR TITLE
Improving smoothness of RHS search

### PR DESCRIPTION
**Pull request by asaadmahmoodspin**
Hey guys this is for 0.6.0. Have a look.

### CODE REVIEW

**Comment by jwilander** [comment]
+1

**Comment by rgarmsen2295** [comment]
+1

**Comment by hmhealey** [comment]
Looks good

**Comment by asaadmahmoodspin** [comment]
Since we haven't accepted this yet, I'll submit another commit with just text changes for modal close buttons. Please have a look and merge.

**Pull request merged**
