### PR TITLE
Multiple UI Improvements

### PR DESCRIPTION
**Pull request by asaadmahmoodspin**
Hey guys have a look, changes include:
- Truncating long names in members dropdown and in modals
- Also improving long names in mentions
- Fixing some modals and removing irrelevant styles
- Fixing code language being obscured on IOS.
- Increasing time for post arrows.
- Improving webhooks.

Tickets include:
https://mattermost.atlassian.net/browse/PLT-1904
https://mattermost.atlassian.net/browse/PLT-1907
https://mattermost.atlassian.net/browse/PLT-1906
https://mattermost.atlassian.net/browse/PLT-1683
https://mattermost.atlassian.net/browse/PLT-1916

### CODE REVIEW

**Comment by coreyhulen** [comment]
+1

**Comment by jwilander** [comment]
+1

**Comment by asaadmahmoodspin** [comment]
Hey guys, re review the code. Fixed some css stuff with long usernames and full names in mentions too.

**Comment by jwilander** [comment]
+1

**Pull request merged**
