### PR TITLE
PLT-5077: Fix floating date on mobile view.

### PR DESCRIPTION
**Pull request by grundleborg**
#### Summary
Fix the floating date view on mobile.

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-5077

### CODE REVIEW

**Comment by jasonblais** [comment]
Thanks @grundleborg! Tested both on mobile view (Windows 10, Chrome) and the mobile app (iPhone 5s).

Found a couple of issues:

1 - Floating timestamp doesn't show on the right-hand sidebar comment threads, only in the center pane

Repro: (in mobile view)
1) Post a message
2) Click the "..." of the message and choose "Reply"
3) Post enough comments so that they don't all fit on the screen
4) Scroll up the right-hand sidebar

Observed: No floating timestamp
Expected: Floating timestamp similar to center pane

NOTE: The floating timestamp shouldn't be shown for search results (it should only be shown for comment threads on the right-hand sidebar)

2) Floating timestamp shown after posting a message

Repro: (in mobile view)
1) Scroll to the bottom of the channel
2) Post a message

Observed: Floating timestamp appears
Expected: No floating timestamp

----

Also found an issue unrelated to this PR. Filed here: https://mattermost.atlassian.net/browse/PLT-5280

**Comment by jasonblais** [comment]
By the way, re-reading the JIRA ticket --> I'm not sure if the changes I'm proposing are beyond the scope of the bug ticket. If so, please let me know and we can consider making a separate improvement ticket for at least the first part.

(It would be nice to fix the second item though just because it's a little annoying in my opinion when it shows up each time)

**Comment by grundleborg** [comment]
@jasonblais I think both of those are separate feature tickets, as this bug was just to reinstate the old behaviour that was lost.

I think changing the behaviour for your second point may be quite invasive, so I'd rather keep it separate from this PR.

**Comment by esethna** [comment]
+1, tested, agree with what's been said above

1) I've made an [improvement ticket](https://mattermost.atlassian.net/browse/PLT-5317) to add the floating date indicator to the RHS. Agree that this is out of scope for the bug ticket.

2) I think it's okay to take this without fixing the second point. It seems like high mana for not much gain since on mobile the keyboard pushes the screen up so you don't see the floating date indicator until you close the keyboard.

**Pull request merged**
