### PR TITLE
PLT-4358 Improve performance when loading system console statistics

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
This adds a couple of columns to the `Posts` table that eases the queries in the System Console to show the amount of posts with files and hashtags

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-4358

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [ ] All new/modified APIs include changes to the drivers
- [ ] Has enterprise changes (please link)
- [ ] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/platform/blob/master/i18n/en.json) and [.../webapp/i18n/en.json](https://github.com/mattermost/platform/tree/master/webapp/i18n/en.json)) updates
- [x] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by jwilander** [comment]
What about for existing posts? Won't this break the query so that existing posts don't get counted correctly?

**Comment by enahum** [comment]
good catch, I'll submit a fix for that.

thanks @jwilander

**Comment by enahum** [comment]
@jwilander take a look, now it should include existing posts

**Comment by coreyhulen** [comment]
Lets chart about this....not sure I like adding a extra columns to make a system console query faster.  We can/should just cache the result after first load.

**Comment by jwilander** [comment]
Closing, please submit against master once the performance branch is merged in

**Pull request closed without merging**
