### PR TITLE
PLT-1244 Changed serverside mention parsing to support usernames containing periods

### PR DESCRIPTION
**Pull request by hmhealey**
Instead of breaking up the string into words based on certain non-alphanumeric characters (spaces, periods, slashes, etc), we break it up into words based on whitespace and then if that doesn't match a mention, it further breaks it up like it previously did and checks again.

I'm really thinking we'll want something more robust in the future, but that's a lot larger task.

### CODE REVIEW

**Comment by crspeller** [comment]
@hmhealey Has this been thoroughly tested? Nervous about adding this right at the end bcause of our history of breaking stuff like this. Plus it is more of a feature than a bug.

**Comment by hmhealey** [comment]
I did some manual tests, but we don't actually have any unit tests for this. It'll need some refactoring to add tests since this function is large and depends on the database state.

**Comment by hmhealey** [comment]
I added a ticket for adding unit tests to this, but I agree that this should be pushed back. I'll add these later this week once the release has branched and once I'm done my remaining stuff for this sprint. https://mattermost.atlassian.net/browse/PLT-1441

**Comment by crspeller** [comment]
+1

**Comment by coreyhulen** [comment]
+1

**Pull request merged**
