### PR TITLE
MM-1870 Creating local version of fonts retrieved from Google

### PR DESCRIPTION
**Pull request by crspeller**

### CODE REVIEW

**Comment by rgarmsen2295** [comment]
+1, looks good (like that we're moving this kind of stuff in house)

**Comment by coreyhulen** [comment]
+1

**Comment by felixbuenemann** [comment]
@crspeller You should realize that Google Fonts does user agent sniffing to provide just the right font definitions for your user agent. This means that the files you saved are only compatible with user agents that support both [WOFF2](http://caniuse.com/woff2) and [unicode-range subsetting](caniuse.com/font-unicode-range) for font-face.

TLDR: You broke Webfonts for everything but recent Chrome, FF, Opera Webkit.

**Comment by crspeller** [comment]
@felixbuenemann Thanks for pointing this out. I have submitted #512 to fix this.

**Pull request merged**
