### PR TITLE
MM-1841 Corrected help text

### PR DESCRIPTION
**Pull request by lfbrock**
Propose for 0.7.0

### CODE REVIEW

**Comment by jwilander** [comment]
Looks good, will merge after we branch for 0.6.0

**Comment by crspeller** [comment]
Why is this waiting for 0.7.0?

**Comment by jwilander** [comment]
I'm 0/5 either way, just went with what was proposed

**Comment by crspeller** [comment]
I think this one line not code change is safe enough for 0.6.0. :)

**Pull request merged**
