### PR TITLE
Update to CLI error text when EE license is missing

### PR DESCRIPTION
**Pull request by jasonblais**

### CODE REVIEW

**Comment by coreyhulen** [comment]
@jasonblais did you maybe submit from an old branch?  guessing that's why the build failed.

**Comment by coreyhulen** [comment]
wait looks like master might be messed up from a merge.

**Comment by coreyhulen** [comment]
@jasonblais I think you might need to rebase to fix the build.

**Comment by jasonblais** [comment]
Resubmitted: https://github.com/mattermost/platform/pull/7248

**Pull request closed without merging**
