### PR TITLE
Moving tests to javascript client

### PR DESCRIPTION
**Pull request by crspeller**

### CODE REVIEW

**Comment by enahum** [comment]
what about the test script in `package.json`?

**Comment by crspeller** [comment]
What about it?

**Comment by enahum** [comment]
did I understand this the wrong way? you're removing test from the client side or just for the driver?

if its just for the driver shouldn't you remove the script for tests in package.json too?

If I understood it wrong then dismiss my comment

**Comment by crspeller** [comment]
Not all the tests are leaving. There are some that are testing react code which stay. The ones testing the client are leaving.

**Comment by enahum** [comment]
+1

**Comment by jwilander** [comment]
+1

**Pull request merged**
