### PR TITLE
PLT-2765 Limit username UI to 22 characters

### PR DESCRIPTION
**Pull request by DavidLu1997**
Limited usernames to 22 characters, existing usernames will not be affected. Any new usernames must be between 3 and 22 characters. 

Updated help text upon username creation and change.

@asaadmahmoodspin please review :)

### CODE REVIEW

**Comment by coreyhulen** [comment]
You need to modify the messages in en.json and remove the localized versions.

**Comment by DavidLu1997** [comment]
Updated en.json

**Comment by coreyhulen** [comment]
you need to delete user.settings.general.usernameInfo and user.settings.general.usernameRestrictions from all the non-english files so the localizer know to update the text.

**Comment by DavidLu1997** [comment]
I think I got all of them :)

**Comment by coreyhulen** [comment]
looks like you have a build break 

```
> mattermost@0.0.1 check /var/lib/jenkins/jobs/mattermost-platform-pr/workspace/src/github.com/mattermost/platform/webapp
> eslint --ext ".jsx" --ignore-pattern node_modules --quiet .


/var/lib/jenkins/jobs/mattermost-platform-pr/workspace/src/github.com/mattermost/platform/webapp/components/user_settings/user_settings_general.jsx
  111:156  error  Parsing error: Unexpected token

✖ 1 problem (1 error, 0 warnings)


```

**Comment by DavidLu1997** [comment]
Now compiles!

**Comment by enahum** [comment]
+1

**Pull request merged**
