### PR TITLE
SAML Unit Tests, Go Driver & Removed vendor dependency

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
Unit tests for SAML and added management of certificate files in the go driver

Also removed dependancy for `github.com/kardianos/osext` as it is no longer needed

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields.]
- [x] Added or updated unit tests (required for all new features)
- [x] Added API documentation (required for all new APIs)
- [x] Has enterprise changes (https://github.com/mattermost/enterprise/pull/43)

### CODE REVIEW

**Comment by enahum** [comment]
I guess tests are going to pass once the PR for EE is merged

**Comment by coreyhulen** [comment]
+1

**Comment by jwilander** [comment]
+1

**Comment by jwilander** [comment]
Waiting on enterprise PR to go in so we can rerun the build before we merge this

**Pull request merged**
