### PR TITLE
PLT-6262 Add config setting to disable file attachments

### PR DESCRIPTION
**Pull request by jwilander**
#### Summary
Add config setting to disable file attachments. Also use Redux to tell when to reload the page from a version change.

Note for PMs:
I'm just using the existing error displaying code for the file upload box to display the "File attachments disabled." message. I didn't change the placement/clearing behaviour at all so it will behave like other file errors (clear on message send, channel switch, etc.)

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-6262

#### Checklist
- [x] Has UI changes
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/platform/blob/master/i18n/en.json) and [.../webapp/i18n/en.json](https://github.com/mattermost/platform/tree/master/webapp/i18n/en.json)) updates

### CODE REVIEW

**Comment by jasonblais** [comment]
Tested on Windows 10/Chrome. Also tested on iOS Safari browser (only the file upload icon)

- when enabled
   - drag-and-drop works; CTRL+U works; file attachment icon works; pasting an image works
   - max file size setting is honoured
   - updating your profile picture works
- when disabled
   - drag-and-drop UI disabled
   - pasting an image, CTRL+U and dragging a file to a channel gives correct error message
   - attachment icon removed
   - updating your profile picture still works

I haven't tested whether file uploads are disabled via the APIs. @jwilander not sure if you tested this locally?

Some notes:

1 - If you have already uploaded a file in your message draft, then disable file uploads, you can still post the message with file attachments.

There could be an instance where a user posts a message with files well after uploads were disabled. It's a small edge case though so I wouldn't worry about it too much, but something I wanted to bring up as an observation.

2 - In mobile and tablet views, can we extend the message box to the left, aligned vertically with the error message?

image

There is extra whitespace that's "empty" when the file upload icon isn't there.

**Comment by jwilander** [comment]
I did test it locally and I also just pushed unit tests covering it.

1 - I don't think that's a big deal since the files will already be uploaded at that point
2- That's CSS related so we should ask @asaadmahmood to look at that if we want it fixed

**Comment by jasonblais** [comment]
2 - Sounds good, I'll ask Asaad to take a look.

**Comment by jasonblais** [comment]
Asaad submitted a PR for UI, which Joram helped merge into this branch.

Queuing for dev review next

**Pull request merged**
