### PR TITLE
Update Push and Email Notifications Text

### PR DESCRIPTION
**Pull request by esethna**
#### Summary

- Add subtitles into the push notification section in Account Settings
- Clarify batched email help text

#### Checklist

- [x] Has UI changes
- [x] Includes text changes and localization files updated

### CODE REVIEW

**Comment by jwilander** [comment]
+1

**Comment by enahum** [comment]
@esethna building is failing cause of eslint errors

```
> eslint --ext ".jsx" --ignore-pattern node_modules --quiet .


/var/lib/jenkins/jobs/mattermost-platform-pr/workspace/src/github.com/mattermost/platform/webapp/components/user_settings/user_settings_notifications.jsx
  365:30  error  Trailing spaces not allowed  no-trailing-spaces

✖ 1 problem (1 error, 0 warnings)
```

**Comment by esethna** [comment]
Thanks fixed!

**Comment by enahum** [comment]
+1

**Pull request merged**
