### PR TITLE
PLT-1879 Add config setting to accept unsigned TLS certs for SSO and outgoing hooks, also fix delete…

### PR DESCRIPTION
**Pull request by jwilander**
… hooks bug

### CODE REVIEW

**Comment by hmhealey** [comment]
+1

**Comment by crspeller** [comment]
@jwilander Should this not be a configuration setting?

**Comment by coreyhulen** [comment]
I think we should also do the same for https://github.com/mattermost/platform/blob/master/api/command.go#L175

**Comment by jwilander** [comment]
Ready for re-review

**Comment by coreyhulen** [comment]
+1

**Comment by crspeller** [comment]
+1

**Pull request merged**
