### PR TITLE
PLT-4716 fixes cache invalidation issue

### PR DESCRIPTION
**Pull request by coreyhulen**
#### Summary
Fixes a cache invalidation issue.  Should fix several bugs.

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-4716
https://mattermost.atlassian.net/browse/PLT-4708
https://mattermost.atlassian.net/browse/PLT-4715

### CODE REVIEW

**Comment by enahum** [comment]
+1

**Comment by coreyhulen** [comment]
Actually I don't think it's called for preferences.

**Comment by enahum** [comment]
It should, also you have build errors

**Comment by jwilander** [comment]
+1

**Pull request merged**
