### PR TITLE
PLT-3838 Remove close button shadow in modals

### PR DESCRIPTION
**Pull request by phrix32**
#### Summary
Removed the close icons (text) shadow in modals.

#### Ticket Link
[Jira ticket](https://mattermost.atlassian.net/browse/PLT-3838)

#### Checklist
- [x] Has UI changes

### CODE REVIEW

**Comment by jwilander** [comment]
@asaadmahmood can you take a look?

**Comment by asaadmahmood** [comment]
@phrix32 can we add `font-size: 23px;` to the span rule on line `177` in `_modal.scss`. Since it doesn't have a border, would be better if make it slightly bigger.

**Comment by hannapark84** [comment]
Thanks @phrix32 for the pull request!

Per the CONTRIBUTING.md file displayed when you created this pull request, we need to add you to the list of approved contributors for the Mattermost project.

Please help complete the Mattermost contribution license agreement?

This is a standard procedure for many open source projects. Your form should be processed within 24 hours and reviewers for your pull request will be able to proceed.

Please let us know if you have any questions.

We are very happy to have you join our growing community!

**Comment by phrix32** [comment]
done :)

**Comment by hannapark84** [comment]
Thanks, much appreciated!

**Pull request merged**
