### PR TITLE
[PLT-7141] Fix deactivated user from appearing in channel view members list filtering

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
Fix deactivated user from appearing in channel view members list filtering

#### Ticket Link
Jira ticket: [PLT-7141](https://mattermost.atlassian.net/browse/PLT-7141)

#### Checklist
- [x] Has UI changes

### CODE REVIEW

**Comment by jwilander** [comment]
Does this need to be done for the team members list as well?

**Comment by jasonblais** [comment]
@saturninoabril I don't think the ticket got updated, but basically we should confirm the deactivated users are not in 
 - channel lists
 - team lists
 - direct message channel lists

**Comment by jwilander** [comment]
Throwing to PM review to make sure all the lists are handled

**Comment by jasonblais** [comment]
@saturninoabril 

1) Members appear in "Add Members to Channel" list after searching for them

image

2) And in DM list after searching for them

image

3) And in "Add Members to Team" list, even without searching for them

image

**Pull request merged**
