### PR TITLE
PLT-2640 Added searching users by additional field when autocompleting @mentions

### PR DESCRIPTION
**Pull request by hmhealey**

### CODE REVIEW

**Comment by coreyhulen** [comment]
+1

**Comment by jwilander** [comment]
+1

**Comment by it33** [comment]
Propose instead of auto-complete showing 
- `@username FIRST_NAME LAST_NAME`

If there is a nickname, include it as well: 
- `@username FIRST_NAME LAST_NAME - NICK_NAME` 

Otherwise this looks confusing ("Spanky" is nickname): 

image

P2 is to highlight the characters matching the search term. 

Propose we consider having the PM testing and signing off on this also draft the updated help doc, either as a PR that goes in with this feature or just in the thread here so we review everything in one place, rather than waiting a few weeks and forgetting all the detail, and then drafting docs that capture only a portion of the detail.

**Comment by lfbrock** [comment]
Tested this out on Chrome, and found no issues with identical names, substrings, or substrings with `.` and `-`. Agree that we need to show nickname in the autocomplete list. 

@it33 documentation draft is here, please add feedback on the pull request. https://github.com/mattermost/docs/pull/257

**Pull request merged**
