### PR TITLE
PLT-2054 Add DisplayName and Description fields for integrations

### PR DESCRIPTION
**Pull request by hmhealey**

### CODE REVIEW

**Comment by jwilander** [comment]
If a user tries to upload a display name or description that's too long it looks like they will just get "Invalid display name" or "Invalid description" as an error. Maybe add some client-side error checking or just limit the input fields to certain lengths?

**Comment by hmhealey** [comment]
Ah good call. I'll limit the length of the fields

**Comment by jwilander** [comment]
+1

**Comment by coreyhulen** [comment]
+1

**Pull request merged**
