### PR TITLE
Update Amazon-Elastic-Beanstalk.md

### PR DESCRIPTION
**Pull request by pawelad**
Updated `Dockerrun.aws.zip` link to newer, existing version.

### CODE REVIEW

**Comment by jwilander** [comment]
Thanks @pawelad for the pull request! 

Per the [**CONTRIBUTING.md**](https://github.com/mattermost/platform/blob/master/CONTRIBUTING.md#submitting-a-pull-request) file displayed when you created this pull request, we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**

This is a standard procedure for many open source projects. Your form should be processed within 24 hours and reviewers for your pull request will be able to proceed. 

Please let us know if you have any questions. 

We are very happy to have you join our growing community!

**Comment by pawelad** [comment]
Per linked Django's CLE FAQ: `Every contributor of non-trivial amounts of code (more than just a line or two)...` - I think this change counts as a trivial one, and it would be greatly appreciated if I didn't had to 'register'.

**Comment by it33** [comment]
Hi @pawelad, 

When a CLA is completed, no information is shared publicly. All that happens publicly is your GitHub ID is included in the list of approved contributors, which alerts the core team that your pull request can be reviewed (i.e. in our process, reviews happen after CLAs are completed--this is needed as we'll be automating the CLA request process in future), 

Optionally, you can include an address if you'd like to receive a [limited edition Mattermost Mug customized with your GitHub ID and the date of your contribution.](https://forum.mattermost.org/t/limited-edition-mattermost-mugs/143), but address isn't a required field. 

Per the [Contribution Guide](https://github.com/mattermost/platform/blob/master/CONTRIBUTING.md#submitting-a-pull-request), completing the CLA is the first step to submitting a pull request for the Mattermost project. We've had dozens of contributors follow the process and we would love to welcome you to the community if you choose to join, 

If not, we completely respect your choice.  

However you decide, we highly appreciate your effort to improve the product for the community,

**Comment by pawelad** [comment]
Form submitted

**Comment by it33** [comment]
Thanks!

**Pull request merged**
