### PR TITLE
PLT-577 Upgrading dependencies. 

### PR DESCRIPTION
**Pull request by crspeller**
- Upgraded jquery from 1.11.1 to 2.1.4
- Upgraded perfect scrollbar from 0.6.5 to 0.6.7
- Upgraded react 0.13.3 to 0.14
- Upgraded react-bootstrap 0.25.1 to 0.27.1

- Some warnings will appear after this change. Will be fixed in an upcoming PR.

### CODE REVIEW

**Comment by coreyhulen** [comment]
+1

**Comment by coreyhulen** [comment]
@crspeller needs rebase

**Comment by jwilander** [comment]
+1

**Comment by crspeller** [comment]
@coreyhulen Rebased.

**Pull request merged**
