### PR TITLE
Reply button not clickable on first collapsed post from same user in a comment

### PR DESCRIPTION
**Pull request by florianorben**
As reported in the #bugs channel by corey

> I cannot click the  ... reply button when 2 comments from the same user have been collapsed.  There is a slight gap between comments and when you hover up slowly you exit the current comment div causing the reply button to disappear before you can click it.

### CODE REVIEW

**Comment by coreyhulen** [comment]
FYI for @asaadmahmoodspin

**Comment by coreyhulen** [comment]
+1

**Comment by florianorben** [comment]
@asaadmahmoodspin this is probably not really a good example of what was just talked about in the dev-meeting :p, but I guess the scss code will have a refactoring anyway :)

**Comment by asaadmahmoodspin** [comment]
We can get this in if we want, but I've modified a lot of stuff regarding the posts and the center channel in this PR (https://github.com/mattermost/platform/pull/1462) and it will fix this too, also this might also cause conflicts with that PR.

**Comment by crspeller** [comment]
@florianorben As assad said his pr did cause conflicts with this one. Rebase and see if we still require this fix.

**Comment by asaadmahmoodspin** [comment]
This is fixed in my PR, and it will be pushed to master at 12:00AM UTC.

**Comment by florianorben** [comment]
@crspeller , @asaadmahmoodspin  I think we don't need this PR anymore then :)?
(I probably wont be around to close, so feel free to do whatever you like with this :D )

**Pull request closed without merging**
