### PR TITLE
Little mistake in the Readme.

### PR DESCRIPTION
**Pull request by driou**
Just fixing a small mistake reading the Readme. Thanks for your job team.
Hoping soon using Mattermost in my firm.
Adrien

### CODE REVIEW

**Comment by coreyhulen** [comment]
Thanks @driou for the pull request! 

Before we can review, we need to add you to the list of approved contributors for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**

This is a standard procedure for many open source projects. You can view a list of past contributors who have completed the form [here](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true). 

After completing the form, it should be processed within 24 hours and reviewers for your pull request will be able to proceed. 

Please let us know if you have any questions. 

We are very happy to have you join our growing community!

**Comment by jwilander** [comment]
Hey @driou ,

Just a reminder to please fill out the CLA @coreyhulen has linked above. Once that's done we can get your pull request reviewed and merged.

Thanks!

**Comment by crspeller** [comment]
@driou Thanks for completing the CLA.

**Comment by crspeller** [comment]
+1

**Pull request merged**
