### PR TITLE
translations PR 20170612

### PR DESCRIPTION
**Pull request by enahum**
Ideally this PR should be review by community members for each language.

Note: In the event that you see an english translation instead of the desired language is because this PR was submitted before the translation was made on the Mattermost Translation Server and probably will be submitted for the next PR.

### CODE REVIEW

**Comment by wget** [comment]
`fr` lgtm

**Comment by chikei** [comment]
`zh_TW` lgtm

**Comment by ArchRoller** [comment]
`ru` lgtm

**Comment by jwilander** [comment]
@enahum we've got a conflict

**Comment by enahum** [comment]
c'mon really!!!!

**Comment by enahum** [comment]
@jwilander done.

**Pull request merged**
