### PR TITLE
MM-1866 - Adding download icon and adding download links

### PR DESCRIPTION
**Pull request by asaadmahmoodspin**
Hey guys have a look.
Adding download icon and adding download link for both file title and download icon.

### CODE REVIEW

**Comment by jwilander** [comment]
+1

**Comment by asaadmahmoodspin** [comment]
Hey guys, I've also added another small ticket to this PR, which involves the settings UI improvements.

**Comment by jwilander** [comment]
Still +1

**Comment by crspeller** [comment]
+1

**Pull request merged**
