### PR TITLE
translations PR 20161212

### PR DESCRIPTION
**Pull request by enahum**
Ideally this PR should be review by community members for each language.

Note: In the event that you see an english translation instead of the desired language is because this PR was submitted before the translation was made on the Mattermost Translation Server and probably will be submitted for the next PR.

### CODE REVIEW

**Comment by cpanato** [comment]
missing translations for PT-BR i will take a look on the translate server.

**Comment by wget** [comment]
Since there are no changes for French. This is OK for fr.

**Comment by meilon** [comment]
We still have to translate some more, but what is in the PR LGTM

**Comment by rodrigocorsi2** [comment]
pt-BR LGTM 👍

**Comment by ArchRoller** [comment]
`ru` ok.

**Pull request merged**
