### PR TITLE
PLT-4516 Mobile: Sometimes when posts list reloads, it is completely empty until it is scrolled

### PR DESCRIPTION
**Pull request by dmeza**
#### Summary
Mobile: On IOs native application when posts list reloads and has a lot of posts, it is completely empty (white screen) until the screen is touched. Also this happens when you select a channel, from the left menu, that has a good amount of posts.

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-4516
https://mattermost.atlassian.net/browse/PLT-3017
https://github.com/mattermost/platform/pull/3586

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [ ] All new/modified APIs include changes to the drivers
- [ ] Has enterprise changes (please link)
- [ ] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/platform/blob/master/i18n/en.json) and [.../webapp/i18n/en.json](https://github.com/mattermost/platform/tree/master/webapp/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by jasonblais** [comment]
Thanks @dmeza! 

I tested the PR and there are a few instances where the scrolling behaviour is off.

1) When closing and opening right hand sidebar (e.g. by replying to a message), the center channel scrolling jumps up and down and shifts to a different place on the center channel
2) When switching to a new channel, it seems as though the center channel "scrolls" to the bottom of the page, instead of just going there from the start. The same happens on mobile.

**Comment by dmeza** [comment]
Thank you for the tests @jasonblais. Does the current master behave the same way? I was testing and could not see a difference between this test build and master, except for the white screens.

**Comment by jasonblais** [comment]
@dmeza 
1) Opening/closing right hand side

Here are two videos -- both on Windows 10, Chrome.

`master`: https://www.dropbox.com/s/o1s45cr5y64gpgy/repro-master.avi?dl=0
*When opening/closing right hand sidebar, the center channel doesn't scroll*

`test server`: https://www.dropbox.com/s/asut8olktmtqjwl/repro-testserver.avi?dl=0
*When opening/closing right hand sidebar, the center channel scrolls up and down*

Apologies on the video quality in advance, my video recording software is outdated..

2) Channel switching:

On `master`, the center channel "jumps" to the bottom of the page, on the test server it scrolls to the bottom of the page when switching channels.

**Comment by jasonblais** [comment]
The code that touches scrolling is tricky and we've had problems with it before. We can reconsider a PR that fixes the issues outlined above.

Closing for now

**Pull request closed without merging**
