### PR TITLE
New Languages and Translations

### PR DESCRIPTION
**Pull request by enahum**

### CODE REVIEW

**Comment by coreyhulen** [comment]
+1

**Comment by jasonblais** [comment]
seems to be conflicts, but +1 otherwise. Will test translations themselves once they've been merged

I have added an improvement ticket to reorder the languages in the Account Setting page, but I'm fine shipping it as-is for v3.3: https://mattermost.atlassian.net/browse/PLT-3793

**Comment by enahum** [comment]
conflict fixed

**Comment by crspeller** [comment]
+1

**Pull request merged**
