### PR TITLE
Fix missing and bad localization strings

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
Fixed missing and bad ids for localization strings

#### Ticket Link
https://pre-release.mattermost.com/core/pl/cjkj8w67ufft3xdoburwpzbttw
https://github.com/mattermost/platform/issues/3754

#### Checklist
- [ ] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [ ] All new/modified APIs include changes to the drivers
- [ ] Has enterprise changes (please link)
- [ ] Has UI changes
- [x] Includes text changes and localization files updated
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by jasonblais** [comment]
Please do not merge this, hasn't been approved in triage yet.

Will be decided on Monday

**Comment by jwilander** [comment]
just-in-case +1

**Comment by coreyhulen** [comment]
+1

**Comment by jasonblais** [comment]
Approved for RC2

**Pull request merged**
