### PR TITLE
PLT-6486 Add an `@username` button to the profile popover, that puts the username in the post when clicked

### PR DESCRIPTION
**Pull request by dmeza**
#### Summary
Click the @username mention on the profile popover title. A mention for `@username` should be added to your post draft:
plt-6486_add usernamebuttontoprofilepopover

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-6485

#### Checklist
- [ ] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [ ] All new/modified APIs include changes to the drivers
- [ ] Has enterprise changes (please link)
- [x] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/platform/blob/master/i18n/en.json) and [.../webapp/i18n/en.json](https://github.com/mattermost/platform/tree/master/webapp/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by jasonblais** [comment]
Thanks for the contribution! 

Our review process is a little delayed given the upcoming release. We'll have PM review completed by the end of this week.

**Comment by jasonblais** [comment]
Thanks @dmeza! Overall this looks good. I smoke tested the overall functionality of the profile popover and didn't find issues on that.

Just a couple of notes:

1 - When you click the username on the comment thread (on right-hand sidebar), and click their username in the profile popover, I would expect it to add the username to the comment box, rather than to the message box in center pane

image

2 - When you click the username in search results, it's not obvious to me what it should do.

Right now it adds the username in center pane message box, which might make sense, unless you have the right-hand sidebar expanded as shown below. In the attached case, I wouldn't expect it to do anything.

image

This would apply for other searches, such as recent mentions, flagged posts and pinned posts.

----

I also found a bug that reproduces on `master`. Created a separate ticket for it: https://mattermost.atlassian.net/browse/PLT-6580

**Comment by jasonblais** [comment]
@dmeza let me know if you have any questions about my note above?

Would love to accept this for Mattermost 3.10, there's still a few more days before code complete.

**Comment by jwilander** [comment]
@dmeza needs a rebase and @jasonblais has some feedback

**Comment by jasonblais** [comment]
@dmeza Did you have any questions about above?

**Comment by dmeza** [comment]
@jasonblais @jwilander fixed the problems you described. Now the mention fills in the center or RHS based on where the popover is displayed. It won't do anything for any of the elements that do not have a textarea, like search or mentions. Here is an example:
plt-6486 add an username to rhs

**Comment by jasonblais** [comment]
Thanks @dmeza!

Just two notes, otherwise this looks good to me

1) Each time when I click the username on the profile popover, I get a warning in the JavaScript console.

Anything to be worried about?

image

2) Clicking on the username after opening the profile popover in search results throws an error

 - post "hey"
 - search for "hey"
 - in the search results, click on one of the profile pictures to open the popover
 - observed: username is clickable; clicking it throws a JavaScript error

image

 - expected: username is not clickable (so it's more obvious it won't add a username to the message box); clicking it doesn't throw an error

**Comment by dmeza** [comment]
@jasonblais fixed a couple of js errors that were happening in different cases. Also, changed for user name to not be clickable on all search RHS items @mentions, flags, pinned items. It does work on replies. Let me know if you need other changes.

**Comment by jasonblais** [comment]
@jwilander Requesting re-review for latest code changes

**Pull request merged**
