### PR TITLE
PLT-4507 Don't mount modals until opened to make resetting state automatic

### PR DESCRIPTION
**Pull request by jwilander**
#### Summary

Fixes state not resetting for the user list modals.
#### Ticket Link

https://mattermost.atlassian.net/browse/PLT-4507

### CODE REVIEW

**Comment by digitaltoad** [comment]
Nice. This fixes #4304 and possibly #4344.

**Comment by digitaltoad** [comment]
Just a quick note that this does break any outbound animation for the modal because it simply doesn't exist after closed.

**Comment by jwilander** [comment]
@digitaltoad, that's a good point. I think if I switch the onModalDismissed handler over to be fired `onExited` then it should work and maintain the outbound animations. I might need to add a bit of state handling into the modal for that but it should be minimal

**Comment by digitaltoad** [comment]
@jwilander That should still work and should also fix any focusing issues as well.

**Comment by jwilander** [comment]
Alright, that should do it. Ready for review

**Comment by jwilander** [comment]
The fading out animation works with the way I've done it, that's what @digitaltoad and I were talking about above. I much prefer to not mount them unless they're needed since we have lots of them and most of them have a bunch of listener code that is getting fired needlessly.

I agree with moving this functionality to another component that all modals can be built off, `MattermostModal` or something of that nature, but I think that should work like I've made these modals work. I only didn't do that here due to time constraints.

**Comment by jwilander** [comment]
I chatted with @hmhealey last night after his comment and he agreed with me that this was a good way to do it.

I don't think this breaks React conventions at all, and I'm pretty sure the React-Bootstrap modals are doing something very similar underneath.

**Comment by jwilander** [comment]
I'll queue an item for the dev meeting for us to discuss

**Comment by coreyhulen** [comment]
Needs to be rebased.

**Pull request merged**
