### PR TITLE
[#1947] Fix different mysql user and password

### PR DESCRIPTION
**Pull request by Pimo**
I've seen that there are all the ENV needed so I decided to make it more customizable.

### CODE REVIEW

**Comment by jwilander** [comment]
@crspeller please take a look

**Comment by crspeller** [comment]
@Pimo Can you help me understand why customizing the username and password of the sql server inside the docker container is desirable? It seems to me that there would be no need to change the password as the server is only accessible within the docker container.

**Comment by Pimo** [comment]
Yes, at the moment it is only accessible inside the docker container.
In some other applications, that usually use the MySql standard image (https://hub.docker.com/_/mysql/), you can modify MYSQL_DATABASE, MYSQL_USER, MYSQL_PASSWORD and other parameters by default.
For example for administration reasons, if there isn't a standard password and if you need, you can make it accessible.

**Comment by crspeller** [comment]
@Pimo The current docker container is only meant for preview. I don't see a use case where you would want access to the internal SQL server. So I don't think this is worth supporting.

**Pull request closed without merging**
