### PR TITLE
PLT-911 Search autocomplete improvements

### PR DESCRIPTION
**Pull request by hmhealey**
1) Keeps the selected menu item visible when scrolling with the arrow keys c1ae28c
2) Fixed the search autocomplete click handler 52e7501
3) Separated public and private channels into seperate sections 578eb252

### CODE REVIEW

**Comment by jwilander** [comment]
Got some ESLint failures @hmhealey

**Comment by hmhealey** [comment]
I could've sworn I had ran it myself beforehand, but I guess not. It should be fixed now.

**Comment by coreyhulen** [comment]
+1

**Comment by jwilander** [comment]
+1

**Pull request merged**
