### PR TITLE
translations PR 20170501

### PR DESCRIPTION
**Pull request by enahum**
Ideally this PR should be review by community members for each language.

Note: In the event that you see an english translation instead of the desired language is because this PR was submitted before the translation was made on the Mattermost Translation Server and probably will be submitted for the next PR.

### CODE REVIEW

**Comment by wget** [comment]
No changes for `fr`. It is OK.

**Comment by cpanato** [comment]
`PT-BR` lgtm

**Comment by enahum** [comment]
@jasonblais can you test that polish is working fine please?

**Comment by jasonblais** [comment]
Looks like it's working fine

image

image

**Comment by kaakaa** [comment]
`ja` LGTM!

**Pull request merged**
