### PR TITLE
PLT-1316/PLT-3280 Change client-side max file size limit

### PR DESCRIPTION
**Pull request by tbalthazar**
It now relies on the value set in config.json.
Also:
- Re-enable the max file size setting in system console. (It was removed by [this pull request](https://github.com/mattermost/platform/pull/3324/files))
- Tweak the max file size setting in system console according the specs in [this ticket](https://mattermost.atlassian.net/browse/PLT-1316)

### CODE REVIEW

**Comment by tbalthazar** [comment]
For the record, this pull request should close 2 tickets if merged:
https://mattermost.atlassian.net/browse/PLT-3280
https://mattermost.atlassian.net/browse/PLT-1316

**Comment by esethna** [comment]
Hey @tbalthazar, thanks for the submission! Tested on the spinmint server, looks good! Would you mind making a small tweak to the error message?

`File above XXMB could not be uploaded:` > `Files above XXMB cannot be uploaded:`

**Comment by tbalthazar** [comment]
@esethna Done! :)

**Comment by jwilander** [comment]
+1

**Comment by it33** [comment]
Just an update, we tested this feature with a max file size of 500MB and tried uploading multiple video files and were able to crash the server. 

We're a little worried about this feature and are trying to figure out how to offer this without risking a few people having very bad, unexpected outcomes. 

Maybe it's just adding really loud help text and warnings, we're trying to figure this out.

**Comment by esethna** [comment]
I chatted with our lead dev and it would be difficult to set a hard limit since the limit would still be dependent on your server hardware. Sounds like the team is okay to take this with the caution note in the help text and we will also put a warning in our docs.

**Comment by enahum** [comment]
@esethna is this PR ready to merge?

**Comment by esethna** [comment]
@enahum yes

**Comment by enahum** [comment]
+1

**Pull request merged**
