### PR TITLE
#7005 - Selecting channels using tab

### PR DESCRIPTION
**Pull request by augustnmonteiro**
#### Summary
Improving UX of suggestion box, adding tab to select channels

#### Ticket Link
#7005

### CODE REVIEW

**Comment by jasonblais** [comment]
Thanks @augustnmonteiro! Have queued for UX approval

**Comment by jasonblais** [comment]
@augustnmonteiro After thinking about it more and discussing with other team members, I don't think we'll be able to accept this pull request.

Currently, TAB selects an entry in other autocomplete lists, including
 - ~ -channel linking
 - @ -user mentions
 - : -emoji

Hence, we should follow a similar design for the channel switcher modal.

We would be open to accepting a contribution where TAB selects the channel similar to ENTER in the channel switcher modal.

Let me know what you think, open for feedback. 

Very much appreciate your time and effort in contributing back to the Mattermost codebase.

**Comment by augustnmonteiro** [comment]
@jasonblais there is any way to keep both? because tab it's more typing friendly that arrows and that are a behavior that almost all the other chats have so some people like me (hahaha) are used to that :)

**Comment by jasonblais** [comment]
Thank you @augustnmonteiro, really appreciate your feedback. Thank you for sharing it.

I do see where you're coming from, and some systems have this behaviour, agree.

At the same time, the worry is that the behaviour will be significantly different from the other autocompletes. In particular, I worry that
 - someone using channel switcher and notices that TAB scrolls through results, will expect the same in other autocompletes such as emoji.
 - someone using the emoji autocomplete and notices that TAB selects the result, will expect the same in channel switcher.

The end result could be a confusing experience where a new user isn't certain what TAB is supposed to do in such instances (does it scroll, or choose an entry).

Wondering as a next step if you would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered as an improvement? It would be helpful to get other opinions from the community before making a decision.

If you do open a feature proposal, please include a link back to this GitHub Issue.

PS: You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by jasonblais** [comment]
I'll close this for now.

If you'd like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered as an improvement, please include a link back to this GitHub Issue.

**Pull request closed without merging**
