### PR TITLE
fix misaligned checkbox; remove list-style from list-elements with checkboxes

### PR DESCRIPTION
**Pull request by florianorben**
UX Issue 1 / 2015-12-04
ux-1

### CODE REVIEW

**Comment by coreyhulen** [comment]
Looks like the build is reporting

```
cd web/sass-files && compass compile -e production --force
    error sass/styles.scss (Line 645 of sass/partials/_post.scss: Invalid US-ASCII character "\xE2")
Sass::SyntaxError on line ["645"] of /go/src/github.com/mattermost/platform/web/sass-files/sass/partials/_post.scss: Invalid US-ASCII character "\xE2"
Run with --trace to see the full backtrace
make: *** [build-client] Error 1
make: *** [build-container] Error 2
```

**Comment by florianorben** [comment]
Hmm it didn't do that on my machine, grml.
Should hopefully be fixed with the next commit(s) ;)

**Comment by coreyhulen** [comment]
@asaadmahmoodspin please take a look.

**Comment by florianorben** [comment]
@coreyhulen / @asaadmahmoodspin The PR now also adds a `@charset UTF-8` to all scss files, this should prevent future problems with utf-8 characters.
--> Build error fixed now

**Comment by coreyhulen** [comment]
+1

**Comment by asaadmahmoodspin** [comment]
+1 Even though I think we can just add @charset "UTF-8" in just the styles.scss file since all scss partials are compiled into one file.

**Comment by jwilander** [comment]
@florianorben can you try only including the `@charset` in style.scss?

**Comment by asaadmahmoodspin** [comment]
Had a chat with Florian regarding my concern, looks like the main file compiles with only one charset so we're cool.

**Comment by jwilander** [comment]
+1

**Pull request merged**
