### PR TITLE
Update emoji set (fix #1778)

### LINKED ISSUE #1778: Emojione set not up to date
https://github.com/Ranks/emojione/commit/6fb30b7ca3c80bba70dab5b206df59b088720aca

### PR DESCRIPTION
**Pull request by Ticki**

### CODE REVIEW

**Comment by it33** [comment]
Thanks @Ticki for the pull request! 

Per the [**CONTRIBUTING.md**](https://github.com/mattermost/platform/blob/master/CONTRIBUTING.md#submitting-a-pull-request) file displayed when you created this pull request, we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**

This is a standard procedure for many open source projects. Your form should be processed within 24 hours and reviewers for your pull request will be able to proceed. 

Please let us know if you have any questions. 

We are very happy to have you join our growing community!

**Comment by Ticki** [comment]
Sorry, but I don't want to give my real name.

**Comment by it33** [comment]
Hi @Ticki, 

Definitely understand not wanting to share your real name publicly. There are members of the core team who feel the same, and who also don't publicly share (before Mattermost, a number of us built [indie MMOs](http://marsfrontier.wikia.com/wiki/Mars_Frontier_Wiki) together, and privacy from our player base was important for some team members).  

When you complete the CLA form, [only your GitHub ID is shared publicly](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true). Your real name is only stored in the form and remains private. 

The only other place it might be used is if you fill out the mailing address so we can send you a [limited edition mug](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) with your GitHub ID and date of first contribution, then we'll use your real name for shipping. Otherwise it does nothing. 

Similar to Django, Apache Software Foundation, and a number of open source projects, we're not able to accept contributions without a completed form, and the form requires a real name. 

[Django has a good FAQ on the topic](https://www.djangoproject.com/foundation/cla/faq/)

**Comment by it33** [comment]
Per [contribution guidelines](https://github.com/mattermost/platform/blob/master/CONTRIBUTING.md#submitting-a-pull-request) displayed by GitHub to potential contributors during the pull request creation process, we're unable to review this PR given the lack of a completed CLA.

**Pull request closed without merging**
