### PR TITLE
PLT-1279 Make sure posts in common threads are included in getPosts DB query

### PR DESCRIPTION
**Pull request by jwilander**

### CODE REVIEW

**Comment by coreyhulen** [comment]
+1

**Comment by coreyhulen** [comment]
eer...wait I thought this kind of query happens in other places?  search maybe?

**Comment by jwilander** [comment]
The other queries for jumping to a post and getting posts since a certain time all worked properly, it was just this one that wasn't working.

**Comment by crspeller** [comment]
+1

**Pull request merged**
