### PR TITLE
Bug fixes and UI improvements for multiple tickets

### PR DESCRIPTION
**Pull request by asaadmahmoodspin**
Hey guys have a look. Changes in this PR include couple of bug fixes.
- Attachement icon not taking theme color.
- Adding global tooltip event.
- Adding tooltip for times in the center channel.
- Styling markdown blockquotes and lines.
- Removing mention link from css since it's already a link and can take the link styling.
- Improving the title for youtube videos

### CODE REVIEW

**Comment by jwilander** [comment]
+1

**Comment by crspeller** [comment]
Tooltips should probably use react-boostrap instead of jquery magic. (2/5)

**Comment by asaadmahmoodspin** [comment]
Updated the tooltip for the timestamp to use react bootstrap one.

**Comment by crspeller** [comment]
+1

**Pull request merged**
