### PR TITLE
PLT-395: Add syntax highlighting to Markdown code blocks

### PR DESCRIPTION
**Pull request by florianorben**
Included languages since I didn't want to become the compiled js file too big:

- Diff
- Apache
- Makefile
- HTTP
- JSON
- Markdown
- Java
- CSS
- nginx
- ObjectiveC
- Python
- XML
- Perl
- Bash
- PHP
- Coffee
- C
- C
- SQL
- Go
- Ruby 

= highlight.js' common languages + golang

---
*Edit:*
- Java
- ini

added

### CODE REVIEW

**Comment by it33** [comment]
Awesome!!

**Comment by crspeller** [comment]
+1

**Comment by hmhealey** [comment]
Nice job, it looks great

**Comment by it33** [comment]
Hi @florianorben, 

Thanks again for the syntax highlighting feature. The team really likes it, 

We hit a minor issue unfortunately, which is that the change now allows Javascript execution within Mattermost (e.g. if we paste the below into a message, it'll now render a button). 

```
<!DOCTYPE html>
<html>
<body>

<h1>What Can JavaScript Do?</h1>

<p id="demo">JavaScript can change HTML content.</p>

<button type="button"
onclick="document.getElementById('demo').innerHTML = 'Hello JavaScript!'">
Click Me!</button>

</body>
</html>

```

We need to revert this change for now, wondering if you could help take a look? 

Also, one additional request, so that Mattermost users can more easily share their theme settings, including your new syntax highlight support, we wondered if we could have your help including the name of the code theme as a parameter in the import string (under **Account Settings** > **Appearance Settings** > **Copy and paste to share theme colors:**). 

This would allow users to pass each other theme colors that include your syntax highlighting options. 

```

So instead of: 

#171717,#fff,#1f1f1f,#FFFFFF,#fff,#302e30,#196CAF,#FFFFFF,#0177e7,#0177e7,#FFFFFF,#1F1F1F,#DDDDDD,#CC992D,#0D93FF,#0177e7,#FFFFFF,#784098,#A4FFEB,


The import function would accept: 

#171717,#fff,#1f1f1f,#FFFFFF,#fff,#302e30,#196CAF,#FFFFFF,#0177e7,#0177e7,#FFFFFF,#1F1F1F,#DDDDDD,#CC992D,#0D93FF,#0177e7,#FFFFFF,#784098,#A4FFEB,solarized_light

```

**Comment by florianorben** [comment]
Hey @it33,

wow - stupid mistake my side, sorry.
Bug is now fixed in https://github.com/mattermost/platform/pull/1220

The shareable option is now also implemented + language "HTML" will now be highlighted as xml (since there is now dedicated html parser in hightlight.js)

P.S.: I cherry-picked the commits of my old pull requests on top of this one, so there shouldn't be any conflicts

**Pull request merged**
