### PR TITLE
PLT-509 - Fixing search for RC3

### PR DESCRIPTION
**Pull request by asaadmahmoodspin**
Hey guys have a look.

### CODE REVIEW

**Comment by jwilander** [comment]
RC2 has been cut already, we're not cutting an RC3 are we @crspeller ?

**Comment by crspeller** [comment]
@jwilander There is some discussion about cutting an RC3. RC2 has been cut so the title of this PR does not make much sense.

**Comment by asaadmahmoodspin** [comment]
Maybe it'll be decided in triage today whether this goes in. So it's okay to hold this off for now I guess.

**Comment by it33** [comment]
This is a regression and we need to make a call whether it makes sense to do an RC3, or add this to a final release, or do a 1.0.1 or do nothing.

screenclip 63

**Comment by crspeller** [comment]
Not going to take this.

**Pull request closed without merging**
