### PR TITLE
PLT-4602 Fix misaligned close button and fix Android icon rendering bug

### PR DESCRIPTION
**Pull request by kaifaust**
Summary (Edited)
There are two bugs fixed in this PR:
1. The popover close button's horizontal position was miscalculated.
2. The popover close button's icon was rendering incorrectly on Android. I initially replaced the unicode character with an SVG, but in accordance to the following discussion, I resorted to using font-family to fix the bug for implementation consistency and performance.

Ticket
https://mattermost.atlassian.net/browse/PLT-4602

Checklist
- [x] Has UI Changes

### CODE REVIEW

**Comment by kaifaust** [comment]
screen shot 2016-11-07 at 6 25 15 pm
screen shot 2016-11-07 at 6 25 10 pm

**Comment by jasonblais** [comment]
Thanks @kaifaust,

For the mobile web experience, CSS is best so we can avoid increasing page load times. Every kilobyte matters so CSS buttons are typically preferred.

If the line height isn't taken properly on Android, it's okay not to fix this for Mattermost 3.5 and instead revisit adding the SVG icon when we can download and cache assets with the React Native apps.

Would that make sense?

**Comment by yangchen1** [comment]
+1, fixed on Android! Thanks @kaifaust.

**Comment by jasonblais** [comment]
Great, thanks @kaifaust! 

@asaadmahmood please have a look when you're back online tomorrow?

**Comment by asaadmahmood** [comment]
+1

**Comment by hmhealey** [comment]
Merged in preparation for RC4 later today or tomorrow

**Pull request merged**
