### PR TITLE
PLT-3112 Sorted teams by alphabetical order under System Console > Teams

### PR DESCRIPTION
**Pull request by R-Wang97**
#### Summary
When showing list of teams through System Console > Teams they are now sorted by team name in alphabetical order.

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-3112

### CODE REVIEW

**Comment by jwilander** [comment]
Hi @R-Wang97, we just had a PR go in that touched the same code. Would you be able to do a rebase and then sort based off the `team.display_name` instead of `team.name`? That would be much appreciated

**Comment by R-Wang97** [comment]
Will do as soon as I get a chance

**Comment by hmhealey** [comment]
+1 Looks good. This was always really annoying how it worked before. Thanks for fixing it!

**Comment by jwilander** [comment]
Thanks @R-Wang97, +1

**Comment by lfbrock** [comment]
+1

**Pull request merged**
