### PR TITLE
[PLT-6363-3] Create DotMenu components and add dotmenu IDs to posts at center and RHS

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
This PR is for Selenium UI automation testing which adds `dotmenu` IDs and refactors on `dotmenu` components. Dynamic IDs for the last 10 posts.

Deleted the following components:
- `rhs_dropdown.jsx`
- `rhs_dropdown_menu.jsx`

Added the following components:
- `dot_menu.jsx`
- `dot_menu_edit.jsx`
- `dot_menu_flag.jsx`
- `dot_menu_item.jsx`

 Added IDs for UI testing:
 - dotmenu ID at center e.g. `centerDotMenu0`, `centerDotMenu9`, etc.
 - dotmenu ID at rhs e.g. `rhsDotMenu0`, `rhsDotMenu9`, etc.
 - dotmenu ID at rhs root - `rhsRootDotMenu`
 - ID for each menuitem (e.g. Reply, Flag, Permalink, Pin, Delete and Edit) at center, rhs and rhs root e.g. `centerDotMenuReply0`, `rhsDotMenuPermalink1`, `rhsRootDotMenuPin`, etc.

#### Ticket Link
Addresses items 3 to 9 of Jira ticket: [PLT-6363][6363]

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] All new/modified APIs include changes to the drivers

[6363]: https://mattermost.atlassian.net/browse/PLT-6363

### CODE REVIEW

**Comment by jasonblais** [comment]
Thanks for the contribution! 

Our review process is a little delayed given the upcoming release. We'll have PM review completed by the end of this week.

**Comment by lindalumitchell** [comment]
@jasonblais @saturninoabril I'm still in the process of testing this, but wanted to post this comment now as my notes are somewhat lengthy (because it wasn't consistently repro-ing). Will comment again with any further testing results. I'm testing on OSX, Chrome.

Seeing issues with deleting messages. Couldn't repro every case consistently, but three cases that produced errors at least once:

**A. User deletes own message from center that has no reply:**
1. Post message (no replies)
2. Click […] > Delete on that message
3. In confirmation, click Delete
4. Javascript error bar appears at top. Message is deleted.
Expected: Message is deleted without an error.
casea-user1-jserror

**B. Admin deletes user2's message that has no reply:**
1. User2 posts a message
2. User1, system admin, uses […] > Delete to delete user2's message
3. User1 sees message disappear as expected
4. User2 sees Javascript error
5. User2 sees deleted message continue to display until page refreshed
Expected: User2 sees message disappear without error
caseb-user2-jserror

**C. User1 deletes own message that has a user2 reply on it:**
1. User1 posts message
2. User2 replies, leaves RHS open in their browser
3. Back to user1, delete parent message (from center; no need to open RHS)
4. User1 sees message and reply disappear as expected
5. User2 sees Javascript error bar at top
6. User2 sees their reply disappear from center but parent post still appears
7. User2 sees both parent post and their reply still appear in RHS until refresh
Expected: User2 sees parent message and reply disappear without error
casec-admin-deletes-user2-message-user2-jserror

**Comment by lindalumitchell** [comment]
@jasonblais @saturninoabril, I finished testing other options in the [...] menu and found no further issues. Looks good aside from Delete issues above. 

Testing notes for Reply, Permalink, Pin, Un-pin, and Edit (Delete is noted above). Tested on OSX, Chrome, in combinations of the following:

1. Center and RHS
2. User's own messages, other user's messages
3. Parent message, replies
4. Permalink view
5. Mobile view
6. Compact view
7. With and without attachments

**Comment by jasonblais** [comment]
Thanks @lindalumitchell! Great work testing this

@saturninoabril can you help take a look when you have the chance?

**Comment by saturninoabril** [comment]
Thanks @lindalumitchell and @jasonblais! I did a rebase on this PR. 
item A - fixed by [PLT-6270](https://github.com/mattermost/platform/pull/6344)
items B and C - are now fixed as well, could be by above PR as well.

**Comment by lindalumitchell** [comment]
@saturninoabril @jasonblais I re-tested, on a test server built after the PR you mentioned, and sure enough, all of the Delete cases mentioned above are working as expected now. 

I re-tested the other menu options, following the same test methods I described above, and it all looks great! No issues found.

**Comment by jwilander** [comment]
@saturninoabril needs a rebase

**Comment by coreyhulen** [comment]
Looks like this is ready to merge, just needs a rebase.

**Pull request closed without merging**
