### PR TITLE
PLT-703: Support multiple users being shown as typing underneath input boxes.

### PR DESCRIPTION
**Pull request by florianorben**

### CODE REVIEW

**Comment by it33** [comment]
Really nice addition, thanks again Florian!

**Comment by jwilander** [comment]
Nice work @florianorben! My only suggestion would be to set the state inside `getTypingText` (maybe call it `updateTypingText` too) since every time you call it you're just setting the state anyways

**Comment by crspeller** [comment]
+1

**Comment by florianorben** [comment]
good idea! fixed

**Comment by jwilander** [comment]
Thanks! Looks good

**Pull request merged**
