### PR TITLE
MM-1683 Removed a vestigial wait condition from the signup process.

### PR DESCRIPTION
**Pull request by nickago**
Originally, a 5 second delay was triggered on the clicking of "create team" to allow for the route53 dns to make the required operations. However, now that we have removed route53, we no longer need this time break.

### CODE REVIEW

**Comment by crspeller** [comment]
Looks good.

**Comment by jwilander** [comment]
+1

**Comment by hmhealey** [comment]
Looks good. We'll need to make a note to change out that instance of window.location.origin once https://github.com/mattermost/platform/pull/252 is in so that this works correctly on IE10.

**Comment by crspeller** [comment]
@nickago Please resolve your conflicts and change any instances to window.location.origin to use the new function created in #252

**Comment by nickago** [comment]
Content has been rebased and had the correct function swapped in.

**Comment by jwilander** [comment]
@hmhealey can you give one final sign-off on the most recent changes?

**Comment by hmhealey** [comment]
Yep, looks good

**Pull request merged**
