### PR TITLE
MM-1875 Url parameters are now removed after logging in

### PR DESCRIPTION
**Pull request by rgarmsen2295**
Removes things like `?redirect=...` from the url after being redirected during login.

### CODE REVIEW

**Comment by coreyhulen** [comment]
+1

**Comment by crspeller** [comment]
Looks good to me. @rgarmsen2295 If you want you can rebase this and refactor to the class syntax.

**Comment by hmhealey** [comment]
Looks good, but it still needs the cosmetic refactoring crspeller mentioned.

**Comment by rgarmsen2295** [comment]
Yup can do, didn't want to do it initially in case this was merged first, time to try out this crazy new syntax :)

**Comment by rgarmsen2295** [comment]
Okay updated it to match the new eslint standards (minus the config/strings define issue). @hmhealey 
@crspeller please take a look when you get a moment, thanks!

**Comment by crspeller** [comment]
+1

**Comment by hmhealey** [comment]
Looks good to me

**Pull request merged**
