### PR TITLE
Updating user access token UI

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
UI updates for access token stuff
PLT-7286 - Fixing minor UI for tokens stuff

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-7286

#### Checklist
- [ ] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [ ] All new/modified APIs include changes to the drivers
- [ ] Has enterprise changes (please link)
- [x] Has UI changes
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/platform/blob/master/i18n/en.json) and [.../webapp/i18n/en.json](https://github.com/mattermost/platform/tree/master/webapp/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by jwilander** [comment]
I thought it was going to be `Personal Access Tokens` not `Private Access Tokens`?

**Comment by asaadmahmood** [comment]
You're right @jwilander, updated it.

**Comment by asaadmahmood** [comment]
This PR is not ready for merge, just submitted it to get Joram's feedback on something, and some other changes are coming.

**Comment by jwilander** [comment]
@asaadmahmood pushed a fix for the case we discussed

**Comment by asaadmahmood** [comment]
@jasonblais Ready for review.

**Pull request merged**
