### PR TITLE
Fixes mm-1355 adds rate limiting apis

### PR DESCRIPTION
**Pull request by coreyhulen**
Please review but do not merge.  It has config changes.

### CODE REVIEW

**Comment by crspeller** [comment]
- Should we reset the password attempts when a user successfully authenticates?
- I think the default number of attempts should be higher. Something like 10. With 3 your going to get a lot of people getting locked out, which is a pain, and it annoys users. I don't think smaller numbers here add much security as an automated guesser (which is what this defends against) is going to need much more than 10 guesses to get it right.

**Comment by coreyhulen** [comment]
@crspeller yes on both points.  I will change the code.

**Comment by coreyhulen** [comment]
@crspeller ready for re-review.

**Comment by crspeller** [comment]
Looks good!

**Comment by jwilander** [comment]
+1

**Pull request merged**
