### PR TITLE
[PLT-6400] Add README file to config directory

### PR DESCRIPTION
**Pull request by R-Wang97**
#### Summary
Added `README.md` under `config` to specify what the `config.json` file is used for.

#### Ticket Link
https://github.com/mattermost/platform/issues/6496
https://mattermost.atlassian.net/browse/PLT-6400

### CODE REVIEW

**Comment by jasonblais** [comment]
Perhaps a dumb question..if someone downloads Mattermost, will they be able to access the README file from the config directory?

**Comment by R-Wang97** [comment]
@jasonblais I'm not sure, I think it depends on how they download it.

**Comment by jasonblais** [comment]
Okay, I'll queue this for dev review: 

DEVS: Once someone downloads Mattermost, they should be able to access the README file from the config directory.

**Comment by hmhealey** [comment]
I think it should copy it over, but it would be good to double check.

@R-Wang97, if you have a dev environment set up, would you mind running `make package` and seeing if the generated tar file contains config/README.md?

**Comment by R-Wang97** [comment]
@hmhealey Packaged it, and I can confirm the README does get included.

**Pull request merged**
