### PR TITLE
Adding react scrollbar to the RHS thread

### PR DESCRIPTION
**Pull request by asaadmahmoodspin**
Hey guys have a look. Just adding it to the RHS for now so we can see if it works fine before we move it elsewhere.

### CODE REVIEW

**Comment by jwilander** [comment]
+1

**Comment by crspeller** [comment]
@asaadmahmoodspin Found a bug. When you type messages into the RHS. If the RHS is full the textbox scrolls down past the bottom of the screen.

**Comment by asaadmahmoodspin** [comment]
Hey guys can we have a second look if required on this?

**Comment by crspeller** [comment]
Looks good! +1

**Pull request merged**
