### PR TITLE
PLT-4943: Warn when editing a message > 4000 chars

### PR DESCRIPTION
**Pull request by fraziern**
#### Summary
Similar to PR #4687, applied to the edit post modal.

#### Ticket Link
see PLT-4943 for details

#### Checklist
- [x] Has UI changes

### CODE REVIEW

**Comment by yangchen1** [comment]
+1. Tested on Mac Desktop App, tested repro steps in [ticket](https://mattermost.atlassian.net/browse/PLT-4943) in center channel and RHS.

**Comment by esethna** [comment]
Hi @fraziern, thanks for the PR! Functionally the PR is working great but I noticed one issue with where the text is very hard to ready on dark themes. I'd propose the text for this message follows the same color scheme as the `**bold** _italic_ ...` notes:

image

____

image

image

**Comment by fraziern** [comment]
@esethna good call, didn't take into account theme changes. I think I've got it fixed, and went ahead and fixed it for my related PR #4687 (merged) as well.

**Comment by fraziern** [comment]
FYI while testing this I found an unrelated issue, more related to #4687. 

Repro:
1. Draft a post > 4000 chars without submitting
2. Refresh page (the draft will still be there but the warning is gone)
3. Submit post

Observed:
Post is created.

Expected:
Error should appear and post submission should be blocked.

I can work on this separately...

**Comment by esethna** [comment]
Thanks @fraziern! Looks great. We've also noticed an issue with the new error message not appearing in the right-hand sidebar. We have an [open ticket](https://mattermost.atlassian.net/browse/PLT-4976) if you're interested in helping resolve it in a different PR (since it is unrelated to the editing functionality in this PR).

image

**Comment by enahum** [comment]
@fraziern when you have the change and address the comment by @esethna you could rebase this PR as it has conflicts

**Comment by fraziern** [comment]
@enahum conflicts cleared. 

@esethna yep, I can take a look at that ticket. Are there any outstanding changes on this PR needed before your approval?

**Comment by yangchen1** [comment]
Hey @fraziern, just letting you know that ticket has been added as [an issue here](https://github.com/mattermost/platform/issues/4856). If you'd like to take it, please comment! :)

**Pull request merged**
