### PR TITLE
MM-1788 Removed ^replying in preparation for 0.6.0

### PR DESCRIPTION
**Pull request by hmhealey**
Pretty much a straight reversion of #201 (including a couple of fixes made in later pull requests). We'll be bringing this feature back in a less buggy state after 0.6.0 branches.

### CODE REVIEW

**Comment by jwilander** [comment]
+1

**Comment by rgarmsen2295** [comment]
+1

**Comment by nickago** [comment]
All good, merge on

**Comment by kolis** [comment]
When is this coming back? Is there some other way of replying without clicking with the mouse?

**Pull request merged**
