### PR TITLE
MM-1613 Add option to hide Terms of Service disclaimer during signup

### PR DESCRIPTION
**Pull request by hmhealey**
Also reformats web/react/components/signup_user_complete.jsx to match the style guide. The first commit just reformats the file while leaving the functionality unchanged while the second commit makes the actual functional changes.

### CODE REVIEW

**Comment by nickago** [comment]
This looks good, but need to be re-run

**Comment by rgarmsen2295** [comment]
+1 on rebuild

**Comment by crspeller** [comment]
This is not particularly useful until we move this config file server side. We don't provide any instructions on modifying this file or even mention that it exists.

**Comment by crspeller** [comment]
But this is ok for now.

**Pull request merged**
