### PR TITLE
PLT-6474 Basic Elasticsearch System Console Page

### PR DESCRIPTION
**Pull request by grundleborg**
#### Summary
This provides the basic settings for Elasticsearch in the System Console.

It doesn't include the Indexer and Status sections as these will come later once the PRs for the Job framework have been merged.

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-6474

#### Checklist
- [x] Has UI changes
- [x] Includes text changes and localization file updates

### CODE REVIEW

**Comment by esethna** [comment]
@grundleborg please help set up an Elasticsearch server for testing when you get a chance?

**Comment by grundleborg** [comment]
@esethna 

http://george.spinmint.com:8065

`test@test.com` / `passwd`

**Comment by grundleborg** [comment]
@esethna I can do (1), but (2) and (3) both make it possible to get the elasticsearch config into broken, counter-intuitive states because pressing the "Test Config" button saves the config, regardless of whether it is valid or not. I think we have 2 options:

1. (lowest mana) Don't try and be clever with disabling/enabling things based on the "Test Config" outcome.

2. (a little more mana) Change the "Test Config" button to not actually save the config, but to send it's own independent copy of the config, and to test with that, so nothing actually gets saved when pressing "Test Config". That will deal with the potentially invalid config states getting saved with the UI behaving like they weren't saved, if we make changes 2 & 3 as you requested.

**Comment by esethna** [comment]
Discussed in stand-up, we are going with option 2 to follow the email test connection button

**Comment by grundleborg** [comment]
@esethna updated the spinmint with option (2) changes. Ready for you to test again now.

**Comment by grundleborg** [comment]
@esethna fixed 1-3 & 5-7.

4. This is the same behaviour as the email test, and I assume is intended to stop someone with access to the system console pointing the server URL at a server they control and using the test button in order to extract the password, which would normally be secret from someone with just access to the system console.

**Comment by grundleborg** [comment]
@esethna done and updated the spinmint.

**Pull request merged**
