### PR TITLE
PLT-3156 Typo in 'Edit Nickname' message when nickname is set through login provider

### PR DESCRIPTION
**Pull request by tehraven**
Text should say "you need to do so through your login provider". Notice that the typo says "though" instead of "through".

### CODE REVIEW

**Comment by jwilander** [comment]
Hi @tehraven, thanks for the pull request!

It looks like this string is also missing from our translation file. Would you be able to add as a line in `webapp/i18n/en.json` for us? It would be much appreciated.

**Comment by tehraven** [comment]
@jwilander Sorry for the delay. I pushed the change for the english file. Other languages will need to follow.

**Comment by coreyhulen** [comment]
+1

**Comment by enahum** [comment]
+1

**Pull request merged**
