### PR TITLE
PLT-3513 Made /shortcuts separate for Mac

### PR DESCRIPTION
**Pull request by DavidLu1997**
#### Summary
Made /shortcuts separate for Mac

Typing `/shortcuts` or pressing CTRL/CMD+/ now gives the correct message based on your operating system. Windows/Linux users can see Mac shortcuts by typing `/shortcuts mac`.

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-3513

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields.]
- [ ] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [ ] Has driver changes that have been merged and package.json updated
- [ ] Has enterprise changes (please link)
- [ ] Has UI changes
- [x] Includes text changes and localization files updated
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by enahum** [comment]
+1

**Comment by coreyhulen** [comment]
+1

**Comment by jasonblais** [comment]
@DavidLu1997 Why did we want to add `/shortcuts mac/linux` for Windows users?

Otherwise +1 (on Windows), will ask another PM to test on Mac

**Comment by DavidLu1997** [comment]
@jasonblais `/shortcuts mac` is just a side effect of making `/shortcuts` separate. It doesn't exist in the UI or anything, but I added it as a feature in case it gets reported as a bug later on. Typing `/shortcuts` on Windows should always get you the Windows version of the shortcuts.

**Comment by DavidLu1997** [comment]
@jasonblais changes made to force `/shortcuts mac` to display Windows shortcuts on Windows

**Comment by jasonblais** [comment]
Tested `/shortcuts`, `CTRL+/` on Windows, in both center and right hand side. No issues found.

`/shortcuts mac` now also outputs a list of shortcuts for Windows, instead of for Mac.

+1, to be tested by a PM with Mac tomorrow

**Comment by lfbrock** [comment]
+1, works fine on mac.

**Pull request merged**
