### PR TITLE
Update README.md - make it little user friendly

### PR DESCRIPTION
**Pull request by firstrow**
1. Make installation instructions look a bit nicer.
2. Fixed two typos.

### CODE REVIEW

**Comment by firstrow** [comment]
Ok, need to fix lists...

**Comment by it33** [comment]
Hi there, prior to team review of your pull request, could we have your help completing the Contributor License Agreement per the contribution process for Mattermost? http://www.mattermost.org/contribute-to-mattermost/. 

The mailing address is optional, if you do fill it out, we would like to send you a modest gift to thank you for being among the earliest contributors to the project,

**Comment by firstrow** [comment]
Hello. Done.

**Comment by firstrow** [comment]
Also, i send two "License Agreement" request) because in first one I entered "mailing addr" as my email)

**Pull request merged**
