### PR TITLE
PLT-3219 	Fixed file upload overlay not showing up on Edge

### PR DESCRIPTION
**Pull request by hmhealey**
#### Summary
Despite various standardization claims, Edge uses the same file handling code as IE11.

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-3219

### CODE REVIEW

**Comment by enahum** [comment]
+1

**Comment by crspeller** [comment]
+1

**Comment by enahum** [comment]
I've submitted a rebuild on this PR, seems related to #3587

**Comment by jwilander** [comment]
I'm working on fixing TestUserTyping at the moment

**Pull request merged**
