### PR TITLE
MM-1696 - Improvements for Slack Import

### PR DESCRIPTION
**Pull request by asaadmahmoodspin**
Hey guys have a look, just improving the UI for Slack Import.

### CODE REVIEW

**Comment by jwilander** [comment]
+1

**Comment by crspeller** [comment]
Looks good to me, but needs a rebase.

**Comment by asaadmahmoodspin** [comment]
Hey guys have a look at it again. Rebased.

**Comment by crspeller** [comment]
Rebase looks good. Waiting for @hmhealey

**Comment by hmhealey** [comment]
Looks good

**Pull request merged**
