### PR TITLE
Updating client dependancies

### PR DESCRIPTION
**Pull request by crspeller**
### Summary
Updates the web client dependencies

#### Checklist
- [ ] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [ ] Has driver changes that have been merged and package.json updated
- [ ] Has enterprise changes (please link)
- [ ] Has UI changes
- [ ] Includes text changes and localization files updated
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by enahum** [comment]
@crspeller I think the guy from autolinker updated the library which includes a PR with the fix we're using in our fork

**Comment by enahum** [comment]
either way +1

**Comment by crspeller** [comment]
@hmhealey Can you confirm this? If so then we can point back at the source instead of our fork.

**Comment by hmhealey** [comment]
@crspeller Yep, it works so we can point it at the 0.2.7 release instead of our fork. Thanks for submitting the PR to them, Elias

**Comment by crspeller** [comment]
@hmhealey @enahum Updated!

**Comment by enahum** [comment]
+1 yet again

**Comment by hmhealey** [comment]
+1

**Pull request merged**
