### PR TITLE
[PLT-4150] "Channel not found" message appears during autocomplete.

### PR DESCRIPTION
**Pull request by kulak-at**
#### Summary
Error "Channel not found" now appears during autocomplete. During this task I redesigned way of handling blur/focus on these fields. Before on every blur the list was cleared. Now on blur we simply hide the list, but the results are still loaded, so we can show then once again when focus is back.

#### Ticket Link
https://github.com/mattermost/platform/issues/4596
https://mattermost.atlassian.net/browse/PLT-4150

#### Checklist
- [X] Has UI changes

### CODE REVIEW

**Comment by jasonblais** [comment]
Awesome, thanks @kulak-at! Can you help take a look at the build failure?

**Comment by kulak-at** [comment]
@jasonblais It should be fine now, small linting error :)

**Comment by jasonblais** [comment]
Thanks for the contribution! 

Our review process is a little delayed given the upcoming release. We'll have PM review completed by the end of this week.

**Comment by jasonblais** [comment]
Thanks @kulak-at! I gave a test pass on the pull request and overall looks great!

Just a few notes/questions:

1 - Would you be able to help describe the note below a little more? In particular, what do you mean by "blur"?

> Before on every blur the list was cleared. Now on blur we simply hide the list, but the results are still loaded, so we can show then once again when focus is back.

2 - Propose not showing `No matches found` when there are in fact matches.

 - Click CTRL+K to open channel switcher
 - Type `t`
 - Observed: You can see red text appear behind the autocomplete before the autocomplete results are loaded

image

3 - Using the mouse doesn't select any entries on the channel switcher autocomplete
 - Click CTRL+K to open channel switcher
 - Type `t`
 - Use the mouse to choose a channel 
 - Observed: No channel selected.

4 - As described in #4596, propose that the error message isn't be red. It should use the same colour when searching for members in "Manage/View Members" list with no results (see screenshot below). 


image

Note: The "Manage/View Members" list can be found from the three-dotted Mattermost Main Menu next to your username and profile picture in the top left corner.

5 - It appears that the slash command autocomplete doesn't close properly:
 - Type `/away` in message box. Then hit space
 - Observed: Autocomplete remains open
 - Expected: Autocomplete should close

image

^same reproduces for all other autocomplete, including emoji

**Comment by kulak-at** [comment]
@jasonblais Thank you very much for the review. I've pushed new version with fixes, details below:

1. By blur I mean action of clicking outside the input, so un-focusing. Previously if you clicked outside the input and the clicked on it again, no results were shown, I believe in such scenario we should show user all the results because search didn't changed.

2. That should be fixed now. Just small question for dev reviewing to check if the line 87 of suggestion_box.jsx is acceptable - this is a hack to allow all click handlers for list to complete. If not, maybe you know better solution to do that.

3. Fixed. Should behave as before, so autocompletes the search.

4. Color fixed.

5. Should work fine now.

**Comment by jasonblais** [comment]
Thanks @kulak-at! Looking really good

1) Ah, got it. Agree, it's working much better now. Nice work 👍 
2) Confirmed fixed
3) This still seems to reproduce. Can you help take a look?
4) Confirmed fixed
5) This also still seems to reproduce for me.

I did additional testing and otherwise works like a dream. Will be great to have this improvement.

Can you help investigate 3 & 5, when you have the chance?

**Comment by kulak-at** [comment]
@jasonblais Fixed issue 5. About issue number 3 - I've tested it once again on current `master` version and it seems to behave the same as my version. Both are not working correct in my opinion as they just autocomplete the field with the value. I think after click it should just select the channel and go straight to it. I can either work on it within this pull request or create a new ticket with proposed behavior change.

**Comment by jasonblais** [comment]
> I think after click it should just select the channel and go straight to it

Yeah, that's correct, but no need to change this behaviour. I believe there's a separate ticket for this.

What happens in the test server is that no channel is selected: so when you use the mouse to click a channel, the autocomplete closes and no value is selected.

What the expected (current) behaviour on `master` is that the value is added to the input box as you mentioned.

**Comment by jasonblais** [comment]
I'll re-test just in case 3 is fixed on your branch as well

**Comment by jasonblais** [comment]
@jwilander Let us know if your work on the channel switcher will overwrite what's done here? There are two improvements here: 
 - clicking outside the input box closes the autocomplete (no change), but now when you click the input again, the autocomplete is displayed if there are results. Before you were forced to change the input for the autocomplete to be shown
 - "No channels found" message is shown when there are no results (before it was only shown after hitting Enter, which was largely useless)

**Comment by jwilander** [comment]
@jasonblais I'm removing errors on the new switcher so I don't think this is needed anymore, is this doing more than just changing the error message behaviour?

**Comment by jasonblais** [comment]
@jwilander There are two improvements here:

1. clicking outside the input box closes the autocomplete (no change), but now when you click the input again, the autocomplete is displayed if there are results. Before you were forced to change the input for the autocomplete to be shown
2. "No channels found" message is shown when there are no results (before it was only shown after hitting Enter, which was largely useless)

**Comment by jasonblais** [comment]
@kulak-at Some of the work here will be in conflict with https://github.com/mattermost/platform/issues/6486

Once the PR is merged (will be in a few hours), I'm wondering if you'd like to help rebase your branch and make any necessary changes?

Sorry about that.

**Comment by jasonblais** [comment]
Hey @kulak-at, let me know if you had any questions? Would be happy to clarify anything on my note.

**Comment by jasonblais** [comment]
Closing the ticket due to inactivity.

@kulak-at would be happy to help you out if you're still interested finishing the pull request.

[Big thanks for all your help thus far](https://github.com/mattermost/platform/pulls?q=is%3Apr+author%3Akulak-at+is%3Aclosed)

**Pull request closed without merging**
