### PR TITLE
Online status in all modals

### PR DESCRIPTION
**Pull request by samogot**
#### Summary
add wrapper to modal avatar image which show small round indicator of online/away status of member in all modals
image
image

#### Ticket Link
Resubmitting of https://github.com/mattermost/platform/pull/2729

#### Checklist
- [ ] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [ ] Has driver changes that have been merged and package.json updated
- [ ] Has enterprise changes (please link)
- [x] Has UI changes
- [ ] Includes text changes and localization files updated
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by lfbrock** [comment]
Thanks @samogot, can you add the offline indicator to the profile picture as well for consistency?

**Comment by samogot** [comment]
@lfbrock done

**Comment by lfbrock** [comment]
Thanks @samogot, found one more thing - can you make the color of the status indicators follow the theme? 

Other than that looked good, (tested online, away, offline status showing up in DM and channel list in Google Chrome).

**Comment by samogot** [comment]
It's ok, but there is no theme color for offline indicator, should i leave it hardcoded in css or what?

**Comment by lfbrock** [comment]
Hi @samogot, you can leave it hardcoded and we can take a look at the color after it's merged in.

If you're interested in the color blending, I checked with Asaad who did the colors and he said the offline indicator is 0.5 opacity, with a 1px border the same color as the text color wherever the indicator is placed, and the background of the circle is the same as the background of the location where it is placed.

**Comment by samogot** [comment]
@lfbrock done

**Comment by lfbrock** [comment]
+1, looks good

**Comment by hmhealey** [comment]
+1

**Comment by crspeller** [comment]
+1

**Comment by Aka4Code** [comment]
I'm new to mattermost, how can I install this commits on my installation? 
I need to wait for release or I can modify some files on my own? 

I use:
Mattermost Team Edition
Version: 3.2.0  (3.2.0)
Database: mysql
Build Date: Thu Jul 14 16:27:27 UTC 2016

**Comment by it33** [comment]
@Aka4Code easiest to wait for the release, you can [subscribe to the mailing list](http://mattermost.us11.list-manage.com/subscribe?u=6cdba22349ae374e188e7ab8e&id=2add1c8034) for announcements and there are step-by-step instructions on upgrading.

**Pull request merged**
