### PR TITLE
Added .prepare step to make test

### PR DESCRIPTION
**Pull request by hmhealey**
This should hopefully resolve the issues that people were having [here](https://forum.mattermost.org/t/developer-machine-setup-cant-make-test/558/7)

### CODE REVIEW

**Comment by crspeller** [comment]
@hmhealey Can we break it up into two steps? I don't want to have to waste my time installing npm dependencies to run the golang tests. How about one step to go get godep and another to do the npm stuff.

**Comment by hmhealey** [comment]
@crspeller I broke the .prepare step up and made it so make test only requires the go one now. It works running make test on its own, running make test and then make run, and just starting with make run

**Comment by coreyhulen** [comment]
+1

**Comment by crspeller** [comment]
+1

**Pull request merged**
