### PR TITLE
PLT-2863 adding remove user from team

### PR DESCRIPTION
**Pull request by coreyhulen**
This also has a corresponding javascript driver PR at https://github.com/mattermost/mattermost-driver-javascript/pull/11

### CODE REVIEW

**Comment by it33** [comment]
1) For **System Console > Team > Users** propose re-ordering options 

Remove from Team 
Reset Password 
Make System Admin 
Make Team Admin 
Make Inactive 

Instead of: 
image

**Comment by lfbrock** [comment]
Draft documentation is here: https://github.com/mattermost/docs/pull/261

Tested on Chrome: 
- Removing a user from a team (from Manage Member list and System Console) as a System Admin
- Removing a user from a team (from Manage Member list, removing both members and System Admins) as a Team Admin 
- Leaving a team (as a Member, Team Admin, and System Admin)
- Making a user inactive
- Removing a user from a private (not open) team, and making sure they couldn't rejoin

Things found during testing: 

1. There was one weird case where I made a user inactive, and then removed them from a team, and there was no way to make the user active again. This should be fixed by https://mattermost.atlassian.net/browse/PLT-2713, but is currently an issue. 

2. When removing a user from a team, the DM list didn't seem to update for me (they didn't get moved to "Outside this team" even though they were no longer in the team's member list)

screenshot 2016-06-28 11 17 21

screenshot 2016-06-28 11 17 28

3. Hitting the URL of a private team you used to belong to does not redirect to the team selection page (just shows a blank page). 

4. The other small thing is I think "re-join" should just be "rejoin" on this screen:
screenshot 2016-06-28 10 57 55

**Comment by coreyhulen** [comment]
I've re-order the list
1. already has a tix
2. fixed
3. created https://mattermost.atlassian.net/browse/PLT-3511
4. has been fixed

**Comment by jwilander** [comment]
+1, although once the driver changes are merged you should update `webapp/package.json` here to point at the new commit instead of the branch

**Comment by enahum** [comment]
+1

**Pull request merged**
