### PR TITLE
PLT-5628: Add confirmation dialog to emoji delete

### PR DESCRIPTION
**Pull request by VeraLyu**
Please make sure you've read the [pull request](http://docs.mattermost.com/developer/contribution-guide.html#preparing-a-pull-request) section of our [code contribution guidelines](http://docs.mattermost.com/developer/contribution-guide.html).

When filling in a section please remove the help text and the above text.

#### Summary
Split delete modal trigger for reuse and add delete emoji trigger.

#### Ticket Link
JIRA: https://mattermost.atlassian.net/browse/PLT-5628
issue: https://github.com/mattermost/platform/issues/5669

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Has UI changes
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/platform/blob/master/i18n/en.json) and [.../webapp/i18n/en.json](https://github.com/mattermost/platform/tree/master/webapp/i18n/en.json)) updates

### CODE REVIEW

**Comment by lindalumitchell** [comment]
@jasonblais @VeraLyu I tested and verified that the confirmation message appears after clicking to delete a custom emoji. Tested on a non-admin user deleting their own, and on system admin deleting their own and another user's. 

I have two quick clarifications though:
1. Should the message be a red warning color? Not sure of the guidelines, or which example screenshot has the style it should be following.
2. Looks like it's missing the word "the" before "custom emoji" (comparing with the example screenshot). Do we want to add the "the"?

Attaching screenshot.
screen shot 2017-03-13 at 2 11 10 pm

**Comment by VeraLyu** [comment]
@lindalumitchell @jasonblais  for 1. style of the warning I reused warning style in "integration hook deletes" to keep the warning style consistent, let me know if you think these two should be changed to red color. 2. I will update my change to add "the". Thanks for test and review.

**Comment by jasonblais** [comment]
Thanks @VeraLyu and @lindalumitchell! Great work here

1. Let's use a consistent styling with the "Delete Integration" modal. My mistake for having the warning in red colour.
2. Nice catch on missing `the` and thanks @VeraLyu for the quick fix :)


PS: The "warning sign" is a little too close to the word `This` at the beginning of the warning message. I've created a separate ticket for it later since it's also in the "Delete Integrations" screen ([link to ticket](https://mattermost.atlassian.net/browse/PLT-5885))

image

**Comment by jwilander** [comment]
Thanks @VeraLyu, great work!

**Pull request merged**
