### PR TITLE
[GH-5691] Fixed mobile search focus - keyboard collapse/focus

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
- Updated SidebarRight component so that SearchBar component does not re-render when switching between RhsThread and SearchResults
- Added blur function on SuggestionBox component

(note: only tested on dev machine, will help on testing upon test server setup)

#### Ticket Link
GitHub issue: #5691 

#### Checklist
- [x] Has UI changes

### CODE REVIEW

**Comment by jasonblais** [comment]
@lindalumitchell please help with testing?

**Comment by saturninoabril** [comment]
Not sure why it fails. Just let me know if I could help.

**Comment by jasonblais** [comment]
Thanks @saturninoabril, looks like we were out of space, should work now

**Comment by lindalumitchell** [comment]
@jasonblais @saturninoabril on the iOS simulator (iPhone 5s and 6) the keyboard isn't visibly opening at all (on any type of app or screen, not just Mattermost). Focus moves in and out of search field as expected, but I'm unable to observe keyboard behavior. Can someone else test on iOS who can verify keyboard behavior?

When I test on my Android, the keyboard displays and then collapses (and focus is removed from search field) as expected.

**Comment by lindalumitchell** [comment]
@jasonblais @saturninoabril Disregard my previous comment; a setting on simulator had changed, preventing the keyboard from displaying. I can now verify that the keyboard displayed and collapsed as expected on iOS simulator, and search field focus behaved as expected as well. No issues found.

**Comment by grundleborg** [comment]
Looks good. Thanks for the PR @saturninoabril

**Pull request merged**
