### PR TITLE
Added letter to fix spelling

### PR DESCRIPTION
**Pull request by maiki**

### CODE REVIEW

**Comment by jwilander** [comment]
Hi @maiki , thanks for the pull request! 

Before we can review and accept your PR we'll need you to sign the CLA here http://www.mattermost.org/mattermost-contributor-agreement/ .

**Comment by crspeller** [comment]
Closed because no response from submitter.

**Comment by maiki** [comment]
Sorry I didn't reply to this, the email I received said I could reply by email, but apparently the message didn't come through.

My reply was:

> I tried to before I sent the PR, but your form requires a last name and I am mononymous, so I could not submit it. But as my change is adding a single letter to correct the spelling of a word in the readme, I have no issue with you ignoring my PR and making the change yerself.
>
> And you might change the name field from two subtypes to a single text field. That is a Western-centric way of thinking about names, and will exclude many potential contributors. ^_^

**Comment by jwilander** [comment]
Thanks @maiki and no worries about the missed response.

Yes, you're right, having two fields was a mistake. We'll make sure to change that as we don't want to exclude anyone. Once that's fixed I'll let you know so you can submit the PR and get on the contributor's list :)

**Comment by it33** [comment]
hi @maiki, 

Thanks for both your contribution and for bring mononymous names to our attention. We realize there are large parts of the world that use mononymous names, in many parts of Indonesia for example, and we definitely want to include those communities. 

Can you help us understand more about how people with mononymous names handle issues with non-mononymous systems? 

We definitely want to figure out a working process for this, so we can be more inclusive. Also, we'd love to send you a (mononymous!) personalized mug as a thank you for being one of the first 100 contributors to the project: http://forum.mattermost.org/t/limited-edition-mattermost-mugs/143

Every contribution, small or large, makes a difference, and we hope you'll join our early community.

**Comment by maiki** [comment]
Hiya folks. Completely unrelated, responding via email is apparently not working for me with GitHub. Weird.

 > Can you help us understand more about how people with mononymous names handle issues with non-mononymous systems?

It really depends on how "serious" a system is. If it isn't critical, most folks will either refuse to participate, or use a stand-in, such as "maiki N/A", though you can imagine that certain filters will tag that as invalid as well. For something crucial, like civil services, it is normal to contact someone and figure out how their particular system deals with it.

I didn't fill out your form, because it is a legal document, so I am unable to fill it out accurately, and figured it would either be rejected by you, or it could cause trouble later on by calling into question the validity of the contributions signed; we don't expect that to happen, but it is why we have CLAs, ya know?

Anyhow, I'd be happy to fill it out if the fields are changed so I can leave my name. ^_^

**Pull request closed without merging**
