### PR TITLE
Add initial tests for app/team.go

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
Add initial tests for app/team.go 
I will add more tests during the week this is just s initial PR

#### Ticket Link
n/a

#### Checklist
- [x] Added or updated unit tests (required for all new features)

### CODE REVIEW

**Comment by jwilander** [comment]
Looks like a test not touched by this PR is failing @cpanato, do you know what might be causing it? I think you wrote it recently right
```
--- FAIL: TestEmailMention (1.04s)
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 30973 [running]:
panic(0xc7f740, 0xc420014140)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc4211d89c0)
	/usr/local/go/src/testing/testing.go:579 +0x25d
panic(0xc7f740, 0xc420014140)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/mattermost/platform/api.TestEmailMention(0xc4211d89c0)
	/var/lib/jenkins/jobs/mattermost-platform-pr/workspace/src/github.com/mattermost/platform/api/post_test.go:1036 +0x897
testing.tRunner(0xc4211d89c0, 0xdd87d0)
	/usr/local/go/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:646 +0x2ec
exit status 2
```

**Comment by cpanato** [comment]
@jwilander i will take a look,  maybe i did something wrong :)

**Comment by cpanato** [comment]
@jwilander I think was an issue related to the load of the server, took more time to receive the email. I will update the tests to wait a little bit

**Comment by jwilander** [comment]
Sounds good, thanks!

**Pull request merged**
