### PR TITLE
Added Gmail and Office 365 SMTP info

### PR DESCRIPTION
**Pull request by toyorg**
Based on[ Google support](https://support.google.com/a/answer/176600?hl=en) and [Microsoft Technet](https://technet.microsoft.com/en-us/library/dn554323(v=exchg.150).aspx#option2).

### CODE REVIEW

**Comment by it33** [comment]
Thanks @toyorg! Much appreciated!

**Comment by coreyhulen** [comment]
@toyorg have you tested the O365 settings?  We had reports that Mattermost doesn't work with O365.

**Comment by coreyhulen** [comment]
Thanks @toyorg  for the pull request!

Before we can review, we need to add you to the list of approved contributors for the Mattermost project.

Please help complete the Mattermost contribution license agreement?

This is a standard procedure for many open source projects. Your form should be processed within 24 hours and reviewers for your pull request will be able to proceed.

Please let us know if you have any questions.

We are very happy to have you join our growing community!

**Comment by toyorg** [comment]
Joined, sorry for delay.

**Comment by phillip-white-sociomantic** [comment]
@toyorg Did you manage to get this working with Office 365. The issue is still open https://github.com/mattermost/platform/issues/954

**Pull request merged**
