### PR TITLE
Channel switcher UI improvements

### PR DESCRIPTION
**Pull request by asaadmahmood**
Please make sure you've read the [pull request](http://docs.mattermost.com/developer/contribution-guide.html#preparing-a-pull-request) section of our [code contribution guidelines](http://docs.mattermost.com/developer/contribution-guide.html).

When filling in a section please remove the help text and the above text.

#### Summary
Channel switcher UI improvements.
Also just reverted the mattermost theme.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [ ] All new/modified APIs include changes to the drivers
- [ ] Has enterprise changes (please link)
- [x] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/platform/blob/master/i18n/en.json) and [.../webapp/i18n/en.json](https://github.com/mattermost/platform/tree/master/webapp/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by jasonblais** [comment]
Thanks @asaadmahmood, a few notes but otherwise looks great!

1) I still see whitespace between where the channel name is cut off and where the channel switcher border is

image

2) I think there might be slightly more padding above the `Switch Channels - CTRL+K` text than below it

image

3) Would you be able to remove the hyperlink when hovering over the button? It's currently hidden behind the link in the desktop app.

image

I think we just need to remove the URL tag similar to the channel member icon that doesn't show a hyperlink.

image


^ if this needs a dev, let me know and I'll create a ticket

PS: I'll ask LB or ES to check Mac on the symbols, but I assume they're okay.

**Comment by asaadmahmood** [comment]
@jasonblais 
1. FIxed.
2. Didn't fix 2 because it looks fine to me. If you can, then take a screenshot and measure the spacing without zooming in, and see how many pixels is the text off?
3. Can't do, might need a dev, as the buttons are links, where as the channel member is a popover.
4. Sure.

**Comment by jasonblais** [comment]
Also messaged in pre-release: Do we want to have the "unread posts below" bubble so high up?  

image

**Comment by hmhealey** [comment]
@asaadmahmood Needs a rebase

**Comment by jwilander** [comment]
I resolved the conflict

**Pull request merged**
