### PR TITLE
PLT-3506 Added flagged posts functionality

### PR DESCRIPTION
**Pull request by jwilander**
#### Summary
Added the ability to flag/unflag posts in the centre channel, RHS and archive view with the ability to view all flagged posts by clicking the icon in the top right. Thanks to @asaadmahmood for the UI work.

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-3506
https://mattermost.atlassian.net/browse/PLT-3757
https://mattermost.atlassian.net/browse/PLT-3758

#### Checklist
- [x] Added or updated unit tests (required for all new features)
- [x] Added API documentation (required for all new APIs)
- [x] All new/modified APIs include changes to the drivers
- [x] Has UI changes
- [x] Includes text changes and localization files updated

### CODE REVIEW

**Comment by hmhealey** [comment]
@jwilander You've got some style errors due to missing and unused imports

**Comment by jwilander** [comment]
Argh, I ran `make test` but not `make check-style`

**Comment by lfbrock** [comment]
Tested and found a couple issues (they're both related). I filed tickets since JW is away, will discuss if someone else is able to fix them. 

1. In the list of flagged messages, click reply and no "<" arrow appears to let you get back to the search results
https://mattermost.atlassian.net/browse/PLT-3757

2. (Bug) Search for text, and then open the flagged message list and click reply. The "<" arrow does appear, but it takes you back to the search result and not the flagged message. 
https://mattermost.atlassian.net/browse/PLT-3758

**Comment by hmhealey** [comment]
The contents of the tooltip don't properly recenter when the text changes:
image
image

**Comment by jwilander** [comment]
@asaadmahmood can you take a look at the tooltips?

**Comment by jwilander** [comment]
@lfbrock Fixed two issues above.

**Comment by jasonblais** [comment]
@jwilander Looks like there are merge conflicts and the PR needs a rebase

**Comment by jwilander** [comment]
@jasonblais rebased and fixed @hmhealey's issue with the flag tooltip position by having the tooltip disappear after clicking on the flag

**Comment by crspeller** [comment]
+1

**Comment by it33** [comment]
Please don't merge this yet, looks really weird,

**Comment by it33** [comment]
Feedback shared with @asaadmahmood and @jasonblais, if we just revert to LEFT placement and tidy a few things, this looks really good. 

Can't wait for this feature, it is awesome!

**Comment by coreyhulen** [comment]
+1, needs a rebase

**Comment by jasonblais** [comment]
+1 from PM

Verified above bugs have been fixed and latest UI tweaks look good. There are a couple of UX bugs around search that we'll fix later, but nothing that would block the release or that would affect functionality.

Docs have been done.

Can a dev give a quick review on the latest changes?

**Comment by enahum** [comment]
+1

**Comment by crspeller** [comment]
+1 For code.
-1 For inconsistent design.

**Pull request merged**
