### PR TITLE
PLT-3640 Add mobile landing pages

### PR DESCRIPTION
**Pull request by hmhealey**
#### Summary
- Adds landing pages direct the user to download the mobile apps when they visit Mattermost from a mobile browser. These only show up when the user first logs into Mattermost on Android or iOS. 
- Moved all of the client-side browser snooping code into a single file and removed some that was unused

#### Linked PRs
https://github.com/mattermost/ios/pull/33

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-3640

#### Checklist
- Has UI changes
- Includes text changes and localization files updated

### CODE REVIEW

**Comment by jwilander** [comment]
Build failure is unrelated to this PR, I'm looking into it separately.

**Comment by lfbrock** [comment]
Tested: 
- Using iOS App (page did not show up, as expected)
- Safari on iOS
- Android tested by Asaad

**Feedback:**
1) If possible, show the landing page before the user logs in

2) Can’t scroll the page (iPhone 5s), so the bottom button is cut off and I also can’t continue to site
img_4271

3) Clicking the “open” button results in error 
img_4272

**Comment by lfbrock** [comment]
I still seem to be hitting issue #3 where the open button isn't working.

**Comment by asaadmahmood** [comment]
Tested on android, seems to work for me. The continue button took me to google play store.

**Comment by crspeller** [comment]
+1

**Comment by esethna** [comment]
+1, "open button" issue handled with another PR.

**Comment by coreyhulen** [comment]
+1

**Pull request merged**
