### PR TITLE
Fix TLS warning due to insecure content

### PR DESCRIPTION
**Pull request by zackify**
Pretty self explanatory.

### CODE REVIEW

**Comment by coreyhulen** [comment]
Thanks @zackify, but I think all the references in error.html look old.  They should be pulling from our /static dir.  I've created https://mattermost.atlassian.net/browse/PL-23 to track this issue.

**Comment by coreyhulen** [comment]
Hi @zackify, thanks for the pull request and I would still like to get this in irrespective of PL-23.

Before we can review and accept your PR we'll need you to sign the CLA here http://www.mattermost.org/mattermost-contributor-agreement/ .

**Comment by coreyhulen** [comment]
+1 on the review

**Comment by jwilander** [comment]
+1

**Comment by zackify** [comment]
I have friends who won't sign up due to the page saying it is loading mixed content, would be nice to have this fixed soon.

**Comment by jwilander** [comment]
Hi @zackify as @coreyhulen pointed out, we're unable to accept your PR until you sign the CLA here http://www.mattermost.org/mattermost-contributor-agreement/ . Once you've done that we can merge this in quickly.

**Comment by zackify** [comment]
Sorry about that, done.

**Pull request merged**
