### PR TITLE
Emoji autocomplete

### PR DESCRIPTION
**Pull request by hmhealey**
Based off of #1540 and #1579 and it will probably conflict with #1554

Actual changes for this one are in https://github.com/mattermost/platform/compare/cc3e93b7a255d246d79af4d66a19398efef4d09e%5E...b2ae0c8

### CODE REVIEW

**Comment by ninja-** [comment]
:+1:

**Comment by florianorben** [comment]
@hmhealey I could rebase #1554 on this one if you'd like?

**Comment by hmhealey** [comment]
@florianorben Thanks, but that's not necessary. It'll take this one a while to go in anyway since it relies on two of my other PRs so I'll just rebase it when mine are in.

**Comment by florianorben** [comment]
@hmhealey Ok :)

**Comment by trashcan** [comment]
+1. I tested this and couldn't find any bugs.

**Comment by coreyhulen** [comment]
+1

**Comment by crspeller** [comment]
@hmhealey Needs a rebase.

**Pull request merged**
