### PR TITLE
Ui Improvements

### PR DESCRIPTION
**Pull request by asaadmahmoodspin**
Hey guys have a look.
- Increasing width of edit button in modals to support more languages.
- Removing extra span on signup pages.
- Minor font weight change.

### CODE REVIEW

**Comment by jwilander** [comment]
+1

**Comment by asaadmahmoodspin** [comment]
Hey guys, also fixed an issue with the text messing up in account settings modal sidebar.

**Comment by crspeller** [comment]
+1

**Comment by hmhealey** [comment]
+1

**Pull request merged**
