### PR TITLE
translations PR 20170515

### PR DESCRIPTION
**Pull request by enahum**
Ideally this PR should be review by community members for each language.

Note: In the event that you see an english translation instead of the desired language is because this PR was submitted before the translation was made on the Mattermost Translation Server and probably will be submitted for the next PR.

### CODE REVIEW

**Comment by cpanato** [comment]
`PT-BR`lgtm

**Comment by kaakaa** [comment]
`ja` is ok.

**Comment by wget** [comment]
I haven't applied changes for `fr` this week-end. `fr` lgtm.

**Comment by der-test** [comment]
`de` lgtm

**Comment by enahum** [comment]
Closing this one as release 3.9 was cut yesterday and this should be against master.

**Pull request closed without merging**
