### PR TITLE
Mobile Web: Auto-focus cursor in the search box

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
Mobile Web: Auto-focus cursor in the search box and open keyboard when the search icon is tapped

#### Ticket Link
Github issue: #5266 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x ] Has UI changes

### CODE REVIEW

**Comment by jasonblais** [comment]
Thanks @saturninoabril! @doosp can you help test this one when you get the chance?

**Comment by doosp** [comment]
Hi, @saturninoabril 

I just tested this and couldn't find any issue as well. Awesome work! 

@jasonblais would you please help review it when you have a chance? Thanks.

Test Summary:
1. Testing Search Button. The cursor on the search input field and the keyboard appeared right away.
image

**Comment by jasonblais** [comment]
Thanks @saturninoabril! Tested on desktop (Windows 10, Chrome, mobile view) without issues.

However, I found one when testing on iOS 10, iPhone 5s, Safari browser (mobile view):

1) Click the search icon --> search bar gets focus
2) Click "Cancel" --> to get focus away from the search bar (this is bad experience, but https://github.com/mattermost/platform/issues/5261 will address that)
3) Click the back arrow to get back to Mattermost page

Observed: The three-dotted Mattermost menu opens 

image

Expected: The menu doesn't open and instead the previous screen is shown

**Comment by saturninoabril** [comment]
@jasonblais noted. this may be related to autofocus and z-index issue in mobile safari. I tried a few css tricks like '-webkit-transform' and hidden visibility but couldn't get it right. I'll get back to this issue later...

**Comment by jasonblais** [comment]
@saturninoabril thanks for looking into it. 

If you need any help with CSS, let us know. We'd be happy to help

**Comment by saturninoabril** [comment]
@jasonblais see changes made to fix issue with safari mobile view. I don't have a way to actually test it with IOS but hopefully it also solved the issue there. thanks!

**Comment by jasonblais** [comment]
Thanks @saturninoabril! Tested search, recent mentions and flagged posts on desktop browser mobile view, and on mobile Safari browser.

1. [correct] Search bar gets focus after clicking the search icon on desktop Chrome, mobile view
2. [correct] The issue [described above](https://github.com/mattermost/platform/pull/5284#issuecomment-277287290) where Mattermost main menu would open in safari mobile is now fixed
3. [incorrect] Unfortunately it looks like your most recent commit led to the search bar not getting focus on iOS Safari browser after clicking the search icon.

Can you help take a look at 3? If you're not able to reproduce it since you don't have an iOS device, let me know.

----

PS: I also found an unrelated issue during the tutorial steps for which I created a separate ticket: [tutorial pages are cut off for iPhone 5s, Safari](https://mattermost.atlassian.net/browse/PLT-5475)

**Comment by saturninoabril** [comment]
@jasonblais I've pushed revision to this PR. Could you please check again and let me know how it works in IOS safari? thanks!

**Comment by jasonblais** [comment]
Thanks @saturninoabril! 

Tested on Windows 10/Chrome and iOS Safari, all issues resolved. Thank you!

@lindalu, can you help test this on your Android device when you get the chance?

**Comment by lindalu** [comment]
@jasonblais Android/Chrome looks good! Tested search, recent mentions, and flagged posts.

After clicking Search icon, recent mentions, or flagged posts:
1. Search bar gets focus and x to clear input appears, as expected
2. Back arrow opens Mattermost page (without three-dot menu open), as expected

**Comment by jasonblais** [comment]
Sweet, great to here! Thanks @saturninoabril, @doosp and @lindalu! 

Queuing for dev review next

**Comment by grundleborg** [comment]
Looks good to me. @asaadmahmood would you mind giving a quick review to the CSS changes?

**Comment by saturninoabril** [comment]
Done rebase and fixed conflict to master. thanks!

**Comment by asaadmahmood** [comment]
The spacing should be consistent with the search icon.
screen shot 2017-02-24 at 11 52 03 am

**Comment by saturninoabril** [comment]
@asaadmahmood noted. but somehow it's related to this [issue](https://github.com/mattermost/platform/pull/5306/files) where PR is already merged. Let me know how you want to proceed.

Regarding the spacing of 'x' to search icon, ok but you'll notice that the 'x' is almost centered with the 'fa-refresh'. therefore it will move as well.

**Comment by asaadmahmood** [comment]
@saturninoabril the fa refresh has quite less spacing compared to the "x" icon, so you only need to move the "x" icon, try targeting the "x" icon instead of just targeting the whole thing.

**Comment by asaadmahmood** [comment]
@saturninoabril Please use the icon: `×`.
Also give this css to the icon:
```
.sidebar--right .sidebar__search-clear-x {
    margin-left: 14px;
    font-size: 22px;
    font-weight: 700;
    opacity: .7;
}
```

**Comment by saturninoabril** [comment]
@asaadmahmood please see changes I've made. honestly, i'm not really sure about the icon ```×``` . is it unicode character 'multiplication' (U+00D7)?

if yes, not sure what's the preferred way of handling it. should it be either:
- ``` <span className='sidebar__search-clear-x'>{'×'}</span> ``` (the one i used),
- ```<span className='sidebar__search-clear-x'>{'\u00D7'}</span>```,
- ```content:"\u00D7";``` in CSS.

**Comment by asaadmahmood** [comment]
@saturninoabril add `aria-hidden='true'` to it.
So it will be:
<span className='sidebar__search-clear-x' aria-hidden='true'>{'×'}</span>

**Comment by jasonblais** [comment]
@asaadmahmood please help review latest changes?

Thanks @saturninoabril, really appreciate your help on the CSS updates.

Just so you know, there may be a delay in merging this PR as we are locking down feature and improvement contributions for the v3.7 release, per our [release process](https://docs.mattermost.com/process/release-process.html). This PR can be merged into `master` after we branch `release-3.7` on March 6th.

**Pull request merged**
