### PR TITLE
PLT-1378 Emoji Reactions

### PR DESCRIPTION
**Pull request by hmhealey**
Initial version of emoji reactions without the full UI (still needs the emoji picker)

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-1378

#### Checklist
- Added or updated unit tests (required for all new features)
- Added API documentation (required for all new APIs)
- All new/modified APIs include changes to the drivers
- Has UI changes
- Includes text changes and localization files updated

### CODE REVIEW

**Comment by it33** [comment]
Wrap in RHS doesn't seem to work
image

**Comment by it33** [comment]
Seem to be losing reactions in RHS... 

image

**Comment by enahum** [comment]
needs rebase

**Comment by lfbrock** [comment]
1. Is it possible to extend the reply bar the full length of the emoji reaction rows? Or else only show the reply bar beside the message, so that it ends before the first emoji reaction row? 
screenshot 2016-08-29 11 18 32

2. Date header here overlaps the second row of emojis
screenshot 2016-08-29 11 18 52

**Comment by hmhealey** [comment]
Closing this as there's more work to be done

**Pull request closed without merging**
