### PR TITLE
Add AllowFrameFrom to config to permit another site to frame Mattermost

### PR DESCRIPTION
**Pull request by adamierymenko**
#### Summary

This PR adds a config-file-only `AllowFrameFrom` option. If present and non-empty it modifies the `X-Frame-Options` and related headers to allow Mattermost to be framed by another site.

#### Ticket Link

There's no ticket for this. It's a minor change, only a few lines. We did sign the contributor agreement.

#### Checklist

None appeared applicable.

### CODE REVIEW

**Comment by coreyhulen** [comment]
@adamierymenko looks like you have a build failure

```
Running GOFMT
diff api/context.go gofmt/api/context.go --- /tmp/gofmt443822621	2017-06-23 20:28:09.444891000 +0000 +++ /tmp/gofmt220910296	2017-06-23 20:28:09.444891000 +0000 @@ -157,8 +157,8 @@  			w.Header().Set(X-Frame-Options, SAMEORIGIN)  			w.Header().Set(Content-Security-Policy, frame-ancestors self)  		} else { -			w.Header().Set(X-Frame-Options, fmt.Sprintf(ALLOW-FROM %s,*utils.Cfg.ServiceSettings.AllowFrameFrom)) -			w.Header().Set(Content-Security-Policy, fmt.Sprintf(frame-ancestors self %s,*utils.Cfg.ServiceSettings.AllowFrameFrom)) +			w.Header().Set(X-Frame-Options, fmt.Sprintf(ALLOW-FROM %s, *utils.Cfg.ServiceSettings.AllowFrameFrom)) +			w.Header().Set(Content-Security-Policy, fmt.Sprintf(frame-ancestors self %s, *utils.Cfg.ServiceSettings.AllowFrameFrom))  		}  	} else {  		// All api response bodies will be JSON formatted by default
/bin/sh: 1: [: diff api/context.go gofmt/api/context.go --- /tmp/gofmt443822621	2017-06-23 20:28:09.444891000 +0000 +++ /tmp/gofmt220910296	2017-06-23 20:28:09.444891000 +0000 @@ -157,8 +157,8 @@  			w.Header().Set(X-Frame-Options, SAMEORIGIN)  			w.Header().Set(Content-Security-Policy, frame-ancestors: unexpected operator
gofmt failure
make: *** [check-server-style] Error 1
[TemplateProject] FAILED performing builders from: 'mattermost-platform-template'
Build step 'Use builders from another project' marked build as failure
[TemplateProject] Starting publishers from: mattermost-platform-template
Performing Post build task...
Match found for :Created database for mysql : True
Logical operation result is TRUE
```

**Comment by adamierymenko** [comment]
That's strange. We built it. Will take a look.

**Comment by adamierymenko** [comment]
Do I need to do any documentation here or is this good to go?

**Comment by jasonblais** [comment]
@adamierymenko I really apologize for the silence here.

There has been some miscommunication on our end which caused such a long delay in responding.

1) Can we have your help taking a look at the build failures? 

```
Running GOFMT
diff api/context.go gofmt/api/context.go --- /tmp/gofmt443822621	2017-06-23 20:28:09.444891000 +0000 +++ /tmp/gofmt220910296	2017-06-23 20:28:09.444891000 +0000 @@ -157,8 +157,8 @@  			w.Header().Set(X-Frame-Options, SAMEORIGIN)  			w.Header().Set(Content-Security-Policy, frame-ancestors self)  		} else { -			w.Header().Set(X-Frame-Options, fmt.Sprintf(ALLOW-FROM %s,*utils.Cfg.ServiceSettings.AllowFrameFrom)) -			w.Header().Set(Content-Security-Policy, fmt.Sprintf(frame-ancestors self %s,*utils.Cfg.ServiceSettings.AllowFrameFrom)) +			w.Header().Set(X-Frame-Options, fmt.Sprintf(ALLOW-FROM %s, *utils.Cfg.ServiceSettings.AllowFrameFrom)) +			w.Header().Set(Content-Security-Policy, fmt.Sprintf(frame-ancestors self %s, *utils.Cfg.ServiceSettings.AllowFrameFrom))  		}  	} else {  		// All api response bodies will be JSON formatted by default
/bin/sh: 1: [: diff api/context.go gofmt/api/context.go --- /tmp/gofmt443822621	2017-06-23 20:28:09.444891000 +0000 +++ /tmp/gofmt220910296	2017-06-23 20:28:09.444891000 +0000 @@ -157,8 +157,8 @@  			w.Header().Set(X-Frame-Options, SAMEORIGIN)  			w.Header().Set(Content-Security-Policy, frame-ancestors: unexpected operator
gofmt failure
make: *** [check-server-style] Error 1
[TemplateProject] FAILED performing builders from: 'mattermost-platform-template'
Build step 'Use builders from another project' marked build as failure
[TemplateProject] Starting publishers from: mattermost-platform-template
Performing Post build task...
Match found for :Created database for mysql : True
Logical operation result is TRUE
```

2) @coreyhulen @crspeller Is there any concern for accepting this pull request?

I thought Mattermost has code to prevent the application from being contained in an iframe to avoid "clickjacking" where a malicious user contains the app in an iframe to steal user data. 

Doesn't this pull request allow Mattermost to be contained within an iframe which isn't recommended?

(Apologies in advance if what I said above is incorrect or unrelevant)

3) @adamierymenko Is there a particular format the `AllowFrameFrom` setting should be supplied with?

Once again, really sorry for the silence here.

**Comment by jasonblais** [comment]
Hey @adamierymenko, wondering if you had any questions about 1) and 3) above, and if there's anything we can help with?

**Comment by jasonblais** [comment]
We haven't received an update so we'll assume that the PR is no longer being worked on.

I'll lave your branch open, so that if you'd like to continue working on it, your previous work isn't lost.

If you have any questions, don't hesitate to let us know.

**Comment by adamierymenko** [comment]
We don't have any build failures with this. As for #3 it's the format outlined in the HTTP spec.

**Comment by jasonblais** [comment]
Thanks @adamierymenko. If you're interested, feel free to re-submit the PR and we can take a closer look at the build failure.

You might need to rebase against the `master` branch though, to resolve conflicts.

**Pull request closed without merging**
