### PR TITLE
WIP performance fixes part 1

### PR DESCRIPTION
**Pull request by ninja-**
big improvements to channel switching time...the things left are mostly code which does CSS/jquery from javascript and is hard to refactor. 

Things left to improve...
1.  sidebar render slow
2. textbox resize slow

Notes: 
1. clearTimeout is slow as hell on chrome
2. removing inactive channels from dom would make the switching time worse (but I tried)

channel switch click event is now just ~ 70ms in my tests

### CODE REVIEW

**Comment by ninja-** [comment]
pinging @h3chief as he was interested in performance

**Comment by it33** [comment]
Similar to feedback in https://github.com/mattermost/platform/pull/1580 and https://github.com/react-bootstrap/react-bootstrap/pull/1548, it's not clear what these changes are doing, and this PR is breaking on automated unit tests. 

If you're looking for feedback from a specific individual, please use a fork. Please avoid making untested WIP PRs to master in future,

**Comment by ninja-** [comment]
@it33 it's not breaking on test just on eslint...this PR improved performance in some areas that accessed DOM directly on channel click event. One of the fixes is for suggestionbox rating CPU every click anywhere

**Comment by H3Chief** [comment]
:-1:  for all the reasons @it33 brings up, and they are still valid.

**Comment by ninja-** [comment]
@H3Chief um no

**Pull request closed without merging**
