### PR TITLE
PLT-5871 Fix permalink in email for DMs/GMs

### PR DESCRIPTION
**Pull request by jwilander**
#### Summary
Fix permalink in email for DMs/GMs

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-5871

### CODE REVIEW

**Comment by jwilander** [comment]
@crspeller might want to look at this for the performance considerations for sending DMs

**Comment by hmhealey** [comment]
@jwilander Shouldn't `team.Id` be non-empty and `channel.Id` always be empty for DM and GM channels? I must not understand the whole situation here

**Comment by jwilander** [comment]
`team` will be an empty struct for DMs since we don't pull the team for DMs anymore

**Comment by hmhealey** [comment]
Oh I see. It used to pass down the current team there even for DM channels, but now it doesn't.

**Pull request merged**
