### PR TITLE
PLT-3753 Added Segment analytics

### PR DESCRIPTION
**Pull request by DavidLu1997**
#### Summary
Added server-side diagnostics:
- License information
- Config settings
Updated privacy policy

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-3753

#### Checklist
- [x] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by jwilander** [comment]
+1

**Comment by hmhealey** [comment]
+1

**Comment by enahum** [comment]
+1

**Comment by enahum** [comment]
@DavidLu1997 build is failing I think you have to add `github.com/segmentio/analytics-go` to glide.yaml and glide.lock files

**Comment by jwilander** [comment]
Make sure to run:
1. `glide get github.com/segmentio/analytics-go`
2. `glide install`

in the platform directory and then push the changes that appear in `glide.yaml`, `glide.lock` and in the `vendor` directory

**Comment by enahum** [comment]
@DavidLu1997 there are some changes in a few vendor packages, can you fix that plz

**Comment by enahum** [comment]
+1 again waiting for build

**Pull request merged**
