### PR TITLE
Fixing localization error in commands

### PR DESCRIPTION
**Pull request by crspeller**
Ticket created so this doesn't happen again: https://mattermost.atlassian.net/browse/PLT-2079

### CODE REVIEW

**Comment by coreyhulen** [comment]
I think we also use a mock context in mattermost.go for cmd line stuff?  does this need to change too?

**Comment by coreyhulen** [comment]
nvm...thought this was in load test

**Comment by coreyhulen** [comment]
+1

**Comment by jwilander** [comment]
+1

**Pull request merged**
