### PR TITLE
Re-add babel-polyfill

### PR DESCRIPTION
**Pull request by hmhealey**
Re-adding this because String.prototype.startsWith is missing on IE11 again

### CODE REVIEW

**Comment by jwilander** [comment]
+1

**Comment by crspeller** [comment]
@hmhealey Is there a version number on the babel stuff? If so it's a good idea to use it so we know what version we are on. Plus it helps for caching errors.

**Comment by hmhealey** [comment]
I added version information and also switched the polyfill from being from https://github.com/JasonBerry/babel-es6-polyfill to the one included with babel-core since I realized babel-es6-polyfill had no clear licensing information

**Comment by crspeller** [comment]
+1

**Pull request merged**
