### PR TITLE
Create zh.json

### PR DESCRIPTION
**Pull request by wuzhengxuan**
Create Chinese Language zh.json

### CODE REVIEW

**Comment by wuzhengxuan** [comment]
Hello,our team create Chinese Language zh.json，but we don't know how to use it.Change utils.jsx?

**Comment by enahum** [comment]
This file is for the Server, and to use it you have to set the LANG env variable to zh. In case you want the frontend to be translated as well you will need to translate `web/static/i18n/en.json` as well.

**Comment by wuzhengxuan** [comment]
I see. I'll translate and submit web/static/i18n/en.json.Thanks~

**Comment by coreyhulen** [comment]
@wuzhengxuan please follow the directions at http://docs.mattermost.com/developer/localization.html#translation-process

**Comment by wuzhengxuan** [comment]
@coreyhulen thanks~

**Comment by coreyhulen** [comment]
Closing this PR, please re-open once completed.  Thanks!

**Pull request closed without merging**
