### PR TITLE
Fix web app manifest

### PR DESCRIPTION
**Pull request by Rudloff**
#### Summary
This patch includes the manifest.json file that was missing in `dist/`.
It also fixes some issues with the manifest itself:
* Added a `display` setting that forces the app in standalone mode (no browser UI)
* Added a `start_url` setting that makes the app shortcut open the home page (instead of the current page)
* Fixed path to icons

#### Ticket Link
https://github.com/mattermost/platform/issues/3541

#### Checklist
- [ ] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [ ] Has driver changes that have been merged and package.json updated
- [ ] Has enterprise changes (please link)
- [ ] Has UI changes
- [ ] Includes text changes and localization files updated
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by crspeller** [comment]
@Rudloff Thanks for the fix! 
One thing. Can you remove the copy and import the file properly from the html file? You can see how the other files in there are imported. I think webpack should be able to handle it properly because a loader is already setup.

**Comment by Rudloff** [comment]
I tried to do this:
```diff
@@ -29,7 +29,7 @@
     <link rel='icon' type='image/png' sizes='32x32' href='images/favicon/favicon-32x32.png'>
     <link rel='icon' type='image/png' sizes='96x96' href='images/favicon/favicon-96x96.png'>
     <link rel='icon' type='image/png' sizes='192x192' href='images/favicon/android-chrome-192x192.png'>
-    <link rel='manifest' href='/static/config/manifest.json'>
+    <link rel='manifest' href='config/manifest.json'>
     <!-- Android add to homescreen -->
 
     <!-- CSS Should always go first -->
```

But then the result is this:
```html
<link rel='manifest' href='[object Object]'>
```

Am I doing something wrong?

**Comment by crspeller** [comment]
Webpack is trying to embed the json file because the default loader for json in the webpack config does not split it out into a file. If you add:
```
{
    test: /manifest\.json$/,
    oaders: [
        'file?name=files/[hash].[ext]',
        'json'
    ]
},
```
below the current json loader it should work.

**Comment by Rudloff** [comment]
Thanks, it works! (I add to exclude it from the other JSON rule to prevent a bug similar to https://github.com/webpack/json-loader/issues/13 though).
I have updated the PR. Is there anything else I need to change?

**Comment by crspeller** [comment]
Nope looks good!
+1

**Comment by enahum** [comment]
+1

**Comment by jasonblais** [comment]
Thanks @Rudloff, appreciate it! Tested this in iOS, two notes:

1) If we add the suggested `display` setting that forces the app in standalone mode, we'll actually lose one piece of functionality, which is the **Back** button on the login screen. 

Example: If a user makes a mistake while entering their team URL, the new `display` setting wouldn't allow them to go back, unless they signed in. This might cause problems if the user accidentally entered a domain they don't belong to, and are stuck in the login screen (attached screenshot has without/with the `display` setting).

Hence, we won't be able to take this setting at this point, may I ask you help remove the `display` setting from your pull request?

image

2) I tried testing your other change `Added a start_url setting that makes the app shortcut open the home page (instead of the current page)`. Can you specify which `app shortcut` do you mean? And by `pages` do you mean `channels` in Mattermost?

Otherwise, I really love your initiative on fixing the icon paths and the missing manifest.json. Big thanks @Rudloff!!

**Comment by Rudloff** [comment]
Hello @jasonblais.

1) Note that this is the current behavior on Android with Chrome (because the manifest can't be loaded, it uses the `mobile-web-app-capable` meta which triggers standalone mode).

But I don't really see why it is a problem in your example because if a user added a wrong domain, he can remove the app, open the correct domain in his browser and re-add the app.
(And progressive web apps are scoped to the domain so if he used the wrong domain, it would open all other domains in a new browser window.)

Also I don't understand what the back button would go back to in this case, as the login screen is the first page loaded in the app? On Android, if I go back from here, it just closes the web app.

2) When I add the app to the homescreen, it creates an app icon, which is actually a shortcut to the URL I was browsing.

For example, imagine that I am on https://team.example.com/my-team/channels/some-channel and I add the app to my homescreen.
* If `start_url` is not set, it will always open this specific channel when I open the web app.
* If it is set, it will open the URL specified in `start_url`.

**Comment by Rudloff** [comment]
@crspeller I just noticed that the json-loader is adding `module.exports` at the beginning of the manifest, making it invalid!
Are you sure CopyWebpackPlugin isn't a better solution here?

**Comment by crspeller** [comment]
@Rudloff Maybe the extract  text plugin would help? https://github.com/webpack/extract-text-webpack-plugin  
We can't use the copy plugin because we set caching headers that cause files to be cached for a long time. So we need to have the filename be a hash like the others in case we change it.

**Comment by Rudloff** [comment]
@crspeller Turns out there was a much easier way: use only the file loader (without the json loader).
I have updated the PR.

@jasonblais Would setting the display property to [minimal-ui](https://www.w3.org/TR/appmanifest/#dm-minimal-ui) be OK for you?

**Comment by crspeller** [comment]
@Rudloff Awesome.

**Comment by jasonblais** [comment]
Thanks @Rudloff for your feedback,

1) While I see where you're coming from, it doesn't follow [Mattermost "Fast, Obvious, and Forgiving" Design Principles](http://docs.mattermost.com/developer/fx-guidelines.html?highlight=forgiving#design-principles). 

If a user has entered an incorrect domain, having an option to go back appears more obvious and forgiving, than removing the app. Attached is a screenshot they would be able to go **Back** to.

image

2) Great, thank you for the description, very helpful. 

The standard behaviour in this case would be to save the bookmark on the URL you were currently viewing. This would be achieved if `start_url` is not specified.

_____________________________________________________________________________________

@rudloff In light of the above, we won't be able to take the two changes (for `display` and `start_url`) at this time. However, the rest of your changes in the pull request look great.

If you're interested in working on Mattermost, we'd welcome your help. If you read CONTRIBUTING.md in the repo it has documentation on how our process works and you can also find a [list of tickets accepting pull requests](https://mattermost.atlassian.net/issues/?filter=12000).

**Comment by Rudloff** [comment]
Oh you're talking about the native app! (I didn't know it uses the manifest.)

I am talking about the [Add to homescreen](https://developer.chrome.com/multidevice/android/installtohomescreen) feature of Android. (This is what I meant by "adding the app".)
When adding a web app to the homescreen, it makes much more sense to have it open as a standalone app (and it's also what Google's guidelines recommend) but if this causes issues with the native app, I will change that to `minimal-ui`. It also makes sense to open the index (like a native app would).

**Comment by Rudloff** [comment]
@jasonblais I updated my PR. I removed `start_url` and set `display` to `minimal-ui`.

**Comment by jasonblais** [comment]
Thanks @Rudloff, appreciate it! And sorry for the confusion previously,

Quick question: I tested the changes from adding `"display": "minimal-ui"`, and it appears to function similarly to the existing setting when `display` isn't set (both in the native and web apps). 

Would there be an example where the change would benefit the user interface (or functionality), or is this change intended to follow an external guideline?

**Comment by Rudloff** [comment]
None of the Android browsers support this yet so I can't test it (and when it is not supported, it fallbacks to `browser` which is the default display mode) but the [spec](https://w3c.github.io/manifest/) says that we should use `minimal-ui` when we want "a minimal set of UI elements for controlling navigation" which seemed appropriate here.

I thought Safari supported this mode but turns out it was [a different minimal-ui property](http://zerosixthree.se/minimal-ui-meta-tag/). So if no browser supports this value for now, I guess we can remove the  `display` property.

**Comment by jasonblais** [comment]
Sounds great. Thanks again @Rudloff for working on this PR!

Can a dev help give this one more review before merging?

**Comment by crspeller** [comment]
+1

**Pull request merged**
