### PR TITLE
Infinite scroll

### PR DESCRIPTION
**Pull request by pan-feng**
Infinite scroll

#### Summary
Automatically load the previous messages instead of click link

#### Ticket Link
#5292 

#### Checklist
- [x] Has UI changes

### CODE REVIEW

**Comment by pan-feng** [comment]
link #5292

**Comment by pan-feng** [comment]
image

**Comment by doosp** [comment]
@pan-feng 

Thanks for another contribution

I tested scrolling in desktop and mobile and couldn't find any issue.

@jasonblais  @esethna would you please review when you have a chance? If there's any other tests I might have missed let me know. Thaks.

**Comment by doosp** [comment]
This is not specified in the task but would it be good idea to add this in the search?

**Comment by jasonblais** [comment]
Thanks for helping test the PR!

@doosp do you mean in the search results on right-hand sidebar? Would you have a screenshot to share?

**Comment by doh5** [comment]
Sorry for not explaining this clearly.

Repro steps:
1. Type same messages (e.g. "d") many many times in channel A and channel B.
2. Search for the message. (without specifying the channel)
3. It shows me the most recent at the top. If I scroll all the way to the bottom, it doesn't give me the next search list.
image

(the channel name is "Town Square" but the last message in the searched list is from off topic. I typed 1st message in the "Town Square" so I should see it at the bottom of search or next page button)

However, the max number of possible search is a lot. It may not be necessary. I'm 0/5.

**Comment by jasonblais** [comment]
Ah, got it, thanks @doh5! The search results are actually limited to 100, so only the 100 most recent search results are returned. That's why more results cannot be loaded. Improving search in Mattermost is on our roadmap.

PS: Linda is helping test this PR as well

**Comment by lindalu** [comment]
Tested this; very cool! I tested on OSX Chrome and FF (desktop width and narrow view) and on Samsung Android Chrome.

Summary:
1. In channel with enough messages to trigger "Load more messages" link, scroll up to view previous messages
2. The next batch of previous messages load automatically, without having to click anything to display them

A couple questions about the loading indicator: 

As previous messages are loading, I see an indicator showing that the system is working. When viewing on Samsung Android (Chrome) it is animated as I'd expect. But on the OSX browsers, both wide and narrow views, I'm not seeing it animated, and it flashes once before messages load. See attached images for examples of the following:
1. View on desktop browser (wide or narrow view)
2. Scroll up to see previous messages
3. Loading indicator appears static
4. Loading indicator flashes off and on before messages display
5. In mobile view, indicator appears mostly behind displayed date

@jasonblais can you reproduce what I'm seeing? If so, should the indicator behave on a desktop browser like it does on a mobile browser, or is it okay as-is?

Second question: On mobile view, is it okay that the indicator appears mostly behind the displayed date? I think it looks fine, but wanted to make sure.

infscroll-desk
infscroll-mob-indicator

**Comment by jasonblais** [comment]
Thanks @pan-feng, @doh5 and @lindalu for helping testing this out! And sorry for a slow response.

@pan-feng would you be able to review Linda's feedback above so that the experience is more smooth when loading more messages?

The flow should be something like
 1. Scroll up to see previous messages
 2. Loading indicator appears and animates
 3. Loading indicator disappears and messages are loaded

For the second question: I think it's fine to show the loading indicator behind the date indicator. If it doesn't work well, we might need to update/remove the date indicator but that can be done on a separate PR

**Comment by jasonblais** [comment]
Hey @pan-feng I've been researching other apps and I think it's easier to do the following:

1. Scroll up to see previous messages
2. Text `Loading more messages...` appears
3. Text disappears and messages are loaded

I worry it'll be difficult to get the loading indicator perfect. We can add the text for now and look at an animated loading bar later.

What do you think?

**Comment by jasonblais** [comment]
@pan-feng Just so you know, there may be a delay in merging this PR as we are locking down feature and improvement contributions for the v3.7 release, per our [release process](https://docs.mattermost.com/process/release-process.html). This PR can be merged into `master` after we branch `release-3.7` on March 6th.

**Comment by jasonblais** [comment]
Hey @pan-feng,

I noticed there hasn't been activity for a couple of weeks - just wanted to touch base and see if there's anything I can help clarify on the feedback provided above.

Would really love to see this feature in the product, and work with you to add it in.

**Comment by jasonblais** [comment]
We haven't received an update so we'll assume that the PR is no longer been worked on. Closing the PR so someone else in the community can help take a look.

If you're still interested helping with this improvement, let us know! Would love to work with you on this. Also, feel free to re-submit the PR anytime.

Many thanks for all your help thus far: https://github.com/mattermost/platform/pulls?q=is%3Apr+author%3Apan-feng+is%3Aclosed

**Pull request closed without merging**
