### PR TITLE
PLT-3504 Sanitize personal information out of license for non system admin users

### PR DESCRIPTION
**Pull request by jwilander**
#### Summary
Some personal/unused fields were coming through in the client license, now they are sanitized out for non system admin users.

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-3504

### CODE REVIEW

**Comment by enahum** [comment]
```go
props["BuildNumber"] = model.BuildNumber
props["SegmentDeveloperKey"] = c.ServiceSettings.SegmentDeveloperKey
props["GoogleDeveloperKey"] = c.ServiceSettings.GoogleDeveloperKey
```

This may have sensitive data too and should be remove according to spec, right?

**Comment by jwilander** [comment]
Nope that's all needed for the client and isn't considered sensitive.

**Comment by enahum** [comment]
+1

**Comment by hmhealey** [comment]
+1

**Pull request merged**
