### PR TITLE
PLT-3721/PLT-3696 Only get channels and posts on WebSocket connect if team is set

### PR DESCRIPTION
**Pull request by jwilander**
#### Summary
Fixes trying to get a channels with a null team id.

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-3696
https://mattermost.atlassian.net/browse/PLT-3721

### CODE REVIEW

**Comment by enahum** [comment]
+1, do we want to localize the message in the console.error ?

**Comment by jwilander** [comment]
I don't think we can since this needs to work standalone as a driver from the webapp, right?

**Comment by enahum** [comment]
right right!!! completely forgot that the driver was back in platform

**Comment by crspeller** [comment]
+1

**Pull request merged**
