### PR TITLE
PLT-5122 - Switching to circular status icons

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
PLT-5122 - Switching to circular status icons
PLT-5220 - Increasing default size for emoticons

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-5122
https://mattermost.atlassian.net/browse/PLT-5220

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [ ] All new/modified APIs include changes to the drivers
- [ ] Has enterprise changes (please link)
- [x] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/platform/blob/master/i18n/en.json) and [.../webapp/i18n/en.json](https://github.com/mattermost/platform/tree/master/webapp/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by jwilander** [comment]
Marking WIP until it gets discussed by UX team.

**Comment by DrLynix** [comment]
image

Dunno if my screen/config is the problem but I still have troubles with emoji mouth details, although it is way better than retail 3.6.

**Comment by lfbrock** [comment]
I think this broke status icons in compact view @asaadmahmood 
screenshot 2017-01-26 21 37 52

**Comment by asaadmahmood** [comment]
@lfbrock the status icons are already broken in compact view on master, I have a [ticket](https://mattermost.atlassian.net/browse/PLT-5106) for it, but that can be addressed in a separate PR.

**Pull request merged**
