### PR TITLE
GH-4685 Post a System Message when channel is renamed

### PR DESCRIPTION
**Pull request by fraziern**
#### Summary
Post a System Message when channel is renamed
Fixed a var name misspelling in `rename_channel_modal.jsx`

#### Ticket Link
#4685 

#### Checklist
- [x] Added or updated unit tests (required for all new features)
- [x] Has UI/UX changes
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/platform/blob/master/i18n/en.json) and [.../webapp/i18n/en.json](https://github.com/mattermost/platform/tree/master/webapp/i18n/en.json)) updates

### CODE REVIEW

**Comment by jasonblais** [comment]
Thanks @fraziern, looking really good!

Just one small issue: It looks like the system message is rendering Markdown even though the channel display name doesn't support Markdown formatting.

I've attached a couple of examples:

image
*Expected: `test2 updated the channel display name from: Link to: [Design](channel 1)`*

image
*Expected: `test2 updated the channel display name from: a to: **HEY**`*

I know this is a bit of a special case, not sure how tricky this would be to change?

**Comment by fraziern** [comment]
@jasonblais I've gone over the codebase and got confirmation from someone on the dev channel as well - looks like this wouldn't be an easy fix. Is this something we can let stand since it's a pretty special case?

**Comment by jasonblais** [comment]
Thanks @fraziern for checking with me,

I've posted this for UX approval, I feel it's fine given it's an edge case and not common when renaming channels.

Will get back to you,

**Comment by jasonblais** [comment]
Thanks again @fraziern,

We discussed in UX and the issue doesn't block this PR as it's such a small case. I've created this JIRA ticket however for a future improvement to address it: https://mattermost.atlassian.net/browse/PLT-5009

Queuing for second PM review

**Comment by esethna** [comment]
Thanks for the PR @fraziern, very well done, I've tested on Win10/Chrome

1. Policy permissions are still intact
2. Channel name character limit still applies.
3. Markdown headings do not render in the message
____

FYI I found an unrelated issue (also repros on `master`) where you cannot change channel handle a second time without switching channels first, [ticket here](https://mattermost.atlassian.net/browse/PLT-5024).

Repo:
1. Channel Menu > **Rename Channel**
2. Edit the channel handle, Save
3. Channel Menu > **Rename Channel**

Observed:
Rename modal does not appear unless you switch channels. No console errors thrown.

Expected:
Rename Channel modal appears.

**Pull request merged**
