### PR TITLE
MM-1654 Anti-clickjacking measures

### PR DESCRIPTION
**Pull request by nickago**
The 'x-frame-options' and 'content-security-policy' headers tell the browser not to allow the given page to be rendered in an iframe, the main method of executing clickjacks. In addition, the head template now has a kill switch that will display nothing even if the page renders inside of an iframe.

### CODE REVIEW

**Comment by crspeller** [comment]
There is a lot of copy code adding the headers in multiple places in web.go. Can we add the headers in the ServeHTTP function in context.go? There you can check if the request is an api request or not and set the headers appropriately.

**Comment by hmhealey** [comment]
Alternatively, can those properties not just be added directly to the header template, or does React not support that?

**Comment by jwilander** [comment]
@hmhealey the HTTP response headers are set server side

**Comment by hmhealey** [comment]
Oh sorry, I was confusing the HTTP and HTML headers. Agree with Chris though that we should see if there's a way to avoid duplicating that code everywhere.

**Comment by nickago** [comment]
@crspeller was completely right on that, I couldn't find that method originally but the code is now in it's appropriate place.

**Comment by hmhealey** [comment]
Looks good now. Ready for merge.

**Comment by crspeller** [comment]
Is it necessary to have the headers be sent back with API calls? If not we should only add the headers if it is not an api url so: `if !h.isApi`

**Comment by nickago** [comment]
The research I did said to put the headers on everything, but if you don't think we'll ever need them, then I can add the switch.

**Comment by crspeller** [comment]
If security experts say to put the headers on everything, including api calls, then that is what we should do. Just not sure how and when the browser interprets the header.

**Comment by nickago** [comment]
I think as long as we have it on all the pages, we should be ok. The only use case I could think of would be our api calls sending html data, but I don't think we have any of those.

**Comment by coreyhulen** [comment]
is X-FRAME-OPTIONS case sensitive?  Because I see it in most places as X-Frame-Options.

**Comment by nickago** [comment]
I saw it everywhere in all capitals, but if you've seen it elsewhere like that it can be changed

**Comment by nickago** [comment]
I added the limiting flag after doing some more research, and also removed the caps lock title of the x-frame-headers flag

**Comment by crspeller** [comment]
Cool, looks good!

**Comment by jwilander** [comment]
+1

**Comment by jwilander** [comment]
@hmhealey can you give one final sign-off?

**Comment by hmhealey** [comment]
Yep, it looks good to me.

**Comment by hubearth** [comment]
I understand the security risk, but it would be nice to add options for choosing  X-Frame-Options SAME-ORIGIN and to specify a domain allowed by content-security-policy frame-ancestor.
I'm using mattermost embedded in Odoo which is a great enhancement.

**Comment by Tizi44** [comment]
@hubearth 

Which file did you change from DENY to ALLOW-FROM.
I cant find head.html or even context.go.
Or how did you embed Mattermost into odoo? 
I want to do the same with Nextcloud. 

Thank's

**Pull request merged**
