### PR TITLE
content type for getFile()

### PR DESCRIPTION
**Pull request by jdeng**
currently image previewing is broken on Chrome due to lack of a proper Content-Type header

### CODE REVIEW

**Comment by crspeller** [comment]
Thanks @jdeng! Please help complete our CLA so this pull request can be reviewed? http://www.mattermost.org/mattermost-contributor-agreement/

**Comment by it33** [comment]
@jdeng, thanks for completing the CLA, you've been added to the approve contributor's list and reviewers can continue

**Comment by coreyhulen** [comment]
+1

**Comment by jwilander** [comment]
HI @jdeng , would you be able to rebase this pull request? There are some merge conflicts now

**Comment by jwilander** [comment]
+1

**Pull request merged**
