### PR TITLE
PLT-5669: Change format of timestamp of access history

### PR DESCRIPTION
**Pull request by VeraLyu**
Add new line for timestamp of access history to
prevent line wrap.

#### Summary
Add new line for timestamp of access history to
prevent line wrap.

#### Ticket Link
Issue: [https://github.com/mattermost/platform/issues/5625](url)
Jira: [https://mattermost.atlassian.net/browse/PLT-5669](url)

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Has UI changes

### CODE REVIEW

**Comment by jasonblais** [comment]
Thanks for the pull request @VeraLyu! Welcome to the Mattermost community :)

@lindalumitchell please help with testing when you get the chance?

**Comment by lindalumitchell** [comment]
@jasonblais @VeraLyu I took a look, and I do see a new line for the timestamp, as described. Now, though, it looks like the date is wrapping to an additional line (the "7" in "2017" is on its own line). Does it look that way for you as well? I tested on desktop view and mobile view. Attaching screenshot.

screen shot 2017-03-09 at 1 53 10 pm

**Comment by jasonblais** [comment]
Good catch @lindalumitchell.

@VeraLyu I've attached the Access History modal in the same screen size from `mattermost:master` and `VeraLyu:PLT-5669` for comparison. Can you help take a look and see where the issue might be?

Thank you once more for your contribution!

`VeraLyu:PLT-5669`
image

`mattermost:master`
image

**Comment by jasonblais** [comment]
PS: I think we should re-design this modal at some point, it's not that great overall. The IP address and session ID wrap around two lines.

But that's a discussion for another time..

**Comment by VeraLyu** [comment]
Thanks for review, I'll take a look this weekend.

**Comment by VeraLyu** [comment]
I've updated this patch to correct timestamp/sessionid/ip wrap problem

**Comment by jasonblais** [comment]
Thanks @VeraLyu! 

@lindalumitchell please help with testing?

**Comment by lindalumitchell** [comment]
@jasonblais @VeraLyu this looks great! Tested on desktop view and mobile view, and the timestamp is formatted as expected (in narrower views, the other columns get pretty odd, but you already noted, Jason, that the whole modal could use some redesign work in the future). But the timestamp column looks great.

**Comment by grundleborg** [comment]
Thnks for the PR @VeraLyu

**Pull request merged**
