### PR TITLE
MM-1593 Added a message deleted indicator

### PR DESCRIPTION
**Pull request by jwilander**
Added a '(message deleted)' indicator when a post is deleted to let the user know what's happening.

### CODE REVIEW

**Comment by crspeller** [comment]
Code looks good to me. Is there better UI coming for this? 

@jwilander Needs rebase.

**Comment by jwilander** [comment]
Rebase complete.

**Comment by hmhealey** [comment]
Looks good to me. +1

**Comment by nickago** [comment]
+1, ready to merge

**Pull request merged**
