### PR TITLE
Prevent channel creation if TeamId invalid

### LINKED ISSUE #4398: [Help Wanted] System Admins can create channels with invalid team IDs
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

---

**Difficulty**: Introductory (new to codebase)

**Details**: ([Jira ticket](https://mattermost.atlassian.net/browse/PLT-4302))
By submitting an API request with an incorrect or random team ID, orphaned channels that have no team can be created.

To remedy the issue, we should add a check to make sure the team exists in `createChannel()` in [api/channel.go](https://github.com/mattermost/platform/blob/master/api/channel.go) before checking permissions. Only need to check the team exists if it's provided by the client (aka the length of the channel.TeamId is greater than zero).

Files you should need to look at or modify:
- https://github.com/mattermost/platform/blob/master/api/channel.go

### PR DESCRIPTION
**Pull request by foggy1**
#### Summary
Now when a user tries to create a channel, the TeamId they associate with it must be relevant and cannot be random or non-existent.  If the TeamId is no good, it's treated as an invalid param.

#### Ticket Link
Resolves #4398 

#### Checklist

- [ ] Added or updated unit tests (required for all new features)

### CODE REVIEW

**Comment by coreyhulen** [comment]
@foggy1 looks like you have a build error

env GOOS=linux GOARCH=amd64 go install  -ldflags "-X github.com/mattermost/platform/model.BuildNumber=3134 -X 'github.com/mattermost/platform/model.BuildDate=Wed Nov  2 21:14:11 UTC 2016' -X github.com/mattermost/platform/model.BuildHash=f09ecc788f9f96c1808d9b1af3b798dfb200b7e5 -X github.com/mattermost/platform/model.BuildHashEnterprise=ec1feaca4ceac0189c2af5d6ba5a068552d53ee5 -X github.com/mattermost/platform/model.BuildEnterpriseReady=true" 
# github.com/mattermost/platform/api
api/channel.go:55: channel.TeamID undefined (type *model.Channel has no field or method TeamID, but does have TeamId)
make: *** [build-linux] Error 2

**Comment by foggy1** [comment]
@coreyhulen Ack, that's a silly one.  Patched it up.

**Comment by jwilander** [comment]
@foggy1 looks like you just need to update this unit test
```
--- FAIL: TestCreateChannel (0.87s)
	channel_test.go:75: : Invalid channel.TeamId parameter, 
```

I think you should just have to change the condition in
```
if _, err := Client.CreateChannel(&channel); err.StatusCode != http.StatusForbidden {
	t.Fatal(err)
}
```
to `err == nil` and the `t.Fatal(err)` to `t.Fatal("should have failed - team ID didn't match client team ID")`

**Comment by jwilander** [comment]
Looks like you have a `gofmt` syntax error here as well:
```
Running GOFMT
api/channel_test.go:74:5: expected 1 expression
gofmt failure
```

**Comment by crspeller** [comment]
Thanks for the PR @foggy1 
Closing because of inactivit please re-submit when build is fixed.

**Comment by cpanato** [comment]
there are any one working on that?

**Comment by jasonblais** [comment]
I don't think so @cpanato, feel free to take it :)

**Comment by cpanato** [comment]
ok! :) will work on that

**Pull request closed without merging**
