### PR TITLE
Removed ESC from /shortcuts

### PR DESCRIPTION
**Pull request by DavidLu1997**
Removed ESC from /shortcuts as it is not going in for v3.1.0

image

### CODE REVIEW

**Comment by jwilander** [comment]
+1

**Comment by coreyhulen** [comment]
+1

**Comment by enahum** [comment]
+1 you're killing me with this changes.

Going to update the translations once this get in. (again)

**Comment by DavidLu1997** [comment]
@enahum sorry, I have cookies

**Comment by jwilander** [comment]
Build failed because mattermopd was restarting, I'm merging since all other checks in the build passed

**Pull request merged**
