### PR TITLE
[WIP] dont sanitize html before katex' parsing, katex does that by itself..

### PR DESCRIPTION
**Pull request by florianorben**
See discussion here... https://github.com/mattermost/platform/pull/1351#issuecomment-156880170, more fixes to come ;)

### CODE REVIEW

**Comment by florianorben** [comment]
Needs a *DO NOT MERGE* label please :)

**Comment by akhmerov** [comment]
Is there any way to test the rendered result or produced html?

**Comment by florianorben** [comment]
I can later send you some examples of the rendered html, currently at work though ;)

**Comment by akhmerov** [comment]
I meant unit tests, but the rendered examples are OK :)

**Comment by florianorben** [comment]
Sorry for not responding, I'm quite busy with work lately :-/

Ah, unit tests - that was a major misunderstanding on my side, oops :D
This is something I had in my mind already yes, but I agree this would make perfect sense for this feature - I'll talk to the core team about this, dont know if anything's planned for that until now - will respond back once more progress has been made!

**Comment by florianorben** [comment]
Hey @akhmerov,

took a while sorry.
I think most of the quirks should be fixed now.

- `&` now longer get escaped
- No more smileys in latex code ;)
-`'`, `"` and `<` `>` no longer break the code

Also delimiters for latex code blocks are now `$$` as you suggested, like this:

```
$$
1 +  \frac{q^2}{(1-q)}+\frac{q^6}{(1-q)(1-q^2)}+\cdots = \displaystyle \prod_{j=0}^{\infty}\frac{1}{(1-q^{5j+2})(1-q^{5j+3})}, f(x) = \sqrt{1+x}, \quad x \ge -1
$$
```

(although
    
    ```latex
    1+2=3
    ```
would work too).

     ```tex
    1+2+3=6
    ```
now applies code-highlighting to a latex code block.

The one thing missing is inline latex.
Using `$` as a delimiter got a little tricky, as this would break quite a lot of text (like if you have some text with a price in USD in it). I'm still trying to figure out, what's the best way to do it....
Perhaps using `\(` and `\)` would be the best option.

For starters I'll add some manual tests for latex parsing (like the one that are used for smileys and markdown in general). Automated unit test will come at some point, but we'll need a automated test system for that first)

**Comment by akhmerov** [comment]
Sorry, I don't currently have time to test the branch. Looking at the implementation, I don't quite understand how the new syntax interacts with the remaining of markdown (or `marked`).

Say, what happens for this input: `` Latex can be used by enclosing it with `$$`: $$ \alpha $$``?

Otherwise I totally agree about single dollar signs: these are just too common. If `\(` and `\)` are too hard to implement, or if they break other logic, then it's perhaps better to use `$$` for inline math. Display math can always be "mimicked" by adding extra blank lines.

**Comment by florianorben** [comment]
Hey,

the latex delimiters have to be on a separate line, like code the backticks in codeblocks, i.e.
``Latex can be used by enclosing it with `$$`: $$ \alpha $$`` would render just the way write it.

Whereas
```
Latex can be used by enclosing it with `$$`:
$$
\alpha
$$
```
would return the desired result (parsing `\alpha` into `α`) (although there's a small bug in there I just noticed where the leading `$$` has to be preceded by an extra line break, but that should easily be fixable).

I guess `\(` `\)` should be fine for inline math, those should be pretty uncommon and having separate start/ending delimiters actually makes it a little easier ;).

Can I help you with testing somehow?
E.g. you tell me some inputs and I check if they produce the correct markup or so?

**Comment by akhmerov** [comment]
What about an analogous code block markup, so triple backquotes containing `$$`?
What if display latex appears in a bullet list? Will indenting it keep it a part of the list?

What about Latex inside headings/blockquotes/bold/italic text? Those issues are probably more relevant to inline markup.

BTW did you see https://www.npmjs.com/package/marked-pax, which implements katex?

**Comment by florianorben** [comment]
> What about an analogous code block markup, so triple backquotes containing $$?
What if display latex appears in a bullet list? Will indenting it keep it a part of the list?

Those are fine, although it looks a little *strange* a bullet list because display latex is center-aligned.

Bold/Italics/etc. I'll check those once I get to inline latex again, good idea to test them though!
For display they're no prob right now :)

Ah cool, thanks for the link, I'll have a look at that one!

**Comment by akhmerov** [comment]
> although it looks a little strange a bullet list because display latex is center-aligned.

That's conventional; I was rather worried about the list being broken (perhaps more important about the numbered lists).

**Comment by akhmerov** [comment]
@florianorben do you know if it's now too late for this PR to enter v1.3? While potentially not being in the final state, it now implements latex much better than the original #1351, so for useable latex it should be merged as is.

**Comment by hmhealey** [comment]
@akhmerov We're currently working on a release candidate for 1.3 right now. If anything else does get accepted, it'll have to be for a serious bug. Having $$ blocks for markdown will be awesome, but we'll need to wait for 1.4 to get it in.

**Comment by akhmerov** [comment]
Got it. This is fixing only a mild bug, but indeed not worth it in view of the timeline.

**Comment by akhmerov** [comment]
Just a quick update: KaTeX rendering isn't triggered on cell edit in 1.3; @florianorben any ideas on how to fix?

**Comment by akhmerov** [comment]
It appears @florianorben is unavailable for a while. At the same time this PR fixes a bunch of annoying bugs and doesn't introduce non-trivial code as far as I can tell. Therefore I suggest to merge it as is, optionally reverting 6fb0afe, since it introduces new syntax and doesn't fix any outstanding bugs.

**Comment by jwilander** [comment]
Unfortunately @akhmerov it needs a rebase. Can you let me know which bugs this fixes and I can port over any fixes into a new PR?

**Comment by akhmerov** [comment]
I've checked it out over here: https://pre-release.mattermost.com/core/channels/justtesting

The outstanding bugs that are fixed by this PR are:
* Incorrect sanitization of input to KaTeX (symbols like `<>$'`, etc).
* emoji substitution is performed inside KaTeX, while it really shouldn't.

**Comment by jwilander** [comment]
Thanks @akhmerov. I've created two tickets in Jira  to get these bugs fixed. I'll make sure they get fixed before our next release.

https://mattermost.atlassian.net/browse/PLT-1817
https://mattermost.atlassian.net/browse/PLT-1818

**Comment by akhmerov** [comment]
Thanks back @jwilander!

I'm not sure where this belongs, but there is one last outstanding issue with latex that we've discussed here. I just wanted to point it out in the hope it doesn't get lost.

Specifically, there's currently no support for inline latex. The same issue was also raised on [mattermost uservoice](http://mattermost.uservoice.com/forums/306457-general/suggestions/11206086-allow-latex-inline-latex-here), and can probably be implemented using the code from https://www.npmjs.com/package/marked-pax.

**Comment by hmhealey** [comment]
I'll have to check that version of marked out at some point since it looks really interesting. We've made some modifications to the version that we use so the code probably won't be directly compatible with ours, but I'll definitely take a look at it if I get to work on that.

**Comment by niemela** [comment]
FWIW, Gitter (https://gitter.im/) supports inline LaTeX between between `$$` pairs (i.e. `$$sqrt(2)$$`). And it's lovely...

**Comment by tgy** [comment]
I'm really interested in inline LaTeX too.

**Pull request closed without merging**
