### PR TITLE
Add a progress bar for file uploads

### PR DESCRIPTION
**Pull request by fengpan23**
i try to complete  this 
i test local this  look‘s great

### CODE REVIEW

**Comment by grundleborg** [comment]
@fengpan23 you appear to have an eslint error which is causing the checks to fail:

    /home/ubuntu/workspace/mattermost-platform-pr/src/github.com/mattermost/platform/webapp/components/create_post.jsx
    254:9  error  Unexpected console statement  no-console

If you don't want to have to wait ages for Jenkins to run the style checks each time you push, you can run them on your local machine with the following command:

    make check-client-style

**Comment by jasonblais** [comment]
hey @fengpan23, big thanks for your contribution!

Would you be interested to join our [Mattermost Contributors community site](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676), if you already haven't, to discuss your contribution?

Once you have signed in, you can direct message me at `@jason`.

Also happy to discuss it here in GitHub. Just thought it might be easier to have a conversation on the Mattermost instance, as I would love to talk about the PR with you and chat about some of the UI.

**Comment by pan-feng** [comment]
@grundleborg  i run  make check-client-style  get some error 
image

**Comment by jasonblais** [comment]
Thanks again @fengpan23 for your work here,

As we chatted on pre-release.mattermost.com, we'll close this pull request given https://github.com/mattermost/platform/pull/4271 has already got this in progress and your work is based off of that PR.

We really value your work and appreciate your interest in contributing [additional improvements]( https://github.com/mattermost/platform/issues/4553)! If you have any questions, don't hesitate to let me know anytime :)

**Pull request closed without merging**
