### PR TITLE
translations PR 20170724

### PR DESCRIPTION
**Pull request by enahum**
Ideally this PR should be review by community members for each language.

Note: In the event that you see an english translation instead of the desired language is because this PR was submitted before the translation was made on the Mattermost Translation Server and probably will be submitted for the next PR.

### CODE REVIEW

**Comment by kaakaa** [comment]
`ja` LGTM.

But original messages have `Elasticsearch` and `ElasticSearch`.
I think that `Elasticsearch` is correct.

**Comment by cpanato** [comment]
`PT-BR` LGTM.
I also fix some missing string in the translation server

**Comment by grundleborg** [comment]
Fixed the strings with incorrect capitalisation of Elasticsearch in this PR: https://github.com/mattermost/platform/pull/7020

**Comment by enahum** [comment]
closing this PR and will be submitting another one when scheduled that will resolve the conflicts

**Pull request closed without merging**
