### PR TITLE
PLT-3767 Promote localizations on System Console and Account Settings

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
We want to promote contributions for translations so we added a couple of links for people who may be interested in contributing.

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-3767

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [ ] All new/modified APIs include changes to the drivers
- [ ] Has enterprise changes (please link)
- [x] Has UI changes
- [x] Includes text changes and localization files updated
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by jasonblais** [comment]
+1 from PM, verified both Account Settings and System Console on Windows/Chrome

**Comment by crspeller** [comment]
+1

**Comment by hmhealey** [comment]
+1

**Comment by crspeller** [comment]
@enahum Needs rebase. Build failure is the websocket thing.

**Comment by enahum** [comment]
rebased, not sure why it failed on websocket tests since I just added a couple of strings

**Pull request merged**
