### PR TITLE
Change post paragraphs' line heights and margins for better readability

### PR DESCRIPTION
**Pull request by florianorben**
Increases post's line height and margin between paragraphs for better readability

*Before*:
before_post_style_change

*After*:
after_post_style_change

### CODE REVIEW

**Comment by it33** [comment]
Sweet!

**Comment by coreyhulen** [comment]
+1

**Comment by coreyhulen** [comment]
@asaadmahmoodspin please take a look

**Comment by asaadmahmoodspin** [comment]
Looks cool.

**Pull request merged**
