### PR TITLE
MM-831 Post timestamp now updates in real time

### PR DESCRIPTION
**Pull request by nickago**

### CODE REVIEW

**Comment by jwilander** [comment]
Have you tried this with a lot of posts on screen? I think the dispatcher might vomit if there is an event listener for every post rendered. If it does you'll probably need to have the event listener at a higher level (maybe in post_list.jsx for center pane and somewhere else for RHS) and then just pass the change down to the child posts.

**Comment by nickago** [comment]
Alright, my original incentive for putting the it in post_info was so that we wouldn't have to re-render a giant part of our ui every minute or so, but would you say the above way is more expensive than doing that?

**Comment by jwilander** [comment]
React shouldn't re-render the entire components, it should only render the stuff that changed. From the docs:

*If the ReactElement was previously rendered into container, this will perform an update on it and only mutate the DOM as necessary to reflect the latest React component.*

https://facebook.github.io/react/docs/top-level-api.html

**Comment by nickago** [comment]
Fantastic, coming right up

**Comment by nickago** [comment]
Update in

**Comment by jwilander** [comment]
1/5 but maybe just add a code comment above the forceUpdate() as to why it's happening, out of context of it seems kind of random. Other than that it looks good

**Comment by nickago** [comment]
Done

**Comment by jwilander** [comment]
Perfect! Will merge after Travis CI build passes (I know it will pass but I want to get into the habit of not merging until Travis says so)

**Comment by jwilander** [comment]
Err, oops forgot this was assigned to @hmhealey , I'll let him merge

**Comment by hmhealey** [comment]
Thanks for doing the work on this for me @jwilander , but I don't have merge access so you'll need to take care of this one.

**Pull request merged**
