### PR TITLE
PLT-1433 OGG files render as audio files with preview

### PR DESCRIPTION
**Pull request by khoa-le**

### CODE REVIEW

**Comment by khoa-le** [comment]
We have already ticket on Jira , so I update title with ticket-id "PLT-1433".

**Comment by it33** [comment]
Perfect, thanks! Test server set up for testing

**Comment by jwilander** [comment]
+1, I tested on Mac Chrome, Firefox and Safari. Couldn't play the preview on Safari but it handled it properly by displaying the audio icon and file info

**Comment by crspeller** [comment]
+1

**Pull request merged**
