### PR TITLE
PLT-1881 - Adding LDAP Syncronization

### PR DESCRIPTION
**Pull request by crspeller**
Corresponding EE PR: https://github.com/mattermost/enterprise/pull/27

TODO:
- Additional performance testing
- Sync now button in system console. 
- Moving other services over to using the updated job system. 
- Forcing all existing users to become LDAP.

### CODE REVIEW

**Comment by jwilander** [comment]
What's with the `RevokeAllSessionsNoContext`? Can't we just update `RevokeAllSessions` to not use the context and always return an AppError and then update all the places that use `RevokeAllSessions` to set the context error themselves?

**Comment by crspeller** [comment]
Ya that was my first thought. But It would be made complicated by the fact that RevokeAllSessions uses the context to log an audit. I didn't want to do all that refactoring for this ticket.

**Comment by jwilander** [comment]
I'm OK with it for now if we make sure to clean it up in the near future. Can you make a ticket for it?

**Comment by enahum** [comment]
+1

**Comment by coreyhulen** [comment]
+1

**Comment by crspeller** [comment]
@jwilander Ticket is here: https://mattermost.atlassian.net/browse/PLT-3174

**Pull request merged**
