### PR TITLE
PLT-7093/PLT-7096 Updates to new message below indicator

### PR DESCRIPTION
**Pull request by jwilander**
#### Summary
Updates to new message below indicator.

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-7093
https://mattermost.atlassian.net/browse/PLT-7096

### CODE REVIEW

**Comment by jwilander** [comment]
@lindalumitchell if you have some time would you be able to give this a quick test? I seem to have got it working but there's a lot of cases and another set of eyes on it might help find some corner cases

**Comment by lindalumitchell** [comment]
@jwilander I'm taking a look now, and seeing a couple issues:

1. Clicking to add a user to a private channel caused a JS error, and thereafter switching channels also caused JS errors
js-error-spinmint-unreads-below

2. After adding another user but without any messages in the channel other than system messages:
  - `New message below` appeared 
  - Channel intro text does not display
  - `Load more messages` displays, and clicking it has no visible effect
screen shot 2017-07-11 at 2 05 14 pm

**Comment by jwilander** [comment]
Thanks Linda, not sure the first one is related to this PR but I'll take a look

**Comment by jwilander** [comment]
Tried a bunch of things and wasn't able to reproduce. Maybe we just keep an eye out for it and try to get repro steps?

**Comment by lindalumitchell** [comment]
@jwilander I tried again a little and couldn't either. That sounds good to me.

**Pull request merged**
