### PR TITLE
PLT-2862 Re-added LDAP login boxes as part of signup flow

### PR DESCRIPTION
**Pull request by hmhealey**

### CODE REVIEW

**Comment by crspeller** [comment]
@hmhealey Why restrict the box to only LDAP? Seems to add a bunch of unnecessary complexity.

**Comment by hmhealey** [comment]
The code is a bit more complex, but it makes the UI more straightforward. Even though there's no technical reason that an existing user couldn't just enter their username/password there, it'd feel kind of confusing if they could login from there. I thought about re-adding the separate API path, but a simple flag was easy enough in this case.

**Comment by enahum** [comment]
+1

**Comment by crspeller** [comment]
The UI is already confusing. User testing proved that. I think we should reduce the complexity in the code. We don't have to advertise the fact that a user can login with anything there. Still call it LDAP, just allow anything to reduce complexity.

**Comment by coreyhulen** [comment]
It does seem a tad complex, but I'm OK with it for now.  We can revisit in 3.1.

**Comment by hmhealey** [comment]
Yeah, I agree that we should revisit it, but we'll do it in 3.1 since we at least need something here for 3.0

**Pull request merged**
