### PR TITLE
Update prod-ubuntu.md

### PR DESCRIPTION
**Pull request by sexybern**
I wasted time setting up an x86-based VM.

### CODE REVIEW

**Comment by jwilander** [comment]
Thanks @sexybern for the pull request! 

Before we can review, we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**

This is a standard procedure for many open source projects. Your form should be processed within 24 hours and reviewers for your pull request will be able to proceed. 

Please let us know if you have any questions. 

We are very happy to have you join our growing community!

**Comment by it33** [comment]
Hi @sexybern, thanks again for the fix! Sorry, reviewer found a [typo in the username entered in your CLA](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true). Could we have your help filling it out one more time so we can get this change in?

**Comment by jwilander** [comment]
+1

**Comment by coreyhulen** [comment]
@sexybern can you rebase please so we can accept the change.  Thanks.

**Comment by sexybern** [comment]
I don't know how to do that, I'm afraid.

**Comment by crspeller** [comment]
@sexybern No worries I did a manual merge for you. Thanks for the PR!

**Pull request merged**
