### PR TITLE
Check auth_service when constructing messages

### PR DESCRIPTION
**Pull request by gramakri**
Check auth_service value to be gitlab when constructing the UI messages. This is useful when you have multiple oauth providers.

### CODE REVIEW

**Comment by gramakri** [comment]
To give some context, we have a couple of oauth providers at - https://github.com/cloudron-io/mattermost/tree/cloudron . We want to get those patches upstream (@tronical is going to try to make the oauth providers more generic so we don't have all this copy/pasting everywhere for each provider).

**Comment by coreyhulen** [comment]
Thanks @gramakri for the pull request! 

Per the [**CONTRIBUTING.md**](https://github.com/mattermost/platform/blob/master/CONTRIBUTING.md#submitting-a-pull-request) file displayed when you created this pull request, we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**

This is a standard procedure for many open source projects. Your form should be processed within 24 hours and reviewers for your pull request will be able to proceed. 

Please let us know if you have any questions. 

We are very happy to have you join our growing community!

**Comment by gramakri** [comment]
@coreyhulen I have signed the agreement

**Comment by jwilander** [comment]
+1

**Comment by hmhealey** [comment]
+1

**Pull request merged**
