### PR TITLE
PLT-886 Add additional max file size checks

### PR DESCRIPTION
**Pull request by hmhealey**

### CODE REVIEW

**Comment by coreyhulen** [comment]
@hmhealey some eslint errors

ESLint...
cd web/react && node_modules/eslint/bin/eslint.js --ext ".jsx" --ignore-pattern node_modules --quiet .
/go/src/github.com/mattermost/platform/web/react/components/user_settings/user_settings_general.jsx
  165:2  error  More than 1 blank lines not allowed  no-multiple-empty-lines
✖ 1 problem (1 error, 0 warnings)
make: *** [build-client] Error 1
make: *** [build-container] Error 2
The command "make dist-travis" exited with 2.

**Comment by coreyhulen** [comment]
+1 besides the eslint error

**Comment by crspeller** [comment]
+1 except ESLint error.

**Comment by hmhealey** [comment]
Fixed the extra blank line

**Pull request merged**
