### PR TITLE
Mm 1550 Mentions are no longer removed from auto complete once used

### PR DESCRIPTION
**Pull request by nickago**

### CODE REVIEW

**Comment by hmhealey** [comment]
Looks good

**Comment by crspeller** [comment]
In post_store.jsx The emitMentionDataChange function needs to be updated to not take the excludeList. Also post_store.jsx does not meet style guide requirements.

**Comment by crspeller** [comment]
Also is there any reason for the `updateMentionTab` code path to even exist anymore?

**Comment by nickago** [comment]
Yes, the `updateMentionTab` function is what hides and shows the post list, as well as what allows it to have its auto-correct feature of shrinking the list based on what has already been typed.

**Comment by nickago** [comment]
Alright, the file has been updated to fit the style guide

**Comment by crspeller** [comment]
Looks good! I missed the emitMentionDataChange. Confusing how the event changes name.

**Pull request merged**
