### PR TITLE
PLT-2586 Fixed problem when New Messages indicator is triggered by own message

### PR DESCRIPTION
**Pull request by Compaurum**

### CODE REVIEW

**Comment by jwilander** [comment]
Hi @Compaurum, thanks for the PR! Looks like your build is failing due to a ESLint error:

```
/var/lib/jenkins/jobs/mattermost-platform-pr/workspace/src/github.com/mattermost/platform/webapp/components/posts_view.jsx
  396:23  error  '&&' should be placed at the end of the line  operator-linebreak

✖ 1 problem (1 error, 0 warnings)
```

To check for ESLint errors before submitting you can [follow these short steps](http://docs.mattermost.com/developer/style-guide.html?highlight=eslint#javascript)

**Comment by Compaurum** [comment]
I couldn't download [The ESLint configuration file](http://docs.mattermost.com/web/react/.eslintrc). I Have error 403 Forbidden

**Comment by jwilander** [comment]
Sorry, that documentation is old and needs to be updated. You can find it here https://github.com/mattermost/platform/blob/master/webapp/.eslintrc.json

**Comment by jwilander** [comment]
+1

**Comment by it33** [comment]
btw, just fixed the link in docs: https://github.com/mattermost/docs/commit/38557d2f0b256003a0447d635b2cf27f6f7605e1

**Comment by coreyhulen** [comment]
+1

**Pull request merged**
