### PR TITLE
PLT-5670 Correct typo in app/email.go

### PR DESCRIPTION
**Pull request by R-Wang97**
#### Summary
Corrected typos of `signup` in `app/email.go`. The localization file was also updated to correct the typo.

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-5670
https://github.com/mattermost/platform/issues/5557

#### Checklist
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/platform/blob/master/i18n/en.json) and [.../webapp/i18n/en.json](https://github.com/mattermost/platform/tree/master/webapp/i18n/en.json)) updates

### CODE REVIEW

**Comment by jasonblais** [comment]
@R-Wang97 Thank you for the contribution!

ust so you know, there may be a delay in merging this PR as we are locking down feature and improvement contributions for the v3.7 release, per our [release process](https://docs.mattermost.com/process/release-process.html). 

Once this PR is ready to merge, we'll add the `Ready to Merge` label and merge into `master` after we branch `release-3.7` on March 6th.

**Comment by jwilander** [comment]
Deferring to @enahum because I think is an unnecessary change that's just going to cause more work for the translators

**Comment by enahum** [comment]
@R-Wang97 this one needs a rebase

**Comment by R-Wang97** [comment]
@enahum Will do.

**Pull request merged**
