### PR TITLE
Fix coding style: replace tab with whitespace in mattermost config

### PR DESCRIPTION
**Pull request by chengweiv5**
Signed-off-by: Chengwei Yang <yangchengwei@qiyi.com>

### CODE REVIEW

**Comment by crspeller** [comment]
Thanks @chengweiv5! Please help complete our CLA so this pull request can be reviewed? http://www.mattermost.org/mattermost-contributor-agreement/

**Comment by jwilander** [comment]
Hi @chengweiv5 just a reminder, for when you get a chance, to please sign the CLA @crspeller posted above. Thanks!

**Comment by chengweiv5** [comment]
sorry for late, singed.

**Comment by jwilander** [comment]
Thanks! +1

**Comment by crspeller** [comment]
+1

**Pull request merged**
