### PR TITLE
PLT-3269 Moved formatting toggle behind EnableDeveloper setting

### PR DESCRIPTION
**Pull request by hmhealey**

### CODE REVIEW

**Comment by enahum** [comment]
+1

**Comment by crspeller** [comment]
@hmhealey I don't think we should be hiding stuff behind that testing flag. It was only really meant for the loadtest slash commands. Can we have a separate flag for enable/disable formatting?

**Comment by hmhealey** [comment]
@crspeller I wanted to avoid adding a new flag since I've only left the ability to disable formatting in there for exceptional cases, and I was going to remove it once we go some time without the formatter failing horribly. Unfortunately, a new one was found today so it's not getting taken out any time soon.

Would it be better if it was behind the Enable Developer Mode flag instead since it's mostly a flag for me to debug regex issues?

**Comment by crspeller** [comment]
@hmhealey Whatever you think is best. Just know that this flag can't be enabled on pre-release because we don't want the loadtest commands to be enabled there.

**Comment by hmhealey** [comment]
@crspeller Oh that's a very good point. I forgot the loadtest commands did more than just post the test files so no sane production server would turn them on. I'll move it to be behind the Developer Mode setting then. That way it's still very out of the way, but doesn't open up the server to even more issues should it be needed

**Comment by jwilander** [comment]
@crspeller can you confirm you're OK with the change and merge?

**Comment by crspeller** [comment]
+1

**Pull request merged**
