### PR TITLE
PLT-1465 Added Password Requirements

### PR DESCRIPTION
**Pull request by DavidLu1997**
Passwords are now validated server and client side using requirements set by the system admin.

Possible requirements:

Minimum length (default 5)
- At least one lowercase letter
- At least one uppercase letter
- At least one number
- At least one symbol (almost all symbols supported)

This should work for everywhere that a password change is required, existing passwords are untouched.

All password settings are EE only, the system defaults to enforcing a minimum length of 5 without a license.

### CODE REVIEW

**Comment by enahum** [comment]
needs rebase

**Comment by DavidLu1997** [comment]
@enahum rebased

**Comment by esethna** [comment]
@DavidLu1997 sorry I can't review this because the spinmint doesn't have EE enabled. Are you able to provide an EE testing environment?

**Comment by DavidLu1997** [comment]
@esethna I'll ping @jwilander Monday :)

**Comment by jwilander** [comment]
Standing one up now

**Comment by esethna** [comment]
Thanks @DavidLu1997, tested this on a spinmint Joram put up, found some issues if you could take a look at them:

1. When you have a lower case number and a symbol selected, the example symbols don't appear in the error preview:
image

2. I think we discussed changing the name of the "Login" system console tab > "Passwords" and putting the password requirement settings in there above the other settings?
image
3. Can we change the error message for this to "Minimum password length must be a whole number less than or equal to 64."
image
4. Also, the error message preview shouldn't preview if the input for the minimum password length is invalid (over limit)
image
5. Minimum password length should not allow you to enter letters, numbers with decimals, or symbols. It should prompt the invalid input error message: "Minimum password length must be a whole number less than or equal to 64."
image
image
image
6. Is there bug in localization in the error message preview? I changed to Portuguese to get this screenshot:
image
7. "at least one lowercase letter" does not show up in the error message on the account creation page, even if it is selected in the system console.
image

**Comment by DavidLu1997** [comment]
@esethna here are my replies:
1. Will fix
2. Will fix, was not sure if Password was suppose to be it's own section
3. Will change
4. Will change
5. Will change
6. Not a bug, just that the translation doesn't exist, the localization server will take care of it once it is submitted
7. This is intentional, I believe somewhere the spec said to tell the user what they are missing. In this case, as the user already has a lowercase letter in there, the error message only prompts them to enter 7 characters. I can change it to always displaying the whole error message.

**Comment by esethna** [comment]
@DavidLu1997 thanks! Regarding (7), sorry I can't find this in the spec, but I think we want to always show everything the password requires to make things "obvious".

**Comment by DavidLu1997** [comment]
@esethna will change :)

**Comment by DavidLu1997** [comment]
Closing to resubmit because of bad rebase

**Pull request closed without merging**
