### PR TITLE
mm-1732 - Decreasing font size for footer in emails

### PR DESCRIPTION
**Pull request by asaadmahmoodspin**
Hey guys have a look. This is for 0.6.0.

### CODE REVIEW

**Comment by rgarmsen2295** [comment]
+1

**Comment by nickago** [comment]
Looks all good to me, merge when ready

**Comment by asaadmahmoodspin** [comment]
Also updated the logos in the same PR guys instead of submitting a new one, please have a look at this too.

**Comment by nickago** [comment]
New logo looks crisp. All good to merge

**Comment by rgarmsen2295** [comment]
Yup looks good, +1

**Pull request merged**
