### PR TITLE
Add Floating Timestamp to Right Hand Side on Mobile #5163

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
Added floating timestamp to right hand side on mobile.

This PR only satifies (hopefully) as per stated in the reference issue but it might also be better to add date separator in the RHS comment and only reflect time (hh:mm) per RHS comment. This might be for another issue if you will.

Thanks. 

#### Ticket Link
Github issue: #5163 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x ] Has UI changes

### CODE REVIEW

**Comment by jasonblais** [comment]
@doosp please help with first test review?

Big thanks @saturninoabril!

**Comment by saturninoabril** [comment]
Sorry to hear build timeout. Let me know if there's something I could do.

**Comment by grundleborg** [comment]
Closing and reopening to try and get Jenkins to re-run the build.

**Comment by doosp** [comment]
@saturninoabril 

Really appreciate your interest in our product and contribution.

I just tested the update and I was able to see the floating timestamp on the RHW whenever I scroll up and down. Great work! 👍 

image

I tested following steps as well:
-Tested using short and long reply list.
-Tested using MM app. (Android)
-Tested using Firefox and Chrome

@jasonblais would you please review when you have a chance?

Thank you.

**Comment by grundleborg** [comment]
Many thanks for the contribution @saturninoabril

**Comment by saturninoabril** [comment]
You're welcome. thanks for accepting the PR.

**Pull request merged**
