### PR TITLE
Adding switch to teams in admin console

### PR DESCRIPTION
**Pull request by coreyhulen**

### CODE REVIEW

**Comment by crspeller** [comment]
Maybe we should have this team selection list as it's own component. We will probably want it in multiple places.

**Comment by coreyhulen** [comment]
Would be nice, but it's really a ComponentPart.  It renders multiple <li> tags at the root and behaves a little differently depending on it's usage/location.  It would involve a larger refactor of the dropdown component to make this work.

**Comment by coreyhulen** [comment]
@crspeller see comment above.

**Comment by jwilander** [comment]
+1

**Comment by crspeller** [comment]
+1

**Pull request merged**
