### PR TITLE
PLT-3384 Improve the "Verify Email" email

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
Improve the "Verify Email" according to spec

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-3384

#### Checklist
- [x] Includes text changes and localization files updated

### CODE REVIEW

**Comment by jwilander** [comment]
+1

**Comment by jwilander** [comment]
@enahum you might need to set up a spinmint with SMTP settings set for a PM to test on

**Comment by enahum** [comment]
Setting up a spinmint for this

**Comment by enahum** [comment]
you might get the emails in the Spam folder cause of the SMTP used in this server, MTA is marked as blacklisted (I think)

**Comment by jasonblais** [comment]
Tested:
 - fresh account creation when **System Console > Security > Sign Up > Require Email Verification** set to `true`
 - email address change from Account Settings when **Require Email Verification** set to `true`
 - email address change from Account Settings when **Require Email Verification** set to `false`

All good, except the title line has a link, which I think should be removed according to the [ticket](
https://mattermost.atlassian.net/browse/PLT-3384)


image

**Comment by enahum** [comment]
@jasonblais I believe the link is auto generated by gmail, can you try and read the mail with any other email client?

**Comment by jasonblais** [comment]
+1

Verified on another email client, and the hyperlink is not in the title.

**Comment by coreyhulen** [comment]
+1

**Pull request merged**
