### PR TITLE
make push-test.mattermost.com default to https

### PR DESCRIPTION
**Pull request by aus**
#### Summary
This changes the default Push Notification Server to use HTTPS instead of HTTP.  

#### Ticket Link
No ticket created for "small improvement" per Contribution Guidelines.

#### Checklist
- [x] Has UI changes
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/platform/blob/master/i18n/en.json) and [.../webapp/i18n/en.json](https://github.com/mattermost/platform/tree/master/webapp/i18n/en.json)) updates

### CODE REVIEW

**Comment by aus** [comment]
any updates on this?

**Comment by it33** [comment]
Hi @aus, 

First, hugely appreciate your PR and intention to improve the product, 

Really sorry about the long delay, and to say we're not able to take it--and it's 100% our fault, not yours. There was a lot of internal discussion and a few things need to change on our end to make sure this unfortunately situation doesn't happen in future. 

1. We've updated the FAQ around TPNS and HPNS

https://docs.mattermost.com/overview/faq.html#are-push-notifications-free

Hope this explains the difference between the two. Would highly appreciate any feedback you have. You've put a significant effort in here. 

2. We need to be more clear about the definition of "small improvement" in our contributor guidelines. 

I've opened a ticket here: https://github.com/mattermost/docs/issues/1028

High level, a small improvement shouldn't affect product documentation and this changes does significantly. 

3. A PR that's not accepted is a big failure for us, and we need to figure out how to change to avoid this in future

I've opened a ticket to do mini-post-mortems on this in future: https://github.com/mattermost/docs/issues/1029

You're clearly someone who's thoughtful and I hope this experience doesn't deter you from finding other ways to work with the Mattermost open source project. 

PS: I noticed from GitHub profile you're based in Texas? 

While I realize it's a massive state, we're thinking of doing a Mattermost User Group meeting May 5 in Austin at [Bangers](https://www.bangersaustin.com/). 

If you're around in person, would love to say "hello" in person.

**Comment by aus** [comment]
Thanks for the update @it33. I'm impressed by the response here and it's great that you guys care so much about PRs.

However, I am disappointed that this PR is being rejected. I understand that Mattermost, Inc. is a business and offering push-proxy encryption exclusively to Enterprise subscribers adds a value incentive. I also realize that hosting a public push-proxy server is ultimately a cost to you. But, encryption is free. It's a shame that we (as an industry) have trended towards offering encryption as a paid premium. Additionally, this response comes at pretty bad timing in light of the [recent legislation](https://www.washingtonpost.com/news/the-switch/wp/2017/03/23/congress-is-poised-to-undo-landmark-rules-covering-your-internet-privacy/) to kill online privacy rules. I had hoped Mattermost, Inc. might be the exception. Perhaps, it should now be emphasized that TPNS is for **testing** only.

But enough complaining. The solution for users is to either subscribe or self-host. And I'm thankful that you guys provide both as an option.

Regarding mattermost/docs#1028 and mattermost/docs#1029, the response here is really great. I hope more OSS projects follow suit. I don't feel "burned" as a contributor. 

And unfortunately, I won't be at the User Group. Texas is indeed a massive state.

**Comment by it33** [comment]
Thanks @aus appreciate your feedback, and self-host is definitely available. 

Yes, I'm also totally disappointed too about not being able to accept the PR. 

100% our fault for not having better guidelines and per the tickets you mentioned, I asking people's help to fix that soon.
 
If you don't have one yet, I'd love to get you a [Mattermost Mug](http://forum.mattermost.org/t/limited-edition-mattermost-mugs/143) if we could find a [Help Wanted ticket](https://github.com/mattermost/platform/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20%5BHelp%20Wanted%5D) that you'd find interesting. 

Thank you again for putting in all the effort this PR. I hope despite this set back you'll continue to be engaged with the project. 

There are great things to come and we'll get there sooner with your help.

**Pull request closed without merging**
