### PR TITLE
MM-756 Don't mark channels as unread after user joined/left messages

### PR DESCRIPTION
**Pull request by hmhealey**
Adds a separate post type for join/leave messages so that they can get special handling and changes it so that channel's aren't flagged as unread when those messages are automatically posted.

### CODE REVIEW

**Comment by coreyhulen** [comment]
It might be a problem with travis-ci, but it say's this pull request does not compile.

**Comment by crspeller** [comment]
This is a lot of little changes and it introduces something that you have to think about every time you use the create a post function. If you where to put a flag in model.Post. Something like IsJoinedLeftMessage. Then you could set that once and check it once instead of passing a flag everywhere.

**Comment by hmhealey** [comment]
After a brief discussion with Chris, I went back and redid the patch to use a separate post type instead of adding a parameter to CreatePost (and by extension the Save method in the store).

**Comment by coreyhulen** [comment]
nice, I like this solution.

**Comment by crspeller** [comment]
Looks good. Will merge after code freeze is over.

**Pull request merged**
