### PR TITLE
fixed copy-paste error in confirmation message

### PR DESCRIPTION
**Pull request by joernhees**
deleting user asked if you're sure that all specified teams will be deleted...

### CODE REVIEW

**Comment by joernhees** [comment]
Nah, i don't feel like it... not a lawyer and don't want to invest the time to understand a legal doc, especially not for this... also this seems somewhat backwards to the "easy contribution" ideas of open source, this already is MIT license, so IMO any changes by default should be as well, it's obvious.

just handle it as django:
> Every contributor of non-trivial amounts of code (more than just a line or two) to Django should sign such a document.

so: take it as is or leave the error in there forever

**Comment by jasonblais** [comment]
Thanks @joernhees,

and thank you for contribution! Appreciate you putting the effort to understand our code base and submitting a pull request to fix an issue.

Signing the [Contributor License Agreement](https://www.mattermost.org/mattermost-contributor-agreement/) (CLA) is common for many other open source projects and is meant to protect both you as the contributor and Mattermost as the company.

The agreement is a document that states you are entitled to contribute the pull request to Mattermost. It's not a transfer of copyright ownership, this simply is a license agreement for contributions. As a result, should there be any kind of legal issue in the future, the form on the file confirms that you were permitted to make this contribution (without conflicts with your employer, for instance).

You also do not change your rights to use your own contributions for any other purpose.

**Comment by lindy65** [comment]
Hi @joernhees,

Thank you for contribution!

[Our CLA doc](https://www.mattermost.org/mattermost-contributor-agreement/) incorrectly referenced Django's contributor license agreement which doesn't require a CLA for one or two-line changes.  We apologise if this led you to believe that signing of our CLA was not required. 

We appreciate the effort you have taken to understand our code base and submit a pull request.  We want to merge it into our repository but are not able to without a signed CLA.

If we were to accept pull requests to our code base without a signed CLA from a contributor, we may face a future legal issue where we cannot show that they were permitted to make the contribution without, say, conflicts with their employer.

We would really appreciate your signing the CLA.  The document simply states that you are entitled to contribute the pull request to Mattermost.  It’s not a transfer of copyright ownership but only a license agreement for contributions.

In order to eliminate any future confusion, we have removed reference to Django’s contributor licence agreement from our CLA doc. 

We trust that our apology and explanation will enable us to work together in future and that our efforts to update and clarify our documentation will prevent future misunderstandings.  We’re really excited to have you join our growing Mattermost community!

**Comment by joernhees** [comment]
Sorry, this is too small a change for me to go through your CLA.

Consider changing your rules (to something similar as django) or just make the change yourselves. The latter might of course lead you into exactly the legal situation that you're trying to protect yourselves from ;).

**Comment by it33** [comment]
Hi @joernhees,

Thanks for your note, the extended discussion, the PR and the issues you've filed with us already--your time and effort in Mattermost is improving the software for thousands of people around the world. 

It seems you're active on many open source projects and we'd love to have your continued help on Mattermost. I believe we all want the same thing. 

Would it be correct to say that the issue to be addressed is not the CLA itself, which more and more OSS projects are using, and which hundreds of Mattermost contributors have already completed, but the time and effort to complete a CLA for the first time, relative to the size of the PR?

If so, I think that view is completely reasonable.

I guess the question is whether a) a CLA would prevent you from ever contributing to OSS projects using them, or b) if it's a matter of when, not if you'll complete a CLA for the first time. 

I'd emphasize it's completely your personal choice, and without the CLA we'd be just as thankful for your issue reports, feedback and time invested. 

In my mind, the purpose of a CLA is to be open, specific and unambiguous about mutual expectations for a contribution. While that requires effort to learn, in my mind, it's like running a "Hello World" program--it takes time to set up, the output isn't interesting, but once we've done it we're ready to do so much more. 

If you do decide to join the Mattermost approved contributor list by [completing the CLA](https://www.mattermost.org/mattermost-contributor-agreement/), we'd love to have you participating at the next level in our community. 

You're clearly smart and thoughtful, and I think the project would be better with you than without you. 

We talked a lot about this PR, just like [we talked a lot about your CLI ticket](https://github.com/mattermost/platform/issues/5257). I'm wondering if it would be faster to speak some time. 

If you'd like to discuss more, you can join our community server at https://pre-release.mattermost.com/ and you can reach me at it33, and we can jump on a [video call potentially](https://docs.mattermost.com/deployment/webrtc.html). 

Again, your decision completely. 

If you decide for any reason a CLA isn't for you, and to close this PR, we 100% respect your choice.

**Comment by joernhees** [comment]
https://www.youtube.com/watch?v=IFe9wiDfb0E

Just cause many projects use CLAs, doesn't make it "the right thing to do", as i hope you can see with the little paradox i created. For community contribution impact of CLAs just google for "linus torvalds cla"...

I have agreed to CLAs, DCOs and NDAs in the past, but never enjoyed it and never done so for a single line or a typo (and i still don't see that as necessary). Also, in all those cases it was either directly in the process or by signing a real legal document with a real (verified) signature. Contrary to that, your external form approach seems a bit weird to me:

- All the information you're collecting can be googled.
- No one hinders you to change the CLA without notice.
- If anyone later wanted to cause legal issues for your project based on their contribution, they could probably just say they never filled out that form themselves or it existed in another way when they did.

I know that your intention behind this is to reduce the overhead for paperwork to a minimum, but it's a pretty effective way to annoy all contributors with a legal insecurity, which is the very thing you're trying to avoid.

Hence, one simple idea: remove the form and put your CLA into this git repo, put a ref to it in your CONTRIBUTING.md and say that by making a PR developers agree to your CLA. That way all of that is at least check-able (by a nowadays weak SHA1). It's still way more difficult to object than your current CLA form approach. Additionally, unless you put something really weird in your CLA no one will bother to object.

Let's make software, not jump through legal hoops...

**Comment by it33** [comment]
Hi @joernhees 

Appreciate the feedback and the suggestion. I can completely see your point of view. I agree the world isn't perfect here and I agree there's many approaches. 

I also agree our focus should be creating software, and again I want to recognize the many ways you've been helping move the product forward with issue reports and thoughtful, researched conversations like we're having now. 

For this ticket specifically, [the CLA requirement is documented clearly in our contributor's guide,](https://docs.mattermost.com/developer/contribution-guide.html#preparing-a-pull-request) as a requirement for submitting a PR. We're having this conversation because our automation found the PR didn't pass the contribution checklist. 

I'd propose, as a matter of procedure, we get to a decision on this PR first. 

I'd ask your help to decide whether you want to: 

a) complete the checklist for the PR as documented in our contribution guide at the time you made the PR. or

b) decide not to complete the checklist as it was stated when you created the PR, and close this PR

If you'd like to submit [a feature proposal](https://www.mattermost.org/feature-ideas/) for how to improve the CLA process to be discussed and upvoted by community, we'd highly welcome your contribution there as well--over a hundred feature proposals in that system have been implemented. 

We have [systems for building Mattermost software](https://about.mattermost.com/help/) and while we welcome your participation in those systems, we also need your help to sequence and organize the ways you influence the project.

**Comment by joernhees** [comment]
... https://about.gitlab.com/2017/11/01/gitlab-switches-to-dco-license/

**Pull request closed without merging**
