### PR TITLE
PLT-2524 Moving javascript driver back to platform

### PR DESCRIPTION
**Pull request by crspeller**
#### Summary
Moves the javascript driver back to platform repository. (there will be a jenkins job to keep the driver repo updated.)

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields.]
- [x] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [x] Has driver changes that have been merged and package.json updated
- [ ] Has enterprise changes (please link)
- [ ] Has UI changes
- [ ] Includes text changes and localization files updated
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by hmhealey** [comment]
You checked in your webapp/data directory by mistake. Otherwise, it looks good

**Comment by crspeller** [comment]
Added it to the ignore file.

**Comment by hmhealey** [comment]
+1

**Comment by enahum** [comment]
build is failing

Also should I close this PR https://github.com/mattermost/mattermost-driver-javascript/pull/19 and wait until this is merged?

other than that +1

**Pull request merged**
