### PR TITLE
PLT-3145 Custom Emojis

### PR DESCRIPTION
**Pull request by hmhealey**

### CODE REVIEW

**Comment by jwilander** [comment]
```
1) Emoticons handleEmoticons:
     TypeError: Cannot read property 'has' of undefined
      at o (.tmp/mocha-webpack/6edeca9cd29de9a526891e6df58fb253/6edeca9cd29de9a526891e6df58fb253-output.js:2:5005)
      at .tmp/mocha-webpack/6edeca9cd29de9a526891e6df58fb253/6edeca9cd29de9a526891e6df58fb253-output.js:2:5253
      at String.replace (native)
      at Object.o [as handleEmoticons] (.tmp/mocha-webpack/6edeca9cd29de9a526891e6df58fb253/6edeca9cd29de9a526891e6df58fb253-output.js:2:5198)
      at Context.<anonymous> (.tmp/mocha-webpack/6edeca9cd29de9a526891e6df58fb253/6edeca9cd29de9a526891e6df58fb253-output.js:2:3711)
```

Looks like a client unit test is failing

**Comment by hmhealey** [comment]
Ready for final review now that the conflicts with the routes are fixed

**Comment by crspeller** [comment]
+1

**Comment by jwilander** [comment]
+1

**Comment by lfbrock** [comment]
Posted feedback in [UX room](https://pre-release.mattermost.com/core/pl/6xcc7j5mo7y75jg1btcdeqynpy), will discuss with Harrison when he is back.

screenshot 2016-06-27 10 00 09

**Comment by hmhealey** [comment]
Marking for re-review since some stuff changed to fix the stuff mentioned by @lfbrock. Also, there's now an enterprise PR to go along with this: https://github.com/mattermost/enterprise/pull/38

**Comment by jwilander** [comment]
+1

**Comment by enahum** [comment]
+1

**Pull request merged**
