### PR TITLE
PLT-6127/PLT-6135/PLT-6137 Added EmojiPickerOverlay component to better position emoji picker

### PR DESCRIPTION
**Pull request by hmhealey**
- The emoji picker should now open on screen. It will appear above the [...] menu if there's enough space, then below if there's enough space, then to the left if neither of those are possible
- I removed the react-outside-event package since it now uses react-bootstrap Overlays or react-overlays RootCloseWrapper (which are part of react-bootstrap)
- I cleaned up the CSS to remove some unused and duplicate classes

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-6127
https://mattermost.atlassian.net/browse/PLT-6135
https://mattermost.atlassian.net/browse/PLT-6137

#### Checklist
- Has UI changes

### CODE REVIEW

**Comment by lindalumitchell** [comment]
@jasonblais @hmhealey Testing this PR, and I'm seeing a couple issues:

1. Clicking an emoji reaction from the picker closes the picker but emoji reaction does not display on message
  - Adding a reaction by typing +:+1: adds the reaction as expected
  - No errors appear in console
2. Still seeing one case of positioning issue (https://mattermost.atlassian.net/browse/PLT-6137):
  - Click reply arrow on a message that has no replies yet
  - Click emoji picker on reply box in RHS (not reaction)
  - Emoji picker opens upward, with top of picker off-scene
  - All other cases of different picker positions that I tested worked as expected

**Comment by hmhealey** [comment]
@lindalumitchell I fixed the first issue, but I spent some time on the second issue, and couldn't get it fixed. I filed a separate ticket for it, and I think we can take this change without it since it's better than the current behaviour in the same case.

**Comment by hmhealey** [comment]
Also, I'm moving this to 3.11 since it may end up messing something else up in the UI

**Comment by jasonblais** [comment]
@lindalumitchell please help with testing next week when you have the chance?

**Comment by lindalumitchell** [comment]
@jasonblais sorry for the delay; finally tested this one. The issue #1 I had mentioned above is fixed. As Harrison noted, the other issue (positioning of the emoji picker) will be addressed in a separate ticket. No new issues found.

**Comment by jasonblais** [comment]
Thanks Linda! 

@hmhealey needs a rebase, but otherwise ready for dev review

**Pull request merged**
