### PR TITLE
PLT-2994 Added @all

### PR DESCRIPTION
**Pull request by DavidLu1997**
Added @all to work just like @channel

Added help text to show that it can be used in Town Square to notify everyone

(my Town Square is called What?)
at all

### CODE REVIEW

**Comment by jwilander** [comment]
I think you need to enable this on the server in `sendNotifications()` in `api/post.go`. Should be some lines to uncomment

**Comment by DavidLu1997** [comment]
Uncommented

**Comment by hmhealey** [comment]
+1 Looks good

**Comment by jwilander** [comment]
+1

**Pull request merged**
