### PR TITLE
Scrolling fixes

### PR DESCRIPTION
**Pull request by samogot**
* fix bad jumps on free scroll when somebody posts a new message (and old one disappears at top)
* add jump for compensation of resize on closing RHS (not only opening)
* fix scroll blinking on opening/closing RHS (caused by delay before resize compensation)

### CODE REVIEW

**Comment by jasonblais** [comment]
Overall looks great, really like the changes. One note:

Suppose a channel has lots of messages, including long messages that take more than one linespace, and I open/close the RHS repeatedly.

Current behaviour on `master`: Center channel tends to remain at the same location
New behaviour with proposed changes: Center channel tends to move upward

Can we have your @samogot help making an adjustment so that the center channel doesn't tend to move upward in this instance?

**Comment by samogot** [comment]
@jasonblais is there repro steps? there is behavior that move upward once - on first open/close of RHS, but this behavior is the same on master and does not affect multiple opening/closing of RHS without scrolling in between, so I don't think this is what you are saying

**Comment by jasonblais** [comment]
@samogot Thank you for your quick response. I found repro steps, but I was able to reproduce it on `master` too. I'm wondering, however, should `add jump for compensation of resize on closing RHS (not only opening)` fix the upward movement I've experienced, when closing the RHS? For repro steps:

1. Log into http://i-84eb0f2b.spinmint.com:8065/pr3200 (username test@test.com, password = passwd)
2. In Town Square, find a post whose length wraps more than one line
3. For the post you identified on step 2: a) open the right hand side clicking on the reply button, b) close the right hand side
4. Repeat 3a) and 3b) a few times

**Observed**: Center channel tends to scroll upward each time you open or close the right hand side, and the scrolling position has significantly changed after repeating this a few times.
**Expected**: `add jump for compensation of resize on closing RHS (not only opening)` fix allows me to close the RHS without a change in the scrolling position of the center channel.

Let me know if my expectation above is correct?

**Comment by samogot** [comment]
@jasonblais ok, I can reproduce it. an important repro step for me was to reduce the window size that it wasn't maximized. I'll look at this bug

**Comment by samogot** [comment]
@jasonblais done. this was bug related to rounding, witch repro only in case when (window height % 3 == 0)

**Comment by jasonblais** [comment]
@samogot We're having trouble setting up test servers for some PRs in github. After we're set for the next release, I'll take a closer look at this PR. 

Really appreciate your work on this and love the changes, will be a great usability improvement. Just want to give it another test before code review.

**Comment by jasonblais** [comment]
Thanks @samogot, the changes look great!

**Comment by jwilander** [comment]
+1

**Comment by enahum** [comment]
+1

**Pull request merged**
