### PR TITLE
PLT-3965 Highlight comment bar for comments considered mentions

### PR DESCRIPTION
**Pull request by jwilander**
#### Summary
Updates the logic for when to highlight a comment as a mention and the UI for displaying it.

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-3965

#### Checklist
- [x] Has UI changes

### CODE REVIEW

**Comment by jasonblais** [comment]
1) We found an issue where all replies are highlighted for a user if the setting is enabled.

The screenshot is from a user `lindsay` containing all messages in the channel. Even though `lindsay` has not posted any messages, replies are highlighted.

It reproduces if the setting is turned to `Trigger notifications on messages in reply threads that I start or participate in`

image

2) @asaadmahmood will also look into updating the colour of the reply bar so that it's a little more prominent. 

Note: Given its the long weekend, we can take this feature for v3.5 instead. No worries on getting this merged for v3.4

**Comment by jwilander** [comment]
Fixed 1), please wait until build is complete before re-toggling the test server.

**Comment by it33** [comment]
Just tested, hit a couple of issues: 

1) Reply bar coloring doesn't show until there's a page refresh

image

2) Highlighting seems to randomly break on IE

**Comment by DavidLu1997** [comment]
+1 for code after rebase

**Comment by jwilander** [comment]
1) Isn't really within scope of this ticket but I can update it to be applied immediately
2) I haven't tried it on IE so I'll take a look

**Comment by jwilander** [comment]
Actually I find myself running out of time for my scheduled tickets this sprint. This was an improvement rush ticket that wasn't even originally in my sprint and I don't have time right now to fix all the issues with this feature. Propose filing bugs for issues unrelated to this improvement and I can take a look at them in a future sprint.

**Comment by jasonblais** [comment]
+1, 

tested as a group in UX meeting with
 - Mac/Windows
 - various browsers
 - standard/compact view
 - mobile and desktop

all works without issues. 

@it33 The setting was changed without requiring a refresh, we weren't able to reproduce the issue you reported.

**Comment by enahum** [comment]
+1

**Comment by coreyhulen** [comment]
+1

**Pull request merged**
