### PR TITLE
PLT-138 Better parsing of the site's title when viewing a channel

### PR DESCRIPTION
**Pull request by rgarmsen2295**
The title would sometimes be parsed incorrectly, specifically when the team name included a hyphen.  The format is now simply "[Active Channel] - [Team Name] [Site Name]".

### CODE REVIEW

**Comment by jwilander** [comment]
I think there are more places where we pass switchChannel the teammate name, can you grep the code and remove those to?

**Comment by rgarmsen2295** [comment]
Erg, thought I got em all but it looks like there's one more in `more_direct_channels`; I had to rollback some changes at one point and must have missed that on my second pass through.  I'll take it out when I can, thanks for catching that, I shouldn't have missed it.

**Comment by rgarmsen2295** [comment]
Ok removed the remaining reference to teammate name being passed to switch channel, please re-review when possible @jwilander thanks!

**Comment by jwilander** [comment]
+1

**Pull request merged**
