### PR TITLE
Multiple UI improvements

### PR DESCRIPTION
**Pull request by asaadmahmoodspin**
- Removing fonts from non app pages.
- Fixing access history modal.
- Fixing text on the full width setting.
- Fixing themes being unclickable

### CODE REVIEW

**Comment by jwilander** [comment]
I just checked and it looks like those three strings you fixed are missing from the `webapp/i1n/en.json` file. Can you add them there quickly?

**Comment by asaadmahmoodspin** [comment]
Done.

**Comment by jwilander** [comment]
Thanks! +1

**Comment by crspeller** [comment]
+1

**Pull request merged**
