### PR TITLE
[PLT-4643] Don't show empheral messages on sidebar when it is reopened.

### PR DESCRIPTION
**Pull request by kulak-at**
#### Summary
When user reopens the sidebar with thread, he will no longer see the ephemeral system messages from before. This fix, although very small, seems to fix all the scenarios.

#### Ticket Link
https://github.com/mattermost/platform/issues/6202
https://mattermost.atlassian.net/browse/PLT-4643

#### Checklist
- [x] Has UI changes

### CODE REVIEW

**Comment by jasonblais** [comment]
Thanks for the contribution! 

Our review process is a little delayed given the upcoming release. We'll have PM review completed by the end of this week.

**Comment by jasonblais** [comment]
Thanks @kulak-at once more!

It appears that slash commands are partially broken on `master` and most of them don't work. This is not related to your changes as I can reproduce it on `master`. I created two related tickets
 - https://mattermost.atlassian.net/browse/PLT-6573
 - https://mattermost.atlassian.net/browse/PLT-6574

Since they don't work, I can't properly test this PR quite yet. 

We'll triage the tickets and investigate the cause. Let us know if you'd be interested taking a look?

**Comment by jasonblais** [comment]
I'll also apply an `Awaiting PR` label until a PR that fixes the slash commands is merged to `master`

**Comment by kulak-at** [comment]
@jasonblais Sure. I can take care of these two as well :)

**Comment by jasonblais** [comment]
Yay, awesome! It looks like a lot of the built-in slash commands don't work, so I suspect there's a single issue that's affecting them.

**Comment by jasonblais** [comment]
@kulak-at Looks like the JavaScript errors no longer reproduce on `master`. 

Can you help rebase your branch so it pulls the latest changes, and I'll give this one another try?

**Comment by kulak-at** [comment]
@jasonblais Rebased :)

**Pull request merged**
