### PR TITLE
PLT-1908 Add a warning when demoting yourself from System Administrator from the team Manage Members menu

### PR DESCRIPTION
**Pull request by ttyniwa**
Add a warning when demoting yourself from System Administrator from the team Manage Members menu.
Not included tests.

### CODE REVIEW

**Comment by enahum** [comment]
hi @ttyniwa can you please remove the strings from the es.json file? the process for translations needs to have those missing.

thanks.

**Comment by ttyniwa** [comment]
@enahum OK, I copied the same text.

**Comment by enahum** [comment]
+1

**Comment by jwilander** [comment]
+1

**Pull request merged**
