### PR TITLE
PLT-4606: Date separator in RHS

### LINKED ISSUE #5291: [Help Wanted] [PLT-4606] Add date separators to the right hand side to prevent dates overlapping the '...' menu on mobile right hand sidebar
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-4606)

Add date separators to the right hand side (like in the center channel).

image

The first date separator should appear below the channel name given at the top of right hand sidebar. Other date separators would appear if the date changes in the thread.

This prevents issues where the date can overlap with the '...' menu on mobile right hand sidebar (see below).

image

### PR DESCRIPTION
**Pull request by mikaoelitiana**
#### Summary
Use date separator in right hand sidebar like in main posts

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-4606

#### Checklist
- [x] Has UI changes

fixes #5291

### CODE REVIEW

**Comment by mikaoelitiana** [comment]
In replacement of #5362

**Comment by jasonblais** [comment]
Thanks @mikaoelitiana! 

@lindalumitchell Can you give this a test similar to what you did here: https://github.com/mattermost/platform/pull/5362

Please check the posts on RHS have a hover effect as described here: https://github.com/mattermost/platform/pull/5362#issuecomment-282217715

**Comment by lindalumitchell** [comment]
@jason @mikaoelitiana - looks great! I verified RHS date separator hover effect on desktop view of:

1. Reply thread, when message follows the date separator
  a. Can't test on a reply that precedes date separator until tomorrow, when tomorrow's date separator will be there
2. Mentions, preceding and following date separator
3. Flagged, preceding and following
4. Search results, preceding and following

There isn't hover shading of the messages on mobile view, so I verified that it looks like the screenshot in the other PR for all the above cases (and didn't have any unexpected effect).

Do we want to wait until tomorrow to verify 1a above? Or should the other cases be enough to verify that that case will behave as expected as well?

Attaching a couple screenshots for reference.

rhs-date-hover-mentions
rhs-date-hover-searchresults
rhs-date-hover-flagged

**Comment by jasonblais** [comment]
Thanks @lindalumitchell! Given the PR matches #5362 and just fixed the hover effect, 1a should work.

@asaadmahmood can you help approve (or request changes) on the CSS? This is a follow-up from your previous comment here: https://github.com/mattermost/platform/pull/5362#issuecomment-282217715

**Comment by jasonblais** [comment]
@asaadmahmood Can you help review the CSS for this PR when you get the chance?

**Comment by grundleborg** [comment]
Looks great. Many thanks for the PR @mikaoelitiana

**Comment by jasonblais** [comment]
Thanks @mikaoelitiana! Really glad to get this PR in. Solves lots of spacing issues on the right-hand side 👍

**Comment by mikaoelitiana** [comment]
You are all welcome!!

**Pull request merged**
