### PR TITLE
PLT-3192 EE: Restricted site name to 30 characters

### PR DESCRIPTION
**Pull request by DavidLu1997**
#### Summary
Restricts custom site name for EE to 30 characters

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-3192

#### Checklist
- [ ] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [ ] Has driver changes that have been merged and package.json updated
- [x] Has enterprise changes
- [x] Has UI changes
- [x] Includes text changes and localization files updated
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by enahum** [comment]
@DavidLu1997 there's no validation client side? like in the System Console

**Comment by DavidLu1997** [comment]
@enahum added `maxLength` to `TextSetting` as a prop

**Comment by jwilander** [comment]
+1

**Comment by enahum** [comment]
+1

**Comment by esethna** [comment]
+1, thanks. Verified that you cannot enter more than 30 characters in the input box and that the site name updates properly on the site home page

**Pull request merged**
