### PR TITLE
PLT-395: Add syntax highlighting to Markdown code blocks

### PR DESCRIPTION
**Pull request by florianorben**
Fixes #1216

### CODE REVIEW

**Comment by it33** [comment]
Thanks @florianorben!

**Comment by crspeller** [comment]
@florianorben Needs a rebase. But looks good!

**Comment by florianorben** [comment]
@crspeller Rebase done!

**Comment by crspeller** [comment]
Looks good to me! +1

**Comment by hmhealey** [comment]
Looks good

**Pull request merged**
