### PR TITLE
Fixed endless loading in join team from invite when logged in

### PR DESCRIPTION
**Pull request by DavidLu1997**
#### Summary
Fixed by redirecting to Town Square instead of team name

#### Ticket Link
PLT-3846

### CODE REVIEW

**Comment by crspeller** [comment]
+1

**Comment by enahum** [comment]
+1

**Comment by jwilander** [comment]
+1

**Comment by jasonblais** [comment]
+1

No issues found during testing when creating teams, joining teams, re-joining teams.

**Pull request merged**
