### PR TITLE
PLT-5263 Dragging and dropping a file in the left-hand sidebar does no action

### PR DESCRIPTION
**Pull request by pan-feng**
#### Summary
Dragging and dropping a file in the left-hand sidebar

#### Ticket Link
Issue #5263 

#### Checklist
- [x] Has UI changes

### CODE REVIEW

**Comment by pan-feng** [comment]
#5263

**Comment by jasonblais** [comment]
FYI for anyone following the thread, since I messaged @pan-feng directly on https://pre-release.mattermost.com/core -- an item is queued for our next UX meeting to confirm the expected behaviour when dragging and dropping a file to the LHS

**Comment by jasonblais** [comment]
Hey @pan-feng, this has been discussed and the conclusion is that instead of allowing the user to drag and drop a file to the left-hand sidebar, no action should be taken.

This is because if the user has the right-hand sidebar open, there are three sections for the Mattermost page:
 1. channel sidebar on the left
 2. message pane in the center
 3. comment thread on the right

If you drag and drop a file in one of these sections, the file should then upload in the corresponding area.

For this particular case, if the user uploaded a file on the left pane, they would probably expect the file to upload to the particular channel they dragged it to (similar to how File Explorer works). However, this is a bit more complex, which is why the proposed change is:

**when a user drags a file onto the left-hand sidebar, do no action*

@pan-feng would you be able to help update the PR according to the new proposal? Sorry for the change in behaviour, I'm really sorry we changed the design after you submitted a pull request for it.

**Comment by pan-feng** [comment]
@jasonblais  I updated, when a user drags a file onto the left-hand sidebar, do no action !

**Comment by jasonblais** [comment]
Sweet, thanks @pan-feng!! 

@lindalu please help with review?

**Comment by jasonblais** [comment]
Thanks also for updating the issue summary, looks excellent! Nice and clean 👍 

image

**Comment by jasonblais** [comment]
@lindalumitchell, can you help with initial testing on this PR later this week?

**Comment by lindalumitchell** [comment]
@jasonblais will do.

**Comment by lindalumitchell** [comment]
@jasonblais I tested on that spinmint (OSX Chrome), and am seeing unexpected behavior:

1. Dragging image file to LHS produces javascript error: `Uncaught TypeError: Cannot read property 'focus' of undefined` (see more info in screenshot)
2. Dragging image file to center displays image in browser. On clicking Back in the browser, I see the file has been uploaded to a new message (but not yet posted)
3. Dragging image file to RHS behaves like center: displays image in browser, uploads file to message but does not post it

dragdrop-lhs-ctr-rhs

**Comment by jasonblais** [comment]
Thanks @lindalumitchell for testing!

@pan-feng can you help take a look at the feedback above?

1. Should not produce a JavaScript error
2 + 3. Should upload a file instead of opening it in the browser

Thanks once more for submitting this improvement, it's getting close!

**Comment by jasonblais** [comment]
@pan-feng Just so you know, there may be a delay in merging this PR as we are locking down feature and improvement contributions for the v3.7 release, per our [release process](https://docs.mattermost.com/process/release-process.html). This PR can be merged into `master` after we branch `release-3.7` on March 6th. 

Really appreciate all your contributions to the Mattermost code base!

**Comment by jasonblais** [comment]
Hey @pan-feng, how are you? Hope all is well,

I noticed there hasn't been activity for a couple of weeks - just wanted to touch base and see if there's anything I can help clarify on the feedback provided above.

Would really love to see this improvement in the product, and work with you to add it in.

**Comment by jasonblais** [comment]
We haven't received an update so we'll assume that the PR is no longer been worked on. Closing the PR so someone else in the community can help take a look.

If you're still interested helping with this improvement, let us know! Would love to work with you on this. Also, feel free to re-submit the PR anytime.

Many thanks for all your help thus far: https://github.com/mattermost/platform/pulls?q=is%3Apr+author%3Apan-feng+is%3Aclosed

**Pull request closed without merging**
