### PR TITLE
Use consistent Display Name sorting code throughout the webapp #5159

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
Use consistent Display Name sorting code throughout the webapp

Implemented:
- sortTeamsByDisplayName() for sorting teams; and
- sortChannelsByDisplayName() for sorting channels.

#### Ticket Link
GitHub issue: #5159 

#### Checklist
- [x ] Has UI changes (maybe, but only touches the underlying functions in sorting)

### CODE REVIEW

**Comment by jasonblais** [comment]
Closed and re-opened the pull request to re-trigger build and hopefully resolve test server build issues.

@doosp will help with initial tests, let me know if you have any questions!

**Comment by doosp** [comment]
@saturninoabril 

Good to see you again! :)

Really appreciate your contribution.

I tested switching, deleting, and adding various the team and channels in webapp and couldn't find any error or inconsistent ordering.

Awesome work!

I tested following:
-English and Korean channel and team name (create, move, and delete)
-Search and jump.

@jasonblais or @esethna  Would you please review when you have a chance? Thanks.

Note:
I couldn't find the admin console when I logged in as admin through webapp. So I couldn't test the admin console page. Let me know whether admin console is disabled in webapp intentionally or there's a specific way to access it.

**Comment by jasonblais** [comment]
ah, sorry about that @doosp, the admin console is synonym to System Console. 

Thanks for testing! I'll give this a try

**Comment by jasonblais** [comment]
Unfortunately there was an underlying issue with `master` where the team list in the System Console is off-positioned. 

image

@saturninoabril can you help rebase your branch, so that https://github.com/mattermost/platform/pull/5225 gets incorporated? I can re-test it afterwards.

Otherwise all seems to be working as expected. Thanks @saturninoabril! :)

image

**Comment by saturninoabril** [comment]
@doosp @jasonblais done rebase. thank you!

**Comment by jasonblais** [comment]
Thanks @saturninoabril!

Tested there too and works. Queueing next for dev review

image

**Pull request merged**
