### PR TITLE
PLT-5208: Trigger Invitation by pressing Enter

### PR DESCRIPTION
**Pull request by senk**
#### Summary
Allow pressing Enter-Key to send invitation
#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-5208

### CODE REVIEW

**Comment by jasonblais** [comment]
@doosp can you help doing the first test review?

**Comment by senk** [comment]
simplified it.

**Comment by doosp** [comment]
@senk 

Thanks for your contribution!

I tested and couldn't find any issue.

@jasonblais  @esethna would you please review and let me know if there's any other test I might have missed? Thanks!

Test Summary:
1. type in one email account and press enter. Correctly got 1 invitation.
2. type in more than 2 email accounts and press enter. Correctly got the right the number of invitations.
3. all the invitation email works.
4. reviewed the code and not sure about the correct naming so I will leave it to the dev.

**Comment by jasonblais** [comment]
Thanks @senk and @doh5! Linda is helping test this PR as well

**Comment by lindalu** [comment]
Yep, I've done some testing on this as well! 

Summary: Enter works as expected for the described scenario (enter email address, press Enter), but does not send the invite if Enter is pressed while focus is in either of the name fields.

As noted in the Jira ticket, this may be expected, but we should confirm. @jasonblais, is that a question for you?

Testing details: 

Action happens on pressing Enter with focus in email field:

1. Enter email address
2. Press Enter (no name entered)
3. Sends invitation as expected

1. Enter email address
2. Enter first and last names
3. Click to add another invite
4. Enter 2nd email address
5. Press Enter
6. Sends invitations as expected

1. Enter first and last names
2. Leave email address blank
3. Put focus in email field
4. Press Enter
5. Displays error message as expected

No action on pressing Enter with focus in a name field: 

1. Enter email address
2. Enter first and last names
3. Press Enter
4. No action

Note: Same behavior (no action) if only first name or only last name is entered, and Enter is pressed with focus in either name field.

1. Enter first and last names
2. Leave email address blank
3. Leave focus in a name field
4. Press Enter
5. No action (no error message displayed)

**Comment by jasonblais** [comment]
Thanks @doosp and @lindalu for your help with testing this out!

@senk would you be interested adding the functionality in where hitting Enter when in the modal always performs the same action as the "Send Invitations" button?

I think the only addition would be sending invitations even when the focus is on the first or last names.

Really sorry that I missed your original note in the Jira ticket. I didn't realize it until @lindalu mentioned it to me.

**Comment by senk** [comment]
@jasonblais Added functionality to First and Last-Name fields as well.
@lindalu @doosp can you test it again?

**Comment by doh5** [comment]
@senk 

Thanks a lot for looking into this!

I just repeated all the previous test cases and all seemed to work as expected including the name focus. 👍

**Pull request merged**
