### PR TITLE
MM-1671 Added support for enter key triggering submission and changed Close to Cancel

### PR DESCRIPTION
**Pull request by nickago**

### CODE REVIEW

**Comment by crspeller** [comment]
Will changing the button type to submit and making it a form work here? That's what I did in the other places I enabled enter key. Much cleaner then setting up handlers. Not sure if that will work for modals or not.

**Comment by nickago** [comment]
I have re-implemented the PR as @crspeller suggested, plus broken it up easier for review

**Comment by crspeller** [comment]
Looks good.

**Comment by hmhealey** [comment]
+1

**Pull request merged**
