### PR TITLE
Rebase #655; Set default Content-Type to application/json

### PR DESCRIPTION
**Pull request by Trozz**
Rebase of PR #655

### CODE REVIEW

**Comment by it33** [comment]
Hi @Trozz, thanks for the PR! 

Could we ask your help to complete a [CLA](http://www.mattermost.org/mattermost-contributor-agreement/) to add you to the contributors list so the team can review and accept the merge?

**Comment by it33** [comment]
Whoops, wrong button, re-opening.

**Comment by Trozz** [comment]
ill sign the CLA now, but it appears that @jwilander has rebased his one already :+1:

**Comment by it33** [comment]
Thanks @Trozz, appreciate your help nonetheless, thanks for joining the contributors list. 

There's lots of ways to get involved in Mattermost: http://www.mattermost.org/

Also, we literally just updated our [code contribution guidelines last night](https://github.com/mattermost/platform/blob/master/doc/developer/code-contribution.md). Which includes links to lists of tickets accepting pull requests. 

Any ideas or questions would be highly welcome on http://forum.mattermost.org as well. 

Thanks for joining the community!

**Pull request closed without merging**
