### PR TITLE
Clarify help text for available lanuages in localization_settings.jsx

### PR DESCRIPTION
**Pull request by esethna**

### CODE REVIEW

**Comment by enahum** [comment]
+1

**Comment by jwilander** [comment]
+1. @esethna is this ready to merge? We normally only add `Needs PM Approval` label for new features

**Comment by esethna** [comment]
Thanks @jwilander, I think we decided that `Needs PM Approval` label should be applied to any PR's that have help text additions or changes as well. Asking @jasonblais to review.

**Comment by jasonblais** [comment]
@esethna Propose queueing text reviews in the PM channel first before submitting a PR, as PMs monitor the channel more frequently

**Pull request merged**
