### PR TITLE
Handle window resize in React way

### PR DESCRIPTION
**Pull request by apaatsio**
Use the React-way of handling resize events. Essentially store the window size in component state instead of doing some custom handling.

See http://facebook.github.io/react/tips/dom-event-listeners.html

### CODE REVIEW

**Comment by crspeller** [comment]
@apaatsio Looks cool but needs a rebase.

**Comment by apaatsio** [comment]
Current master is failing. I'm waiting for it to be ok before the rebase.

**Comment by hmhealey** [comment]
The build is fixed now so you should be safe to rebase

**Comment by coreyhulen** [comment]
awesome, thanks @apaatsio for the PR.  I've also created https://github.com/mattermost/platform/issues/1110 to track other places we need to fix.

**Comment by coreyhulen** [comment]
@apaatsio if you can rebase 1 more time I can merge this.

**Pull request merged**
