### PR TITLE
translations PR 20170116

### PR DESCRIPTION
**Pull request by enahum**
Ideally this PR should be review by community members for each language.

Note: In the event that you see an english translation instead of the desired language is because this PR was submitted before the translation was made on the Mattermost Translation Server and probably will be submitted for the next PR.

### CODE REVIEW

**Comment by cpanato** [comment]
did some fixes on the translation server for pt-br

**Comment by enahum** [comment]
@cpanato do I need to merge those changes to this PR or can they wait until next week's PR?

**Comment by cpanato** [comment]
@enahum I made the suggestions someone need to review that and then its able to merge

**Comment by jasonblais** [comment]
Hey @cpanato, since we're not closet to a release, I think it's okay to merge what we have here and include the updates from the Translation server in next Monday's PR. What do you think?

**Comment by wget** [comment]
@jasonblais LGTM, but I see there are a bunch of translations which have been removed for the API debug messages. Is it normal?

**Comment by jasonblais** [comment]
Hey @wget ,thanks for confirming.

These API debug messages were removed on purpose - they were already removed from `en.json` a couple of days ago via  https://github.com/mattermost/platform/pull/4931

**Comment by kaakaa** [comment]
`ja` looks good.

**Comment by cpanato** [comment]
@jasonblais agree

**Comment by enahum** [comment]
@jasonblais feel free to approve this at any time

**Pull request merged**
