### PR TITLE
added missing translations in pt

### PR DESCRIPTION
**Pull request by rodrigocorsi2**

### CODE REVIEW

**Comment by jwilander** [comment]
+1

**Comment by hmhealey** [comment]
+1

**Comment by hmhealey** [comment]
This needs a rebase

**Comment by rodrigocorsi2** [comment]
rebase is done

**Comment by crspeller** [comment]
@rodrigocorsi2 This needs a rebase again. Sorry.

**Comment by rodrigocorsi2** [comment]
@crspeller no problem, rebase is done

**Pull request merged**
