### PR TITLE
Trim callback urls for outgoing webhooks

### PR DESCRIPTION
**Pull request by npcode**
Adding traling whitespace is common mistake.

### CODE REVIEW

**Comment by jwilander** [comment]
+1

**Comment by npcode** [comment]
Okay @jwilander, I updated it as you said.

**Comment by crspeller** [comment]
@npcode You have an ESLint error. Suggest using the ES6 arrow function syntax instead.

**Comment by npcode** [comment]
@crspeller Thanks, I updated it again.

**Comment by hmhealey** [comment]
+1

**Pull request merged**
