### PR TITLE
Revert "MM-375 Adds text formatting features using a modified version…

### PR DESCRIPTION
**Pull request by crspeller**
Reverts mattermost/platform#360

Spec change.

### CODE REVIEW

**Comment by nii236** [comment]
Was was this reverted? Is formatting of posts no longer possible?

**Comment by crspeller** [comment]
@nii236 It was reverted because it was causing too many bugs. We have refactored some of the code involved and will hopefully be bringing markdown support soon.

**Comment by nii236** [comment]
Thanks for the info!

**Comment by leipert** [comment]
@crspeller /cc @rgarmsen2295 

Did you have a look at [markdown-it](https://github.com/markdown-it/markdown-it)?

It is a good alternative to marked, as you can easily extend (a lot of plugins available) or de-activate markdown features, you do or do not need. It also is just as fast as marked and complies with the [commonmark spec](http://commonmark.org/), which is a combined effort of a lot of people, especially John MacFarlane, the ~~guy~~ Berkeley Professor behind pandoc.

I am really eager to push mattermost in the "right" direction with support for markdown and commonmark through markdown-it. I would also love to help implementing this support if wanted.

**Comment by crspeller** [comment]
Hi @leipert 

We actually just implemented markdown support with this PR: https://github.com/mattermost/platform/pull/723

We would love your feedback on it. Especially if you think it can be improved with the libraries you mentioned. 

You can try it out using docker by running the command `docker run --name mattermost-dev -d --publish 8065:80 mattermost/platform:dev` which is a docker image created from the master branch which includes the markdown support. Or if you want to get started with development you can follow these instructions to get a development environment running: https://github.com/mattermost/platform/blob/master/doc/install/dev-setup.md

A better place to talk about this would be the PR above or our forums http://discourse.mattermost.org/ Look forward to getting your feedback!

**Pull request merged**
