### PR TITLE
PLT-4860 Make ProfilePopover into it's own component and use it consistently everywhere

### PR DESCRIPTION
**Pull request by grundleborg**
#### Summary
* Refactor ProfilePopover into it's own component, replacing all existing places where this functionality is provided.
* Disable the ProfilePopover for system messages and messages from web hooks.

#### Ticket Link

https://mattermost.atlassian.net/browse/PLT-4860

#### Checklist
- [x] Has UI changes

### CODE REVIEW

**Comment by yangchen1** [comment]
This looks good! There's a case where if you click on name first then click on the profile pic you'll get a weird overlap feel like it should just do nothing? Queueing for UX, will circle back.

image

**Comment by yangchen1** [comment]
@grundleborg we don't have to worry about the overlap for now. Just one thing: it seems like only the popup from the name has the video call option - the other one doesn't. See picture.

image
image

**Comment by yangchen1** [comment]
Deleted previous comment, that was on an erroneous server - everything looks good, just the popovers lost their fade out animation (regression from current). If we add that back in, then it's good to go.

**Comment by grundleborg** [comment]
Rebased. Haven't fixed the fade-out animation yet though.

**Comment by yangchen1** [comment]
+1 I'm going to approve this, we can merge this without the fade-out animation and figure it out later. I'm going to file a bug once it is merged.

**Comment by grundleborg** [comment]
Sounds good @yangchen1 . I've update the labels for dev review.

For dev reviewers: we want to get this in so it stops delaying other changes to the popovers. For general tidyup of this component's props and reduction of code duplication around the _instantiation_ of it, we should probably have a future APR ticket.

**Pull request merged**
