### PR TITLE
PLT-16 Add basic API doc.

### PR DESCRIPTION
**Pull request by jwilander**
Looking for feedback.

### CODE REVIEW

**Comment by crspeller** [comment]
@jwilander Needs rebase

**Comment by crspeller** [comment]
Should be named Overview.md so it works with the new generation system. Also a table of contents is not necessary because it will be generated. 
Other than that it looks good.

**Comment by jwilander** [comment]
Ready for re-review @crspeller

**Comment by crspeller** [comment]
+1

**Comment by hmhealey** [comment]
+1

**Pull request merged**
