### PR TITLE
PLT-93 Cleaning up client side configs

### PR DESCRIPTION
**Pull request by coreyhulen**
This is only addressing the client side of the config files.  I'll be submitting another PR that addresses the server side.

### CODE REVIEW

**Comment by hmhealey** [comment]
Looks good to me

**Comment by crspeller** [comment]
- Should all instances of ClientProps be changed to WebClientProps? So there is no confusion when we add props for other clients we build in the future?
- Should we have a mechanism for forcing the client to download a new config? If the admin changes stuff from the admin console it might take a while to propagate to clients.

**Comment by coreyhulen** [comment]
The props will be used by both web and mobile.  I've created a getClientProperties() web method for the latter.  When used in HtmlTemplatePage it's technically WebClientProps at that point, but in that case it's only rendered to the head.html via <script> tags.  In the future all clients will use the same props, but some may only apply to web or mobile.

I've added the config file last modified time to be part of the X-Version Header param.  This should force a page refresh if/when the config file is updated.

**Comment by crspeller** [comment]
Alright sounds good. Very happy this got cleaned up!

**Pull request merged**
