### PR TITLE
[PLT-6790] Fix multiple posts of same message when retry is clicked repeatedly while offline

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
Fix multiple posts of same message when retry is clicked repeatedly while offline

#### Ticket Link
Jira ticket: [PLT-6790](https://mattermost.atlassian.net/browse/PLT-6790)

### CODE REVIEW

**Comment by jwilander** [comment]
What's the root cause here? I'm not sure how checking if the WS is open is fixing anything

**Comment by esethna** [comment]
Adding @hmhealey to investigate further since Saturn is out today

**Comment by hmhealey** [comment]
I haven't been able to repro the issue myself to take a shot at debugging. Using Linda's repro steps locally, I have the loading spinner on the post for 30 seconds or so before it switches to show the `Retry - Cancel`, but clicking it repeatedly doesn't cause it to post once I reconnect the network.

And as Joram said, I'm not sure how this would fix the problem. The problem seems to be that it's queueing the post multiple times even though the PendingPostAction appears to prevent that

**Comment by jwilander** [comment]
Per @hmhealey's comment, closing this until we get better reproduction and an understanding of the cause

**Comment by saturninoabril** [comment]
@jwilander agree. that's just an initial attempt, re: checking WS open
@hmhealey I was not able to repro the problem on local. It's reproducible with remote server. I just posted the repro steps with screen recording in our channel.

**Pull request closed without merging**
