### PR TITLE
PLT-2937 Don't allow gitlab users to activate mfa

### PR DESCRIPTION
**Pull request by jwilander**

### CODE REVIEW

**Comment by crspeller** [comment]
What's the justification for this? Is it just that OAuth providers should implement MFA themselves?

**Comment by jwilander** [comment]
A couple things. First, it's a different flow for OAuth login right now and it doesn't support MFA currently. We could probably support it but there'd be some extra work involved. Second, the way OAuth is supposed to work is that whatever provider you're authenticating against should perform all the authentication so MFA should be implemented on their side. We don't necessarily need to be concrete on doing it this way but that's just how we're doing it right now.

**Comment by enahum** [comment]
+1

**Comment by coreyhulen** [comment]
+1

**Pull request merged**
