### PR TITLE
PLT-1319 Fixed direct channels not being visible when no actual channel exists

### PR DESCRIPTION
**Pull request by hmhealey**
I moved all the code for making direct channels visible when you receive a message to the server so that I could make the sidebar just be driven entirely off the preferences. It also gets rid of the weirdness which involved the client updating the PreferenceStore while it is updating in response to other changes.

### CODE REVIEW

**Comment by jwilander** [comment]
I feel like this is a pretty big change to fix a small bug, which is normally fine but I'm not sure it should go in so close to a release

**Comment by coreyhulen** [comment]
I'm not sure I follow the PR.  *any* unread direct message channel should be shown + anyone you have in your preferences list ??  Doesn't seem to hard, not sure why all the crazy post process for every DM is needed.

**Comment by hmhealey** [comment]
I'm fine with pushing it back until 1.4, but we were basically doing the same stuff on the client before as part of the sidebar code. When updating the sidebar's state, it would check for an unread direct channel and update the preferences on the server [here](https://github.com/mattermost/platform/blob/master/web/react/components/sidebar.jsx#L106-L109) which would in turn trigger another rerender of the client. This logic should belong to the server since there was some potential weirdness before if you had two tabs open since both would trigger the same preference update.

I went for the better long term solution with this instead of just making the sidebar check both preferences and the existing unread direct channels.

**Comment by crspeller** [comment]
+1

**Comment by jwilander** [comment]
+1

**Comment by jwilander** [comment]
@coreyhulen do you want a last look before this is merged?

**Comment by coreyhulen** [comment]
+1

**Pull request merged**
