### PR TITLE
Badge for all unread non-mention messages

### PR DESCRIPTION
**Pull request by samogot**
add second "light" badge for unread non-mention messages. it's style is clumsy a little :(
also it would be best if i made an option in user settings for this, but i am to lazy and have not experience in golang for server side modifications 
image

### CODE REVIEW

**Comment by lfbrock** [comment]
Thanks @samogot for the proposal,

There's not an existing [APR](http://docs.mattermost.com/process/accepting-pull-request.html) for this change and we're not clear how the community will react to it. 

Would you consider contributing a [feature idea](http://www.mattermost.org/feature-requests/) for this to be discussed and upvoted by the community so we can get more feedback on this approach?

**Comment by samogot** [comment]
Hi @lfbrock. I've created feature idea. https://mattermost.uservoice.com/forums/306457-general/suggestions/13740840-add-badge-for-all-unread-non-mention-messages
About long team names, that **lindsay** write me in mattermost
Now, after last commit, my feature looks like this

In case of long team name it would overlaps

But the same problem might appear even now (not such noticeable, but still)

_(screenshot from pre-release.mattermost.com)_
As this feature idea came from skype, I have looked, how it implemented there. In skype any names can not fill all width of sidebar. Also when badge is bigger then reserved space - it just overwrite channel name without extra ellipsis 

_(must be three dots instead of two)_
So the easiest way to implement it - add background under the badge

**Comment by it33** [comment]
Hi @samogot, 

First, huge thanks for all your efforts and contributions across the product, and your involvement in design discussions, 

It's difficult to open an APR on this because: 

1. It makes it difficult to identify users with long usernames in the left-hand sidebar, and it makes spoofing long usernames easier. 
2. There could be confusion between the mention and unread indicators, both in the left-handside bar and tabs

Regarding 1, in Mattermost 3.0 we're going to go back to our original limit of 22 characters in a hand-entered username, which will help a little. 

Regarding 2, this is too big a change to consider without having feedback from the community. It looks like [there are 9 votes for this feature so far](https://mattermost.uservoice.com/forums/306457-general/suggestions/13740840-add-badge-for-all-unread-non-mention-messages), and we can re-open the discussion after we see more support. 

Would you be open to posting some screenshots in the feature idea post to help draw attention? 

Closing this PR for now since we're not ready for an APR yet.

**Comment by samogot** [comment]
Hello @it33. This patch is not applicable to usernames, because all unread direct messages is already count as mentions. Spoofing on channels names? It is hard to imagine for me. I have a lot of users in my team who need this. We still in deciding stage, should we go to mattermost, or not. Is it ok if I ask my teammates, who need it to vote on feature? This can be activated by options and false by default if you want. Of course I can adapt my feature for every release in case of code change in our local version, but it is tediously.

**Comment by REDLINK** [comment]
We just deployed our Enterprise instance and the lack of this feature was the first thing our users criticized -.- @it33 what's the problem about adding this feature, disabling it by default and leaving the choice to your customers? Make it an experimental option like all the others.

**Comment by ylluminate** [comment]
Yes, this is very strange that this hasn't been added as per @REDLINK's suggestion - at the very least as an experimental feature.....

**Pull request closed without merging**
