### PR TITLE
MM-1183 Allow channel descriptions on 1-1 channels

### PR DESCRIPTION
**Pull request by nickago**
If one wants to add a description or notes on a 1-1 channel, the capability had now been added. I removed the popover on the username as it was very annoying for the user to try and click the arrow and have it covered up by the popover.

### CODE REVIEW

**Comment by rgarmsen2295** [comment]
Looks good, +1

**Comment by crspeller** [comment]
I think we should also enable the ability to edit the description from the channel introduction header. This is found in post_list.jsx:315

**Comment by nickago** [comment]
Alright, the requested link has been added

**Comment by crspeller** [comment]
Looks good.

**Comment by crspeller** [comment]
@rgarmsen2295 Confirm that you have looked at the changes and this can be merged.

**Comment by rgarmsen2295** [comment]
Yup looks good +1

**Pull request merged**
