### PR TITLE
PLT-1233: "Display Font" option in Account Settings > Display

### PR DESCRIPTION
**Pull request by florianorben**

### CODE REVIEW

**Comment by it33** [comment]
Wow, thank was really fast, thanks @florianorben!!

**Comment by florianorben** [comment]
:)

**Comment by jwilander** [comment]
+1, I think this is a speical case where direct DOM manipulation is OK and probably the right method

**Comment by jwilander** [comment]
Merger please resolve https://mattermost.atlassian.net/browse/PLT-1233

**Comment by crspeller** [comment]
@florianorben Can you let us know where you got these fonts before we merge this?

**Comment by jwilander** [comment]
@crspeller the ticket specifies using Google Fonts (which these are) and they are all open source https://www.google.com/fonts#AboutPlace:about

**Comment by florianorben** [comment]
@crspeller, @jwilander Is there something missing from me :)?

**Comment by jwilander** [comment]
Nope @florianorben, just waiting on a seconder :)

**Comment by crspeller** [comment]
+1

**Comment by florianorben** [comment]
Ah ok :)
Thought so because it still had the "Awaiting Submitter Response" label :)

**Pull request merged**
