### PR TITLE
display loading screen when changing team

### LINKED ISSUE #4997: [Help Wanted] Add a loading screen while switching teams via the teams sidebar
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5140)

The same loading screen that appears when you open up a team, should appear while switching to another team as the center channel and left-hand sidebar loads.

See attached example

image

### PR DESCRIPTION
**Pull request by mikaoelitiana**
#### Summary
Display loading screen when switching to another team from sidebar button. 

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-5140

#### Checklist
- [x] Has UI changes

Fixes #4997

### CODE REVIEW

**Comment by jwilander** [comment]
Hi @mikaoelitiana, looks like you've got an ESLint error:
```
/var/lib/jenkins/jobs/mattermost-platform-pr/workspace/src/github.com/mattermost/platform/webapp/components/post_view/post_view_cache.jsx
  74:1  error  More than 1 blank line not allowed  no-multiple-empty-lines

✖ 1 problem (1 error, 0 warnings)
```

**Comment by mikaoelitiana** [comment]
@jwilander I will fix this

**Comment by jasonblais** [comment]
Thanks @mikaoelitiana, this is looking really great!

I tried testing with a lot of channels, users and some content on the Mattermost test instance. Team switching feels a lot smoother thanks to the loading screen.

This is a really useful feature, thanks @mikaoelitiana for it! Queuing for dev review.

PS: We might need to do one more iteration on the channel left hand sidebar in a separate PR. It looks like direct message channels update earlier than they should after switching teams, causing potentially confusing user experience if the loading of the channel sidebar takes a while. I'll test it more carefully on https://pre-release.mattermost.com after this PR is merged, and create a separate issue with more detailed repro steps if needed.

**Comment by mikaoelitiana** [comment]
thanks for reviewing it @jasonblais

**Comment by jwilander** [comment]
Good job @mikaoelitiana !

**Comment by mikaoelitiana** [comment]
Thanks @jwilander

**Pull request merged**
