### PR TITLE
PLT-4276 handle file upload progress in post and comment

### PR DESCRIPTION
**Pull request by tudorgergely**
#### Summary

Tracks progress of file uploads and adds a progress circle to file uploads. 
Will start from 0% and increase up to 100%
Uses svg for drawing the circle
- Track progress using superagent request
- Map tracked progress to methods in create_post and file_upload
- Modify style according to theme
- Move constants to constants.jsx
- Parse the number given as percentage to int
#### Ticket Link

https://mattermost.atlassian.net/browse/PLT-4276
#### Checklist
- [ x] Has UI changes

### CODE REVIEW

**Comment by jasonblais** [comment]
Highly appreciated @tudorgergely! Thanks for working on this improvement!

Queuing for [Stage 1: PM Review](https://github.com/mattermost/platform/blob/master/CONTRIBUTING.md)

**Comment by hmhealey** [comment]
Closing and reopening to trigger Jenkins

**Comment by jasonblais** [comment]
Sorry @tudorgergely for the delay in review,

We're having some trouble firing the test server to test the pull request. Once resolved, we'll test it right away to get the review process going.

Thanks again for the pull request, highly appreciated!

**Comment by jasonblais** [comment]
Tested and queued for UX meeting on Monday to review

**Comment by jasonblais** [comment]
Many thanks @tudorgergely, looking really great! Tested as a team and we're excited for this improvement!

Few pieces of feedback:

1) The original design also had an animation that went around the circle as the progress increased from 0% to 100% (one full circle would be completed at 100%). Would this be easy to add?

Sorry if it wasn't clear from the specification.

image

2) Given [attachments are not uploaded in the order they're added](https://mattermost.atlassian.net/browse/PLT-2407), it leads to a potentially confusing use case described as follows:

 a) in this screenshot, the second file is uploading faster

image

 b) once the upload for the second file is complete, it appears the first file completed its upload and the second file 'restarted' at 50% (see screenshot). 

image

However, what happens is that the second file now appears first in the list since its upload was completed first.

To reduce confusion, we were wondering if we could add the display name of the file already when the upload begins, which you should be able to grab from the server side. That way it's more obvious which files are still being uploaded.

3) Once the uploading reaches 100%, it "hangs" there for 1-2 seconds making it look like the uploading freezes for a moment. This is because after the upload is completed, it grabs the file from the server (always being that way, not caused by your PR). 

One improvement we've been thinking about is stopping the counter at 98%, then have it jump to 100% right before the upload is finished and the file type (or image thumbnail) appears.

If you'd have better ideas, let us know.

--

Note: Please let us know if you feel any of the above are beyond the scope of the pull request. These were issues we noticed while testing, but apart from 1) have always been lingering issues. They just appear more prominent with the new file upload progress.

**Comment by tudorgergely** [comment]
Sure, I can work on the changes you presented. Should I do another pull request for the name or is this one fine?

**Comment by jasonblais** [comment]
Thanks @tudorgergely! Submitting the changes directly in this pull request are perfectly fine.

**Comment by jasonblais** [comment]
Hey @tudorgergely, just checking if you need any help or further information on the above changes?

Thanks again for working on this improvement!

**Comment by tudorgergely** [comment]
Hi, I am working today on this. Sorry for the delay :)

**Comment by jasonblais** [comment]
Not a problem at all, just wanted to touch base :)

**Comment by jasonblais** [comment]
Hey @tudorgergely, just touching base to see how things are going.

I'm quite excited to try out the latest changes.  :) 

This could be a fantastic improvement that many have been hoping for

**Comment by tudorgergely** [comment]
Finally managed to finish this :)

**Comment by jasonblais** [comment]
Thanks @tudorgergely for this! Looking great!

Minor nits:
1) For the upload bar, it looks like 0% starts almost full, so it appears it's "almost done" after a user has uploaded a file. 

Wondering if it would be easy to change so that 0% starts the progress bar from the start, then carries a full circle to 100%?

image
image

Otherwise the progress bar is fantastic! Excellent work!

2) I'm wondering if you had a chance to [look at my third note above](https://github.com/mattermost/platform/pull/4271#issuecomment-256169239), which is stopping the counter at 98%, then have it jump to 100% right before the upload is finished and the file type (or image thumbnail) appears?

3) I seem to get JavaScript errors on the console when uploading an image. Seems that the property `'percent' of undefined(…)` cannot be properly read

image

**Comment by jasonblais** [comment]
Another team member found one more issue, can you help take a look?

Just wanted to share his excitement for this feature as well! It's working quite well! :) 

4. Dragging and dropping a file causes a JavaScript errors
 a. open the file upload dialog (for instance, by clicking the paper clip icon on the message box)
 b. from the file upload dialog, drag and drop a file onto the center pane
 
Observed: Instead of uploading a file, Mattermost downloads it and gives an error `There appears to be a problem with your internet connection.` Also attached are the corresponding JavaScript console errors

image

**Comment by tudorgergely** [comment]
Hi, I will take a look over those errors and see why they happen.

Thanks for pointing them out!

**Comment by jasonblais** [comment]
Sounds great, thanks @tudorgergely!

**Comment by yangchen1** [comment]
Hey @tudorgergely, how's this PR going? Is there anything you need help with? :)

**Comment by esethna** [comment]
Hi @tudorgergely, looks like there is a build failure that is stopping the test server from firing. When you get a chance can you take a look at what might be causing the issue?

**Comment by jasonblais** [comment]
Hi @tudorgergely, let me know if you need any help with resolving the build errors?

Would love to give this another try!

**Comment by tudorgergely** [comment]
Hi, I could use some help fixing the build failure errors. Sorry for the delayed response

**Comment by hmhealey** [comment]
It just looks like you have some stuff that doesn't match the style guide that's causing it to fail. If you click on Details next to the build status at the bottom of the PR, click Console Output in Jenkins, and then scroll down near the bottom, you'll see the following:
```
npm run check

> mattermost-webapp@0.0.1 check /home/ubuntu/workspace/mattermost-platform-pr/src/github.com/mattermost/platform/webapp
> eslint --ext ".jsx" --ignore-pattern node_modules --quiet .


/home/ubuntu/workspace/mattermost-platform-pr/src/github.com/mattermost/platform/webapp/components/create_post.jsx
  569:29  error  Expected indentation of 24 space characters but found 28                       react/jsx-indent
  571:33  error  Expected indentation of 28 space characters but found 32                       react/jsx-indent-props
  572:33  error  Expected indentation of 28 space characters but found 32                       react/jsx-indent-props
  573:33  error  Expected indentation of 28 space characters but found 32                       react/jsx-indent-props
  574:33  error  Expected indentation of 28 space characters but found 32                       react/jsx-indent-props
  575:33  error  Expected indentation of 28 space characters but found 32                       react/jsx-indent-props
  576:33  error  Expected indentation of 28 space characters but found 32                       react/jsx-indent-props
  577:33  error  Expected indentation of 28 space characters but found 32                       react/jsx-indent-props
  578:33  error  Expected indentation of 28 space characters but found 32                       react/jsx-indent-props
  579:33  error  Expected indentation of 28 space characters but found 32                       react/jsx-indent-props
  580:29  error  The closing bracket must be aligned with the opening tag (expected column 25)  react/jsx-closing-bracket-location

/home/ubuntu/workspace/mattermost-platform-pr/src/github.com/mattermost/platform/webapp/components/file_preview.jsx
  65:13  error  Expected dot to be on same line as object          dot-location
  66:17  error  Split 'let' declarations into multiple statements  one-var

/home/ubuntu/workspace/mattermost-platform-pr/src/github.com/mattermost/platform/webapp/components/file_upload_progress.jsx
  68:54  error  Unexpected mix of '/' and '*'  no-mixed-operators
  68:60  error  Unexpected mix of '/' and '*'  no-mixed-operators

✖ 15 problems (15 errors, 0 warnings)
```

**Comment by tudorgergely** [comment]
Should be fine now

**Comment by jasonblais** [comment]
Thanks @tudorgergely! This is looking great!

Our UI designer is also taking a look to ensure all UX guidelines are followed - he might submit a small PR against your branch or post here if he has any changes he'd like to propose.

After that, I'll queue it for one more UX team review, likely for this Friday. 

We're getting really close here! Wonderful work :)

**Comment by jasonblais** [comment]
Quick update: Created a ticket for @asaadmahmood to review the UI: https://mattermost.atlassian.net/browse/PLT-5272

**Comment by jasonblais** [comment]
hey @tudorgergely ,

Really big thank you for your help contributing to the progress bar for file uploads. It's almost there!
Wondering if you'd like to discuss some of the last changes we're considering for the PR in our [Mattermost Contributors community site](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676)? 

Once you have signed in, you can direct message me at `@jason`.

The last changes aren't anything major and mostly minor UI tweaks, but I think it would be easier to have a short conversation and share a few screenshots on Mattermost than in GitHub.

**Comment by tudorgergely** [comment]
@jasonblais I already had an account on the pre-release chat. I replied to your question, let's continue the conversation there! Thanks for the opportunity! :+1:

**Comment by jasonblais** [comment]
Tested on Windows 10, Chrome at various screen sizes + iOS Safari browser.

This is starting to look fantastic! Great work @tudorgergely 👍 

Just a few minor nits:

### 1) During upload, the filename is cut off

See screenshot:
image

After uploading, the filename is fine and fits well.
image

One proposed fix is to wrap the filename over two lines, as otherwise the truncation would be too severe when it's uploading due to the `Uploading` text. See attached for a sample.

image

### 2) No border around the image/file thumbnail during upload

After the file has uploaded, the thumbnail (excluding file name) is surrounded by a border. It would be good to have this also while the file is uploading.

Observed:
image

Expected:
image

### 3a) No filename for images

Looks like some image files don't have the name -- perhaps because it doesn't fit on the screen?

image

Here's a link to sample image I used during testing: https://cloud.githubusercontent.com/assets/13119842/22955481/54d9e2a6-f2ea-11e6-9fc4-ad8d283b6863.png

### 3b) Filename shown briefly after upload

I noticed that for the particular images that don't have a visible filename (see 3a), the filename is briefly shown after the upload is complete, before rendering the thumbnail. Not sure what might be causing that.

image


### 4) The filenames overlap with the horizontal scrollbar on comment thread in right-hand sidebar, and in center channel on mobile:
image

**Comment by jasonblais** [comment]
@tudorgergely Just so you know, there may be a delay in merging this PR as we are locking down feature and improvement contributions for the v3.7 release, per our [release process](https://docs.mattermost.com/process/release-process.html). This PR can be merged into `master` after we branch `release-3.7` on March 6th. 

Also, please let me know if you need any clarifications on the recent post

**Comment by jasonblais** [comment]
Shared some feedback on the pre-release channel. We're really close, thanks @tudorgergely!

**Comment by jasonblais** [comment]
Hey @tudor.gergely, how are you?

Wondering if you had any questions on the notes I shared at pre-release? We're really close to merging this PR :)

**Comment by jasonblais** [comment]
Hey @tudorgergely, how are you? 

I realize I used the wrong username on the my previous post. Just wanted to check in and see if you had any questions on the notes I shared at pre-release?

**Comment by jwilander** [comment]
Closing due to inactivity

**Pull request closed without merging**
