### PR TITLE
PLT-3027 Added Shortcut to close RHS

### PR DESCRIPTION
**Pull request by DavidLu1997**
Escape now closes the RHS, whether it is a search result or a reply chain.

### CODE REVIEW

**Comment by DavidLu1997** [comment]
Changes made :)

**Comment by hmhealey** [comment]
+1

**Comment by enahum** [comment]
Testing this I found that if you have the RHS open and you then open the message editor and press ESC then it closes both, the RHS and the edit message modal. (Probably the same happens with Account Settings and other modals).

**Comment by coreyhulen** [comment]
@DavidLu1997 where are we at on this?

**Comment by DavidLu1997** [comment]
In the backlog, need to figure out how to fix it without conflicts.

**Comment by DavidLu1997** [comment]
Closed as won't do until requested.

**Pull request closed without merging**
