### PR TITLE
PLT-1049: Vine URLs should not generate preview links

### LINKED ISSUE #1280: Accepting Pull Requests: Vine URLs get treated as Youtube, and fail to preview
An example with: https://vine.co/v/eDeVgbFrt9L

screenshot 2015-11-03 13 55 18

### PR DESCRIPTION
**Pull request by florianorben**
I took a little different approach here - this PR will add the correct preview link for vine (instead of a youtube preview).

This also adds various integrations with other services like git/gist/wiki/soundcloud/flickr etc.

If a PR is needed that really *removes* vine previews just tell me, and I'll resubmit one :)

Closes #1280

### CODE REVIEW

**Comment by it33** [comment]
Wow!!!

**Comment by florianorben** [comment]
One question though... 

Currently fetching preview-images/texts/etc. is all done frontend-side via an ajax call (similar to the youtube integration). Probably it would be better to retrieve all of this data backend-side and stored within the actual post (probably for youtube aswell)?
This way there would be no need to re-fetch everything when one refreshes the page...

What do you think?

**Comment by jwilander** [comment]
I think it's fine for the client to fetch the data separately. The browser should be caching it all anyways so it shouldn't need to hit a remote server every time and I'd rather not let the `Post` model get too big on the server since it really should be relatively lightweight since it's a core model that will be accessed very often.

**Comment by florianorben** [comment]
Good point, then I'll leave it this way :)
Should probably move `web/react/providers.json` somewhere else, or is fine in that location?

**Comment by coreyhulen** [comment]
Maybe move providers into components for a future refactor.  We need to organize components better.  In the future I think react/components/posts would be a good spot for everything related to post rendering.

**Comment by florianorben** [comment]
Moved to components folder now.
Had to add an .eslintignore file for it (will from now on ignore any json files), otherwise eslint will throw a huge amount of errors

**Comment by coreyhulen** [comment]
Looks really cool. Can you add a unit test similar to the markdown ones? in textgeneration.go see var FUZZY_STRINGS_POSTS

**Comment by florianorben** [comment]
Yep, I'll submit one once ready

**Comment by florianorben** [comment]
@coreyhulen Test added!

+This will cause a merge conflict with #1351 since both modify textgeneration.go at the same location.
Just tell me if I should rebase one of both PRs once one is merged

**Comment by coreyhulen** [comment]
+1 looks good.  Please rebase

**Comment by florianorben** [comment]
Done.

**Comment by jwilander** [comment]
+1

**Pull request merged**
