### PR TITLE
Update nginx ssl-conf

### PR DESCRIPTION
**Pull request by kh0r**
Added ssl_session_cache to nginx conf sample to prevent crash when using safari.

### CODE REVIEW

**Comment by jwilander** [comment]
Thanks @kh0r for the pull request! 

Per the [**CONTRIBUTING.md**](https://github.com/mattermost/platform/blob/master/CONTRIBUTING.md#submitting-a-pull-request) file displayed when you created this pull request, we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**

This is a standard procedure for many open source projects. Your form should be processed within 24 hours and reviewers for your pull request will be able to proceed. 

Please let us know if you have any questions. 

We are very happy to have you join our growing community!

**Comment by crspeller** [comment]
@coreyhulen Please take a look.

**Comment by crspeller** [comment]
@kh0r Should we have `ssl_session_timeout 10m;` as well?

**Comment by kh0r** [comment]
Default cache time is 5 minutes. I don't think it's necessary. 
src: [nginx conf](http://nginx.org/en/docs/http/configuring_https_servers.html)

**Comment by crspeller** [comment]
OK Sounds good. +1

**Comment by coreyhulen** [comment]
+1

**Pull request merged**
