### PR TITLE
PLT-409 add warning to at rest salt gen

### PR DESCRIPTION
**Pull request by coreyhulen**

### CODE REVIEW

**Comment by jwilander** [comment]
+1

**Comment by crspeller** [comment]
@coreyhulen Which columns to we encrypt? What would happen if someone regenerated this on a production server?

**Comment by coreyhulen** [comment]
currently none. It was used in the kpi feature that was removed.

**Comment by crspeller** [comment]
Should this just be hidden from the admin console then? Do we plan on using this capability in the future?

**Comment by coreyhulen** [comment]
I don't want it hidden because it will still be in the config file and we want people to easily re-gen on machine setup.  I'm not 100% ready to remove since I think its a feature we'll use soon.

**Comment by crspeller** [comment]
+1

**Pull request merged**
