### PR TITLE
Multiple UI Improvements

### PR DESCRIPTION
**Pull request by asaadmahmoodspin**
Hey guys have a look. Changes include:
- Fixing bullets
- Improving icon in system console
- Removing user popover from mobile
- Working on font improvements (Removing Slabo font and adding different variants to the other fonts we've provided)

### CODE REVIEW

**Comment by jwilander** [comment]
Where did we get the new fonts and what is the license on them?

**Comment by asaadmahmoodspin** [comment]
Got them directly off google fonts.

**Comment by jwilander** [comment]
Perfect

**Comment by coreyhulen** [comment]
+1

**Pull request merged**
