### PR TITLE
PLT-4480 Update user search to match against username, full name, nickname and email

### PR DESCRIPTION
**Pull request by jwilander**
#### Summary
This will fix the search in the user list modals so that they don't just match for usernames.

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-4480

### CODE REVIEW

**Comment by jwilander** [comment]
Based off #4413

**Comment by jasonblais** [comment]
The current `master` branch only allows you to search users by start of usernames, which is a regression from what we had in 3.4. This PR adds some of that functionality back (e.g. searching by first and last name, nickname and email where applicable).

Looks like this PR could be a big change so close to code complete, but I don't fully understand the scope of the PR. Would defer to release managers to make the final call on whether to take this.

**Comment by coreyhulen** [comment]
@jwilander can you rebase to make it easier to review since 4413 is in.

**Comment by jwilander** [comment]
Yeah, I'm running some errands right now but I can do that tomorrow morning
or later tonight

**Comment by jwilander** [comment]
Rebase complete, it was a bit wonky thanks to the annoyances of Git

**Pull request merged**
