### PR TITLE
PLT-5571: Updated error messages related to url length, start, end and adjacent underscores

### PR DESCRIPTION
**Pull request by aautio**
#### Summary
Updated english error messages as requested.
 
#### Ticket Link
https://github.com/mattermost/platform/issues/5456
https://mattermost.atlassian.net/browse/PLT-5571

#### Checklist
- [x] Includes text changes and localization file (/webapp/i18n/en.json)

### CODE REVIEW

**Comment by jasonblais** [comment]
Wonderful, thank you @aautio! 

@lindalumitchell please help test when you get the chance?

**Comment by jasonblais** [comment]
Actually, I went ahead and tested it since I noticed it's just string changes.

----

@aautio, it looks like the error messages are in reference to the name field, not the URL.

Repro:
1) Create a new team
2) Enter a valid name
3) Enter a team name `1`
Observed:
image

So might be that on this screen, it's taking the incorrect error messages.

**Comment by grundleborg** [comment]
@jasonblais looking at the code, I don't think that screen is what this PR is changing.

**Comment by aautio** [comment]
Yeah the _New Channel_ dialog and the _Rename Channel_ -dialogs are affected by these text changes.

**Comment by jasonblais** [comment]
Oh sorry, I misinterpreted the PR. Let me retest this

**Comment by grundleborg** [comment]
Thanks very much for the PR @aautio

**Pull request merged**
