### PR TITLE
PLT-1232: More channel info

### PR DESCRIPTION
**Pull request by trashcan**
This adds the channel purpose to the channel info modal. It also renames "Channel Handle" to "Channel URL" as requested in [PLT-1232](https://mattermost.atlassian.net/browse/PLT-1232). The only thing that isn't working is that the purpose is not hidden when it's not set. I couldn't figure out how to get that working.

I tried:
```
var purpose = ""
if (channel.purpose != 'No Channel Found') {
  purpose =  `<div className='row'>
    <div className='col-sm-3 info__label'>{'Channel Purpose:'}</div>
    <div className='col-sm-9'>{channel.purpose}</div></div>`
}
```
And then using {purpose} where the HTML previously was, but it escaped all of the HTML and inserted them rather then rendering it. If that's important let me know what the best practices way to do so would be and I'll update the PR.

### CODE REVIEW

**Comment by trashcan** [comment]
I need to fix channel.URL, set to WIP while I investigate how to do that.

**Comment by it33** [comment]
Cool! Definitely helpful, thanks Pat!

**Comment by trashcan** [comment]
I fixed the URL (I misread the request originally), and also fixed a minor spacing issue in the modal. It looks like all of the rows needed to have "form-group" except the last.

**Comment by it33** [comment]
FYI, we're discussing a sizable PR about to come in to add localization support, were pausing commits to master until that's in (hopefully Saturday morning) and reviewed and merged.

**Comment by trashcan** [comment]
All righty. I'm just going through everything that is accepting pull requests and taking a stab at them. Should I base off a different branch, or just hold off on my pull requests for now?

**Comment by coreyhulen** [comment]
@trashcan If you think your PR's will have a bunch of localizable text I would hold off until the localization branch is submitted then base your PR off that branch.  The ETA for the loc branch is Saturday.  Our hope is to get it merged by early next week and get all the issues worked out of master by mid next week.

If you don't have a lot of loc stuff, then feel free to submit a PR against master, with the expatiation that it will require a rebase/merge once the loc stuff is completed.

**Comment by jwilander** [comment]
+1

**Comment by hmhealey** [comment]
+1. I think it's fine if the purpose field is there even if it's not set.

Also for future reference, you don't need the backticks around the HTML stuff in JSX so you're able to just write `var div = <div />;` without anything special around it. Your example above would look just like this:
```jsx
var purpose = ""
if (channel.purpose != 'No Channel Found') {
  purpose =  (
    <div className='row'>
      <div className='col-sm-3 info__label'>{'Channel Purpose:'}</div>
      <div className='col-sm-9'>{channel.purpose}</div>
    </div>
  );
}
```

**Pull request merged**
