### PR TITLE
PLT-2896 Improved handling of edge case where an LDAP user shares a username w…

### PR DESCRIPTION
**Pull request by hmhealey**
…ith a non-LDAP user

Before, it'd see the error message and just go look for the LDAP user anyway so the non-LDAP user would just see "your password is invalid" if they tried to log in

### CODE REVIEW

**Comment by enahum** [comment]
+1

**Comment by crspeller** [comment]
@hmhealey This is marked 3.1 but submitted against 3.0!

**Comment by hmhealey** [comment]
Sorry, I'm bad at marking things for the right milestone

**Comment by coreyhulen** [comment]
+1

**Pull request merged**
