### PR TITLE
PLT-2188 Integrations: Support raw new lines in the text payload

### PR DESCRIPTION
**Pull request by tbalthazar**
A bit of context: JSON strings are not supposed to contain control characters such as \n, \t, ... but some incoming webhooks might still send invalid JSON and we want to try to handle that. (Slack apparently does).
The Go JSON decoder will return an error if we pass it some JSON data that looks like this (strings for both "text" attributes are invalid JSON strings because they contain unescaped newlines and tabs):
```
{
  "text": "this is a test
				 that contains a newline and tabs",
  "attachments": [
    {
			...
      "text": "Optional text that appears within the attachment
						 that contains a newline and tabs",
			...
    }
  ]
}
```

What this code change does:
if (and only if) the Go JSON decoder fails to decode the JSON data, we search for `"text": "..."` attributes in the original JSON string,  escape `\n` and  `\t` in the string, and try again to decode it with the Go JSON decoder.

Original GitHub issue: https://github.com/mattermost/platform/issues/2278
APR on Jira: https://mattermost.atlassian.net/browse/PLT-2188

That's my first contribution to the project, please let me know what you think.
Thanks!

### CODE REVIEW

**Comment by thoemy** [comment]
I just did some checks with Slack and raw newlines and tabs may also appear in the attachment `author_name`, `fallback`, `pretext` and `title` as well as the attachment field `title` and `value` fields. So basically everywhere. The regex will not cover these cases.

The payload
```json
{
    "text": "text
		that contains a newline and tabs",
    "attachments": [
        {
            "fallback": "fallback
		that contains a newline and tabs.",
            "color": "#36a64f",
            "pretext": "pretext
		that contains a newline and tabs",
            "author_name": "author
		that contains a newline and tabs",
            "author_link": "http://flickr.com/bobby/",
            "author_icon": "http://flickr.com/icons/bobby.jpg",
            "title": "attachment title
		that contains a newline and tabs",
            "title_link": "https://api.slack.com/",
            "text": "attachment text
		that contains a newline and tabs",
            "fields": [
                {
                    "title": "field title
		that contains a newline and tabs",
                    "value": "field value
		that contains a newline and tabs",
                    "short": false
                }
            ],
            "image_url": "http://my-website.com/path/to/image.jpg",
            "thumb_url": "http://example.com/path/to/thumb.png"
        }
    ]
}
```
is rendered as
slack_raw_newline_render

**Comment by tbalthazar** [comment]
Thanks for your remark, I'll update my pull request accordingly.

**Comment by tbalthazar** [comment]
I've updated the patch to take more fields into account.

**Comment by enahum** [comment]
Hi @tbalthazar thanks for this we'll have a look soon.

**Comment by crspeller** [comment]
+1 Looks good to me. @jwilander Can you have a look?

**Comment by jwilander** [comment]
+1, great pull request!

**Pull request merged**
