### PR TITLE
PLT-363 - Ian needs help on this one.

### PR DESCRIPTION
**Pull request by asaadmahmoodspin**
Ian needs help on this one. Adding organisation theme and removing Slack. Also improving bugs with the theme color stuff.

### CODE REVIEW

**Comment by jwilander** [comment]
+1

**Comment by hmhealey** [comment]
Looks good, but it needs to be rebased before we can merge it

**Comment by asaadmahmoodspin** [comment]
Done. In a weird way.

**Comment by hmhealey** [comment]
Woah, something definitely went wrong there. There's also some conflicts in one of your scss files that's breaking everything.

**Pull request closed without merging**
