### PR TITLE
PLT-3817 - Updating flag icon

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
Updated the flag icon in the header and added correctly styling to it, it wasn't working well with darker themes.

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-3817
https://mattermost.atlassian.net/browse/PLT-3794

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [ ] All new/modified APIs include changes to the drivers
- [ ] Has enterprise changes (please link)
- [x] Has UI changes
- [ ] Includes text changes and localization files updated
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by coreyhulen** [comment]
+1

**Comment by enahum** [comment]
+1

**Comment by jasonblais** [comment]
Please do not merge this, hasn't been approved in triage yet.

Will be decided on Monday

**Comment by asaadmahmood** [comment]
@jasonblais I've also added a fix for https://mattermost.atlassian.net/browse/PLT-3794 in this PR.

**Comment by enahum** [comment]
+1 again

**Comment by jasonblais** [comment]
On Windows 10, Chrome, tested:

 - flagged icons on light and dark theme
 - Integrations screen on various screen sizes
 - System Console user list under Teams

+1

**Pull request merged**
