### PR TITLE
Websocket CORS Support

### PR DESCRIPTION
**Pull request by bradhowes**
#### Summary
Honor 'AllowCorsFrom' config setting when upgrading HTTP sockets to web sockets.

This is a second attempt after the first had build errors (but none due to api/websocket.go) Merged with latest Mattermost master just to be safe. Sorry for the noise.

#### Ticket Link
None

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [ ] All new/modified APIs include changes to the drivers
- [ ] Has enterprise changes (please link)
- [ ] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/platform/blob/master/i18n/en.json) and [.../webapp/i18n/en.json](https://github.com/mattermost/platform/tree/master/webapp/i18n/en.json)) updates
- [X] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by bradhowes** [comment]
What's with gofmt failure in build? Is there something I can/should do to fix that?

**Comment by jasonblais** [comment]
@grundleborg any thoughts?

**Comment by grundleborg** [comment]
@bradhowes looks like you've got a gofmt failure in your changes to `api/websocket.go`. You can run gofmt over that file locally to fix this, and then update the PR. You can also run `make check-style` locally to see if there are any similar errors before making a commit, so you don't have to wait for the build server to get to it.

**Comment by slothbag** [comment]
Just updated to v3.7.0 and websockets are broken.   Looking forward to getting this merged :)

**Comment by bradhowes** [comment]
I've added tests that I believe cover the CORS settings. The tests revealed that the order of the arguments to the strings.contains call should be swapped, so I did. But that code I originally copied from the CORS support for regular HTTP connections. Note that I'm talking substring matching, not exact match. If exact match is all that is desired then the order of arguments would be immaterial.

**Comment by crspeller** [comment]
Looks good! Thanks!

**Pull request merged**
