### PR TITLE
PLT-4467 Remove message button from more direct channels

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
When opening the more direct channels modal now you can add or switch to a dm channel by just clicking the row and the *Message* button was removed

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-4467

#### Checklist
- [x] Has UI changes

### CODE REVIEW

**Comment by jwilander** [comment]
+1 on @crspeller's comment, not sure this should be going in

**Comment by enahum** [comment]
The ticket was marked as 3.5, I'm ok with leaving this out, maybe we should talk about this in triage with the PM's

**Comment by hmhealey** [comment]
Yeah, I agree with what's been said. When I brought this up in UX, I didn't intend on it being high priority

**Comment by enahum** [comment]
closing as we'll take this for 3.6

**Pull request closed without merging**
