### PR TITLE
PLT-2873 Hide system-wide DMs in the sidebar when DMs are restricted to team only

### PR DESCRIPTION
**Pull request by jwilander**

### CODE REVIEW

**Comment by coreyhulen** [comment]
I think this is the wrong fix.  Instead of blanking the non-dm list it's suppose to show.  We just need to get the name.

**Comment by jwilander** [comment]
We need to show non-team DMs when they are turned off?

**Comment by coreyhulen** [comment]
correct...the system console setting was only meant for the `More` modal on DM lists.

**Comment by jwilander** [comment]
Let's chat after stand-up, I'm not sure that makes sense

**Pull request closed without merging**
