### PR TITLE
Add two col to theme string, so that we can create theme name and save some custom themes…

### PR DESCRIPTION
**Pull request by pan-feng**
…m themes

Please make sure you've read the [pull request](http://docs.mattermost.com/developer/contribution-guide.html#preparing-a-pull-request) section of our [code contribution guidelines](http://docs.mattermost.com/developer/contribution-guide.html).

When filling in a section please remove the help text and the above text.

#### Summary
[A brief description of what this pull request does.]

#### Ticket Link
https://github.com/mattermost/platform/issues/4553

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Added or updated unit tests (required for all new features)
- [x] Added API documentation (required for all new APIs)
- [ ] All new/modified APIs include changes to the drivers
- [ ] Has enterprise changes (please link)
- [ ] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/platform/blob/master/i18n/en.json) and [.../webapp/i18n/en.json](https://github.com/mattermost/platform/tree/master/webapp/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by jasonblais** [comment]
Thanks @pan-feng for the contribution! 

If you can help complete the Mattermost contribution license agreement, we'll start the review process.

**Comment by pan-feng** [comment]
I already did

**Comment by jasonblais** [comment]
@doosp when testing, here's a few things to check:
 - format is something like `(Sidebar BG, #2071a7), (Sidebar Text,#fff) , ....` in Account Settings > Display > Theme > Custom Theme
 - the custom theme vector updates correctly if you change any of the values in 
    - in Account Settings > Display > Theme > Theme Colours
    - in Account Settings > Display > Theme > Custom Theme
 - importing a theme colour via Account Settings > Display > Theme > Import theme colors from Slack works
 - copying and pasting theme colours from different accounts works as well

**Comment by doosp** [comment]
Hello, @pan-feng 
Thanks for your interest in our product and contribution.
I think there was a bit of miscommunication?
I couldn't find name & value pair in the custom theme.

image

I tested few other theme changes but still couldn't find the name & value pair update:

-Importing the Slack Theme works. Still no name & value pair.
-“Theme Colors” update correctly change the custom theme vectors but no name and value pair.
-“Custom Theme” update correctly changes the custom theme vectors but no name and value pair.
-Copying the vector works. Again, no name and value pair.

Everything is tested on desktop Chrom + Windows 10

Would you please help to check it again?

Thank you.

**Comment by pan-feng** [comment]
@doosp This pull request is help me to finish #4553

**Comment by jasonblais** [comment]
Ah, gotcha @pan-feng - can I label this as "Work in Progress" while you're working on it? That way others know it's still work in progress.


Really appreciate your help here, and we'd love to help if you need anything.

**Comment by pan-feng** [comment]
Of course,

**Comment by doosp** [comment]
@jasonblais  @pan-feng 

Changed the label to Work In Progress. Thanks!

**Comment by jasonblais** [comment]
Thanks @pan-feng, I'll close this in favor of #5301 - thanks for the contributing #5301!

**Pull request closed without merging**
