### PR TITLE
mm-1874 - Improving team url screen and fixing file attachments in IE 10

### PR DESCRIPTION
**Pull request by asaadmahmoodspin**
This is for 0.6.0, please have a look.

### CODE REVIEW

**Comment by hmhealey** [comment]
The stuff to shorten the team URL looks good except it still cuts off the full team name in the hover text.
screen shot 2015-08-04 at 2 32 07 pm

I don't have a copy of IE10 to test the file stuff, but it looks fine in Chrome.

**Comment by asaadmahmoodspin** [comment]
Fixed the word wrap on tooltip.

**Comment by crspeller** [comment]
@hmhealey Re-review and I can merge.

**Comment by hmhealey** [comment]
Looks good

**Comment by rgarmsen2295** [comment]
+1

**Pull request merged**
