### PR TITLE
PLT-2755 Shortcut to upload file

### PR DESCRIPTION
**Pull request by DavidLu1997**
Shortcut to upload file implemented as CTRL+K instead of CTRL+U, as CTRL+U opens page source on most browsers.

Tested on Windows/Chrome and Mac/Chrome

Open to suggestions on CTRL+key :)

### CODE REVIEW

**Comment by hmhealey** [comment]
If you use Ctrl+U, you should be able to add `e.preventDefault()` to prevent the page source from opening.

Also, the way you have this set up now, it triggers multiple file uploads if you have the RHS open

**Comment by DavidLu1997** [comment]
Reverted to CTRL+U with `e.preventDefault()`, removed multiple FileUpload dialogs

**Comment by coreyhulen** [comment]
+1

**Comment by jwilander** [comment]
+1

**Pull request merged**
