### PR TITLE
Docker image builds for arbitrary revisions (enable CI/CD pipeline)

### PR DESCRIPTION
**Pull request by bkeroack**
The PR adds a root Dockerfile and scripts required to build a full production version of Mattermost. This allows developers to build a deployable Docker image from any arbitrary revision (current Docker setup only allows official releases). This also allows Mattermost Docker images to be built automatically in a CI/CD pipeline.

This does not change any application functionality otherwise.

### CODE REVIEW

**Comment by bkeroack** [comment]
This also serves to document the Node dependencies required to build the React client. It took quite a bit of trial and error to figure out that it only will build with node 5.x since that doesn't seem to be documented anywhere.

**Comment by jwilander** [comment]
@crspeller please take a look

**Comment by crspeller** [comment]
Hi @bkeroack, thanks for the contribution!

This feature already exists in the form of the `make docker-build` target. That command will build a docker image based on your current working copy. It currently requires updating however. I have created: https://mattermost.atlassian.net/browse/PLT-1502 to track this issue. 

I am not going to accept this pull request because of the maintenance burden of the scripts and additional dockerfile.

**Comment by bkeroack** [comment]
@crspeller Thanks for taking the time to review the PR. Would you be willing to reconsider if the root Dockerfile and Makefile shared the same build scripts? I find the root Dockerfile solution to be less opaque than a Makefile solution, and it also plays nicely with, eg, quay.io's automated image builder.

**Pull request closed without merging**
