### PR TITLE
doc: Document a "harder" deployment

### PR DESCRIPTION
**Pull request by stephenfin**
The existing documentation suggests using the default 'ubuntu' user and
home directory for running/storing Mattermost, respectively. There are
suggestions that this is not the way to do this. Make changes to
run the user as a service.

While at it, resolve some Markdown issues to make it a little easier to
read from source.

### CODE REVIEW

**Comment by stephenfin** [comment]
I'm aware that I've mixed a few things in the commits here. If this is an issue I'm happy to fix. I would like your feedback on the ideas contained within, however.

**Comment by crspeller** [comment]
Hi @stephenfin Thanks for the better docs! I will be testing these soon. If I don't find any problems they should be merged for the upcoming 1.1 release.

**Comment by coreyhulen** [comment]
+1

**Comment by crspeller** [comment]
Hi @stephenfin Thanks for this. We tested these instructions internally and found a few issues. We are working on redoing our documentation and will be using your instructions to help us. 

Closing this pull request because we will make edits and resubmit with rest of improved docs.

**Pull request closed without merging**
