### PR TITLE
PLT-159 Properly hide unread indicators when there are no unread channels

### PR DESCRIPTION
**Pull request by hmhealey**
Since components that don't change are just reused by React even if their inline style changes, we need to manually hide the unread indicators when there are no unread channels (and thus firstUnreadChannel and lastUnreadChannel are null).

### CODE REVIEW

**Comment by jwilander** [comment]
+1

**Comment by crspeller** [comment]
This would be much better done refactored out into a react component, and pops passed to hide/unhide. 0/5 if you want to do this now. @hmhealey

**Comment by hmhealey** [comment]
I'll take a look at that to see how difficult it would be to separate out the unread indicators. It would definitely be nicer to separate it out, but it might be difficult given it's coupled pretty closely to the sidebar. For example, we can't always set visibility in the render function because we can't tell if an unread channel will be off the screen at that point.

**Comment by hmhealey** [comment]
Moved the unread indicators into their own component and file. There's a bit more coupling than I'd like between them and the sidebar, but it's not too much. Plus, there's not many other places we would be able to use these anyway.

**Comment by crspeller** [comment]
Looks good +1

**Comment by jwilander** [comment]
+1

**Pull request merged**
