### PR TITLE
PLT-6213 Move team store and actions over to use redux

### PR DESCRIPTION
**Pull request by jwilander**
#### Summary
Move team store and actions over to user redux. Waiting on #6140 for merge/dev review but is ready for PM review.

Testing areas:
* Joining/creating/leaving/inviting to/from team
* Switching teams
* Unreads/messages between teams
* Updating team settings
* Managing user teams in the system console
* Anything else team related you can think of

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-6213

### CODE REVIEW

**Comment by jasonblais** [comment]
Tested on Win10/Chrome
 - joining and creating channels
 - adding users to a team
 - inviting via email + team invite link
 - tested invite link salt re-generation
 - team settings (name, description, toggling open/invite-only teams)
 - leaving teams
 - switching teams
 - in System Console: 
    - enable/disable team creation
    - max users/teams/notifications per team
    - opening DMs with any user on the server vs with team members only
    - manage teams modal works in users list
 - unreads/mentions seem to work
 - syncing unreads/mentions across browser tabs works as expected (synced after going to a browser tab with 10+ seconds of inactivity)

Didn't find much, which is good but also makes me nervous if I just didn't catch things..

**Comment by jwilander** [comment]
Thanks for testing! I did test this one much more thoroughly and also this didn't include any of the set-up and general configuration work since that was handled by the previous PR

**Comment by jasonblais** [comment]
@jwilander I realized after posting that I forgot to test "Send Email Invite" option. I got this JS error after attempting to send one. Doesn't reproduce on `master`. Email was configured on the server.

image

PS: Also, after manually revoking my session, I was able to view the instance for a long time (~30 seconds) -- I wasn't logged out until after I tried to perform an action (e.g. switch channels / post a message). 

I know you mentioned in #6140 that the delay might be due to when the API request is sent, but mentioning just in case.

**Comment by jwilander** [comment]
Ok cool, I'll take a look at the JS error.

For the session revoking that's normal, you really shouldn't revoking the session that you're currently using if you want to logout you out immediate, that's what the regular logout button is for

**Comment by jasonblais** [comment]
> ...if you want to logout you out immediate, that's what the regular logout button is for

Yeah, that's true. Should be fine then

**Comment by jwilander** [comment]
@jasonblais Fixed

**Comment by jasonblais** [comment]
JS error fixed -- we can test further on today's bug bash

**Pull request merged**
