### PR TITLE
Update user_settings_general.jsx

### PR DESCRIPTION
**Pull request by esethna**
Clarify email help text

### CODE REVIEW

**Comment by jwilander** [comment]
@esethna  In SSO situations email won't be used for sign-in. Are we okay including that inaccuracy?

**Comment by esethna** [comment]
I think this is okay because if you sign in via GitLab then the help text changes to "Login occurs through GitLab. Email cannot be updated. Email is used for notifications." You will only see the help text I updated if you actually use email to sign-in.
image

**Comment by jwilander** [comment]
Sounds good

**Comment by jwilander** [comment]
+1

**Pull request merged**
