### PR TITLE
Multiple UI Improvements

### PR DESCRIPTION
**Pull request by asaadmahmoodspin**
Changes include:
- Improvements to file names
- Adding scroll for center channel arrows
- Changing position for post actions (comment and the three dots icon)

### CODE REVIEW

**Comment by jwilander** [comment]
@asaadmahmoodspin you've got an ESLint error

**Comment by asaadmahmoodspin** [comment]
Hey guys merge if possible.

**Comment by jwilander** [comment]
+1

**Comment by hmhealey** [comment]
+1

**Pull request merged**
