### PR TITLE
PLT-3957 Ctrl+Enter sends messages in mobile view

### PR DESCRIPTION
**Pull request by R-Wang97**
#### Summary
Made posts/comments in desktop mobile view send on enter/CTRL+enter. Mobile app behaviour is unchanged.

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-3957

### CODE REVIEW

**Comment by jwilander** [comment]
+1

**Comment by jwilander** [comment]
Thanks for the pull request @R-Wang97! We'd love to have you join our [Developer's channel](https://pre-release.mattermost.com/core/channels/developers) on our [Mattermost instance](https://pre-release.mattermost.com). Lots of developer discussion goes on in there and we have weekly developer meetings on Google Hangouts that are open to the public.

**Comment by DavidLu1997** [comment]
+1

**Comment by lfbrock** [comment]
+1, tested it on desktop browser and both enter and ctrl+enter send the message. Tested it using the iOS app, and enter still creates a new line.

**Comment by crspeller** [comment]
+1 Thanks for the help @R-Wang97

**Pull request merged**
