### PR TITLE
PLT-2377: Heath check at `GET /api/v1/ping`

### PR DESCRIPTION
**Pull request by augustohp**
Not a Go developer here, so I probably messed something up.

[Jira issue](https://mattermost.atlassian.net/browse/PLT-2377) related to #2455

### CODE REVIEW

**Comment by crspeller** [comment]
@coreyhulen Do we need to hold this one for you changes?

**Comment by coreyhulen** [comment]
Hi @augustohp thanks for the PR.  We're in the process of a big change to the server as discussed at http://forum.mattermost.org/t/unifying-user-accounts-across-teams-for-mattermost-2-2/1126, which includes re-doing all the /api/ routes.  It may take a few weeks before this gets reviewed/committed.

**Comment by coreyhulen** [comment]
Hi @augustohp PLT-2057 has been merged to master and it's significantly changed our routing.  If you would be willing to update your PR and re-submit that would be great.  Also could we use api/general.go vs api/ping.go which should use BaseRoutes.ApiRoot.  I see us adding more than just a ping in the future.

Sorry for the inconvenience. Thanks.

**Comment by augustohp** [comment]
> Hi @augustohp PLT-2057 has been merged to master and it's significantly changed our routing. If you would be willing to update your PR and re-submit that would be great.

Just give me some time. 😉 


> Also could we use api/general.go vs api/ping.go which should use BaseRoutes.ApiRoot. I see us adding more than just a ping in the future.

Thanks for the cue!

> Sorry for the inconvenience. Thanks.

NP!

**Comment by coreyhulen** [comment]
Thanks @augustohp.  I'm closing this PR.  Please re-submit when you're ready.

**Pull request closed without merging**
