### PR TITLE
Fixing LHS Header css

### PR DESCRIPTION
**Pull request by asaadmahmoodspin**
This is in for 0.6.0, please have a look. Fixing a slight issue with the profile pic.

### CODE REVIEW

**Comment by crspeller** [comment]
If you rebase instead of merge you won't get those extraneous commits "Merge branch 'master' of..." 
Changes look fine though.

**Comment by rgarmsen2295** [comment]
Changes look good, +1

**Comment by asaadmahmoodspin** [comment]
Can we pause the merge, I'll submit a commit for another change Ian wants.

**Comment by asaadmahmoodspin** [comment]
We can merge this now after reviewing the additional css changes.

**Comment by rgarmsen2295** [comment]
+1

**Pull request merged**
