### PR TITLE
Tweaking strings and adding them to the loc files for the signature v2 fix

### PR DESCRIPTION
**Pull request by coreyhulen**

### CODE REVIEW

**Comment by JeffSchering** [comment]
@coreyhulen For the help text, do admins typically know why they'd have to use V2 instead of V4? And do they know what the signature is used for?

**Comment by JeffSchering** [comment]
In that case, if it's very rarely needed and only for an obscure issue in an older S3 clone, then maybe it's best to not clutter the UI with it. It might even cause problems in scenarios where an admin is having trouble connecting to AWS, sees this setting, and turns it on.

Propose that we close this PR and have this as a config.json setting only.

**Comment by coreyhulen** [comment]
We don't have config.json only settings.  Everything in config.json should surface in the admin console.

**Comment by JeffSchering** [comment]
There's this: https://docs.mattermost.com/administration/config-settings.html#settings-configurable-only-in-config-json

**Comment by coreyhulen** [comment]
Geez...I didn't realize that list is so long.  Some of those make sense to have in the admin console.  I'm actually OK with removing this one then.

**Pull request merged**
