### PR TITLE
Created component CodePreview

### PR DESCRIPTION
**Pull request by rodrigocorsi2**
Created component CodePreview using highlight.js.
Used this component to view inline code and view code of attachments.

view_code_inline

view_code

### CODE REVIEW

**Comment by it33** [comment]
Cool! Setting up test server to take a look,

**Comment by it33** [comment]
Really love the new languages added, the line numbers and the ability to preview files. 

Overall, looks really solid. There was one issue I hit with previewing very long files, which pushed the controls at the bottom of the preview window off screen. 

Screenshot (note can't see bottom of preview window):  
image

[Here is the test file](https://pre-release.mattermost.com/api/v1/files/get/91b7oun61bdtjmx7qiuxp5mn3w/3bq1shta93yztg3i6aiu1tzi5h/16ahynion7nytk3czzsu5uwsbc/orc-battle.lisp?d=%7B%22filename%22%3A%2216ahynion7nytk3czzsu5uwsbc%2Forc-battle.lisp%22%7D&h=%242a%2410%24jubl58HghDBA7AARj3Mi0upJ9MbS%2FBPnMvEEogqJ7Cb8gwcCtSDv.&t=rcgiyftm7jyrxnma1osd8zswby)

I'll defer to other team members for further testing, other than the one minor issue, looking good :) 

We'll probably need to update docs, and possibly icons to denote new files we can now preview (and as a fancy feature later, perhaps get the logos of the major languages showing...)

**Comment by rodrigocorsi2** [comment]
Today I'll fix this thank you

**Comment by lfbrock** [comment]
Hi @rodrigocorsi2, 

This is great! Here's my feedback:

1. The preview window for short code files could seems to have some white space at the bottom:
screenshot 2016-03-07 16 06 23

2. Would it also be possible to show the code icon in the thumbnail preview instead of the generic paperclip icon?
screenshot 2016-03-07 16 04 27

3. I think the matlab file extension should possibly be .m instead of .matlab.

**Comment by rodrigocorsi2** [comment]
Create a new PR [#2380](https://github.com/mattermost/platform/pull/2380)

**Pull request closed without merging**
