### PR TITLE
Introduce webpush notification

### PR DESCRIPTION
**Pull request by npcode**
Show notifications even if the web browser is closed and native app is not installed.

screenshot_2016-01-12-12-33-45

See commit messages for more detials.

ps. You can test it at https://chat.npcode.com/push

### CODE REVIEW

**Comment by jwilander** [comment]
Thanks for this @npcode! We're currently in the middle of our release process for v1.4 but we'll give this a review shortly after that's done

**Comment by it33** [comment]
hi @npcode, we're discussing a very large PR about to come in to add localization support, were pausing commits to master until that's in (hopefully Saturday morning) and reviewed and merged. 

Sorry for the delay in getting to this,

**Comment by npcode** [comment]
@jwilander @it33 Thank you for letting me know that. I'll wait and rebase this if it conflicts with master.

**Comment by jwilander** [comment]
Hi @npcode, sorry for the wait, we've just begun merging PRs into master again. Can you rebase your branch and then we can start reviewing it? Thanks!

**Comment by enahum** [comment]
Also maybe have Loc implemented for strings with utils.T for l4g NewLocAppError and c.T for context?

**Comment by it33** [comment]
Before any additional work is done on this pull request, we need to be transparent that we're discussing internally whether we'd be able to take this change. 

Long term, it's probably how mobile devices will work in future. 

However, near term, there's overlapping functionality with the Android app that's being developed, and adding this feature to the monthly manual tests run across different Android platforms, in addition to testing the Android app, has a significant cost there. 

We're meeting to discuss again after the weekend,

**Comment by npcode** [comment]
> However, near term, there's overlapping functionality with the Android app that's being developed, and adding this feature to the monthly manual tests run across different Android platforms, in addition to testing the Android app, has a significant cost there.

I agree with it. The only reason I implemented this is that the android native app does not support LDAP yet.

**Comment by it33** [comment]
Thanks @npcode, sorry about the delay with our Android app, 

We're working on fixing the iOS authentication support this week, then getting the Android to work the same way on its initial release. We had someone new work on Android and while it's functional we feel it needs a re-write before we can offer it as open source. 

Sorry about the delay here, it's taking us a little longer to build to the right level of quality. 

Since this PR is a permanent solution to a temporary problem, propose we close it for now?

**Comment by npcode** [comment]
@it33 

> We're working on fixing the iOS authentication support this week, then getting the Android to work the same way on its initial release. We had someone new work on Android and while it's functional we feel it needs a re-write before we can offer it as open source.

That's a good news! Feel free to close this PR.

**Pull request closed without merging**
