### PR TITLE
Updated Email Check Regex to handle some extra cases

### PR DESCRIPTION
**Pull request by jvasallo**
New Committer here so sorry if I am not fully following the process.

Saw this open issue on Jira:
https://mattermost.atlassian.net/browse/PLT-168

I believe the above handles this case, but there are really no comments as to what is an "invalid email hitting server side" is. I noticed the regex was still hitting the server side with weird emails such as:
.fake@fake.com
fake.@fake.com

I ran it through a cycle of fake emails from this article:
http://blogs.msdn.com/b/testing123/archive/2009/02/05/email-address-test-cases.aspx

### CODE REVIEW

**Comment by jwilander** [comment]
Thanks @jvasallo for the pull request!

Before we can review, we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**

This is a standard procedure for many open source projects. Your form should be processed within 24 hours and reviewers for your pull request will be able to proceed. 

Please let us know if you have any questions. 

We are very happy to have you join our growing community!

**Comment by hmhealey** [comment]
Looks good to me

**Comment by jwilander** [comment]
+1

**Comment by jvasallo** [comment]
Thanks all! :grin:

**Pull request merged**
