### PR TITLE
PLT-3427 Added channel header to view channel info modal

### PR DESCRIPTION
**Pull request by DavidLu1997**
#### Summary
Added channel header (with markdown formatting) to the view channel info modal.
Also removed Purpose and Header displays if they do not exist.

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-3427
https://github.com/mattermost/platform/pull/3563 (discussion)

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields.]
- [ ] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [ ] Has driver changes that have been merged and package.json updated
- [ ] Has enterprise changes (please link)
- [x] Has UI changes
- [x] Includes text changes and localization files updated
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by enahum** [comment]
+1

Added label on PM Approval cause of discussion in #3534

**Comment by crspeller** [comment]
+1

**Comment by esethna** [comment]
Hey @DavidLu1997, tested, looks good, I I just want to make sure that this change does not cause previously set channel headers to be reset?

Tested in private groups and public channels: 
1. Long headers (view info modal will scroll)
2. adding and removing headers and purpose
3. links, headings, bold, numbers, lists, inline images

**Comment by DavidLu1997** [comment]
@esethna this PR does not affect previously set channel headers to reset, it only displays them.

**Comment by esethna** [comment]
Great, thanks!

**Pull request merged**
