### PR TITLE
Update Setup.md

### PR DESCRIPTION
**Pull request by tamtamchik**
Fixed process for Mac OS X, makes it easier to install that way

### CODE REVIEW

**Comment by jwilander** [comment]
Thanks @tamtamchik for the pull request! 

Per the [**CONTRIBUTING.md**](https://github.com/mattermost/platform/blob/master/CONTRIBUTING.md#submitting-a-pull-request) file displayed when you created this pull request, we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**

This is a standard procedure for many open source projects. Your form should be processed within 24 hours and reviewers for your pull request will be able to proceed. 

Please let us know if you have any questions. 

We are very happy to have you join our growing community!

**Comment by tamtamchik** [comment]
@jwilander done :smiley:

**Comment by hmhealey** [comment]
Using Homebrew to install Go sounds good to me, but you can remove the new step 4 since Godep gets downloaded automatically by the Makefile

**Comment by tamtamchik** [comment]
@hmhealey it does not. When you first run test it gives you an error:
 
    $ make test
    Starting docker containers
    ~/go/bin/godep go test  -run=. -test.v -test.timeout=180s ./api || exit 1
    /bin/sh: ~/go/bin/godep: No such file or directory
    make: *** [go-test] Error 1

**Comment by hmhealey** [comment]
Oh yeah, .prepare should be ran by make test. It used to run that step before, but it must've been left out when our build system was overhauled this past week. I'll make a quick PR to add that back in if you want to remove that step from setup.md then

**Comment by hmhealey** [comment]
PR to update the add the .prepare step to make test is here: https://github.com/mattermost/platform/pull/1522

**Comment by tamtamchik** [comment]
@hmhealey updated PR, removed step for installing Godep. Also updated part for Nodejs install on ubuntu. IDK if it was critical to install it from source, but the way to do this using https://github.com/nodesource/distributions is much easier.

**Comment by crspeller** [comment]
+1

**Comment by jwilander** [comment]
+1

**Comment by tamtamchik** [comment]
Great! Thanks!

**Pull request merged**
