### PR TITLE
Change en.json : PLT-3371

### PR DESCRIPTION
**Pull request by paranbaram**
#### Summary
Change files for UI text
- en.json
- privacy_settings.jsx
- invite_member_modal.jsx
- user_settings_notifications.jsx
- user_settings_notifications.jsx

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-3371 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [ ] All new/modified APIs include changes to the drivers
- [ ] Has enterprise changes (please link)
- [ ] Has UI changes
- [x] Includes text changes and localization files updated
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by enahum** [comment]
Hi @paranbaram thanks for this PR.

Also can you change the correspondent `defaultMessages` for each of the changed text in the code itself?

Highly appreciated.

**Comment by paranbaram** [comment]
@enahum Sure, I'm going to commit it tomorrow.  Thanks!

**Comment by jwilander** [comment]
+1

**Comment by esethna** [comment]
+1

**Comment by hmhealey** [comment]
+1 Thanks for changing that

**Pull request merged**
