### PR TITLE
PLT-2188 Support raw new lines in the text payload

### PR DESCRIPTION
**Pull request by khoa-le**
Please review and merge

### CODE REVIEW

**Comment by crspeller** [comment]
@khoa-le  Looks like your changes don't compile.

**Comment by khoa-le** [comment]
Hi @crspeller, already fixed the bug, now it can compile. Thanks!

**Comment by crspeller** [comment]
@jwilander Can you take a look at this?

**Comment by jwilander** [comment]
+1

**Comment by crspeller** [comment]
@khoa-le  +1 But needs rebase

**Comment by jwilander** [comment]
Hi @khoa-le, would you be able to squash your commits (or reapply the changes to a fresh branch and submit a new PR)? It looks like a whole bunch of old commits are being reincluded with this PR

**Pull request closed without merging**
