### PR TITLE
Bump download link to version to 1.4.0

### PR DESCRIPTION
**Pull request by cifvts**

### CODE REVIEW

**Comment by jwilander** [comment]
+1

**Comment by coreyhulen** [comment]
@esethna FYI we should probably replace this in the docs repo too.  Also there are more `Production-*` files that need this.  I think we should probably move to `download/vX.X.X/mattermost.tar.gz`because we seem to keep forgetting to bump this.

**Comment by coreyhulen** [comment]
+1

**Comment by esethna** [comment]
Thanks @coreyhulen, I've updated all the production install guide links on the docs repo to vX.X.X where appropriate.

**Pull request merged**
