### PR TITLE
Remove config.json from repository (fixes #5235)

### LINKED ISSUE #5235: Remove config.json from versioning
Would it be possible to add the config.json file to `.gitignore`?
I get conflicts everytime I switch branch because I have a modified config file.
And it makes it way too easy to accidentally commit a database password.

### PR DESCRIPTION
**Pull request by Rudloff**
#### Summary
This PR removes `config.json` from the repository so users can safely edit it without risking pushing changes.
It also creates a `config.default.json` file that is used when `config.json` can't be found.

#### Ticket Link
https://github.com/mattermost/platform/issues/5235

#### Checklist
- [x] Touches critical sections of the codebase (auth, upgrade, etc.)

PS: I know this would require more changes to tests and docs but I want to make sure you are OK with the idea first.

### CODE REVIEW

**Comment by jasonblais** [comment]
@jwilander Any thoughts on this approach?

**Comment by jwilander** [comment]
This should work, although the Makefile will need some updating since it has commands that assume config.json exists. Per the build failure:
```
sed -i'' -e 's|"ConsoleLevel": "DEBUG"|"ConsoleLevel": "INFO"|g' dist/mattermost/config/config.json
sed: can't read dist/mattermost/config/config.json: No such file or directory
```

**Comment by Rudloff** [comment]
I have updated the tests but they still fail, I'm not sure why. (I can't reproduce this error when running tests locally.)

**Comment by jasonblais** [comment]
Let me re-trigger the build to see if that resolves it (Jenkins builds have had some issues recently)

**Comment by jasonblais** [comment]
@jwilander is this Jenkins related?

```
[2017/02/28 01:19:14 UTC] [CRIT] Failed to ping DB err:Error 1045: Access denied for user 'mmuser'@'172.17.0.1' (using password: YES)
exit status 102
FAIL	github.com/mattermost/platform/api	1.181s
make: *** [test-server] Error 1
[TemplateProject] FAILED performing builders from: 'mattermost-platform-template'
Build step 'Use builders from another project' marked build as failure
[TemplateProject] Starting publishers from: mattermost-platform-template
Performing Post build task...
Match found for :Created database for mysql : True
Logical operation result is TRUE
Running script  : docker exec mattermost-mysql-57 mysql --user=root --password=passwd -e 'drop database `'$BUILD_TAG'`;'
[mattermost-platform-pr] $ /bin/sh -xe /tmp/hudson1423659904064705550.sh
+ docker exec mattermost-mysql-57 mysql --user=root --password=passwd -e drop database `jenkins-mattermost-platform-pr-5067`;
mysql: [Warning] Using a password on the command line interface can be insecure.
```

I wish I could read and understand error messages better

**Comment by grundleborg** [comment]
The problem is that when running the tests, Jenkins is expecting `config.json` to exist so it can modify it. Either we need to change the Jenkins jobs to create it from `config.default.json` before modifying it, or to do the same with the Makefile. @jwilander any thoughts on which approach would be better?

```
cp: cannot stat ‘config/config.json’: No such file or directory
sed: can't read config/config.json: No such file or directory
sed: can't read config/config.json: No such file or directory
test config
cat: config/config.json: No such file or directory
```

**Comment by jwilander** [comment]
I think it's better to update Jenkins. Let me do that and re-run the build

**Comment by jwilander** [comment]
Hmmm ok that should work but I think we need to change the tests back over to using "config.json", which should fall back to "config.default.json" in `FindConfigFile` if "config.json" doesn't exist

**Comment by Rudloff** [comment]
@jwilander I updated my PR. Tests are still failing but some of them are passing now.

**Comment by Rudloff** [comment]
@jwilander I updated my PR. Tests are still failing but some of them are passing now.

**Comment by jasonblais** [comment]
@Rudloff  Just so you know, there may be a delay in merging this PR as we are locking down feature and improvement contributions for the v3.7 release, per our [release process](https://docs.mattermost.com/process/release-process.html). This PR can be merged into `master` after we branch `release-3.7` on March 6th. 

Really appreciate all your contributions to the Mattermost code base!

**Comment by jwilander** [comment]
Hmmm not sure why that test failed, re-rerunning the build

**Comment by jwilander** [comment]
This is failing because of an enterprise test, I'll take a look at that after the release

**Comment by esethna** [comment]
Thanks for another contribution @Rudloff, it's much appreciatd. Sorry for the delay here, I've re-triggered the build to see if it resolves the issues.  

Also, just letting you know again that there may be a delay in reviewing and merging your PR since we are approaching code complete for v3.8, releasing April 16th. Please see our [release process](https://docs.mattermost.com/process/release-process.html) for more details.

**Comment by Rudloff** [comment]
@esethna It seems to fail because of enterprise-related code and I know nothing about this part of the code, sorry.

**Comment by jasonblais** [comment]
@jwilander I think there was some discussion that this implementation may not work and someone on the dev team has a ticket to investigate?

**Comment by jwilander** [comment]
That's correct, CS has a ticket to go look at it https://mattermost.atlassian.net/browse/PLT-5439

**Comment by jwilander** [comment]
Closing since we have a ticket to revisit this, will re-open if necessary

**Pull request closed without merging**
