### PR TITLE
PLT-3876 Only return current user's teams from /teams/all if they're not an admin

### PR DESCRIPTION
**Pull request by hmhealey**
#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-3876

#### Checklist
- Added or updated unit tests (required for all new features)
- All new/modified APIs include changes to the drivers

### CODE REVIEW

**Comment by jwilander** [comment]
Can we return all the teams the user is on for non-admin users or just return a sanitized vserion? This API is used in the Zapier app to let the user select their team from a dropdown and I just need the team name and the ID

**Comment by hmhealey** [comment]
Yeah, I can change it to do that instead. I only realized the function had the strange permissions when a community member was looking for an API that would do that anyway

**Comment by enahum** [comment]
+1

**Comment by jwilander** [comment]
+1

**Pull request merged**
