### PR TITLE
PLT-7: Refactoring frontend (chunk 1)

### PR DESCRIPTION
**Pull request by enahum**
- System console sidebar
- Sytem console email settings
- Error Bar
- Loading Screen
- Select Team Modal
- Add npm mm-intl package

### CODE REVIEW

**Comment by enahum** [comment]
This has to be reviewed carefully cause if this passes then everything in the frontend is going to be like this.

**Comment by coreyhulen** [comment]
open team at http://i-7b79e5a1.spinmint.com:8065/local

**Comment by coreyhulen** [comment]
+1

**Comment by crspeller** [comment]
+1

**Comment by hmhealey** [comment]
+1

**Comment by jwilander** [comment]
+1

**Pull request merged**
