### PR TITLE
PLT-3495 Updated text in Select Team

### PR DESCRIPTION
**Pull request by DavidLu1997**
Please make sure you've read the [pull request](http://docs.mattermost.com/developer/contribution-guide.html#preparing-a-pull-request) section of our [code contribution guidelines](http://docs.mattermost.com/developer/contribution-guide.html).

#### Summary
Updated text to remove references to "Open Teams" and for clarity.

#### Issue/Ticket Link
Spec here: https://mattermost.atlassian.net/browse/PLT-3495

### CODE REVIEW

**Comment by enahum** [comment]
+1

**Comment by hmhealey** [comment]
+1

**Comment by hmhealey** [comment]
@crspeller Is the test server for something that needs to be tested on this or are we good to merge it?

**Comment by crspeller** [comment]
@hmhealey It's text, it needs a PM review.

**Pull request merged**
