### PR TITLE
MM-1900 Removed textToJsx

### PR DESCRIPTION
**Pull request by hmhealey**
Removed textToJsx and replaced it with a transformation pipeline that should hopefully be more easily maintainable and extensible in the future. All new formatting code is in web/react/utils/TextFormatting.jsx and all changes to web/react/components are just to change them over from textToJsx to TextFormatting.

If you're trying to review this, it might be helpful to know how the new text formatting is done. The way that it works is that it does multiple passes over looking for certain tokens and replaces them with some placeholder (like `__MM_MENTION1__`). Some steps also look at other tokens to see if they match a pattern as well and will replace their token (so an at mention token may contain a current user mention token). At the end, we go backwards through the tokens, replacing each token in the string with its final HTML representation.

### CODE REVIEW

**Comment by jwilander** [comment]
@hmhealey You've got a few ESLint errors

**Comment by hmhealey** [comment]
Oh right, I can't believe I forgot that.

**Comment by coreyhulen** [comment]
+1

**Comment by jwilander** [comment]
+1

**Pull request merged**
