### PR TITLE
Moving away from goamz to use minio-go instead.

### LINKED ISSUE #4182: [Help Wanted] Support Minio for Mattermost file storage
Minio is a self-hosted alternative to Amazon S3 and it's driver is compatible with both S3 and Minio. 

Help wanted for changing our Mattermost S3 driver with Minio, which does more: https://github.com/minio/minio-go

If you're interested in working on this and need help, join our Developers channel: https://pre-release.mattermost.com/core/channels/developers

### PR DESCRIPTION
**Pull request by harshavardhana**
#### Summary
minio-go does fully managed way of handling S3 API requests

  - Automatic bucket location management across all s3 regions.
  - Transparently upload large files in multipart if file 64MB
    or larger.
  - GetObject() API provides compatibility with
    io.ReadWriteSeeker interface.
  - Various other APIs including bulk deletes, server-side object
    copy, bucket policies and bucket notifications.

#### Ticket Link
https://github.com/mattermost/platform/issues/4182

#### Checklist
- [x] Added or updated unit tests (required for all new features)
- [x] Includes text changes and localization files updated
- [x] Touches critical sections of the codebase (auth, upgrade, etc.)

Fixes #4182

### CODE REVIEW

**Comment by it33** [comment]
Sweet! Thanks @harshavardhana!

**Comment by harshavardhana** [comment]
@it33 - please let me know how this looks, i haven't removed the goamz deps. Seems like it ends up removing some other deps as well, so was not sure what would you like to do. 

Let me know. Thanks for #hacktoberfest

**Comment by it33** [comment]
Thanks @harshavardhana, and thanks for completing the CLA. I've added the "Dev Review" tag for comments.

**Comment by enahum** [comment]
Hi @harshavardhana I believe your `config.json` has errors

**Comment by harshavardhana** [comment]
> Hi @harshavardhana I believe your config.json has errors

Yes seems like fixing them.

**Comment by harshavardhana** [comment]
@enahum @it33 - ready for review.

**Comment by harshavardhana** [comment]
> Still need a PM to test this.

Can you let me know how to do this.. happy to help.

**Comment by jwilander** [comment]
Haha no worries @harshavardhana, I've poked a PM to come look at this and setup a test server and give it a test. No action needed from you :)

**Comment by esethna** [comment]
Hi @harshavardhana, thanks for the PR! I've attempted to test this but there seems to be a bug with the "Amazon S3 Secure" field. The field seems to copy whatever value is typed into the "Amazon S3 Region" field and then cannot be edited, causing an error on save (see screenshot).

image

Other minor notes regarding the "Amazon S3 Secure" field:

1) If the field only handles true/false values can we make it a radio button selector that defualts to "false" (see example screenshot of radio buttons).

image

2) Can we change the setting label from "Amazon S3 Secure" > "Enable Insecure Amazon S3 Connections". This is more consistent with our UX guidelines and other settings in the console.

3) Can we tweak the help text to "When true, allow insecure connections to Amazon S3. Defaults to secure connections only.

**Comment by harshavardhana** [comment]
Changed @esethna . let me know if the changes look good.

**Comment by it33** [comment]
Thanks everyone, just my thoughts high level: 

#### 1) Replacing the S3 driver with Minio is a great first step 

- We need to test on both S3 and Minio to make sure things work. 
- We can document the initial functionality as `beta/unofficial` for Minio to start 

#### 2) Add UI & docs for Minio

It may be an option that says "S3 or Minio" or different drop down options so the admin knows which is being used. Need to add docs too, including link on how to setup Minio, etc. 

We can take off the "unofficial" tag at this point. 

#### 3) We need to add file scenarios to [Mattermost Load Test](https://github.com/mattermost/mattermost-load-test)

- Benchmark both S3 and Minio just to have some baselines. 

At this point we can take off the `beta` tag. It might even be okay to take the `beta` tag off earlier, just if we're planning to do the file load tests anyway, it could be okay to wait a bit. 
 
Somewhere along the way it probably makes sense to do a Hacktoberfest blog post, as this is a pretty awesome PR.

**Comment by esethna** [comment]
Hi @harshavardhana,

When testing this I ran into an issue where the `FileSettings.AmazonS3Endpoint` has to be set manually for file storage to work. It seems the new library does not support auto-populating the endpoint for recognized S3 regions. After discussing with @jwilander, we think the best course of action is to:

1. Expose the "Amazon S3 Endpoint" field in the system console since this field is used for both S3 and Minio.

Label: **Amazon S3 Endpoint**
Help text: Refer to the [region chart](http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region) to look up a valid endpoint name for your Amazon S3 region.

2. In order to not break existing instances with this change, we need to add code that auto-fills the Amazon S3 Endpoint field based on the Amazon S3 Region currently specified.

3. Remove the Amazon S3 Region field from the system console since it doesn't apply to Minio. However, do not remove it from the config.json so we don't break existing intances.

**Comment by harshavardhana** [comment]
> When testing this I ran into an issue where the FileSettings.AmazonS3Endpoint has to be set manually for file storage to work. It seems the new library does not support auto-populating the endpoint for recognized S3 regions. After discussing with @jwilander, we think the best course of action is to:

For S3 the endpoint and region holds meaning only at bucket level that is why minio-go manages this automatically internally. 

> 1) Expose the "Amazon S3 Endpoint" field in the system console since this field is used for both S3 and Minio.
> 
> Label: Amazon S3 Endpoint
> Help text: Refer to the AWS region chart to look up a valid endpoint name for your Amazon S3 region.

Any pointers here would be appreciated on how this can be achieved.  Also is it possible me to test my changes locally??

> 2) In order to not break existing instances with this change, we need to add code that auto-fills the Amazon S3 Endpoint field based on the Amazon S3 Region currently specified.

Since regions are managed automatically we can prefill this value to "s3.amazonaws.com" by default. 

> 3) Remove the Amazon S3 Region field from the system console since it doesn't apply to Minio. However, do not remove it from the config.json so we don't break existing intances.

**Comment by jwilander** [comment]
Thanks for the changes @harshavardhana, for 2) on @esethna's list I think you will need to add "s3.amazonaws.com" as a default for `AmazonS3Endpoint` in the `SetDefaults()` function inside `model/config.go`. You'll basically need to check if the field is empty and populate correctly if so. That will allow any old config file that doesn't that field specified to get the correct value.

To test it out locally you can change the `FileSettings` section to only have the following (this is from an old config file):
```
"FileSettings": {
        "DriverName": "amazons3",
        "Directory": "./data/",
        "EnablePublicLink": true,
        "PublicLinkSalt": "somesalt",
        "ThumbnailWidth": 120,
        "ThumbnailHeight": 100,
        "PreviewWidth": 1024,
        "PreviewHeight": 0,
        "ProfileWidth": 128,
        "ProfileHeight": 128,
        "InitialFont": "luximbi.ttf",
        "AmazonS3AccessKeyId": "somekey",
        "AmazonS3SecretAccessKey": "someaccesskey",
        "AmazonS3Bucket": "somebucket",
        "AmazonS3Region": "us-east-1"
}
```
Our config files need to be forward-compatible so that upgrading will never cause a user's system to break if they don't change their config file.

**Comment by harshavardhana** [comment]
I see thanks let me do these changes @jwilander

**Comment by harshavardhana** [comment]
All changes have been made was able to use successfully Minio server locally. 

mattermost with minio

```
$ mc ls myminio/testbucket/teams/
[2016-10-12 13:36:08 PDT]     0B wncgr4ikxjbcfkmft7e9jusqyc/
$ mc ls myminio/testbucket/teams/ -r
[2016-10-12 13:32:57 PDT]  86KiB wncgr4ikxjbcfkmft7e9jusqyc/channels/cgsqhpc4pfditrmuhq3f7xz51e/users/1ff81xkh8bgpzfi7hu66tj87je/uracm8xpyp887k7jzoytp7wp5e/MatterMost with Minio.png
[2016-10-12 13:32:57 PDT]  69KiB wncgr4ikxjbcfkmft7e9jusqyc/channels/cgsqhpc4pfditrmuhq3f7xz51e/users/1ff81xkh8bgpzfi7hu66tj87je/uracm8xpyp887k7jzoytp7wp5e/MatterMost with Minio_preview.jpg
[2016-10-12 13:32:57 PDT] 3.4KiB wncgr4ikxjbcfkmft7e9jusqyc/channels/cgsqhpc4pfditrmuhq3f7xz51e/users/1ff81xkh8bgpzfi7hu66tj87je/uracm8xpyp887k7jzoytp7wp5e/MatterMost with Minio_thumb.jpg
```

**Comment by harshavardhana** [comment]
Is there anything needed from my end let me know - Thank you.

**Comment by jwilander** [comment]
Awesome, thanks @harshavardhana! @esethna can you setup a test server and try it out with our S3 configuration?

**Comment by esethna** [comment]
Thanks for the changes @harshavardhana! Mostly looking great, but I ran into two things during testing:

1) The "Enable Insecure Amazon S3 Connections" field seemed to be set to `true` on the fresh spinmint when I enabled S3 for the first time. Can you please verify that the default is set to `false` so only secure secure connections are allowed.

2) There seems to be a bug with uploading profile pictures when the "Enable Insecure Amazon S3 Connections" setting is `true`. Things work as expected when the setting is `false`. Reproduction steps:

a) Set "Enable Insecure Amazon S3 Connections" to `true` and Save
b) Switch back to the team from the system console
c) Account settings > General > Profile Picture
d) Select a new image, then attemp to "Save"

Observed: The profile picture is not uploaded and the profile pic reverts to the default colored circle with the letter inside.
Expected: The profile picture is saved sucessfully and updates in all posts.

**Comment by harshavardhana** [comment]
Let me validate this and get back to you today @esethna

**Comment by harshavardhana** [comment]
After taking a look i see that the profile image is not loading there seems to be a 500 Internal Server error. 

screenshot from 2016-10-18 12-07-27

Are there any pointers where i go about looking at this in the code? does this internally use presigned URL etc? or is it a direct GetObject() operation?

**Comment by esethna** [comment]
Thanks @harshavardhana, maybe @jwilander can help point you in the right direction?

**Comment by harshavardhana** [comment]
> Thanks @harshavardhana, maybe @jwilander can help point you in the right direction?

Fixed it there was bug in how the path was specified during upload v/s how it is read.  Looks like previous library modified this internally by cleaning the prefix '/'. 

```
$ git diff api/
diff --git a/api/user.go b/api/user.go
index ae8136d..6811103 100644
--- a/api/user.go
+++ b/api/user.go
@@ -1174,7 +1174,7 @@ func getProfileImage(c *Context, w http.ResponseWriter, r *http.Request) {
                                return
                        }
                } else {
-                       path := "/users/" + id + "/profile.png"
+                       path := "users/" + id + "/profile.png"
 
                        if data, err := ReadFile(path); err != nil {
 
```

**Comment by harshavardhana** [comment]
> 1) The "Enable Insecure Amazon S3 Connections" field seemed to be set to true on the fresh spinmint when I enabled S3 for the first time. Can you please verify that the default is set to false so only secure secure connections are allowed.

Changed the behavior to have this option as "Secure" instead of "InSecure" it is the negation of what is common. 

> 2) There seems to be a bug with uploading profile pictures when the "Enable Insecure Amazon S3 Connections" setting is true. Things work as expected when the setting is false. Reproduction steps:
> 
> a) Set "Enable Insecure Amazon S3 Connections" to true and Save
> b) Switch back to the team from the system console
> c) Account settings > General > Profile Picture
> d) Select a new image, then attemp to "Save"

This works now with or without SSL. Pushing the new change.

**Comment by harshavardhana** [comment]
Is there anything waiting on me for this one?

**Comment by jasonblais** [comment]
Sorry for the delay @harshavardhana, we had some trouble setting up test servers end of last week. 

@esethna can you help test when you get the chance, now that the test servers are working again?

**Comment by esethna** [comment]
+1, thanks for the changes @harshavardhana! Tested image uploads, downloads and profile pictures with the "Secure Amazon S3 Connections" setting toggled on and off.

**Comment by esethna** [comment]
@harshavardhana Excited that we got this PR in! Would you be interested in helping add documentation for this change? This would involve updating the File > Storage section of [config-settings.rst](https://github.com/mattermost/docs/blob/v3.5-documentation/source/administration/config-settings.rst) doc to mention Minio (appended with `(Beta)` for this release) and also adding the new setting "Secure Amazon S3 Connections".

**Comment by harshavardhana** [comment]
Yes will do @esthena

**Pull request merged**
