### PR TITLE
Ui improvements

### PR DESCRIPTION
**Pull request by asaadmahmoodspin**
- Improving UI for the drag/drop
- Updating mattermost logo
- Updating z-index for date separator
- Updating how the active nav element appears

### CODE REVIEW

**Comment by jwilander** [comment]
I did a grep and we also use `icon50x50.gif` in here `./web/templates/authorize.html`. Can you update it in there as well?

**Comment by coreyhulen** [comment]
+1 besides jorams comment.

**Comment by asaadmahmoodspin** [comment]
Done.

**Comment by asaadmahmoodspin** [comment]
Also fixed the UI for the search help popover.

**Comment by jwilander** [comment]
+1

**Pull request merged**
