### PR TITLE
Introduce LDAP auth functionality for all users

### PR DESCRIPTION
**Pull request by dongsupark**
#### Summary
Goal is to introduce LDAP authentication functionality to allow all users to be authenticated via OpenLDAP, even without LDAP license. For that, create `ldap/ldap.go` to define necessary methods that correspond to `LdapInterface`.

Originally written by @kayrus
Rebased-and-improved by @dongsupark

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/platform/blob/master/i18n/en.json) and [.../webapp/i18n/en.json](https://github.com/mattermost/platform/tree/master/webapp/i18n/en.json)) updates
- [x] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by lfbrock** [comment]
Hi @dongsupark, 

LDAP authentication is currently included in our [Enterprise Edition](https://about.mattermost.com/features/#featuresCompare), and there are no current plans to add it into Team Edition.

**Comment by it33** [comment]
Hi @dongsupark, first, huge thanks for thinking of Mattermost and in putting in the effort to understand our code base and make a pull request. 

Regrettably, this is a change we can't accept because it doesn't follow our [code contribution guidelines](https://docs.mattermost.com/developer/contribution-guide.html), doesn't meet criteria 3 (volunteers want to test and maintain the change) of our [APR policy](https://docs.mattermost.com/process/accepting-pull-request.html). 

You're someone who seems genuinely skilled and interested in improving Mattermost and I hope you'll consider making a contribution in other ways.

**Comment by it33** [comment]
Here's a list of [[Help Wanted] issues as part of Hacktoberfest to try if you're interested](https://github.com/mattermost/platform/issues?q=is%3Aopen+is%3Aissue+label%3AHacktoberfest)

**Comment by dongsupark** [comment]
First of all, thanks to @it33 for detailed explanation.

Before creating this PR, I already had a look into [Code Contribution Guidelines](https://docs.mattermost.com/developer/contribution-guide.html), and tried to create a corresponding ticket for the "APR Tickets list". I couldn't, because I didn't have permission to create a new ticket for PLT.

What I could do instead would be to [start a conversation in the feature idea forum](http://www.mattermost.org/feature-requests/). However I don't see a particular point to do that by myself, because there has been already [one](https://mattermost.uservoice.com/forums/306457-general/suggestions/8589415-integration-with-ldap-active-directory) since a long time. The ticket is marked as completed, but of course until today the LDAP auth feature is not available for the Team Edition.

So at this point I cannot see how I can meet the [Code Contribution Guidelines](https://docs.mattermost.com/developer/contribution-guide.html). The entire list of rules just looks like a high barrier to newcomers.

As for [APR policy](https://docs.mattermost.com/process/accepting-pull-request.html), criteria 3 says "volunteers are willing to test, document, support and maintain changes" for each release. I can see the point, and I'm willing to do that. That's why I rebased a PR based on 3.2 on top of the current master branch (3.4.0+). But for now I can only say that this PR passed every in-tree test. Could you please tell me how I can further maintain the changes including tests, documents, supports?

Note that we at Endocode have been using Mattermost internally with the LDAP authentication since months. There is a practical need in the real world, and I believe we are not the only one who wants the LDAP auth feature.

BTW yesterday 30 minutes after creating this PR, someone closed the PR by commenting "LDAP authentication is currently included in our [Enterprise Edition](https://about.mattermost.com/features/#featuresCompare), and there are no current plans to add it into Team Edition". However, that comment has been apparently removed for some reason. Don't you think it's somewhat amusing?

Thanks.

**Comment by it33** [comment]
Hi @dongsupark, 

I think it's important to acknowledge that out of the thousands of companies using Mattermost you're someone who's stepped up and invested a lot of time to propose a substantial change you felt was meaningful. 

It completely, totally, utterly sucks that we're not able to make use of what you worked hard to provide. 

It's a failure of [our contribution guidelines](https://docs.mattermost.com/developer/contribution-guide.html), of our process, and I consider it a personal failure. 

We try to be explicit in our guidelines that APR tickets are only opened by core team members: 

image

If this wasn't clear enough, it's our fault, not yours. 

What I can say is: 

- We try to make it easy to contribute to Mattermost with [clear lists of tickets where we need help](https://github.com/mattermost/platform/issues?q=is%3Aopen+is%3Aissue+label%3AHacktoberfest). We try to carefully consider each of these tickets and make it easy for people to see value in the changes and provide a patch for something they want to see. 

- For changes outside the list, we have a process to [nominate, upvote and discuss new additions](http://www.mattermost.org/feature-ideas/) so designs are clearly thought out before a ticket is opened to accept a change, and before a single line of code is written. 

While this system works for our existing community, and while we agree it can be improved, we realize that some people will have work styles and priorities that aren't compatible.

My hope is that you're not completely turned off by this first result. 

I hope that you'll consider other tickets that benefit the product, the community and your own deployment. 

Regarding LDAP, as you've cited, we've already said it's [not in scope for Team Edition](https://www.mattermost.org/manifesto/). What we're looking for in Team Edition are improvements to delight end users, like: 

- [React Native mobile apps](https://github.com/mattermost/mattermost-mobile)
- [Favorite Channels](https://github.com/mattermost/platform/issues/4095)
- [Pinned Posts](https://github.com/mattermost/platform/pull/4217)

And other features that are straight-forward for our existing community to test, document, and maintain at high quality. 

If we did add one more IT feature that would commit us to more perpetual testing and maintenance, the focus is on: 

- [sudo apt-get install](https://github.com/mattermost/platform/issues/4176) 

You're obviously talented. You have a lot to contribute. We've tried to be transparent with our process and our decisions, and in this case we failed. 

I hope you'll consider working with us on a different project that we know can ship to Mattermost users. 

It's entirely your decision.

**Comment by razaqadams** [comment]
Hi @dongsupark does your improvement work with version 3.6.2? And how can I implement it in my local installation? Thanks in advance for this great work! The community needs more of you!

**Comment by dongsupark** [comment]
@razaqadams I haven't tried to rebase the patch against mattermost 3.6.2. Last time when I tried, it worked based on 3.4. Probably we would need to rebase it against master, and test it again etc. I'm not sure when I could do that.

**Pull request closed without merging**
