### PR TITLE
PLT-446 Added help text to incoming webhooks.

### PR DESCRIPTION
**Pull request by jwilander**

### CODE REVIEW

**Comment by crspeller** [comment]
The help text makes it sound like I can restrict where the webhooks post, but as you described it they can actually post anywhere. What I pick is just default. Maybe mention this?

**Comment by jwilander** [comment]
Yeah, good call. I'll add "by default" somewhere in there

**Comment by jwilander** [comment]
How's the new text sound @crspeller ?

**Comment by hmhealey** [comment]
Looks good to me

**Comment by crspeller** [comment]
It's a bit of a run on sentence. How about: "Create webhook URLs for channels and private groups. These URLs can be used by outside applications to create posts in any channels or private groups you have access to. The specified channel will be used as the default."

**Comment by jwilander** [comment]
Done

**Comment by crspeller** [comment]
+1 Cool to merge when travis is done.

**Pull request merged**
