### PR TITLE
PLT-5057 Make image preview work if URL contains a query

### PR DESCRIPTION
**Pull request by khawerrind**
**SUMMARY**

When posting an image URL that contains a query, the image preview was not working now it is fixed.

**Ticket Link**

https://mattermost.atlassian.net/browse/PLT-5057

### CODE REVIEW

**Comment by khawerrind** [comment]
@esethna it is because the link of the dropbox is not a direct link to the image. It is a HTML page as you can see in the attached screenshot. Also you can see in this [FIDDLE](https://jsfiddle.net/f1y4864n/) that even this link does not work in the img src attribute.
screenshot-www dropbox com 2016-12-28 20-51-39

**Comment by esethna** [comment]
@khawerrind is it possible to recognize if the page is HTML and then don't display the image preview UI? Currently on master links to dropbox images do not display the image preview.

The behavior observed above feels like a bug, so I'm trying to propose solutions for how we can improve the user experience.

**Comment by esethna** [comment]
@khawerrind yes. We should hide the collapse/expand buttons unless they are functional and an image preview can be generated.

**Comment by khawerrind** [comment]
@esethna fixed, the expand/collapse icon will not be available if the image failed to load.

**Comment by esethna** [comment]
Thanks @khawerrind, I still seem to be running into an issue where the image preview briefly attempts to load when you post the link and then disappears. See GIF: 

dropbox image

**Comment by khawerrind** [comment]
@esethna can i fix this tomorrow if its not urgent? Currently a bit busy.

**Comment by esethna** [comment]
@khawerrind sounds great, thanks!

**Comment by esethna** [comment]
Hi @khawerrind,

Just so you know, there may be a delay in reviewing and merging this PR as we are locking down feature and improvement contributions for the v3.6 release, per our [release process](https://docs.mattermost.com/process/release-process.html). This PR can be merged into `master` after we branch `release-3.6` on January 4th.

**Comment by khawerrind** [comment]
@esethna this is because there is code for showing an image placeholder while the image is still loading. I can remove that placeholder but then the height of the container will increase when the image is fully loaded and it will be not pleasant to the eyes if the container is constantly changing its height and will cause flickering. This might disturb the logic for `Jump To Post` functionality as well because then the position of the post will not be accurate if the container height is increasing after the images are loaded. What do you suggest should i remove that placeholder or should i keep it.

**Comment by khawerrind** [comment]
@esethna according to me there is less possibility for an image to not load. So the container height will reshuffle less likely. But if we will remove the image placeholder then the container height will always increase on each image load. And if the channel has many images you can imagine the amount of reshuffling in the height of the container. I would suggest to leave it as it is but i am open to suggestions as well 🙂

**Comment by jasonblais** [comment]
Thanks @khawerrind, 

As we're hiding the collapse/expand buttons when an image isn't generated (such as for the above example), could we also remove the placeholder for that case? Since there's no image to generate, there is no need for the placeholder either.

I'm not sure if that's feasible / easy to do, so let me know.

For images that have a preview and the collapse/expand button, keeping the placeholder makes sense for the reasons you described, preventing container height from reshuffling as the images load.

**Comment by khawerrind** [comment]
@jasonblais the problem is that you don't know if the preview can be generated or not unless the image is fully loaded. So you have to hide the placeholder unless the image is fully loaded. Which again will cause issues as i have described above

**Comment by jasonblais** [comment]
Hey @khawerrind, sorry for the delay,

I've been testing this out and trying in a few other apps too just to get a feel for it. I'm leaning towards not having a placeholder, as the size of the placeholder might not be accurate even if we had it --> that is, if the image is vertically smaller, then the post will jump anyways.

I'm queuing this for our UX meeting to discuss on Monday though and will get back to you soon. Sorry for the wait and many thanks for working on this improvement! Really looking forward to it!

**Comment by jasonblais** [comment]
Hey @khawerrind, we didn't get to this item on Monday, so it's re-queued for Wednesday. Will let you know then, sorry for the wait

**Comment by jasonblais** [comment]
Hey @khawerrind, we discussed it on Wednesday and reviewed further details today.

The recommendation is to remove the placeholder as the current user experience when posting a link without an actual image preview isn't good -- especially if multiple people are posting messages simultaneously.

So the proposal would be to
 1) Remove the placeholder we discussed
 2) If the user is at the bottom of the channel, the user should stay there after the image preview has loaded. To keep the channel scrolled to the bottom, we need some way to call the `PostList.updateScrolling` method whenever a markdown image is loaded. The `markdownImageLoaded` function in `markdown.jsx` is called whenever an image is loaded, but we have no way for it to call back to the `PostList` when that happens. We need to figure out a way to do this, hopefully without a global function like the one that we currently have. [this note is from one of our core devs]

For this proposal I [created a separate ticket to address it](https://mattermost.atlassian.net/browse/PLT-5267). Would this be something you'd be interested to take a look? If so, it's up to you if you'd like to incorporate the change in this PR or create a second PR for it.

Huge thanks for your help here, this has the potential of significantly improving how image previews work in Mattermost!

**Comment by jasonblais** [comment]
Hey @khawerrind, also, if you'd like to discuss it further, feel free to direct message me [at our Mattermost community instance](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676) (my username is `@jason`).

**Comment by jasonblais** [comment]
Thanks again @khawerrind for this.

Tested the functionality on Windows 10, Chrome
  - with and without using a link URL that contains a query
  - with and without link URLs that generate an image preview
  - across channels and direct messages
  - center pane and right-hand sidebar

All works as expected apart from 
  - removing the placeholder, which can be a separate improvement ticket: https://mattermost.atlassian.net/browse/PLT-5267
  - link previews (including images) not showing for replies on the right-hand sidebar (separate improvement ticket: https://mattermost.atlassian.net/browse/PLT-5268)

Queuing for dev review next

**Pull request merged**
