### PR TITLE
PLT-486: Remove spell check feature from input boxes during signup flow

### PR DESCRIPTION
**Pull request by florianorben**
Add spellcheck="false" attribute to login and signup form inputs

### CODE REVIEW

**Comment by florianorben** [comment]
Hey,

in addition to removing the spellchecking from inputs during the signup process I also removed it from 
- login
- reset-password
- invite-members

input fields. Since I found those are pretty much the same category.
I've you wish I'll revert changes to these fields though and update the MR.

Cheers,
Florian

**Comment by jwilander** [comment]
Hi @florianorben , thanks for the PR!

It looks like it needs a rebase, would you be able to quickly do that for us when you get a chance?

**Comment by florianorben** [comment]
Hey,

rebase sent - just waiting for Travis build

2015-10-12 18:04 GMT+02:00 Joram Wilander <notifications@github.com>:

**Comment by coreyhulen** [comment]
+1

**Comment by rgarmsen2295** [comment]
+1, looks good, glad this is getting fixed!

**Comment by jwilander** [comment]
+1

**Pull request merged**
