### PR TITLE
Fix email encoding issue

### PR DESCRIPTION
**Pull request by layzerar**
The subject of email could be non-ascii string ,it should be encoded according to [rfc2047](http://www.ietf.org/rfc/rfc2047.txt).

### CODE REVIEW

**Comment by layzerar** [comment]
Unfortunately,  `mime.BEncoding` seems not available in go1.4.

**Comment by jwilander** [comment]
Hi @layzerar, thanks for the pull request!

Unfortunately we currently need to support Go 1.4.2. If you could find a solution that works with both Go 1.4 and 1.5 that would be ideal, and we'd very much appreciate it

Also feel free to join our list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) by signing the [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/). With that done we can review and merge any PRs you make here :)

**Comment by layzerar** [comment]
@jwilander  
I signed the contribution license agreement just now.

**Comment by layzerar** [comment]
The subject of notification email would contain the channel name. Thus, memtioning someone in a channel with a non-ascii name would product a good testing email.

**Comment by jwilander** [comment]
+1

**Pull request merged**
