### PR TITLE
SiteURL help text update

### PR DESCRIPTION
**Pull request by esethna**
Followup from code complete meeting on unclear help text for siteurl field

### CODE REVIEW

**Comment by enahum** [comment]
+1

**Comment by hmhealey** [comment]
+1

**Comment by enahum** [comment]
@esethna your PR is failing

/var/lib/jenkins/jobs/mattermost-platform-pr/workspace/src/github.com/mattermost/platform/webapp/components/admin_console/configuration_settings.jsx
  70:26  error  'FormattedHTMLMessage' is not defined  react/jsx-no-undef

✖ 1 problem (1 error, 0 warnings)

Make sure you import `FormattedHTMLMessage` into that file

**Comment by enahum** [comment]
@esethna your PR is failing

/var/lib/jenkins/jobs/mattermost-platform-pr/workspace/src/github.com/mattermost/platform/webapp/components/admin_console/configuration_settings.jsx
  70:26  error  'FormattedHTMLMessage' is not defined  react/jsx-no-undef

✖ 1 problem (1 error, 0 warnings)

Make sure you import `FormattedHTMLMessage` into that file

**Comment by enahum** [comment]
@esethna your PR is failing

/var/lib/jenkins/jobs/mattermost-platform-pr/workspace/src/github.com/mattermost/platform/webapp/components/admin_console/configuration_settings.jsx
  70:26  error  'FormattedHTMLMessage' is not defined  react/jsx-no-undef

✖ 1 problem (1 error, 0 warnings)

Make sure you import `FormattedHTMLMessage` into that file

**Comment by esethna** [comment]
Thanks! Updated.

**Pull request merged**
