### PR TITLE
translations PR 20170731

### PR DESCRIPTION
**Pull request by enahum**
Ideally this PR should be review by community members for each language.

Note: In the event that you see an english translation instead of the desired language is because this PR was submitted before the translation was made on the Mattermost Translation Server and probably will be submitted for the next PR.

### CODE REVIEW

**Comment by wget** [comment]
I haven't performed any changes for French. So `fr` LGTM.

**Comment by kaakaa** [comment]
`ja` LGTM!

**Comment by cpanato** [comment]
there are missing translations for `PT-BR` i will take care today

**Comment by enahum** [comment]
@jasonblais when this happens is way easier to close the PR and submit another one.

Maybe it would be best if people adding new translations do so at the end of the file just to prevent this issues.

let me know what you want to do

**Comment by jasonblais** [comment]
I'm 0/5, would be nice to get it submitted before code complete. Fine closing this one, and submitting a new one

There might still be merge conflicts with people updating existing English strings.

**Comment by enahum** [comment]
Ok going to close this as a new one will get submitted on monday

**Pull request closed without merging**
