### PR TITLE
PLT-2922 403 errors logged when switching teams from channel containing files

### PR DESCRIPTION
**Pull request by enahum**

### CODE REVIEW

**Comment by coreyhulen** [comment]
+1

**Comment by crspeller** [comment]
Isn't this just removing the post view caching?

**Comment by enahum** [comment]
Lets just wait for https://github.com/mattermost/platform/pull/3054 then if the error is fixed then we can close this.

**Comment by crspeller** [comment]
Sounds good.

**Comment by enahum** [comment]
Closing cause this issue was fixed with #3054

**Pull request closed without merging**
