### PR TITLE
[PLT-6394] [...] menu no longer hides when not hovered.

### PR DESCRIPTION
**Pull request by kulak-at**
#### Summary
[...] menu no longer hides when not hovered (on right panel)

#### Ticket Link
https://github.com/mattermost/platform/issues/6296

#### Checklist

- [X] Has UI changes

### CODE REVIEW

**Comment by jasonblais** [comment]
Thanks for the contribution! 

Our review process is a little delayed given the upcoming release. We'll have PM review completed by the end of this week.

**Comment by grundleborg** [comment]
@asaadmahmood please could you review this one as it's a CSS only change?

**Comment by asaadmahmood** [comment]
@kulak-at This fix seems fine for a quick fix, but if you look at the behaviour in the center channel, there's a `post--hovered` class that is applied to the post who's menu is toggled. We would preferably need that same behaviour on comments as well. With this current fix, the post who's menu is open is not highlighted, and the emoji reactions icon (if enabled) dissapears if you hover over another post.

**Current**
screen shot 2017-05-12 at 4 19 03 pm

**Expected**
screen shot 2017-05-12 at 4 19 16 pm

**Comment by kulak-at** [comment]
@hmhealey Thank you for pointing this out. I fixed the issue - now it should behave similarly to the main chat window.

**Comment by jasonblais** [comment]
Assigning to 3.11 given we're two days from code complete - but looks like this is ready to merge otherwise with two dev approvals

**Pull request merged**
