### PR TITLE
fixed typo speical -> special, url to upgrade info

### PR DESCRIPTION
**Pull request by rompic**

### CODE REVIEW

**Comment by hmhealey** [comment]
+1 because Corey can't spell special :grinning:

**Comment by coreyhulen** [comment]
@rompic thanks for the PR.  We fixed the link on our side or can we revert that part.  We would still take the PR to correct the spelling mistakes.

**Comment by rompic** [comment]
@coreyhulen done.

**Comment by jwilander** [comment]
Hi @rompic, would you also be able to [squash your commits](http://stackoverflow.com/a/5189600) into one? It would be much appreciated

**Comment by coreyhulen** [comment]
+1

**Comment by rompic** [comment]
@jwilander done.

**Pull request merged**
