### PR TITLE
Add a notification for new messages on mobile (#5179)

### PR DESCRIPTION
**Pull request by Rudloff**
#### Summary
This PR adds a notification badge when there are unread messages but no unread mentions:
capture d ecran 2017-01-31 a 11 18 22

#### Ticket Link
https://github.com/mattermost/platform/issues/5179

#### Checklist
- [x] Has UI changes

### CODE REVIEW

**Comment by doosp** [comment]
@Rudloff 

Really appreciate your interest in our product and contribution.

I just tested and couldn't find any issue. Awesome work! 👍 

@jasonblais Would you help review when you have a chance? Thanks.

Test Summary:
1. when there's unread message (not mention). It correctly shows the read mark badge.

image

2. If there's any unread mention + at least one unread message, the number of unread mention appears correctly.
3. There's an unread message in room A, an unread mention in room B. After I check the unread mention in room B, the badge changes to unread message mark.
4. Unread message mark disappears after I check the message.

**Comment by jasonblais** [comment]
Thanks @Rudloff! Everything works as expected on a single team.

However, the experience is a little inconsistent with multiple teams:
 - If you receive an unread message in team B (while viewing team A), the red badge doesn't appear. 
 - If you receive a mention in another team, then the red badge with the correct number appears.

^ I will queue this for UX discussion to confirm the expected behaviour and respond back to you.


----

PS: Found an unrelated issue where `@here` doesn't properly trigger mentions: I've created a separate Jira ticket to track it: https://mattermost.atlassian.net/browse/PLT-5435

**Comment by jasonblais** [comment]
Thanks @Rudloff! Everything works as expected on a single team.

RESPONSE EDITED:

However, I found just one issue with multiple teams (on mobile view):

1) Join teams A and B. Open team A
2) Have another account post a message in team B (without a mention)

Observed: No red badge shown to indicate unread messages in team B.
Expected: Red badge shown.

NOTE: This works if the other account in step 2 posts a mention: the red badge with the correct count is shown.

----

PS: Found also an unrelated issue where `@here` doesn't properly trigger mentions: I've created a separate Jira ticket to track it: https://mattermost.atlassian.net/browse/PLT-5435

**Comment by Rudloff** [comment]
@jasonblais I've updated my PR to fix this issue.

**Comment by jasonblais** [comment]
@Rudloff I'm using mobile on `master` and the unread message indicator is so nice...thank you!

**Pull request merged**
