### PR TITLE
Fix typo on help text

### PR DESCRIPTION
**Pull request by jasonblais**
Fix typo on `allow anyone to join this team` help text.

### CODE REVIEW

**Comment by jwilander** [comment]
You'll actually need to fix this in `webapp/i18n/en.json` as well. Search for `general_tab.openInviteDesc` and you'll find the string

**Comment by jasonblais** [comment]
Thanks, fixed

**Comment by jwilander** [comment]
+1

**Comment by enahum** [comment]
+1

**Pull request merged**
