### PR TITLE
Merge release-4.0 back into master

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
Merge release-4.0 back into master

#### Checklist
- [x] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by hmhealey** [comment]
@saturninoabril It looks like you might need to merge the release-4.0 branch of the enterprise repo first.

Also, we need to make sure to merge this without squashing it so we don't lose the commit history and make any potential future merges even harder

**Comment by coreyhulen** [comment]
Leaving this one for CS.

**Comment by coreyhulen** [comment]
Leaving this one for @crspeller

**Comment by saturninoabril** [comment]
Closing this PR. @crspeller to handle separately.

**Pull request closed without merging**
