### PR TITLE
Add pull-left and pull-right to autocomplete command suggestions.

### PR DESCRIPTION
**Pull request by trashcan**
Fix for https://github.com/mattermost/platform/issues/844

### CODE REVIEW

**Comment by it33** [comment]
Thanks @trashcan for the pull request! 

Before we can review, we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**

This is a standard procedure for many open source projects. Your form should be processed within 24 hours and reviewers for your pull request will be able to proceed. 

Please let us know if you have any questions. 

We are very happy to have you join our growing community!

**Comment by trashcan** [comment]
I'm on there, as of today ;).

**Comment by it33** [comment]
Perfect!

**Comment by crspeller** [comment]
+1

**Comment by asaadmahmoodspin** [comment]
+1 Changes look good.

**Pull request merged**
