### PR TITLE
translations PR 20170306

### PR DESCRIPTION
**Pull request by enahum**
Ideally this PR should be review by community members for each language.

Note: In the event that you see an english translation instead of the desired language is because this PR was submitted before the translation was made on the Mattermost Translation Server and probably will be submitted for the next PR.

### CODE REVIEW

**Comment by jasonblais** [comment]
@grundleborg Please merge this prior to cutting RC1 -- I'll leave it open for a few hours if we get community members reviewing it in the meantime

**Comment by crspeller** [comment]
@enahum Conflict that needs to be resolved.

**Comment by enahum** [comment]
@crspeller rebased
@jasonblais fix the issue with zh_TW

**Comment by kaakaa** [comment]
`ja` LGTM

**Pull request merged**
