### PR TITLE
Update permalink error message

### PR DESCRIPTION
**Pull request by esethna**
[Discussed in UX](https://pre-release.mattermost.com/core/pl/oe1ac4j4wpgppfmg1s3rafcddh) to clarify error message for if permalink post is deleted.

### CODE REVIEW

**Comment by it33** [comment]
Thanks @esethna, propose: 

`Permalink belongs to a message that has been deleted or exists in a channel you do not have access to` > `Permalink belongs to a message that was deleted or that was posted in a channel to which you do not have access.`

Original message: 

image

**Comment by esethna** [comment]
Updated

**Comment by it33** [comment]
+1 thanks @esethna!

**Comment by crspeller** [comment]
+1

**Comment by jwilander** [comment]
+1

**Pull request merged**
