### PR TITLE
translations PR 20170313

### PR DESCRIPTION
**Pull request by enahum**
Ideally this PR should be review by community members for each language.

Note: In the event that you see an english translation instead of the desired language is because this PR was submitted before the translation was made on the Mattermost Translation Server and probably will be submitted for the next PR.

### CODE REVIEW

**Comment by cpanato** [comment]
pt-BR looks good  :P

**Comment by grundleborg** [comment]
@enahum is this PR meant to be merged before the 3.7.0 release?

**Comment by enahum** [comment]
Yes it for 3.7 you can merge it now if you want

**Comment by jasonblais** [comment]
@enahum can you help rebase against `master`?

Thanks @meilon and @cpanato for the review!

**Comment by enahum** [comment]
I'll just submit another PR

**Pull request closed without merging**
