### PR TITLE
PLT-5100 add member count to direct message list

### PR DESCRIPTION
**Pull request by jsfeb26**
#### Summary
Adds member count in direct message modal
Requires mattermost/mattermost-redux#192

#### Ticket Link
JIRA Ticket: https://mattermost.atlassian.net/browse/PLT-5100
Github Issue: #6521 

#### Checklist
- [x] Added or updated unit tests (required for all new features)
- [x] Added API documentation (required for all new APIs) (mattermost/mattermost-api-reference#267)
- [x] All new/modified APIs include changes to the drivers
- [x] Has UI changes

### CODE REVIEW

**Comment by jsfeb26** [comment]
@esethna pushed some changes to show the correct value when searching. But there still seems to be some issues in the way the `user_store` is returning the user list. When I open the modal it shows "50 of 92" when it really should be "50 of 899". Then if I hit the next button or do a search the total users will increase until it eventually reaches 899. I'm really not sure how that store is working, but it looks like it's partially loading more each time I call it.

**Comment by jasonblais** [comment]
@jwilander  Would you be able to help @jsfeb26 on his note above, since you worked on the modal recently?

**Comment by jsfeb26** [comment]
I did some more digging and I think i found out why the store only has a some of the users and then adds more every time i change the page. 

On `componentDidMount` it loads 100 users https://github.com/mattermost/platform/blob/master/webapp/components/more_direct_channels/more_direct_channels.jsx#L81

And on `handlePageChange` it loads an additional 50 https://github.com/mattermost/platform/blob/master/webapp/components/more_direct_channels/more_direct_channels.jsx#L181

So if I bump the page size to a really high number the store will have more users. But I'm still having an issue where the response can only contain a max of 200 users.
screen shot 2017-06-17 at 12 23 07 pm

**Comment by esethna** [comment]
Thanks for looking into this @jsfeb26. This is likely a result of performance concerns. Adding @jwilander to see what we can do here.

**Comment by jwilander** [comment]
Hi @jsfeb26, apologies for the late response. This is indeed because of performance concerns that we limit the number of users that can be loaded at one time. The way we do this for team/channel specific modals is to use `/teams/{team_id}/stats` or `/channels/{channel_id}/stats` endpoints which will return the total users in a team/channel. To add the total user count here we would need to add a new endpoint for system-wide user, something like `/system/stats` or `/users/stats`

**Comment by esethna** [comment]
@jsfeb26 please let us know if you have any questions

**Comment by jsfeb26** [comment]
@jwilander I see. As I understand the direct messages would be only with people within a team, so the team endpoint you listed would be the one to use. @esethna do you know if that is correct, that the direct messages modal would only be messages within a team?

**Comment by esethna** [comment]
@jsfeb26 direct messages are not connected to teams. However, the users that DMs can be started with depends on the System Console setting "Enable users to open Direct Message channels with:". If this is set to all users on the server, then the number in the direct messages modal must reflect all the users on the server. If this is set to "Any member of the team", then the number in the direct messages modal must reflect the users in the team only.

image

**Comment by jsfeb26** [comment]
@esethna I'll have to add a `/system/stats` or `/users/stats` endpoint then. I'll try to do this on the weekend

**Comment by jsfeb26** [comment]
Added an endpoint to get total user count and added another pr for redux to use the new endpoint. Not sure if this is good, I've never done any Go before

**Comment by esethna** [comment]
Thanks @jsfeb26, added "Awaiting PR" label until the redux PR is merged.

**Comment by esethna** [comment]
Closing this PR due to inactivity on the redux PR. Please let us know if you're interested in continuing to work on it.

**Pull request closed without merging**
