### PR TITLE
EE: PLT-3747 Add create_channel to command line

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
Ability to add public channels and private groups using the CLI

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-3747

#### Checklist
- [x] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [ ] All new/modified APIs include changes to the drivers
- [ ] Has enterprise changes (please link)
- [ ] Has UI changes
- [ ] Includes text changes and localization files updated
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by coreyhulen** [comment]
Needs a unit test like https://github.com/mattermost/platform/blob/master/api/cli_test.go#L138

**Comment by enahum** [comment]
cool I'll add it, actually I looked for an example and didn't find one.

Thanks.

**Comment by enahum** [comment]
@coreyhulen tests added

**Comment by jwilander** [comment]
+1, I think we can skip PM approval on CLI changes though

**Comment by enahum** [comment]
needs to be reviewed again, moved as EE feature

**Comment by jwilander** [comment]
re +1

**Comment by coreyhulen** [comment]
+1

**Pull request merged**
