### PR TITLE
PLT-3182 - Improving switch channels modal and some minor UI improvements

### PR DESCRIPTION
**Pull request by asaadmahmoodspin**
- Improved UI for switching channels modal.
- Added compact view to the RHS.
- Did improvements for compact view.

### CODE REVIEW

**Comment by hmhealey** [comment]
+1

**Comment by jwilander** [comment]
I'm working with Asaad on this one, please don't merge yet

**Comment by asaadmahmoodspin** [comment]
Done, this should probably be okay for a review now.

**Comment by jwilander** [comment]
+1

**Pull request merged**
