### PR TITLE
PLT-5897: Respect intrinsic ratio of img in emoji picker

### PR DESCRIPTION
**Pull request by VeraLyu**
Please make sure you've read the [pull request](http://docs.mattermost.com/developer/contribution-guide.html#preparing-a-pull-request) section of our [code contribution guidelines](http://docs.mattermost.com/developer/contribution-guide.html).

When filling in a section please remove the help text and the above text.

#### Summary
Changed style of img emoji picker, also fixed preview of emoji.

#### Ticket Link
jira: https://mattermost.atlassian.net/browse/PLT-5897

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Has UI changes

### CODE REVIEW

**Comment by jasonblais** [comment]
Thanks @VeraLyu! Overall looks great! Tested on Windows 10 Chrome/IE11/Firefox/Edge

Two nits:

1 - Emoji size in post view is small

It appears after posting the emoji to a channel, the emoji size renders quite small

Observed:
image

Expected (tested on `master`):
image

2 - Custom emoji do keep their aspect ratio, but it's
  - missing shadow when hovering over the emoji
  - edges are rounded/smoothed out

image
**custom emoji**

image
**standard emoji**

**Comment by VeraLyu** [comment]
Fixed problem @jasonblais mentioned and updated patch.

**Comment by jasonblais** [comment]
Really nice work @VeraLyu 

Looks like there's still two remaining issues, but otherwise all good!

1) Hovering over a custom emoji doesn't show the emoji preview unless your mouse is directly on top of the image

 - create a custom emoji
 - enable the picker and go to the bottom of the picker
 - hover over the custom emoji but keep your mouse on the shadow area, see example below where the red dot indicates where my mouse was
image

Observed: No emoji preview shown
Expected: Emoji preview shown

2) It seems alignment changes caused inconsistency in the position of emoji preview images and text

Observed: Notice that `pizza`, `hamburger` and `fries` text isn't vertically aligned
image

Expected (from `master`): The texts are vertically aligned
image

**Comment by esethna** [comment]
Thanks @VeraLyu, appreciate another pull request! Once again, just letting you know that there may be a delay in reviewing and merging your PR since we are approaching code complete for v3.8, releasing April 16th. Please see our [release process](https://docs.mattermost.com/process/release-process.html) for more details.

**Comment by VeraLyu** [comment]
@jasonblais Good catch! Fixed problem mentioned above.

**Pull request closed without merging**
