### PR TITLE
PLT-1192 Convert links in Slack attachment text to Markdown format

### PR DESCRIPTION
**Pull request by jwilander**

### CODE REVIEW

**Comment by hmhealey** [comment]
Does linkRegex just match strings of the form `<www.google.ca>`? If it does, there's no reason to replace those since that's a valid markdown link as long as it starts with http(s) or www.

**Comment by coreyhulen** [comment]
+1 other than harrisons comment.

**Comment by jwilander** [comment]
Ok, remove that type of link replacement.

**Comment by crspeller** [comment]
+1

**Pull request merged**
