### PR TITLE
plt-510 - Updating oauth register modal along with fixes for image modal

### PR DESCRIPTION
**Pull request by asaadmahmoodspin**
Hey guys have a look.

### CODE REVIEW

**Comment by hmhealey** [comment]
Looks good to me

**Comment by coreyhulen** [comment]
+1

**Comment by coreyhulen** [comment]
@asaadmahmoodspin needs rebase then it can be merged.

**Comment by asaadmahmoodspin** [comment]
Okay I need to close this PR, since Joram needs to do some changes on it first.

**Pull request closed without merging**
