### PR TITLE
Adding doc links

### PR DESCRIPTION
**Pull request by it33**

### CODE REVIEW

**Comment by coreyhulen** [comment]
@it33 

html 
ERROR   -  Error building page index.md 
Error: The page "index.md" contained a hyperlink to "../CONTRIBUTING.md" which is not listed in the "pages" configuration.
make: *** [travis] Error 1

**Comment by it33** [comment]
Thanks @coreyhulen, fixed,

**Comment by jwilander** [comment]
+1

**Comment by coreyhulen** [comment]
+1

**Pull request merged**
