### PR TITLE
Remove unneeded additional space detected by Pootle

### PR DESCRIPTION
**Pull request by wget**
#### Summary
Remove unneeded additional space detected by Pootle. Create unneeded confusion for translator as the space is highlighted as an issue in the Pootle interface.

#### Ticket Link
N/A

#### Checklist
- [x] Has UI changes
- [x] Includes text changes and localization files updated

### CODE REVIEW

**Comment by jasonblais** [comment]
+1

**Comment by jwilander** [comment]
+1

**Comment by crspeller** [comment]
@wget Do you mind rebasing this? Thanks!

**Comment by wget** [comment]
@crspeller Done! Thanks to @JanJoris for letting let me know about the `git pull myRemote master --rebase` command :-)

**Pull request merged**
