### PR TITLE
PLT-3742 Changed emoticon pattern. (:D > grinning to smile)

### PR DESCRIPTION
**Pull request by joonsun-baek**
#### Summary
Changed emoticon mapping pattern.

#### Ticket Link
[Link](https://mattermost.atlassian.net/browse/PLT-3742?jql=labels%20%3D%20good-first-contribution%20and%20Resolution%20%3D%20unresolved)

#### Checklist
- [x] Has UI changes

### CODE REVIEW

**Comment by jwilander** [comment]
Hi @joonsun-baek, thanks for the pull request! Do you mind removing the extra space you added as a test at the beginning of the README?

**Comment by joonsun-baek** [comment]
@jwilander Oh, my mistake. Please remove 'test commit'. thanks :)

**Comment by DavidLu1997** [comment]
+1, although I dislike the change personally :imp:

**Comment by jwilander** [comment]
+1

**Comment by esethna** [comment]
+1, thanks @joonsun-baek!

**Pull request merged**
