### PR TITLE
Push and Email Notifications should follow "Teammate Name Display" setting

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
Push Notifications and Email Notifications should follow "Teammate Name Display" setting

#### Ticket Link
Jira: https://mattermost.atlassian.net/browse/PLT-4760
GitHub: https://github.com/mattermost/platform/issues/4575

### CODE REVIEW

**Comment by esethna** [comment]
Thanks for the PR @cpanato!

After testing this I can't seem to get it to work. The email and push notifications I received still show the username in the notification, I tried to:

1. In account settings, I've added a full name and nickname of the account sending the mention (`@test2`)
2. In account settings > Display > Teammate name display, I've set the account receiving the notification (`@eric`) to show a) first and last name or b) nickname.

See below the name in the notification does not change:
image
image

**Comment by cpanato** [comment]
@esethna I just saw now this. I will take a look, sorry for the delay

**Comment by esethna** [comment]
@cpanato, it looks like the test@test.com account has the "Teammate Name Display" setting set to nickname? 

If you've set the name and nickname on Account 1 (@test - Hipster Name - mynicknamehipster) and then send a mention to Account 2 (@cpanato), the notification received by Account 2 should follow the "Teammate Name Display" setting for Account 2.

Sorry this should have been more explicit on the ticket.

**Comment by cpanato** [comment]
@esethna AHHH its the other way round!
ok, got it I will close this PR and revert the changes to make it as you described, ok?
If its good I will close this PR

**Comment by cpanato** [comment]
@esethna did the change, I'm working in a private branch a way to we test the sending emails, i will try to finish that till next week and that will include some tests that use the email.

**Comment by esethna** [comment]
Thanks @cpanato! Please let us know when this pull request is ready to test? For now I will apply the "work in progress" label.

**Comment by cpanato** [comment]
@esethna I just pushed the change

**Comment by esethna** [comment]
@cpanato ah okay, I misunderstood, I will queue for testing, thanks!

**Comment by esethna** [comment]
Great, thanks @cpanato it works exactly as expected with email and push notifications. I also tested that it correctly falls back to full name or username if the fields aren't set in account settings. 

+1

**Comment by hmhealey** [comment]
Nice job @cpanato!

**Pull request merged**
