### PR TITLE
PLT-3988 Add statuses to profiles pictures and remove from header in DMs

### PR DESCRIPTION
**Pull request by jwilander**
#### Summary
Adds statuses to the profile pictures in DMs to match every other channel and removes it from the channel header in DMs.

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-3988

#### Checklist
- [x] Has UI changes

### CODE REVIEW

**Comment by enahum** [comment]
For WebRTC we need to listen for the status change event in the `channel_header`

**Comment by jwilander** [comment]
Ok that's cool, when you rebase the webrtc branch feel free to add it back. I'd rather not leave it in here for now since it'd be unused and in some weird limbo state

**Comment by enahum** [comment]
Sure thing I'll add it back then.

+1

**Comment by hmhealey** [comment]
+1

**Pull request merged**
