### PR TITLE
PLT-4532: added link to Members model in channel member list

### PR DESCRIPTION
**Pull request by CrEaK**
#### Summary
Added a link to the "..."-Text to open the team-list modal 

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-4532
https://github.com/mattermost/platform/issues/4591

#### Checklist
- [x] Has UI changes

### CODE REVIEW

**Comment by jasonblais** [comment]
Big thanks @CrEaK for the contribution! Well done :) 

Tested and mostly it's working great, just two notes:

1 -  Clicking the link in channel member list opens the "Manage Members" list for the team instead of the channel

Repro:
1) Click the "person icon" next to search bar to open channel member list
2) Scroll to the bottom and click the '...'

Observed: Modal from **Main Menu > View/Manage Members** opens
Expected: Channel members modal opens, the same you get by
   - Clicking the channel name
   - Choosing "Manage Members" on the drop down list

Exception is for Town Square, which doesn't have this View/Manage Members modal yet ([we have a ticket to add it here](https://mattermost.atlassian.net/browse/PLT-4560)). In this case, it should open the modal from **Main Menu > View/Manage Members** as is currently implemented.

2 - This wasn't specified in the original ticket, so I'm okay if you don't want to make this change in this PR (I can create a separate issue for it). 

But I'm wondering if we could change '...' in the channel member list to 'View Members' or 'Manage Members' depending on the modal that opens?

Right now the '...' at the bottom of the list isn't obvious to the user that clicking it will open a new modal

image

**Comment by CrEaK** [comment]
Thanks for your feedback!
I will take a look into both points and submit the changes, no problem :+1:

**Comment by jasonblais** [comment]
Awesome, thanks @CrEaK!

**Comment by CrEaK** [comment]
I commited my changes, please have a look :)

**Comment by esethna** [comment]
Hi @CrEaK, thanks again for the PR, it's looking great! After testing the most recent changes I just have one point of feedback:

1. Regular members (non-admins) should see the text "Manage Members" in all channels except town square. This is because all channel members have the permission to remove and add members to channels. The exception in town square would be that team and system admins see "Manage Members" and regular members see "View Members", since only admins can manage users on the team, but all team members can view the member list.

**Comment by CrEaK** [comment]
Thanks @esethna for your feedback! I will have a look at it right now 👍

**Comment by CrEaK** [comment]
Thanks! I look forward to contribute more to mattermost :)

**Pull request merged**
