### PR TITLE
PLT-4606: Date separator in RHS

### LINKED ISSUE #5291: [Help Wanted] [PLT-4606] Add date separators to the right hand side to prevent dates overlapping the '...' menu on mobile right hand sidebar
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-4606)

Add date separators to the right hand side (like in the center channel).

image

The first date separator should appear below the channel name given at the top of right hand sidebar. Other date separators would appear if the date changes in the thread.

This prevents issues where the date can overlap with the '...' menu on mobile right hand sidebar (see below).

image

### PR DESCRIPTION
**Pull request by mikaoelitiana**
#### Summary
Use date separator in right hand sidebar like in main posts

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-4606

#### Checklist
- [x] Has UI changes

fixes #5291

### CODE REVIEW

**Comment by mikaoelitiana** [comment]
@jasonblais this is the replacement PR for #5351

**Comment by jasonblais** [comment]
@lindalu can you help with initial testing?

**Comment by lindalu** [comment]
@jasonblais yes, happy to! Looks great so far. Planning to finish verifying tomorrow when I can see different date separators displayed in the same thread, if that's okay time-wise.

**Comment by jasonblais** [comment]
Yeah, tomorrow totally works. Thanks @lindalu! 

Good idea to test how different date separators are displayed :+1:

**Comment by lindalu** [comment]
@jasonblais I verified today that the different date separators display in the message thread as expected in mobile view. Attaching a screenshot for reference. Overall it looks great, and no more overlap b/w date and "..." menu!

screen shot 2017-02-14 at 1 40 40 pm

**Comment by jasonblais** [comment]
Thanks all!

@mikaoelitiana Just one minor nit: the whitespace above the date separator that appears right after `MESSAGE DETAILS` is quite small.

Can we make it match the whitespace that appears for search results? See screenshots for samples

RHS (observed):
image


SEARCH (expected):
image

**Comment by mikaoelitiana** [comment]
I will fix that

**Comment by mikaoelitiana** [comment]
Just pushes the fix

**Comment by jasonblais** [comment]
@asaadmahmood please help with CSS review?

**Comment by asaadmahmood** [comment]
Correct hover effect should be added to the date separator when hovering over a post after or before it.

**Center Channel**
screen shot 2017-02-24 at 11 45 56 am

**Comment thread**
screen shot 2017-02-24 at 11 46 01 am

**Comment by jasonblais** [comment]
Hey @mikaoelitiana can you help take a look at the note above?

**Comment by mikaoelitiana** [comment]
Okay I will check that

**Comment by jasonblais** [comment]
Thanks @mikaoelitiana !

Just so you know, there may be a delay in reviewing and merging this PR as we are locking down feature and improvement contributions for the v3.7 release, per our [release process](https://docs.mattermost.com/process/release-process.html). This PR can be merged into `master` after we branch `release-3.7` on March 6th.

**Comment by mikaoelitiana** [comment]
Something went wrong in my git rebase so I had to create a new branch and a new PR #5606

**Pull request closed without merging**
