### PR TITLE
PLT-1576 display iOS device in session history

### PR DESCRIPTION
**Pull request by coreyhulen**

### CODE REVIEW

**Comment by jwilander** [comment]
+1

**Comment by crspeller** [comment]
@coreyhulen Since this will have to change when we add an android client shouldn't we have a better way to detect this?

**Comment by coreyhulen** [comment]
@crspeller android is already there (see further down).  This is just fixing it for iPhone which was detecting as unknown.  We probably should come up with a better scheme, but that's probably another PR.

**Comment by crspeller** [comment]
@coreyhulen Won't the android app show up as "Mattermost/" as well?

**Comment by coreyhulen** [comment]
@crspeller I don't think so.  The android shim is different and doesn't report it's browser as "Mattermost/"

**Comment by crspeller** [comment]
Ok. +1

**Pull request merged**
