### PR TITLE
translations PR 20170522

### PR DESCRIPTION
**Pull request by enahum**
Ideally this PR should be review by community members for each language.

Note: In the event that you see an english translation instead of the desired language is because this PR was submitted before the translation was made on the Mattermost Translation Server and probably will be submitted for the next PR.

### CODE REVIEW

**Comment by cpanato** [comment]
`PT-BR` LGTM

**Comment by wget** [comment]
I haven't applied any changes to French, but there are new French translations in the file :-/ And these are different from the ones available on Pootle. I don't understand. 
Otherwise, `fr` LGTM.

**Comment by jasonblais** [comment]
@wget do you have an example of where the translation differs from Pootle?

**Comment by wget** [comment]
@jasonblais I meant nodes like `.store.sql_job_status.delete_by_type.app_error` for which I didn't provide a translation yet, but the Pootle auto translator made its job and translated approximately. Not an issue since the strings are marked as "approximations" on pootle. Not a problem, just wanted to let you know. Sorry for disturbing :)

**Comment by jasonblais** [comment]
Thanks @wget, that sounds good. Good that it's still marked by Pootle for someone to confirm the translations.

**Pull request merged**
