### PR TITLE
Fix garbled mail subject

### PR DESCRIPTION
**Pull request by maruTA-bis5**
#### Summary
Notification email subject is garbled in Japanese.
mm-garbled-subject
For example, 20th July should be `7月 20, 2016` in Japanese. 

#### Ticket Link
There was no tickets for this PR but I thought this is obvious bug.

### CODE REVIEW

**Comment by crspeller** [comment]
+1

**Comment by jwilander** [comment]
+1

**Comment by esethna** [comment]
Thanks @maruTA-bis5! @hmhealey can you help review to make sure this doesn't conflict with your changes to email batching?

**Comment by esethna** [comment]
Hi @maruTA-bis5, we discussed this in UX meeting today. Would you mind please including the full month rather than the shortened 3 character month? This will avoid any conflicts with the email batching changes that are also going in.

**Comment by maruTA-bis5** [comment]
Thanks @esethna. Fixed in 6cfd5a1 !

**Comment by esethna** [comment]
+1

**Comment by hmhealey** [comment]
+1 for the new version

**Comment by enahum** [comment]
+1

**Pull request merged**
