### PR TITLE
Updating golang dependancies (godep)

### PR DESCRIPTION
**Pull request by crspeller**

### CODE REVIEW

**Comment by hmhealey** [comment]
I'm not sure what's happening here. Are we removing everything to switch to Go's new vendoring stuff or did the updated stuff not get added in properly?

**Comment by crspeller** [comment]
Apparently `godep update` is not the same as `godep save`. This updated the pr with more changes.

**Comment by hmhealey** [comment]
Cool. It still looks like a lot of removals, but if everything breaks, we can always just revert it

**Comment by jwilander** [comment]
+1

**Pull request merged**
