### PR TITLE
Ui improvements

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
PLT-5091 - Adding a faint border to inactive teams
PLT-5092 - Fixing dropdown in system console
PLT-4650 - Simplifying bot indicator on mobile for standard theme.

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-5091 - Adding a faint border to inactive teams
https://mattermost.atlassian.net/browse/PLT-5092 - Fixing dropdown in system console
https://mattermost.atlassian.net/browse/PLT-4650 - Simplifying bot indicator on mobile for standard theme.

#### Checklist
- [ ] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [ ] All new/modified APIs include changes to the drivers
- [ ] Has enterprise changes (please link)
- [x] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/platform/blob/master/i18n/en.json) and [.../webapp/i18n/en.json](https://github.com/mattermost/platform/tree/master/webapp/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by esethna** [comment]
Thanks @asaadmahmood, after a review:

1. There seems to be a white space issue with the `bot` indicator on desktop
image

2. The `bot` indicator on the profile picture in mobile view has strange placement. I'm wondering if we should review a few options in UX before we push this through? One option might be moving it to the bottom of the profile pic, only partly overlapping with a faint outline.

image

3. Also the flagged post icon still overlaps the [...] menu on narrow screens with long usernames. See above ^

**Comment by asaadmahmood** [comment]
1. Sure, I'll fix that.
2. That option won't work, since if I place the indicator below it, it would take up extra space, and if the bot post only has one line of content, then the bot indicator would jump into the other post.
3. It doesn't, the minimum width we support is 320px, the screenshot that you took goes even below that. My guess is, you didn't test it on a mobile device, and were just testing it on the browser.
4. It was just a scrolling issue, the dropdown was not scrolling in the system console.

**Comment by esethna** [comment]
Thanks @asaadmahmood, I think this is much better. I'm wondering if we have room to use the same codeblock formatting for mobile as on desktop? I think this would make it more consistent. It could probably overlap the profile pic slightly if it needs to?

Current Desktop:
image

Currrent Mobile:
image

Proposed Mobile:
image

**Comment by jasonblais** [comment]
Thanks @asaadmahmood, tested and all looks pretty good! 

Noticed that the "bot" tag placement breaks in Compact view (on mobile) however, see attached. Please help take a look?

image

In Compact view, propose having the bot tag next to the username - I think this should fit since we don't show the profile picture in Compact view.

**Comment by asaadmahmood** [comment]
@jasonblais Done, that's how I intended it. Nice catch.

**Pull request merged**
