### PR TITLE
Adding notice for golang-freetype

### PR DESCRIPTION
**Pull request by it33**
Also changing from .md to .txt file, and adding formatting changes, because golang-freetype license doesn't format well in .md

### CODE REVIEW

**Comment by jwilander** [comment]
Just wondering why we didn't just for the golang-freetype license to look ok in .md? .md is kind of the standard for README type files and I'd prefer to keep this one as .md if possible

**Comment by jwilander** [comment]
Or just put it into a different text file and just reference it here?

**Comment by nickago** [comment]
Also I thought we removed whatever was using freetype, so do we still need the license?

**Comment by it33** [comment]
In my mind, the purpose of the NOTICE file is to meet the attribution requirements of different open source software libraries we use, and being unambiguously correct is higher priority than using a modern formatting standard. 

1) NOTICE files at typically text, not .md

The guidance for NOTICE files (required to meet attribution requirement of Apache license http://www.apache.org/licenses/LICENSE-2.0.html#redistribution) describes them as text files and I'd tried to get fancy and make ours .md, which works for simple licenses, but this breaks with the golang-freetype license we're using because it's long and includes formatting that renders weird in .md style. 

2) golang-freetype license specifically says it must be unaltered

It's probably okay to change carriage returns to line wrap certain licenses, but to make it .md compatible we'd probably need to delete underline characters and it just walks us into a grey area that doesn't seem worthwhile. 

3) golang-freetype license requires attribution notice when we distribute in binary format

Because attribution requirements differ across libraries, it seems easiest to me to drop a NOTICE.txt file containing full licenses, which make attribution obvious and includes attribution notices, than to cherry pick from or drop the entire Godep directory. We technically don't need to drop the entire license, and can drop just an attribution notice, but in my mind, it's less risk to standardize our approach and drop the entire license via NOTICE.txt, rather than hand craft notices for different licenses we use.

**Comment by jwilander** [comment]
Ok, makes sense

**Pull request merged**
