### PR TITLE
[PLT-7219] Fix username as default for Teammate Name Display setting

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
- Fixed username as default for Teammate Name Display setting. (This should have been covered by my previous PR but unfortunately missed out ): )
- Updated `webapp/i18n/en.json`

#### Ticket Link
Jira ticket: [PLT-7219](https://mattermost.atlassian.net/browse/PLT-7219)

#### Checklist
- [x] Has UI changes
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/platform/blob/master/i18n/en.json) and [.../webapp/i18n/en.json](https://github.com/mattermost/platform/tree/master/webapp/i18n/en.json)) updates

### CODE REVIEW

**Comment by MusikPolice** [comment]
@enahum the ticket says that username is the expected default. I think @saturninoabril's change is valid here.

**Comment by saturninoabril** [comment]
@enahum related code was addressed previously by this PR (https://github.com/mattermost/platform/pull/6857/files) but just missed out the text.

**Comment by enahum** [comment]
I'm talking about this https://github.com/mattermost/platform/blob/eea64f8049d90c5dcf14a739d640f5aa6a9c7add/webapp/components/admin_console/users_and_teams_settings.jsx#L196

**Comment by saturninoabril** [comment]
@enahum thanks for pointing out! Awesome, thanks!

**Pull request merged**
