### PR TITLE
Minor bug fixes

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
PLT-6774 - Fixing color for offline icon
PLT-6784 - Fixing status icon in the header

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-6774
https://mattermost.atlassian.net/browse/PLT-6784

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [ ] All new/modified APIs include changes to the drivers
- [ ] Has enterprise changes (please link)
- [x] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/platform/blob/master/i18n/en.json) and [.../webapp/i18n/en.json](https://github.com/mattermost/platform/tree/master/webapp/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by asaadmahmood** [comment]
Guys, do not merge this, one change might be coming for the status icon in the sidebar header.

**Comment by jwilander** [comment]
Noted

**Comment by lfbrock** [comment]
@asaadmahmood this still needs to be fixed it's not centred properly.

screenshot 2017-06-08 16 57 35

screenshot 2017-06-08 16 57 14

It looks different from the screenshot you posted here: https://pre-release.mattermost.com/core/pl/f5xyheibjtr3uyqie5ju9konco

screenshot 2017-06-08 16 59 23

**Comment by esethna** [comment]
@asaadmahmood looks much better. One minor tweaks, it seems like the on-hover caret is not vertically centered:

image

**Comment by esethna** [comment]
Requesting UX approval from LB: https://pre-release.mattermost.com/core/pl/4qznnewbppymzcrm71ms4b5f3c

**Pull request merged**
