### PR TITLE
PLT-3346/PLT-3342/PLT-3360 EE: Add the ability to restrict channel management permissions

### PR DESCRIPTION
**Pull request by jwilander**
#### Summary
Adds channel management permissions to the System Console for Enterprise Edition and allow any user in Team Edition to manage channels.

#### Unit Tests
Whole bunch of them.

#### Ticket Links
https://mattermost.atlassian.net/browse/PLT-3342
https://mattermost.atlassian.net/browse/PLT-3360
https://mattermost.atlassian.net/browse/PLT-3346

### CODE REVIEW

**Comment by enahum** [comment]
+1

**Comment by jwilander** [comment]
Need to add one more piece of functionality, so marked as WIP

**Comment by esethna** [comment]
Hey @jwilander , tested and found one issue where renaming a private group can cause the header to disappear.
image

Repro: 
1) Use the channel drop down to click "Rename Channel"
2) Edit the channel name
3) Click save and notice that the channel header will disappear until something else in the UI is clicked.

**Comment by esethna** [comment]
+1 other than that. 

Tested that 
1. the setting obeys what is selected in the system console for the channel type. 
2. manage members is available for team and system admins always, regardless of system console setting
3. able to delete the group if you are the last one, relgardless of permissions

**Comment by jwilander** [comment]
Just checked and that bug is on `master` too and is unrelated to my changes in this PR. I've made a ticket [here](https://mattermost.atlassian.net/browse/PLT-3499) for it

Thanks @esethna !

**Comment by enahum** [comment]
+1 re-reviewed.

Bug found by @esethna should be fix with https://github.com/mattermost/platform/pull/3470

**Comment by coreyhulen** [comment]
+1

**Pull request merged**
