### PR TITLE
MM-1754 Modals now close upon pressing ESC

### PR DESCRIPTION
**Pull request by nickago**
Modals that needed the implementation
+ User Settings
+ Team Settings
+ Delete Post
+ Edit Post
+ Delete Channel
+ Edit Channel

### CODE REVIEW

**Comment by rgarmsen2295** [comment]
+1 looks good

**Comment by ralder** [comment]
why not just using `tabIndex="-1"` ?

**Comment by nickago** [comment]
Good suggestion @ralder, I've refactored accordingly

**Comment by crspeller** [comment]
Wow! That's a lot simpler. Seems that bootstrap has the esc button functionality built in but it needs to be activated by setting the tabIndex to -1. Thanks @ralder!

**Comment by crspeller** [comment]
@rgarmsen2295 Can you take another look at this then I will merge.

**Comment by rgarmsen2295** [comment]
Wow yeah big +1, that's awesome

**Pull request merged**
