### PR TITLE
PLT-3002 Removed Auto-capitalization on Mobile Devices

### PR DESCRIPTION
**Pull request by DavidLu1997**
Added `autoCapitalize='off` for mobile devices on:
 - Login
 - User creation
 - Changing
    - LDAP ID
    - Email
    - Nickname
    - Username

Tested on Android 5.0 and 6.0. Should work on iOS according to:
https://developers.google.com/web/updates/2015/04/autocapitalize?hl=en

### CODE REVIEW

**Comment by enahum** [comment]
+1

**Comment by crspeller** [comment]
@DavidLu1997 For the email fields would it not be better just to set their type to email? Then it should disable automatically. Plus you might get niceties from your keyboard like an easy to reach @ sign.

**Comment by DavidLu1997** [comment]
Changed to email

**Comment by crspeller** [comment]
@DavidLu1997 You don't need autocapitalize off if you have email set.

**Comment by crspeller** [comment]
+1

**Pull request merged**
