### PR TITLE
PLT-2342: Incorrect formatting of last password update string in all …

### PR DESCRIPTION
**Pull request by enahum**
…languages

### CODE REVIEW

**Comment by jwilander** [comment]
+1

**Comment by hmhealey** [comment]
+1

**Comment by hmhealey** [comment]
This needs a rebase

**Comment by enahum** [comment]
rebased!

**Comment by crspeller** [comment]
@enahum Sorry this needs a rebase again.

**Comment by enahum** [comment]
rebased

**Pull request merged**
