### PR TITLE
PLT-3153 Converted slash command triggers to lowercase on save

### PR DESCRIPTION
**Pull request by DavidLu1997**
#### Summary
Converted slash command triggers to lowercase upon save

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-3153

#### Checklist
- [ ] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [ ] Has driver changes that have been merged and package.json updated
- [ ] Has enterprise changes (please link)
- [ ] Has UI changes
- [ ] Includes text changes and localization files updated
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by jwilander** [comment]
If I create a command using /UPPERCASE, it will get changed to /uppercase on save. What happens if I type /UPPERCASE to try and use my command, does that work?

**Comment by DavidLu1997** [comment]
@jwilander Typing /UPPERCASE will not work. I can make it so that capitalization does not matter for slash commands client side.

**Comment by jwilander** [comment]
Yeah, let's do that. I think it would help avoid some user confusion and stick to our forgiving principle.

**Comment by coreyhulen** [comment]
+1

**Comment by DavidLu1997** [comment]
@jwilander changed it client side

**Comment by enahum** [comment]
+1

**Comment by enahum** [comment]
waiting approval from @jwilander

**Comment by jwilander** [comment]
+1

**Pull request merged**
