### PR TITLE
PLT-4562: add dropdown option to search

### PR DESCRIPTION
**Pull request by VeraLyu**
Please make sure you've read the [pull request](http://docs.mattermost.com/developer/contribution-guide.html#preparing-a-pull-request) section of our [code contribution guidelines](http://docs.mattermost.com/developer/contribution-guide.html).

When filling in a section please remove the help text and the above text.

#### Summary
Abstract and refactored dropdown component for post and rhs. 

#### Ticket Link
jira: https://mattermost.atlassian.net/browse/PLT-4562

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Has UI changes
- [x] Includes text changes and localization file ([.../i18n/en.json)

### CODE REVIEW

**Comment by lindalumitchell** [comment]
@jasonblais @VeraLyu one question on this, when you have a chance:

It appears that the flag icon in center is no longer toggling when I click it (on this spinmint server). It still toggles as expected in the RHS. I don't see this issue on master or pre-release, so do you think it's a result of this PR? Can you see the issue too?

Testing notes for reference:
1. [...] menu now appears in RHS in all cases: reply thread, pinned posts, at-mentions, and flagged posts
  1. Permalink
  2. Pin to channel (or Un-pin from channel)
  3. Delete (if user has permission)
  4. Edit (if user has permission)
2. Reply arrow and Jump link also still appear in RHS on pinned posts, at-mentions, and flagged posts

Before this PR:
1. Reply thread: [...] menu
2. Pinned posts, at-mentions, and flagged posts: Reply arrow and Jump link

**Comment by jasonblais** [comment]
Thanks for helping with testing! 

@VeraLyu can you take a look at the flag icon issue described above?

Only saw one UX defect, which reproduces on `master`. Filed a separate ticket to fix later: https://mattermost.atlassian.net/browse/PLT-6394

**Comment by jasonblais** [comment]
Hey @VeraLyu, how are you?

Wondering if you noticed the feedback from @lindalumitchell about not being able to flag messages? Let us know if there's anything we can help on that.

I demo'd this pull request for our team, and they loved the improvement! Really looking forward to seeing this in Mattermost

**Comment by jasonblais** [comment]
@saturninoabril  Vera let me know that you'd like to take over this PR as it's related to work you're doing at the moment?

**Comment by jasonblais** [comment]
Hey @VeraLyu, 

I'll assign a WIP label for this PR and assign the issue to @saturninoabril. 

I'll keep the branch active so Saturnino can continue from your work. 

Huge thanks for your help here!

**Comment by saturninoabril** [comment]
@VeraLyu @jasonblais closing this PR; works were continued at PR #6663.

**Pull request closed without merging**
