### PR TITLE
PLT-480 Use `Utils.displayUsername` for username renderings

### PR DESCRIPTION
**Pull request by gabel**
(fixes https://github.com/mattermost/platform/issues/847)

### CODE REVIEW

**Comment by coreyhulen** [comment]
+1

**Comment by jwilander** [comment]
+1

**Comment by coreyhulen** [comment]
@gabel fyi this was reverted because it was causing issues on a clean first page load.  It would get stuck with the `Loading...` message.

**Comment by gabel** [comment]
@coreyhulen OK any solution so far? I couldn't see a stuck `Loading...` behavior on my local dev box.

**Comment by gabel** [comment]
@coreyhulen I think I've managed to reproduce the problem, but it occurred randomly as well with the former line of code (see screenshot). 

bildschirmfoto 2015-11-11 um 19 18 07

**Comment by coreyhulen** [comment]
Thanks,  I think this is being tracked in several different places

https://github.com/mattermost/platform/issues/1343
https://mattermost.atlassian.net/browse/PLT-995

**Pull request merged**
