### PR TITLE
PLT-6098 Added Manage Teams modal to System Console users list

### PR DESCRIPTION
**Pull request by hmhealey**
The Manage Teams modal is needed for 3.8 since we'd be losing some functionality without it (specifically, the ability for System Admins to promote/demote Team Admins and remove users from teams).

This is based upon #5882 so changes specific to this one are here: https://github.com/mattermost/platform/compare/PLT-2713c...PLT-6098

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-6098

#### Checklist
- Has UI changes
- Includes text changes and localization file ([.../i18n/en.json]

image

### CODE REVIEW

**Comment by hmhealey** [comment]
@esethna What are you waiting on me to do with this PR?

**Comment by esethna** [comment]
Thanks Harrison, Just minor tweaks:

1. Can you please move the "System Admin" text to be right justified at the same level as the "Remove From Team" button?
image

2. Please unbold the dropdowns (but leave the team names bolded)

image

3. The words "Manage Teams" and "Team Member" don't seem to be localized yet. Just making sure they are covered once a translation PR goes in?

**Comment by hmhealey** [comment]
@esethna 
1. Should I change the spacing on the left side as well? The text and profile picture are both lined up with the lines between teams, not the text for each team
2. Oops. I'll fix that
3. Those will be handled when the translators get to them, but that'll be after this PR goes in to add them to en.json

**Comment by esethna** [comment]
@hmhealey I think the left side looks fine since it is a profile picture and teams nest under accounts in our heirarchy. The right side just looks awkward because it is text

**Pull request merged**
