### PR TITLE
Rename last private group reference to private channel

### PR DESCRIPTION
**Pull request by jasonblais**
#### Summary
Rename last private group reference to private channel

@hmhealey @enahum  Not sure if this change will need to be somehow reflected on the mattermost-mobile repo?

#### Ticket Link
N/A (kudos to @lindalumitchell for catching)

#### Checklist
- [X] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/platform/blob/master/i18n/en.json) and [.../webapp/i18n/en.json](https://github.com/mattermost/platform/tree/master/webapp/i18n/en.json)) updates

### CODE REVIEW

**Comment by enahum** [comment]
That one needs to be done in the other repo

**Comment by jasonblais** [comment]
How is it going to be reflected on the platform repo? I'm not sure I understand the flow

**Comment by enahum** [comment]
Ok let me explain.

Sync translations to the translations server
1. Grab everything from `i18n/en.json` and `webapp/i18n/en.json` from platform repo
2. Grab everything from `app/i18n/en.json` from mattermost-mobile repo
3. push `i18n/en.json` changes from platform into the translation server
4. merge `webapp/i18n/en.json` with `app/i18n/en.json` taking everything non prefixed with mobile from webapp and all `mobile` prefixed from the app and create a new en.json file
5. push the new merge file to translation server

Submit PR with translations
1. Take everything that belong to the server and create the files for `i18n` and `webapp` and make a PR to platform
2. Take everything that belongs to webapp+app and create files for both `webapp/i18n` and `app/i18n` and make a PR to both platform and mattermost-mobile

**Comment by jasonblais** [comment]
Thanks, that's helpful!

**Pull request closed without merging**
