### PR TITLE
PLT-4907 Sort teams alphabetically by Display Name on Team Selection Page

### PR DESCRIPTION
**Pull request by debanshuk**
#### Summary
Sorting user's teams and other teams alphabetically by Display Name on Team Selection Page in front-end (JS).

#### Ticket Link
JIRA Ticket: https://mattermost.atlassian.net/browse/PLT-4907
Gihub issue: #4713

### CODE REVIEW

**Comment by jasonblais** [comment]
Thanks @debanshuk!! [Starting the review process](https://github.com/mattermost/platform/blob/master/CONTRIBUTING.md#review-process-for-this-repo).

**Comment by it33** [comment]
Technically, this PR is correct, as the team selection page is alphabetically ordered: 

image

However other places where teams appear are not ordered, in System Console: 

image

and in Main Menu: 

image

There needs to be a decision whether we open another ticket for the other changes, because this PR makes the ordering inconsistent.

**Comment by debanshuk** [comment]
@it33, I agree that teams need to be in same order at all places mentioned by you. I can update my PR to include same sorting in all these places, as used in team selection page. Though I would prefer to add sorting at the back-end API (in the query itself) instead of at multiple places in front-end. I tried that while working on this PR too, but fount that currently the team list API returns teams as an object with ids as attributes. To achieve back-end sorting teams object would have to be converted to an array and all the places where the team list API is being used would need to be updated accordingly.

So, in your opinion which approach would be better adding sorting in API and updating it's response format or adding sorting at multiple places in front-end?

**Comment by debanshuk** [comment]
@it33, Shall I implement sorting in the other places mentioned by you in this pull request (at the front-end for now, as doing back-end sorting would be big change) or shall I leave the pull request as it is?

**Comment by it33** [comment]
Thanks @debanshuk, highly appreciate your help, 

I've asked @coreyhulen and the core committers their opinion: https://pre-release.mattermost.com/core/pl/ijorfgpuwigs58krxs3nayp6ge

Sorry for the late reply,

**Comment by it33** [comment]
Also, really great work!

**Comment by enahum** [comment]
Oh definitely it should be done in the front-end as changing the API's would mean a change in the return object and that can be a pain, also it will break existing integrations and such...

**Comment by jasonblais** [comment]
Thanks @debanshuk, great work here!

I have created a Help Wanted issue to resolve the ordering in two of the System Console screens: https://github.com/mattermost/platform/issues/4775. It's up to you if you'd prefer to work on #4775 on a separate PR or add them here, either works.

The ordering in the Main Menu will be resolved by team sidebar PR #4569, so we don't need to worry about that one.

**Comment by debanshuk** [comment]
@jasonblais, Thanks for the update. Sure I would like to work on #4775 and I guess I'll create a new PR for that issues as it's different issue and has a different JIRA ticket.

**Comment by jasonblais** [comment]
Sure thing! Thanks again @debanshuk, I'll queue this for dev review next

**Comment by hmhealey** [comment]
Thanks for the fix @debanshuk! That's always bugged me that they were out of order

**Pull request merged**
