### PR TITLE
Makefile: fix for non-enterprise build

### PR DESCRIPTION
**Pull request by chengweiv5**
Signed-off-by: Chengwei Yang <yangchengwei@qiyi.com>

### CODE REVIEW

**Comment by jwilander** [comment]
@crspeller please take a look

**Comment by crspeller** [comment]
@chengweiv5 Is this for the golang unit tests? If so it should probably go under go-test and not be a modification of this section.

**Comment by chengweiv5** [comment]
@crspeller I build mattermost.tar.gz from source code and found that this target will print **nomv** since apparently there isn't files that only for enterprise version. So this patch just fix this small problem for local build.

**Comment by crspeller** [comment]
Oh I see I read that backwards. Looks good +1

**Pull request merged**
