### PR TITLE
Fix deadlink to AWS file in doc

### PR DESCRIPTION
**Pull request by LAndreas**
Fix deadlink to AWS file in doc

### CODE REVIEW

**Comment by it33** [comment]
Hi @LAndreas, thanks for the change! Before we can review, we just need your help completing the CLA here: http://www.mattermost.org/mattermost-contributor-agreement/

To thank you for being among the first 100 contributors, we'll be sending you a personalized mug as a thank you gift once the commit is accepted: http://forum.mattermost.org/t/limited-edition-mattermost-mugs/143

**Comment by it33** [comment]
Whoops, wrong button... didn't mean to close.

**Comment by LAndreas** [comment]
Hi @it33,
i've completed the CLA. :)

**Comment by crspeller** [comment]
+1 for working links.

**Comment by jwilander** [comment]
+1

**Comment by it33** [comment]
Thanks @LAndreas!

**Pull request merged**
