### PR TITLE
auto-link mentions with user names having symbols

### PR DESCRIPTION
**Pull request by girishso**
this also handles the case where user_name is having '_'

rel #1130

### CODE REVIEW

**Comment by it33** [comment]
@girishso Thank you! Awesome!

**Comment by girishso** [comment]
:)

**Comment by hmhealey** [comment]
Only problem with this is that it breaks mentioning people at the end of a sentence so something like `@girishso.` isn't linked because it considers the period to be part of the username. I think @trashcan had the right idea [here](https://github.com/mattermost/platform/issues/1130#issuecomment-150094942) where he was going to just remove any trailing punctuation one-by-one to see if if finds a valid username.

Otherwise, it looks good. I'm a bit nervous about adding more formatting code to MarkdownRenderer.paragraph since the text parameter has already been passed through doFormatText in pieces, but I wasn't able to break anything when I tried so it should be fine for now.

**Comment by trashcan** [comment]
I worked on this a bit more last night but its not ready yet, sorry. I have
a regex that detects punctuation at the end of words (including Unicode).
Do we also want to handle the situation where there is something other than
a space before an @?

**Comment by girishso** [comment]
@hmhealey I am not sure how pragmatic it is to send `n` number of requests to server to find a valid username. If at all you want to proceed this way, the right place in my opinion is to implement this in Go server itself.

**Comment by hmhealey** [comment]
@girishso Ignore what I said about needing to remove trailing punctuation from the mention. I just merged #1171 and it covers that. This just needs a rebase and then it'll be good to go.

**Comment by crspeller** [comment]
_1

**Pull request merged**
