### PR TITLE
Moves up command list

### PR DESCRIPTION
**Pull request by kernicPanel**
After https://github.com/mattermost/platform/pull/1389 command list is overlapping textbox.
This PR fixes this.

### CODE REVIEW

**Comment by jwilander** [comment]
+1

**Comment by asaadmahmoodspin** [comment]
No need for this PR. 
I've submitted a PR: https://github.com/mattermost/platform/pull/1406
This PR will fix the UI issues caused by the preview links and then it will work with the same positioning for the command list.

**Comment by jwilander** [comment]
Closing then, but thanks for the effort anyways @kernicPanel :)

**Comment by kernicPanel** [comment]
Nice, it was a quick fix, as I worked on something else :)

**Pull request closed without merging**
