### PR TITLE
Plt 3475 - Post control improvements

### PR DESCRIPTION
**Pull request by asaadmahmoodspin**
#### Summary
- Makes the background of a highlighted post different to the background of current user posts.
- Added the behaviour now so the dropdown would not close until you click elsewhere. So it's really easy to hover around without worrying.

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-3475

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields.]
- [ ] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [ ] Has driver changes that have been merged and package.json updated
- [ ] Has enterprise changes (please link)
- [x] Has UI changes
- [ ] Includes text changes and localization files updated
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

This goes in 3.2.

### CODE REVIEW

**Comment by asaadmahmoodspin** [comment]
We can also setup a test server to test it out.

**Comment by jwilander** [comment]
+1

**Comment by enahum** [comment]
+1

**Comment by jasonblais** [comment]
+1: tested the following behaviour: `Added the behaviour now so the dropdown would not close until you click elsewhere. So it's really easy to hover around without worrying.`

**Pull request merged**
