### PR TITLE
Slash commands accept Slack format

### PR DESCRIPTION
**Pull request by ZJvandeWeg**
Until this commit the slash commands only accepted 'text' properties.
For better styling however, Slack formatting support was added.

However, ephemeral messages are not supported, and only text will be
displayed.

### CODE REVIEW

**Comment by jwilander** [comment]
This completes #4238

**Comment by ZJvandeWeg** [comment]
@jwilander Is there a way to get this a milestone earlier? 

Also, what would be the best way to discuss [the ephemeral issue](https://pre-release.mattermost.com/core/pl/of39bfnfspnjjxscdd9qkhtq4c)? Should I open a new issue?

**Comment by jwilander** [comment]
We're past code complete for 3.6 and are currently only accepting high priority bugs for 3.6. I can bring it up in daily triage but policy isn't to accept improvements or new features this late in the release cycle.

As for the ephemeral issue, I was just about to respond to your post on pre-release. Let's chat there so it's more real time

**Comment by ZJvandeWeg** [comment]
Closes in favour of #4999

**Pull request closed without merging**
