### PR TITLE
MM-1497 image thumbnails now scale appropriately so there is no whitespace

### PR DESCRIPTION
**Pull request by jwilander**
Also generalized some thumbnail loading code so the RHS posts loaded thumbnails properly. Tested on all major browsers (Chrome, FF, Safari, IE10+).

Edited the config.

### CODE REVIEW

**Comment by hmhealey** [comment]
The serverside changes look good, but the clientside changes will probably be unnecessary since I've redone most of that code in #271 .

**Comment by coreyhulen** [comment]
looks good, I see some merge pain coming with hmhealey's changes.

**Comment by jwilander** [comment]
I'll remove the client changes since they won't be needed after #271 is in

**Comment by coreyhulen** [comment]
waiting on https://github.com/mattermost/platform/pull/271

**Comment by jwilander** [comment]
Ready for re-review

**Pull request merged**
