### PR TITLE
PLT-3568 Fixed highighting at all mentions when enabled

### PR DESCRIPTION
**Pull request by hmhealey**
#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-3568

### CODE REVIEW

**Comment by crspeller** [comment]
This fix doesn't make sense at first glance. Can you explain please?

**Comment by hmhealey** [comment]
It's just that we used to have separate settings for enabling `@all` and `@channel` before (notify_props.all and notify_props.channel respectively), but now there's just a [single setting for both](https://github.com/mattermost/platform/blob/master/api/post.go#L521).

**Comment by crspeller** [comment]
+1

**Comment by jwilander** [comment]
+1

**Pull request merged**
