### PR TITLE
Added babel-es6-polyfill

### PR DESCRIPTION
**Pull request by hmhealey**
Adds polyfills for ES6 functions such as string.prototype.startsWith so they're supported on browsers that don't implement them (like IE11 and Safari). Just requiring the library at the code's entry point adds them.

### CODE REVIEW

**Comment by crspeller** [comment]
You found the polyfills! Yay!

@hmhealey Is there any way to include these globally instead of in a bunch of root files? Seems like bad form to do it this way.

**Comment by hmhealey** [comment]
I'm pretty sure there's an option to just include it in the header. I'll check that out.

**Comment by coreyhulen** [comment]
+1 other than crspellers comment

**Comment by hmhealey** [comment]
Okay I've changed it around so that instead of being included as an NPM dependency and importing it everywhere, it's just included in a <script> tag in the header of all mattermost pages. This also has the added benefit of being exposed to the developer console of all browsers when debugging.

**Comment by crspeller** [comment]
Perfect!

**Pull request merged**
