### PR TITLE
Fixed typo in single-container-install.md

### PR DESCRIPTION
**Pull request by chengkun**
Remove the typo of quotation marks after 'docker-machine create -d virtualbox dev'

### CODE REVIEW

**Comment by it33** [comment]
Thanks for the pull request! 

Before we can review, we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**

This is a standard procedure for many open source projects. Your form should be processed within 24 hours and reviewers for your pull request will be able to proceed. 

Please let us know if you have any questions. 

We are very happy to have you join our growing community!

**Comment by it33** [comment]
Hi @chengkun, just circling back, any questions on the process for adding you as an approved contributor?

**Comment by chengkun** [comment]
Hi @it33 , just back from vocation, I have submitted the agreement. Great to be a contributor even just a tiny fix.

**Comment by it33** [comment]
Every fix improves the product, ever fix matters, thank you @chengkun!

**Pull request merged**
