### PR TITLE
PLT-3725 Removed /shortcuts from mobile apps

### PR DESCRIPTION
**Pull request by DavidLu1997**
#### Summary
`/shortcuts` no longer appears in the slash command autocomplete on mobile devices. Typing `/shortcuts` will return an error `Keyboard Shortcuts are not supported on your device.`.

Other changes
- Fixed `UserAgent.isMobileApp()` not working as intended
- Added `isIos()` and `isAndroid()` to `user_agent.jsx`
- Rewrote logic for special `/shortcuts` handling

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-3725

#### Checklist
- [x] Includes text changes and localization files updated

### CODE REVIEW

**Comment by enahum** [comment]
+1

**Comment by jwilander** [comment]
+1

**Comment by DavidLu1997** [comment]
Rebased, first time I've see a merge conflict in `en.json`...

**Comment by enahum** [comment]
DL thats almost my day to day fixing conflicts in localizations

**Pull request merged**
