### PR TITLE
PLT-3461 Add notification settings to control what statuses allow push notifications

### PR DESCRIPTION
**Pull request by jwilander**
#### Summary
Add notification settings to control what statuses allow push notifications.

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-3461

#### Checklist
- [x] Has UI changes
- [x] Includes text changes and localization files updated

### CODE REVIEW

**Comment by coreyhulen** [comment]
+1, needs rebase

**Comment by enahum** [comment]
+1 still needs rebase

**Comment by esethna** [comment]
+1, tested on the spinmint fired before conflicts. Looks great!

**Comment by jwilander** [comment]
Argh, I did rebase before and had to do it again :P

**Pull request merged**
