### PR TITLE
MM-1657 Removes tag highlighting for mentions

### PR DESCRIPTION
**Pull request by rgarmsen2295**
Removes the blue tag highlighting from mentions that would appear after typing a mention.

### CODE REVIEW

**Comment by jwilander** [comment]
There's actually a lot more you can rip out. There's no longer a need for the hidden div that mimics the textbox, so you can get rid of that and anything that manipulates it as well.

**Comment by rgarmsen2295** [comment]
OK, I figured there was probably more, I tried to be pretty conservative with what I was cutting out; I meant to mention you and Corey to see who had originally implemented it to get your opinion on what else could be cut but must have forgot.  I'll rip out all the textdiv stuff and comment back here when it's ready for another look.

**Comment by rgarmsen2295** [comment]
Removed code that worked with the pseudo-textbox as described, please take another look when you get a moment and let me know if there's anything else I missed that could be cut out, thanks!

**Comment by hmhealey** [comment]
One other thing you can do is completely remove the scroll method since it's empty now. There's some other stuff that look a bit weird like the variables named e, w, and d and what appears to be stashing data in the title attribute, but that's not part of this pull request so we don't need to worry about it right now.

**Comment by rgarmsen2295** [comment]
Ugh I even remember deleting that, I must have undone it at some point, thanks for catching that.  And yeah there's definitely some stuff that could probably be cleaned up but I want to rock the boat as little as possible for the release :)

**Comment by rgarmsen2295** [comment]
Ok take another look when you get a chance, thanks!

**Comment by hmhealey** [comment]
Looks good now. Ready for merge.

**Comment by jwilander** [comment]
+1

**Pull request merged**
