### PR TITLE
GIT-1806 - Fixes the notification display in Firefox

### PR DESCRIPTION
**Pull request by GuillaumeAmat**
refs #1806

### CODE REVIEW

**Comment by jlebleu** [comment]
Sorry, but it still does not work for me, working for my collegues, I don't know how to investigate ....

**Comment by GuillaumeAmat** [comment]
@jlebleu are tou sure you had allowed Mattermost to display notifications? I mean the first time it wanted to, when Firefox asked you to display or not notifications from Mattermost.

**Comment by GuillaumeAmat** [comment]
@jwilander @lfbrock Any clue about when this fix will be merged into master?

**Comment by jwilander** [comment]
Hi @GuillaumeAmat, sorry for the delay. We're in the middle of a release at the moment so we're a bit slow on PRs not critical to the release. We'd also like to see a some other community members confirm that the fix worked for them since we were unable to reproduce the issue. As soon as we have that (and the release is out) then this should go in pretty quick.

**Comment by GuillaumeAmat** [comment]
I perfectly understand ;)
Thank you.

**Comment by it33** [comment]
Hi @GuillaumeAmat, can you let us know on which operating system and browser this fixes the issue of notifications not displaying? 

We can then find another community member with that set up to verify.

**Comment by GuillaumeAmat** [comment]
Hi @it33, it fixes the issue on Firefox Linux and Windows. Don't know about Mac OS but it not seems to be an OS related issue.

**Comment by jwilander** [comment]
Looks like this also needs a rebase now. @GuillaumeAmat could you give it one?

**Comment by tomswartz07** [comment]
It's working for me as well.

**Comment by it33** [comment]
We need two reviewers to confirm a fix works for a [supported platform (specifically FireFox 38+ on Windows 7+)](http://docs.mattermost.com/install/requirements.html#pc-web-experience) before we can merge this PR. 

Not trying to be difficult, we just have a standard process to ensure quality. The "Needs Review" and "Needs Seconder" labels get removed after testing and review is done: 

image

Any volunteers from the community to help with testing this? 

@crspeller, I imagine you took down the test server on account of changes we discussed this morning to automation, when you have a chance, could you fire up another test server so anyone on the community can help with this? 

@tomswartz07, thanks for confirming the fix for Firefox on Arch, odds are this fix will work, we just need to confirm the fix for Firefox on Windows is working.

**Comment by crspeller** [comment]
@it33 Whenever the rebase is done feel free to set another setup test server label.

**Comment by GuillaumeAmat** [comment]
@jwilander It's done

**Comment by jwilander** [comment]
@GuillaumeAmat I think there was an issue with your rebase, I'm seeing 2000+ line changes and a whole wack of old commits being included

**Comment by GuillaumeAmat** [comment]
@jwilander Old commits? I didn't check their dates...
I don't understand what has caused the mess. Just pulled last commits from mattermost/platform:master to my fork's master and rebased the PR branch with it.

It will be much faster/easier to delete the PR and recreate it. Your opinion?

**Comment by jwilander** [comment]
Feel free to recreate the PR and link to this one

**Comment by GuillaumeAmat** [comment]
Here it is! #2249

**Pull request closed without merging**
