### PR TITLE
Reverting change css function

### PR DESCRIPTION
**Pull request by asaadmahmood**
Hey guys, have a look. Just reverting the css function change.

### CODE REVIEW

**Comment by enahum** [comment]
Why are we reverting this?

**Comment by asaadmahmood** [comment]
Because the code wasn't working as intended. The current code actually duplicates tags everytime we update it.

**Comment by hmhealey** [comment]
Is it possible to fix the new code instead of outright reverting it? Maybe contact pepf to see if he can fix it since he made those changes in the first place

**Comment by asaadmahmood** [comment]
Did ask him but he didn't didn't provide any suggestions.

**Comment by asaadmahmood** [comment]
@pepf found the issue with the insertrule(), he's going to submit a PR to fix it.

**Pull request closed without merging**
