### PR TITLE
GH-5855 User 'props' attributes should be visible

### LINKED ISSUE #5855: User 'props' attributes should be visible
#### Summary
According to v3 REST API, fetching a User should reveal any 'props' it has.

#### Steps to reproduce
v3.7.3

#### Expected behavior
If I have added one or more custom 'props' key/values to a user, I would expect to be able to see those keys/values when I receive the JSON representing the user.

#### Observed behavior
The JSON has no 'props' attributes for any users after a GET request.

#### Possible fixes
The problem is due to User.ClearNonProfileFields method in user.go. This is from a patch I will be submitting to resolve the issue in a configurable way that retains current behavior unless overridden in a Mattermost configuration setting:

```
@@ -325,7 +335,6 @@ func (u *User) ClearNonProfileFields() {
 	u.MfaSecret = ""
 	u.EmailVerified = false
 	u.AllowMarketing = false
-	u.Props = StringMap{}
 	u.NotifyProps = StringMap{}
 	u.LastPasswordUpdate = 0
 	u.LastPictureUpdate = 0
```

### PR DESCRIPTION
**Pull request by BRH-Enrian**
#### Summary
Fixes #5855 - User 'props' attributes should be visible

#### Ticket Link
#5855  

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x ] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [ ] All new/modified APIs include changes to the drivers
- [ ] Has enterprise changes (please link)
- [ ] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/platform/blob/master/i18n/en.json) and [.../webapp/i18n/en.json](https://github.com/mattermost/platform/tree/master/webapp/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by jasonblais** [comment]
@BRH-Enrian @bradhowes Can you help take a look at the build failure? I've re-triggered the build in case it was an issue in the build process

**Comment by enahum** [comment]
@BRH-Enrian can you please rebase this PR?

**Comment by esethna** [comment]
Thanks @BRH-Enrian, appreciate the pull request!  Just letting you know that there may be a delay in reviewing and merging your PR since we are approaching code complete for v3.8, releasing April 16th. Please see our [release process](https://docs.mattermost.com/process/release-process.html) for more details.

**Comment by hmhealey** [comment]
Hi @BRH-Enrian,

We appreciate the PR, however we're actually looking at moving away from the simple `User.Props` field to an `ExtraProps` table will allow assigning these for all different types of objects (users, channels, etc). We'd rather not accept your changes just to blow them away in a month or so when we go to this new model, breaking everything that's been built to rely on these. Would you have any interest in helping with the newer version instead? An early spec for the feature is [here](https://docs.google.com/document/d/1ZyYyb_rqAYf4WO2BRycBoKijwABApu57wyNk7jiU5kg/edit#heading=h.lw6zytz8beh9)

**Comment by BRH-Enrian** [comment]
Hi @hmhealey 

That's fine with me. I understand that my patch targets a specific use-case and lacked features for a general release. I'm certainly willing to help out with the newer version when time permits.

**Comment by jasonblais** [comment]
Thanks again @BRH-Enrian for the pull request,

I'll close this one based on @hmhealey note above,

If you're interested and have the time to help with the new type of custom user attributes, let us know! Would love to work with you.

As a side note, the best bet is to work on a help wanted ticket to ensure your contributions can be accepted as described in the [code contribution guidelines](https://docs.mattermost.com/developer/contribution-guide.html). The best way to discuss opening a Help Wanted ticket with the core team is by starting a conversation in the [feature idea forum](https://www.mattermost.org/feature-ideas/).

Again, really really appreciate you taking the time and effort to submit this contribution.

**Comment by gbrehmer** [comment]
@jasonblais Please review this PR again! We also need this feature to persist additional user meta data, which should be fully available to all users. We are fine with future changes (e.g. migration to a new endpoint). It should be feasible to get updates automatically (websocket updates).
Currently our fix is to remove clearing props-field in sanitizeUser Object only (removing 1 line of code).

**Comment by jasonblais** [comment]
@gbrehmer Would you have interest helping with the updated feature for it, with an early spec here? https://docs.google.com/document/d/1ZyYyb_rqAYf4WO2BRycBoKijwABApu57wyNk7jiU5kg/edit#heading=h.lw6zytz8beh9

**Pull request closed without merging**
