### PR TITLE
PLT-831 Improve file thumbnails

### PR DESCRIPTION
**Pull request by khawerrind**
#### Summary
Improve file thumbnails

#### Ticket Link
https://github.com/mattermost/platform/issues/4868

#### Checklist
- [ x] Has UI changes

### CODE REVIEW

**Comment by asaadmahmood** [comment]
Hey @khawerrind thanks for the PR, but based on the design, the image should completely be displayed in the thumbnail, and the thumbnail should size according to the image proportions (with a max height/ max width set). Currently, all the thumbnails are of the same size, and the full image is not being shown, which was one of the major purpose of the improvement, to show the full image in the thumbnail.

**Comment by asaadmahmood** [comment]
One easy way to do it would be to include that thumbnail as an image, and that the box takes the width/height of the image, and d then we can limit it with css.
It would be pretty hard to it by specifying the width/height everytime for each thumbnail.

**Comment by jasonblais** [comment]
Hey @khawerrind, let me know if you had any questions?

This is a fantastic start, thank you for working on this! Improved thumbnails is greatly needed in Mattermost, to make them look nicer :)

**Comment by jasonblais** [comment]
hey @khawerrind, let me know if there's anything we clarify on the feature.

Also, if you're busy with other work, that's fine too. Just wanted to make sure you're not blocked on anything.

Thank you for your contributions to the Mattermost code base so far!

**Comment by jasonblais** [comment]
@khawerrind Just so you know, there may be a delay in merging this PR as we are locking down feature and improvement contributions for the v3.7 release, per our [release process](https://docs.mattermost.com/process/release-process.html). This PR can be merged into `master` after we branch `release-3.7` on March 6th.

**Comment by jasonblais** [comment]
I'll close this due to inactivity.

@khawerrind We'd love to work with you on the feature. If you're interested to continue working on it, please help re-submit a new PR for it.

**Comment by BobTB** [comment]
Oh, please can someone do this? Thumbnails are now cropped and with the wrong aspect ratio...

**Comment by kelderek** [comment]
I agree with BobTB - this should be a higher priority as the current behavior feels lack a big step backwards for Slack users.  It seems like a small thing, but it really impacts speed and user satisfaction when they they have to click to see a preview that shows images without cropping, at a decent size, and animated (if applicable).  Then they have click again to get back to what they were doing.

**Comment by 2075** [comment]
any news on this?

**Comment by jasonblais** [comment]
Thanks all for the feedback! We're working on designs, an early mockup attached. Very much a work-in-progress

image

**Comment by 2075** [comment]
great to see some progress! anywhere to support to make this happen?

**Comment by jasonblais** [comment]
@2075 This might be one (although, there might be other feature proposals for it too): https://mattermost.uservoice.com/forums/306457-general/suggestions/18784858-add-inline-preview-for-attached-images

Also, if you're interested helping, either with design, implementation or testing, let us know :)

**Comment by BobTB** [comment]
This looks great! Fantastic if implemented as soon as possible. Very important for Slack users coming to mattermost. Most of them are dissapointed just because of this "simple" to fix thing.

**Pull request closed without merging**
