### PR TITLE
PLT-521: Fix emoji with underscores

### PR DESCRIPTION
**Pull request by trashcan**

### CODE REVIEW

**Comment by trashcan** [comment]
Fixed the semi-colon. Sorry I'm a javascript noob.

**Comment by hmhealey** [comment]
Thanks for catching that while I was in the process of commenting :). There's still an error from ESLint though since you're overwriting the text argument there.

image

**Comment by trashcan** [comment]
Thank you. TIL how to use eslint :ice_cream:

**Comment by crspeller** [comment]
+1

**Comment by jwilander** [comment]
+1

**Comment by hmhealey** [comment]
That's much nicer than my last attempt which changed some regex and ended up breaking a bunch of stuff. I'm going to make a small change to it and only reparse emoticons there since it has already ran through doFormatText once at that point and doing it twice may cause some things like hashtags to be formatted weirdly.

**Pull request merged**
