### PR TITLE
PTL-7: Mattermost Localization

### PR DESCRIPTION
**Pull request by enahum**
- Clean history with only one commit.
- Localization support for backend console messages, logs and frontend
- Includes spanish locale
- Fallback to english

### CODE REVIEW

**Comment by it33** [comment]
Thanks @enahum! This is going to be the largest PR review we've done in Mattermost so far. Extremely excited about getting this in!

**Comment by jwilander** [comment]
I'm going to throw some comments in here, not sure if we want to fix them with in this PR or accept it and fix them in new PRs. We can wait for @coreyhulen to chime in on that

**Comment by jwilander** [comment]
Can't comment directly on the diff because it's too large but:

Line 52 in `/web/react/components/user_settings/manage_languages.jsx` is setting the `user.language` property when it should be setting the `user.locale` property. This prevents the user from choosing their language properly.

**Comment by jwilander** [comment]
When creating a new user, a default language does not get set anywhere. So when viewing **Language** in **Account Settings** Spanish is selected when the user doesn't have any language selected. We should probably set a default language for each user as they're created and update the `manage_lanuages.jsx` control to default to English if the user has none selected (which shouldn't ever happen if we add the Locale column properly).

The default language could even be set by the system admin in the System Console

**Comment by enahum** [comment]
Ok i'll fix the user.language to user.locale for this PR, then in i18n/i18n_init.go you can see the DEFAULT_LANGUAGE being set to English

**Comment by jwilander** [comment]
Also the Team Sign-up page is missing text. I think we just need to add `page.Props["SignupTitle"] = T("signup_team.title")` just before line 222 in `web/web.go`

**Comment by jwilander** [comment]
Closing as we're going to take this in chunks.

**Pull request closed without merging**
