### PR TITLE
PLT-3132 Add a direct message link to the contact pop-over

### PR DESCRIPTION
**Pull request by khawerrind**
**Summary**

In the popover that appears when you click on user profile picture or user name added the button for direct message

**Ticket Link**
https://mattermost.atlassian.net/browse/PLT-3132

### CODE REVIEW

**Comment by yangchen1** [comment]
Hey @khawerrind, I'm just going to hold off a tiny bit reviewing this PR until [this major one](https://github.com/mattermost/platform/pull/4701) dealing with profile pop-overs is merged, thanks for your patience!

**Comment by khawerrind** [comment]
@esethna i have resolved the conflicts. However i am noticing couple of console errors due to this [PR](https://github.com/mattermost/platform/pull/4701)

```
Failed prop type: The prop `status` is marked as required in `ProfilePopover`, but its value is `undefined`.
Failed prop type: The prop `isBusy` is marked as required in `ProfilePopover`, but its value is `undefined`.
```

Do you want me to remove `isRequired` for these properties from `ProfilePopover` component?

**Comment by esethna** [comment]
@jwilander any thoughts on the above? ^

**Comment by jwilander** [comment]
Yes if you could remove those that would be great, thanks!

**Comment by khawerrind** [comment]
@esethna @jwilander done.

**Pull request merged**
