### PR TITLE
Set focus to server log control in System Console when loading panel

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
Set focus to server log control in System Console when loading panel

#### Ticket Link
JIRA: https://mattermost.atlassian.net/browse/PLT-4663
GitHub: https://github.com/mattermost/platform/issues/4491

### CODE REVIEW

**Comment by esethna** [comment]
Hi @cpanato, thanks for another PR! 

Just letting you know again, there may be a delay in reviewing and merging this PR as we are locking down feature and improvement contributions for the v3.6 release, per our [release process](https://docs.mattermost.com/process/release-process.html). This PR can be merged into `master` after we branch `release-3.6` on January 4th.

**Comment by cpanato** [comment]
hello @esethna I tried the test server and when I press up or down the log scroll works similiar to page up and down 

8ty6puyihf


how I can reproduce your issue?

**Comment by jasonblais** [comment]
@cpanato Looks like it's reproducing for me in at least two instances:

1) Height of server logs table is large enough so that NO vertical scrollbar appears

 - go to **System Console** > **Logs**
 - press either UP or DOWN arrow keys

Observed: Left-hand sidebar scrolls
Expected: Left-hand sidebar doesn't scroll. Server logs table should still have focus, so that the user can scroll left/right

2) Height of server logs table is small enough so that vertical scrollbar appears

 - go to **System Console** > **Logs**
 - press **Reload**
 - go to another **System Console** tab (e.g. **Site Statistics**), then back to **Logs**
 - press either UP or DOWN arrow keys

Observed: Left-hand sidebar scrolls
Expected: Server logs table scrolls

**Comment by cpanato** [comment]
@jasonblais @esethna Got it, however if you look the control it gas the focus.
I observed after you apply the steps in the number 2 (as describe per @jasonblais ) your mouse pointer is in the sidebar area and if you move the arrows up/down will move the sidebar. If you move your mouse to the log view area and move the arrows it will work only in the logs.


Also if you keep the window size and move back to the chat and then return to the logs and leave your mouse pointer in the sidebar you will be able to arrow up/down the scrool, then if you remove the mouse from the sidebar will not how anymore.

I dont know if this is a bug. please advise.

k8cg05iwom

**Comment by jasonblais** [comment]
Ah you're right, the scrolling is dependent on mouse position. Re-tested on Windows 10, Chrome, looks good to me.
 - visiting System Console > Reporting > Logs for the first time
 - reloading the logs
 - going to another System Console tab, then back to Logs
 - repeated above tests when the logs panel had and didn't have a vertical scrollbar
 - repeated above tests for LEFT/RIGHT arrows

Only found an unrelated issue, where if you go to any other System Console settings page such as **Configuration**, the UP/DOWN arrow keys do nothing if I'm hovering over the settings page. It would be nice if the arrows worked on the other pages too. Ticket here: https://mattermost.atlassian.net/browse/PLT-5125

**Pull request merged**
