### PR TITLE
PLT-2397 Send email notification when username changed

### PR DESCRIPTION
**Pull request by tbalthazar**
I've included the English and French translations.
Please let me know if there's a better way to handle i18n files.

### CODE REVIEW

**Comment by jwilander** [comment]
For localization you only need to update the english, but if you know french then we'll gladly take that at the same time :)

+1

**Comment by tbalthazar** [comment]
French is my mother tongue so if that helps, I'll keep providing both localizations for my next contributions ;)

**Comment by enahum** [comment]
@tbalthazar there is a [Translation Server](http://translate.mattermost.com) if you like to help out with french :)

**Comment by enahum** [comment]
+1

**Comment by crspeller** [comment]
Looks good @tbalthazar !

Just one thing. We are trying to move away from the "andForget" style of function. Can you modify the function to not immediately start a go routine, then call the function as a go routine when needed?

**Comment by crspeller** [comment]
@tbalthazar Little collision of merge and comment there. Sorry about that! Could we have your help submitting another PR with the fix please?
Thanks!

**Comment by tbalthazar** [comment]
@crspeller That makes perfectly sense to me.
Here is the pull request: https://github.com/mattermost/platform/pull/3043

**Pull request merged**
